### ISSUE TITLE
Localize Open Graph description tag

### ISSUE THREAD

**Issue by mikehenrty** [common-voice/common-voice#1051]
So that if you share https://voice.mozilla.org/cy, you get a welsh description in FB/twitter/slack/etc.

**Comment by MichaelKohler** [comment]
Just tried this with German, still displays English. Would be great if that would take the localized descriptions: https://twitter.com/KohlerSolutions/status/1229899994800513027

**Comment by Heyhillary** [comment]
Hey I am closing this issues, as we recieved a similar request that has had a bit more conversation. If you have any questions or point please use this issue https://github.com/common-voice/common-voice/issues/2861
