### ISSUE TITLE
Download personal recorded dataset

### ISSUE THREAD

**Issue by irvin** [common-voice/common-voice#1210]
One of the local researchers is trying to collect the voice samples of ALS patients, in order to synthesize the patient's voice when necessary. I feel we can really help with a "download personal dataset" feature.

**Comment by mikehenrty** [comment]
This usecase is also good for building TTS (speech synthesis) based on your own voice.

**Comment by irvin** [comment]
And I feel it’s also something we should implement in order to respect the principle of GDPR data portablility right.

**Comment by kdavis-mozilla** [comment]
This use case can also be of interest in creating a STT engine for, say, people with a particular speech impediment.

**Comment by mikehenrty** [comment]
As Irvin mentions, we will have to do this due to GDPR. Plus it's a nice feature to have.

**Comment by Gregoor** [comment]
#434 is a related issue (maybe we should merge them)

**Comment by Gregoor** [comment]
![Settings Build Profile_06 1](https://user-images.githubusercontent.com/4051932/61617979-2b098380-ac6c-11e9-9020-6b0d37dbf4b3.png)

We have designs for it, but so far haven't found time to look at implementation. Happy to review PRs for it!

**Comment by kjreills** [comment]
I'd like to start working on this feature. This will be my first contribution, so let me know if you have any advice or additional information I should know.

Thanks!

**Comment by phirework** [comment]
@kjreills Please feel free! If you run into any issues getting the repo set up locally for development please submit a PR to CONTRIBUTING.md so that we can improve our documentation :)

**Comment by irvin** [comment]
the feature had landed to beta, 
ref: https://github.com/common-voice/common-voice/releases/tag/release-v1.55.0
#3242 #2865
