### ISSUE TITLE
plan on removing TLS 1.0 support

### ISSUE THREAD

**Issue by Djfe** [common-voice/common-voice#1255]
This definitely has a very low priority, but are there stats on how many of this page's viewers only support TLS 1.0?
And are we even interested in them? (they can't contribute, right? / they would need to install new software to do so anyways)

**Comment by Gregoor** [comment]
I don't think we have stats directly on that (though it would be possibly to calculate it based on caniuse and users' browser versions). And those browsers are barred from the site anyway, as they don't have the necessary JS features.

**Comment by Djfe** [comment]
almost/virtually all browsers that support tls 1.1 support tls 1.2 (maybe 1 or 2 versions later)

tls 1.1 could be dropped as well

the ssltest shows it in a different (imo better) way:
https://www.ssllabs.com/ssltest/
(which browsers only support tls 1.0)

usage stats wise (on caniuse) they are almost not existent (but caniuse isn't that accurate on those numbers, it always depends on the usage, it would be useful to know the browser exact stats for common voice :) )
