### ISSUE TITLE
Can't hear my records before sending

### ISSUE THREAD

**Issue by elpimous** [common-voice/common-voice#1273]
Hello. 
Wonderfull app !
I can record, but not hear my records before sending !!
Phone : samsung s7 edge.
Browser : samsung internet.

Hope to help.
Vincent

**Comment by Gregoor** [comment]
Hi, thanks for the report and the kind words. I can indeed reproduce the problem with samsung internet. I'm now trying to figure out how to get Chrome Remote Debugging to work with it, so that we can find the source of the problem.

**Comment by mbransn** [comment]
@ovidiuboca1 can you take a look into this?

**Comment by ovidiuboca1** [comment]
I tested on Samsung s7 NOTSamsung s7 edge with Samsung browser but I can't reproduce the issue, in my case I'm able to hear my recording. 
@Gregoor do you use Samsung S7 Edge?

**Comment by phirework** [comment]
Closing for now due to inability to reproduce + inactivity on the issue. Feel free to open another issue if this problem persists!
