### ISSUE TITLE
Tooltip won't disappear after playing recording in Common voice app

### ISSUE THREAD

**Issue by viorelaioia** [common-voice/common-voice#1308]
Env: iOS -11.4.1, iPhone 7, Common Voice app 

STR:
1. Launch Common Voice app
2. Navigate to Contribute - Speak page
3. Record a sentence
4. Go back to the sentence you just recorded and play it (You have to press Play button 2 times in order to play it)
5. Go to next sentence to record

Expected:
Tooltip disappears when switching to the next sentence.

Actual:
Tooltip for the sentence won't disappear. Switching to listen still shows the tooltip.

![photo5980828473662484157](https://user-images.githubusercontent.com/5293100/43444651-faabf164-94ac-11e8-99e8-55909bcfbe5f.jpg)
![photo5980828473662484158](https://user-images.githubusercontent.com/5293100/43444658-01412968-94ad-11e8-9fc8-a83a964d64f5.jpg)

**Comment by phirework** [comment]
Closing as the app is no longer relevant/supported.
