### ISSUE TITLE
Keyboard accessibility: Language drop-down

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#1388]
[Environment]:
Windows 10, Chrome 68, Firefox 61, latest Edge

[Steps to reproduce]:
1. Open https://voice.mozilla.org/en/new
2. Press the Tab key to navigate to the language drop-down
3. Open the drop-down using the keyboard
4. After the drop-down is opened press on different letter keys

[Expected results]:
3.T he drop-down can be opened using the keyboard
4. Different languages should be selected

[Actual results]:
3. The drop-down can't be opened using the keyboard
4. The languages are not selected using the keyboard

**Comment by zaccolley** [comment]
I'm going to pick this one up, thanks for the report
