### ISSUE TITLE
New Homepage: Listen and Speak icons are not correctly displayed on Firefox for iOS

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#1449]
[Environment]:
iOS 11.4.1. Firefox

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Observe the Listen and Speak icons

[Actual result]:
The coloured circles are not displayed
![image1](https://user-images.githubusercontent.com/41474886/45368694-dda09c80-b5ec-11e8-9b50-3ef4cf3d4974.png)

[Note]:
Not reproducible on Chrome for iOS or Safari
When entering https://voice.mozilla.org address on Safari iOS, the page is not redirected to https://voice.mozilla.org/en/new

**Comment by phirework** [comment]
I think this has been fixed at some point - I can no longer reproduce.
