### ISSUE TITLE
Frontend only setup

### ISSUE THREAD

**Issue by Gregoor** [common-voice/common-voice#1475]
The biggest hurdle I see towards contributing to the code is the amount of work required to setup the backend. Docker should've solved that for us, but it has its own problems (one of which is that I don't use it myself for development).
Also the largest share of our issues are frontend related. So I think it'd be valuable to look into a frontend-only setup that would either talk to a backend mock or our staging server.

Steps necessary:
- CORS on staging
- proxy API requests to staging
- split up the FE & BE build / dev tasks
- document it

**Comment by f0cus10** [comment]
I think this is something interesting. 
If I understand the issue correctly, you're suggesting 
1. Setting up a CORS configuration on S3
1. Proxying the front-end so it communicates with S3 staging server instead of the backend 
1. And make a build script for the client side only

**Comment by Gregoor** [comment]
Yes, that sounds about right :)
