### ISSUE TITLE
Listen success: UI issues on iOS

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#1478]
[Environment]:
iOS 11.4.1. Firefox , Chrome, Safari
Common Voice app

[Steps to reproduce]:
1.Open https://voice.mozilla.org/en/new
2.Go to Contribute -> Listen section
3.Listen 5 clips 

[Expected result]:
https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5afd9ced98e7ef0321f0ef10

[Actual result]:
1."Ready to do more 5" text is cut at the bottom and the arrow is missing
2. Instead of "Log in/Sign up" is "Create a profile" button. The button is too small
3. The number of submitted clips is not displayed

![listen success](https://user-images.githubusercontent.com/41474886/45824172-0e24bc80-bcf8-11e8-894e-0fefa028e66e.jpg)

**Comment by poush** [comment]
Is this still valid, because when I tried opening up the contribute section on the Safari's iOS Responsive mode, it says to download the iOS app.
