### ISSUE TITLE
Visibility issues on dashboard elements for RTL languages

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#1771]
[Environment]:
Mac OS 10.12, Windows 10 - Safari, Chrome, Firefox

[Preconditions]:
browser's window is not in maxim size

[Steps to reproduce]:
1.Go to voice.allizom.org/ar/dashboard
2.Hover using mouse over the" i" button from the graph

[Actual result]:
The  "more info" dialog is not fully visible

![50921731_1866890136767575_5560416303811919872_n](https://user-images.githubusercontent.com/41474886/51541356-4c2a1c80-1e61-11e9-86f1-cb892c27be2d.png)
![50507953_1420513968083459_3082138668425543680_n](https://user-images.githubusercontent.com/41474886/51541357-4cc2b300-1e61-11e9-9f0d-bd1cf91cd5b5.png)

[Note]:
The issue is reproducible on Mac Book with full window size

**Comment by Gregoor** [comment]
Thank you for the continued investigation, very helpful!

I fixed the former, will need some more time for the latter.
