### ISSUE TITLE
Subscribtion checkbox is not automatically updated after subscribing via footer

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#1986]
[STR]:
1.Subscribe to newsletter via footer

[Expected result]:
Subscription checkbox should be automatically checked in Settings and goal setting

[Actual result]:
The subscription checkboxes are updated only after page refresh
https://vimeo.com/333351133

**Comment by aryamanpuri** [comment]
@MichaelKohler @phirework Is this still a valid issue?

**Comment by phirework** [comment]
Closing as the entire email subscription system has been in limbo and will be changing - will revisit architecture when the new system is in place.
