### ISSUE TITLE
Can't change email address

### ISSUE THREAD

**Issue by jwatt** [common-voice/common-voice#2110]
I created an account with my @mozilla.com email address, and now seem unable to change it. When I click on the Edit button on https://voice.mozilla.org/en/profile/settings it redirects me to log in with SSO every time, repeatedly.

**Comment by Gregoor** [comment]
Heya, so just to clarify: The edit button is supposed to take you to SSO where you enter a NEW email address, after which you're supposed to be redirected back to the settings page and your new email should be shown there. This might not be the best UX, but unfortunately we can't control what SSO displays.

**Comment by jwatt** [comment]
Oh! Yeah, that wasn't what I expected given the UI. I think because the place where your current email address is displayed to the left of the Edit button looks quite like a form field. I expected the Edit button to make that contenteditable, or something, so when it required me to log in "again" I just thought that was a security measure.

Maybe the UI could be made less confusing by making the current email address look less like a form field (maybe display it as "Email: user@example.com") and changing the text on the "Edit" button (which isn't to edit the value on the left) to "Enter new email address". Or something like that...

**Comment by Gregoor** [comment]
Good point, I can see how that form field can be misleading. Thanks for raising this!

**Comment by mbransn** [comment]
@grailean I agree with the recommendation, can you take a pass at UI update for this so the email doesn't appear as a form field?
