### ISSUE TITLE
MySQL error when running docker build

### ISSUE THREAD

**Issue by EuphoriaCelestial** [common-voice/common-voice#2127]
Hi, am trying to run docker build of Common Voice in my own server, after successfull config of S3, Auth0, HTTPS, it shows up this error:

![image](https://user-images.githubusercontent.com/43977734/61958117-f2aad200-afea-11e9-885c-449cc44382a7.png)

I did not change anything about database or MySQL script in source code

**Comment by MichaelKohler** [comment]
@EuphoriaCelestial is this still an issue?
