### ISSUE TITLE
Data to be exposed in Kibana

### ISSUE THREAD

**Issue by Gregoor** [common-voice/common-voice#2180]
```mysql
SELECT *, hash(client_id) AS client_id
FROM awards, clips, custom_goals, votes, language_requests, reported_clips,
     reported_sentences, skipped_sentences, user_client_accents, user_client_activities;

SELECT *, hash(email) AS email FROM downloaders;

SELECT * FROM locales, requested_languages;

SELECT hash(email) AS email, hash(client_id) AS client_id, age, gender
FROM user_clients;
```

A bit of pseudo-MySQL up there, I suppose that's not quite how hashing will work. Are we gonna use the [jdbc plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html) to get the data into Kibana?
If so, from reading [this blog post](https://medium.com/@erangadulshan.14/pushing-relational-data-to-elasticsearch-using-logstash-jdbc-input-plugin-48af81ed1000) it sounds like in the config output section one has to describe what the resulting document should be named (and which column should be the ID)?

**Comment by phirework** [comment]
Closing as Kibana is no longer being supported - we're using Grafana for metrics dashboards instead.
