### ISSUE TITLE
[Voice app]: Blank page displayed on Listen

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#2218]
[Environment]:
iOS 12.4 - Tablet

[STR]:
1.Open Common Voice app
2.Tap the Listen button

[Expected result]:
Listen page should be displayed

[Actual result]:
Blank page is displayed

[Note]:
Not reproducible for Speak

**Comment by phirework** [comment]
We removed support for the iOS app in spring of 2020.
