### ISSUE TITLE
Truncated text in hourly graph under "Voices online now"

### ISSUE THREAD

**Issue by peiying2** [common-voice/common-voice#2245]
There are a few issues with the current design/layout. It is affecting many languages. The `Hour` text in the graph under `Voices online now` is truncated. It should allow ability to disable the hours if the word exceeds N number of letters. See the screenshots for hsb and dsb.

https://www.sorbzilla.de/commonvoice/commonvoice_hlosy_online.png
https://www.sorbzilla.de/commonvoice/commonvoice_glose_online.png

Is the word hard coded? Apparently it is not in Pontoon so contributors can't abbreviate it. 

To test:
- https://voice.mozilla.org/hsb
- https://voice.mozilla.org/dsb

**Comment by mbransn** [comment]
>Is the word hard coded? Apparently it is not in Pontoon so contributors can't abbreviate it.

Thanks @peiying2, great question; @Gregoor can you let us know how you implemented?

**Comment by Gregoor** [comment]
Looks like the time string formatting has simplistic assumptions:
https://github.com/mozilla/voice-web/blob/6ac48efc92b77cd64cfb400c8df35fd9936b14ca/web/src/components/plot/plot.tsx#L146-L152
