### ISSUE TITLE
Mobile profile build page UI fixes

### ISSUE THREAD

**Issue by georai** [common-voice/common-voice#2313]
https://www.dropbox.com/s/4xfmyepe56tqtw2/Screenshot%202019-11-13%2018.36.54.png?dl=0

1. There is a line that separates the copy and the fields. Also, we have a style for required field. 
2. We need to have padding 20 px on right and left also 20 px.
3. Checkboxes style ( old issue)
4. The button for the  save, needs to be grey, when the the have checked the boxes make it black, after we press it's becoming green.

@mbransn @rileyjshaw

**Comment by rileyjshaw** [comment]
These are not Voice Challenge specific. Removing that label.
