### ISSUE TITLE
[mobile] Logged in profile UI updates

### ISSUE THREAD

**Issue by georai** [common-voice/common-voice#2314]
https://www.dropbox.com/s/yvvq7u1ugx5ch70/Screenshot%202019-11-13%2018.44.19.png?dl=0

1. The spacing between the tabs needs to be like in design. Let me know if you need the measures. 
2. Weird box in the footer, please remove.
3. Can we have the dividers in the footer too: https://www.dropbox.com/s/l44lhpj9g2ajfkd/Screenshot%202019-11-13%2018.45.27.png?dl=0

@mbransn @rileyjshaw

**Comment by rileyjshaw** [comment]
Related: https://github.com/mozilla/voice-web/issues/2313

**Comment by rileyjshaw** [comment]
These are not Voice Challenge specific. Removing that label.

**Comment by Dnouv** [comment]
I want to work on this issue. Please assign me on this if it's available.

**Comment by Dnouv** [comment]
@georai, @phirework, I understand you may be busy, but I will truly appreciate if you could look into my request.

**Comment by Dnouv** [comment]
@mbransn, could you please look into my request.

**Comment by Dnouv** [comment]
@phirework, thank you so much for assigning me on this issue.
