### ISSUE TITLE
Larger image avatar coming through pixelated

### ISSUE THREAD

**Issue by mbransn** [common-voice/common-voice#2388]
The larger avatar image is coming through pixelated on the challenge dashboard in the weekly challenge card.

<img width="159" alt="Screen Shot 2019-11-19 at 9 46 43 AM" src="https://user-images.githubusercontent.com/18686986/69196030-3073bf00-0ae2-11ea-8e73-c9d65fb182dc.png">

**Comment by mbransn** [comment]
@can-007 @catherine917 do you have thoughts on this? cc @rileyjshaw

**Comment by catherine917** [comment]
@mbransn When you upload an avatar, the image is compressed and stored as a `Canvas` in the database.  The screenshot below is the image from the database. You can see it has already pixelated
![Annotation 2019-11-20 161244](https://user-images.githubusercontent.com/8065961/69220739-a181a800-0bb0-11ea-8645-ba16b7a1abe1.png)

**Comment by can-007** [comment]
I think this phenomenon have existed for a long time. I guess the original idea was to protect CV from heavy network payload, in case someone might upload a huge picture.

**Comment by phirework** [comment]
Yep as @can-007 this is behaviour enforced by existing code. However, I took a look at the automatic resizing function on avatars and it looks like it restricts images to be a max of 80px in either dimension, which in the age of high res retina displays is probably too small. I've pushed a tiny change to master to increase that limit to 200px in either dimension. You won't see an improvement until you re-upload an avatar, because we have no way of regenerating a new avatar based on an already pixellated thumbnail, but this should fix it for new users. 

https://github.com/mozilla/voice-web/commit/f6c3b2c44b373807f2383efda26e422e4ba3638e

**Comment by mbransn** [comment]
Got it, thanks all. 200px sounds alright for now and heard from some people internally testing the flow that providing dim info up front will enable easier clarity on what can be uploaded. I'm going to log that, along with a separate issue to look into larger image handling capabilities for those people not able to resize/compress (want this to be a friendly experience that doesn't require manual image resizing).

**Comment by phirework** [comment]
Just to clarify, when I say "restrict" I mean that the system as it is resizes images down to 80px at the widest (or 200px now) no matter what's uploaded, not that users have to manually crop to that size. I can totally see where I was unclear there, sorry about the confusion.

**Comment by mbransn** [comment]
Ah, got it. Thanks for clarifying. I'll test and rework issues (or delete) as needed. Thanks!

**Comment by mbransn** [comment]
@phirework FYI new image upload is not working for me, meaning:
Precondition: have image in place already as avatar
Expected: `Browse` on avatar page allows successful upload of a new image
Actual: `Browse` triggers mac os finder > image selected > finder closes > no visible image change

@viorelaioia can you please try and test the above on your end too and let us know the results?

**Comment by phirework** [comment]
@mbransn Did you test this on prod or stage? I haven't deployed anything to prod today so if it's there then that was a pre-existing problem...

**Comment by mbransn** [comment]
...yep, prod. @viorelaioia please verify and if indeed an issue, let's open a new bug for tracking outside the challenge.

**Comment by viorelaioia** [comment]
@mbransn , the issue is reproducible. This is the new bug: https://github.com/mozilla/voice-web/issues/2405

**Comment by mbransn** [comment]
Thank you!
