### ISSUE TITLE
Login issues on Edge

### ISSUE THREAD

**Issue by rleitan** [common-voice/common-voice#2403]
[Environment]:
Windows 10 - Edge

[Precondition]:
Have an account in voice.mozilla.org - already joined the Voice challenge

[STR]:
1.Open https://voice.mozilla.org
2.Choose a login option and enter valid credentials (e.g. LDAP)

[Expected result]:
Login should be successful

[Actual result]:
The page is redirected to https://voice.mozilla.org/en/login-success but it looks like the login is not successful

![2019-11-21_11h01_33](https://user-images.githubusercontent.com/41474886/69323459-70a48000-0c4f-11ea-8387-f9cb1aae483c.png)

After few seconds the login is successful and the page is redirected to https://voice.mozilla.org/en/dashboard/challenge

**Comment by MichaelKohler** [comment]
Is this still an issue?

**Comment by Dnouv** [comment]
@rleitan I did follow the STR, but there were no issues. It successfully got logged in and redirected to the dashboard page.
