### ISSUE TITLE
Logging-in without a profile when pointing to a different page gets stuck in a loop

### ISSUE THREAD

**Issue by emilio** [common-voice/common-voice#2416]
I was going to investigate https://bugzilla.mozilla.org/show_bug.cgi?id=1597630.

 * Click on https://voice.mozilla.org/el/dashboard/stats
 * Get prompted to log in.
 * Click any of the options, with an account where you don't have a profile yet.

I'd expect to be redirected to the "create your profile" page or something, but instead I get redirected to https://voice.mozilla.org/el/dashboard/stats, and deauthenticated instantaneously.

Also happened to our QA: https://bugzilla.mozilla.org/show_bug.cgi?id=1597630#c2

**Comment by Damian96** [comment]
Login with **Firefox Account**, is working on Firefox 70, Chrome and Opera.
**Github**, seems works only in my Firefox.

**Comment by emilio** [comment]
Yeah, it works if you go to `voice.mozilla.org` and create a profile, but otherwise you get stuck as described above.

**Comment by phirework** [comment]
Thanks for the report, we're investigating it.
