### ISSUE TITLE
Missing column has_login in user_clients table

### ISSUE THREAD

**Issue by arambh-gaur** [common-voice/common-voice#2527]
Hi,
During the schema creation in MySql has_login column is not added in user_clients table. But when we bring up the webpage on http://localhost:9000, the client makes some requests to the api and we get this error in the backend :

/api/v1/en/clips/votes/daily_count Unknown column 'has_login' in 'where clause'. 

There is a query for altering the user_clients table and add this column but that does not seem to execute which is causing this error. Could someone please guide us on how to resolve this.

**Comment by can-007** [comment]
It would be very helpful if you could provide the version of MySQL.

**Comment by rileyjshaw** [comment]
@arambh-gaur which version of MySQL are you using?
