### ISSUE TITLE
Invalid Data for Punjabi

### ISSUE THREAD

**Issue by soniasingla** [common-voice/common-voice#2690]
Steps to reproduce:

Go to https://voice.mozilla.org/en/languages , and choose "Punjabi" language.

**Actual results:**

The dataset is found to be in English.

**Expected results:**

The dataset must be in Punjabi.

I have attached screenshot with this bug of `German` language. Please note I am talking about the dataset under `Speak` section, not the localization of website. As shown in screenshot, the data provided must be same with the given language.
![Screenshot_2020_0420_223254](https://user-images.githubusercontent.com/33036742/80096003-84e60380-8586-11ea-8589-a2b4112dcb3f.jpg)

**Comment by phirework** [comment]
Thanks for the report, we're on it.

**Comment by soniasingla** [comment]
Any updates on this bug?

**Comment by phirework** [comment]
Hi there, this was fixed a few months ago, my apologies for not reporting back. Are you still experiencing this problem? I've just verified this on both desktop and mobile.

**Comment by ftyers** [comment]
@soniasingla is this issue still a problem for you?

**Comment by soniasingla** [comment]
@ftyers thanks, this issue is fixed now. Closing :)
