### ISSUE TITLE
Mobile View Stats Issue

### ISSUE THREAD

**Issue by shakti97** [common-voice/common-voice#2707]
1. language selector going out of the alignment
2. Recorded Clips/ Validated Clips alignment issue

![Screenshot from 2020-05-02 02-39-12](https://user-images.githubusercontent.com/30585570/80842728-f6c1eb00-8c1f-11ea-94dc-56ce4aa7ee41.png)

I need the mobile design, so that I can work and fix this issue.

**Comment by bacharakis** [comment]
Thanks for the report @shakti97 !

Can you please share with us some more information like your operating system, browser version and screen resolution?
Thank you!
