### ISSUE TITLE
A cancelled re-record action wipes the original recording

### ISSUE THREAD

**Issue by rileyjshaw** [common-voice/common-voice#2716]
Steps to reproduce:

1. Navigate to https://voice.mozilla.org/en/speak
2. Record the displayed sentence
3. Once the next sentence displays, click "Review and re-record" (circular arrow button) beside entry 1
4. Start a recording by clicking the microphone button
5. Cancel the recording by clicking "Cancel Re-recording"
6. Click the play icon beside entry 1

*Observed behaviour:* no audio plays; the initial recording has been deleted. The interface still treats the slot as recorded.

*Expected behaviour:* the initial recording is preserved until replaced by a re-recording (@mbransn, can you confirm that this is the intent?)

**Comment by mbransn** [comment]
@rileyjshaw confirmed, initial recording should be preserved until replaced. Great catch!

**Comment by rileyjshaw** [comment]
This should hopefully be fixed by https://github.com/mozilla/voice-web/pull/2721.
