### ISSUE TITLE
Blurry image on specific page of new website

### ISSUE THREAD

**Issue by OddHouseGames** [common-voice/common-voice#2719]
https://voice.mozilla.org/en/profile/settings

This image is blurry on the new website:

[image](https://user-images.githubusercontent.com/62911518/81936030-8cb22a00-95bf-11ea-9eeb-f32322a6a170.jpeg)

**Comment by bacharakis** [comment]
hi @Githubuxer , can you please share with us the device you are experiencing this problem?
Thanks

**Comment by Githubuxer** [comment]
iPhone 6S with latest iOS.

**Comment by Rexogamer** [comment]
Also an issue on my iPad Air 3 running iOS 13.4.1:
![061535DD-8ACE-432F-BF68-5746D436FEF9](https://user-images.githubusercontent.com/42586271/82556510-c22bba00-9b61-11ea-9218-c64c24ae4bc1.jpeg)
