### ISSUE TITLE
Can’t record on iPad

### ISSUE THREAD

**Issue by Rexogamer** [common-voice/common-voice#2720]
On the site, when I try to record a sentence, the following happens:
- I tap the record button
- Safari asks for perms
- I grant them
- It seems to freeze, (presumably) not recording anything and not given the option to stop recording

iOS 13.4.1, iPad Air 3, Safari (tried requesting both desktop and mobile site)

**Comment by rileyjshaw** [comment]
Hi, thanks for reporting this bug! We've been noticing some inconsistencies in mobile Safari's treatment of various hardware, so hearing from the community is very helpful.

• Did you have any headphones or a microphone plugged in while trying to record (wired or bluetooth)?
• Were you screen-recording, or recording system audio in some other way?
• Did you navigate to voice.mozilla.org from the Safari browser, or have you saved a shortcut icon using the "Add to Home Screen" button?

If you've got time to troubleshoot, I've found that various combinations of the above can sometimes cause this "frozen button" bug. Please let me know if you're able to narrow it down further, or if it works under a particular combination of settings.

Thanks again!

**Comment by Rexogamer** [comment]
At the time of encountering this bug:
- I had headphones in, but using the default iPad mic
- Nope
- From Safari

**Comment by dag7dev** [comment]
@Rexogamer are you still experiencing this issue?

**Comment by Rexogamer** [comment]
Sorry for the late response - I am now using headphones with a mic, but it's working fine now.
