### ISSUE TITLE
Can't listen my recorded voice more then one time

### ISSUE THREAD

**Issue by Insun35** [common-voice/common-voice#2732]
When I contribute my voice on the web(Speak), I couldn't listen the voice file more then one time before submit.

**Comment by phirework** [comment]
Hello! Thanks for reporting this. Can you tell me what OS and browser you were using? Also, did you used to be able to listen the voice file multiple times in the past, or has this always been the case?

**Comment by Insun35** [comment]
First of all, thank you for your reply. Now I'm using Window10 for OS and Chrome browser. And I can't listen the voice file only after I record whole 5 sentences. That is to say, I could listen when I recorded only 3 or 4 sentences.

**Comment by bacharakis** [comment]
Thank you for following up @Insun35 ! 
I will reach out with further updates as soon as we have them, regarding the issue you reported.
Thanks

**Comment by dag7dev** [comment]
@bacharakis Windows10 Firefox 82.0.2 (64 bit) and Chrome Version 86.0.4240.183 (official build) (64 bit)
I think Common Voice has been updated or both of the browsers have been updated: this issue is not valid anymore.
