### ISSUE TITLE
Move “you are contributing to our first target segment” outside of sentence box

### ISSUE THREAD

**Issue by dabinat** [common-voice/common-voice#2743]
People keep reading the “you are contributing to our first target segment” text as if it was a sentence 🤦‍♂️

Maybe move it out of the sentence box?

**Comment by bacharakis** [comment]
Thanks for your suggestion @dabinat !
Our team will review it and I will come back to you as soon as we have something.

**Comment by zaccolley** [comment]
This seems to be no longer the case as there is no 'you are contributing to our first target segment' in the codebase any longer. I am going to close. @dabinat if you think that's wrong feel free to explain further the issue and reopen! Thank you
