### ISSUE TITLE
Some (mainland) Chinese sentences are incorrect in grammar    部分中文句子存在语病

### ISSUE THREAD

**Issue by RuikangSun** [common-voice/common-voice#2749]
Examples:

晚年的佩格劳仍继续从事交通号志小人的设计工作。
指出麦卡锡名单上大部分人是应该合理地被怀疑有安全风险。
而后五人则各家版本有所不同。
而芙蓉女儿诔更是作者发挥文学才华最充分的一篇。
小鲁一想到可以被嘘就好兴奋欧
人权的许多价值以强化人的能动性并以普世原则要求所有人应享有此天赋权利。

**Comment by nukeador** [comment]
How many of these are you encountering on average each 10 clips?

/cc @mko

**Comment by irvin** [comment]
Those are coming from Wikipedia, @RuikangSun can you help us to estimate how many percent do you consider is not grammar correctly
這些句子是擷取自維基百科，想請你協助查看一下下面的文字檔，幫我們估計一下大概有多少比例的句子是你認為「存在語病」的。
https://github.com/mozilla/voice-web/blob/master/server/data/zh-CN/wiki.zh-cn.txt

**Comment by RuikangSun** [comment]
> 
> 
> How many of these are you encountering on average each 10 clips?
> 
> /cc @MichaelKohler

Approximately，20% clips are completely wrong in grammar, 30% clips cannot be complete sentences (lack subject or object etc). It seems that these Chinese sentences are translated by machine.
Maybe it was caused by wrong comma separation. In Chinese, commas are used quite often in sentences.

**Comment by RuikangSun** [comment]
> 
> 
> Those are coming from Wikipedia, @RuikangSun can you help us to estimate how many percent do you consider is not grammar correctly
> 這些句子是擷取自維基百科，想請你協助查看一下下面的文字檔，幫我們估計一下大概有多少比例的句子是你認為「存在語病」的。
> https://github.com/mozilla/voice-web/blob/master/server/data/zh-CN/wiki.zh-cn.txt

Approximately，20% clips are completely wrong in grammar, 30% clips cannot be complete sentences (lack subject or object etc).

**Comment by nukeador** [comment]
We did a review of these sentences with native speakers at the time and the error ratio was really low. I'm checking again with the team but I'm surprised to read a completely different error estimation.

**Comment by irvin** [comment]
well, I think the criteria could be very different. 

Are those just "readable" or if "look like completed daily dialog sentences" can lead to very different perceptions. As [in here](https://discourse.mozilla.org/t/wikipedia-extraction-feedback/36843/44?u=irvin) I estimate the problematic rate is around 10%. Obviously we break the sentences on the comma after iterate v13, in order to make it shorter, lead to more sentences without the object. 

Also due to zh Wikipedias's mixed use of zh-cn and zh-tw ([as we discuss last year here](https://discourse.mozilla.org/t/mandarin-sentences-from-wikipedia/36146)), the sentences could feel 'non-natively'.

**Comment by irvin** [comment]
I would like to know exactly how many sentences are considered bad on current corpus. 

@RuikangSun here are 100 sentences I randomly fetch from [the corpus](https://github.com/mozilla/voice-web/blob/master/server/data/zh-CN/wiki.zh-cn.txt), can you help point out which of them are "wrong in grammar", and which of them are "not complete"?

For example, for grammar problem prefix a 'g' before sentences, and for complete problem, prefix a 'c'.

> 吓跑组合演唱的歌曲。
> 抗原表位可被免疫系统识别。
> 父亲勃艮地公爵是路易十四独子高大的王太子路易的长子。
> 巴巴多斯岛主要由石灰石构成。
> 孙敏汉是一名韩国男子棒球运动员。
> 音乐由千住明担当。
> 其在早期记载技术中为最为普遍的使用方式。
> 约翰和杰克相逢在他们最开始遇见彼此的街道转角处。
> 同年十月就任工兵营副营长。
> 最近则在车站的北边发现了布鲁内尔非常早期的作品。
> 宁海桥的历史年代为元。
> 久里滨线的铁路线。
> 希尔伯恩镇区是位于美国阿肯色州麦迪逊县的一个行政镇区。
> 为首位以非政府组织成员名义参加欧盟访问计划的澳门居民。
> 后裂小副克里介为荆花介科小副克里介属下的一个种。
> 并且在本书中还加入了许多新药物。
> 在行政上属于尼永区管辖。
> 十大功劳属是小檗科下的一个属。
> 国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来。
> 史学家李铭汉次子。
> 贝利斯普林斯是一个位于美国阿拉巴马州劳德代尔县的非建制地区。
> 卢瓦龙吕耶人口变化图示
> 这样的设定原先用意是想回避爱因斯坦所提相对论中的光速限制。
> 王祺可以指
> 亦在此时顾福生鼓励三毛学习写作。
> 目前效力于西班牙足球甲级联赛球会皇家马德里。
> 在佛律癸亚或吕底亚出生。
> 烟是一种物理及化学的现象。
> 战国至秦汉时期的历书称为日书。
> 副作用包含嗜睡和晕眩。
> 各媒体对本次地震及所带来的灾害采用不同的名称。
> 浙江乡试中举。
> 而你为甚么不让赵王进京？
> 后入读纽约音乐学院戏剧艺术研究表演。
> 于尔维尔人口变化图示
> 骆驼街道得名于慈东后江上的骆驼桥。
> 盆地一般有一圈与周边地表上撞击时所抛出岩石相隔开的主环。
> 厚叶八角
> 当地居民和游客被疏散至附近被临时关闭的旅馆。
> 梅斯佩尔布伦是德国巴伐利亚州的一个市镇。
> 为国家庆典幕后指定旁白。
> 最终马里也赢得了这届非洲国家杯季军。
> 塘栖尾孢虫为尾孢科尾孢虫属的动物。
> 南苏丹足球协会是专门管辖南苏丹足球事务的组织。
> 州里有大量大工业化公司。
> 列兹金斯坦。
> 许多新的开发者在后来的数年内一直追随这家公司的领导。
> 东蛇山子乡是中国辽宁省沈阳市新民市下辖的一个乡。
> 他擅长蝶泳项目。
> 张尔素人。
> 这些将军常发起北伐意图从五胡手中收复北方。
> 该物种的模式产地在琉球群岛。
> 马斯卡拉斯阿龙人口变化图示
> 任中国社会科学院外国文学研究所助理研究员。
> 整洁短浆蟹为梭子蟹科短浆蟹属的动物。
> 可是由于预算不足提案再度否决。
> 布卢里奇是一个位于美国乔治亚州范宁县的城市。
> 无政府资本主义者坚持应该将互不侵犯原则套用在政府层面上。
> 钻光鱼科是辐鳍鱼纲巨口鱼目的其中一科。
> 他在之后承认这是个错误。
> 这张专辑在事故发生一个月后被释放发行。
> 长春微蛛为皿蛛科微蛛属的动物。
> 他还有一个弟弟。
> 翡翠湾是位于美国加利福尼亚州埃尔多拉多县的一个非建制地区。
> 从此步入演艺界。
> 该反应是通氢气于悬浮有催化剂的酰氯溶液中来进行。
> 隆庆二年庞尚鹏升任右佥都御史。
> 但也有人指摘文明开化只是限于都市人及知识分子摄取西方文明。
> 事件告一段落。
> 巴基斯坦超级足球联赛是巴基斯坦足球联赛系统的最高级别。
> 艾查殊体育会是一家已解散足球会。
> 它也可以应用于诸如在追捕游戏中做为实际奖励。
> 来自蒙古和巴拿马代表团的运动员赢得了该国参加夏季奥运会历史上的第一枚金牌。
> 极昼和极夜。
> 傅亮人。
> 参与这项概念的公司还包括铁路运营商威立雅运输和建筑企业斯堪斯卡。
> 大红菇最早是由丹麦植物学家。
> 季裂裂痕的特征是黄铜受氨影响的部件会出现较深的脆性裂痕。
> 沙尔梅人口变化图示
> 英语盲文是记录英语的盲文。
> 永昌府是中国古代的一个府。
> 他为该博物馆收集了大量精美的矿物样本。
> 唯节目内的介面以至字幕全部均使用简体字。
> 涿郡安平人。
> 目前家族的掌舵人是其第四代。
> 基督教堂小修道院是英国多塞特郡克赖斯特彻奇的一座教堂。
> 最终建立了中国历史上第一个中央集权君主统治国家。
> 县治林登。
> 引发抢购热潮。
> 中华民国政府接受德国的军事援助。
> 为什么？
> 嘉庆八年出生。
> 地点是哥伦比亚特区东北部托腾堡站和塔科马站间。
> 拜伦下属的一座城市。
> 太史第更另外在广州市郊自设农场生产花果荔枝等等。
> 密支那往雷多路段则又复归与旧中印公路共线。
> 但后来逐渐跟巴布亚新几内亚融合。
> 刚楚布寺位于日喀则地区吉隆县境内。
> 这期间丘吉尔几乎每周都亲自到被炸现场视察。
> 烟台话全不分阴阳。

**Comment by RuikangSun** [comment]
> 
> 
> I would like to know exactly how many sentences are considered bad on the current corpus.
> 
> @RuikangSun here are 100 sentences I randomly fetch from [the corpus](https://github.com/mozilla/voice-web/blob/master/server/data/zh-CN/wiki.zh-cn.txt), can you help point out which of them are "wrong in grammar", and which of them are "not complete"?
> 
> For example, for grammar problems prefix a 'g' before sentences, and for the completion problem, prefix a 'c'.
> 
> > 吓跑组合演唱的歌曲。
> > 抗原表位可被免疫系统识别。
> > 父亲勃艮地公爵是路易十四独子高大的王太子路易的长子。
> > 巴巴多斯岛主要由石灰石构成。
> > 孙敏汉是一名韩国男子棒球运动员。
> > 音乐由千住明担当。
> > 其在早期记载技术中为最为普遍的使用方式。
> > 约翰和杰克相逢在他们最开始遇见彼此的街道转角处。
> > 同年十月就任工兵营副营长。
> > 最近则在车站的北边发现了布鲁内尔非常早期的作品。
> > 宁海桥的历史年代为元。
> > 久里滨线的铁路线。
> > 希尔伯恩镇区是位于美国阿肯色州麦迪逊县的一个行政镇区。
> > 为首位以非政府组织成员名义参加欧盟访问计划的澳门居民。
> > 后裂小副克里介为荆花介科小副克里介属下的一个种。
> > 并且在本书中还加入了许多新药物。
> > 在行政上属于尼永区管辖。
> > 十大功劳属是小檗科下的一个属。
> > 国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来。
> > 史学家李铭汉次子。
> > 贝利斯普林斯是一个位于美国阿拉巴马州劳德代尔县的非建制地区。
> > 卢瓦龙吕耶人口变化图示
> > 这样的设定原先用意是想回避爱因斯坦所提相对论中的光速限制。
> > 王祺可以指
> > 亦在此时顾福生鼓励三毛学习写作。
> > 目前效力于西班牙足球甲级联赛球会皇家马德里。
> > 在佛律癸亚或吕底亚出生。
> > 烟是一种物理及化学的现象。
> > 战国至秦汉时期的历书称为日书。
> > 副作用包含嗜睡和晕眩。
> > 各媒体对本次地震及所带来的灾害采用不同的名称。
> > 浙江乡试中举。
> > 而你为甚么不让赵王进京？
> > 后入读纽约音乐学院戏剧艺术研究表演。
> > 于尔维尔人口变化图示
> > 骆驼街道得名于慈东后江上的骆驼桥。
> > 盆地一般有一圈与周边地表上撞击时所抛出岩石相隔开的主环。
> > 厚叶八角
> > 当地居民和游客被疏散至附近被临时关闭的旅馆。
> > 梅斯佩尔布伦是德国巴伐利亚州的一个市镇。
> > 为国家庆典幕后指定旁白。
> > 最终马里也赢得了这届非洲国家杯季军。
> > 塘栖尾孢虫为尾孢科尾孢虫属的动物。
> > 南苏丹足球协会是专门管辖南苏丹足球事务的组织。
> > 州里有大量大工业化公司。
> > 列兹金斯坦。
> > 许多新的开发者在后来的数年内一直追随这家公司的领导。
> > 东蛇山子乡是中国辽宁省沈阳市新民市下辖的一个乡。
> > 他擅长蝶泳项目。
> > 张尔素人。
> > 这些将军常发起北伐意图从五胡手中收复北方。
> > 该物种的模式产地在琉球群岛。
> > 马斯卡拉斯阿龙人口变化图示
> > 任中国社会科学院外国文学研究所助理研究员。
> > 整洁短浆蟹为梭子蟹科短浆蟹属的动物。
> > 可是由于预算不足提案再度否决。
> > 布卢里奇是一个位于美国乔治亚州范宁县的城市。
> > 无政府资本主义者坚持应该将互不侵犯原则套用在政府层面上。
> > 钻光鱼科是辐鳍鱼纲巨口鱼目的其中一科。
> > 他在之后承认这是个错误。
> > 这张专辑在事故发生一个月后被释放发行。
> > 长春微蛛为皿蛛科微蛛属的动物。
> > 他还有一个弟弟。
> > 翡翠湾是位于美国加利福尼亚州埃尔多拉多县的一个非建制地区。
> > 从此步入演艺界。
> > 该反应是通氢气于悬浮有催化剂的酰氯溶液中来进行。
> > 隆庆二年庞尚鹏升任右佥都御史。
> > 但也有人指摘文明开化只是限于都市人及知识分子摄取西方文明。
> > 事件告一段落。
> > 巴基斯坦超级足球联赛是巴基斯坦足球联赛系统的最高级别。
> > 艾查殊体育会是一家已解散足球会。
> > 它也可以应用于诸如在追捕游戏中做为实际奖励。
> > 来自蒙古和巴拿马代表团的运动员赢得了该国参加夏季奥运会历史上的第一枚金牌。
> > 极昼和极夜。
> > 傅亮人。
> > 参与这项概念的公司还包括铁路运营商威立雅运输和建筑企业斯堪斯卡。
> > 大红菇最早是由丹麦植物学家。
> > 季裂裂痕的特征是黄铜受氨影响的部件会出现较深的脆性裂痕。
> > 沙尔梅人口变化图示
> > 英语盲文是记录英语的盲文。
> > 永昌府是中国古代的一个府。
> > 他为该博物馆收集了大量精美的矿物样本。
> > 唯节目内的介面以至字幕全部均使用简体字。
> > 涿郡安平人。
> > 目前家族的掌舵人是其第四代。
> > 基督教堂小修道院是英国多塞特郡克赖斯特彻奇的一座教堂。
> > 最终建立了中国历史上第一个中央集权君主统治国家。
> > 县治林登。
> > 引发抢购热潮。
> > 中华民国政府接受德国的军事援助。
> > 为什么？
> > 嘉庆八年出生。
> > 地点是哥伦比亚特区东北部托腾堡站和塔科马站间。
> > 拜伦下属的一座城市。
> > 太史第更另外在广州市郊自设农场生产花果荔枝等等。
> > 密支那往雷多路段则又复归与旧中印公路共线。
> > 但后来逐渐跟巴布亚新几内亚融合。
> > 刚楚布寺位于日喀则地区吉隆县境内。
> > 这期间丘吉尔几乎每周都亲自到被炸现场视察。
> > 烟台话全不分阴阳。

Examples：
吓跑组合演唱的歌曲。/"吓跑" means "scare away", but might be the band name
抗原表位可被免疫系统识别。
g 父亲勃艮地公爵是路易十四独子高大的王太子路易的长子。/adjectives are incorrect
巴巴多斯岛主要由石灰石构成。
孙敏汉是一名韩国男子棒球运动员。
g 音乐由千住明担当。/which means "music was taken the position by Qian Zhuming"
g 其在早期记载技术中为最为普遍的使用方式。/"记载技术" should be “技术记载”
约翰和杰克相逢在他们最开始遇见彼此的街道转角处。
c 同年十月就任工兵营副营长。 /lacks subject
g 最近则在车站的北边发现了布鲁内尔非常早期的作品。/"非常"
宁海桥的历史年代为元。/takes time to understand
久里滨线的铁路线。
希尔伯恩镇区是位于美国阿肯色州麦迪逊县的一个行政镇区。
c 为首位以非政府组织成员名义参加欧盟访问计划的澳门居民。/lack subject
后裂小副克里介为荆花介科小副克里介属下的一个种。
c 并且在本书中还加入了许多新药物。/either replace "替换", or add subject
c 在行政上属于尼永区管辖。/lack subject
十大功劳属是小檗科下的一个属。
g 国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来。/either remove "正式名称" or "改组而来"
史学家李铭汉次子。
贝利斯普林斯是一个位于美国阿拉巴马州劳德代尔县的非建制地区。
卢瓦龙吕耶人口变化图示
这样的设定原先用意是想回避爱因斯坦所提相对论中的光速限制。
c 王祺可以指 /lack object
亦在此时顾福生鼓励三毛学习写作。
c 目前效力于西班牙足球甲级联赛球会皇家马德里。/lack subject

Honestly, some sentences could be "grammar correction" questions in Chinese language exams. XD

**Comment by RuikangSun** [comment]
> 
> 
> well, I think the criteria could be very different.
> 
> Are those just "readable" or if "look like completed daily dialog sentences" can have very different perceptions. As [in here](https://discourse.mozilla.org/t/wikipedia-extraction-feedback/36843/44?u=irvin) I estimate the problematic rate is around 10%. Obviously we broke the sentences on the comma after iterate v13, in order to make it shorter (sentences from Wikipedia are longer than daily conversation), lead to more grammar problems such as sentences without the object.
> 
> Also due to zh Wikipedias's mixed-use of zh-cn and zh-tw ([as we discuss last year here](https://discourse.mozilla.org/t/mandarin-sentences-from-wikipedia/36146)), the sentences could feel 'non-natively'.

I don't think it is the result of Wikipedias's mixed-use of zh-cn and zh-tw. It might be the result of machine traslation. In addition, I used to translate papers in English to Chinese, the result is not bad in grammar. So I guess that these incorrect sentences are translated by machine from minority languages. “Minority languages -> English ->Chinese” translation might break the sentences.

**Comment by irvin** [comment]
According to your above evaluate, problem rate of completion problem are 6 out of 100, and grammar error rate are 5 out of 100. 

For these sentences you point out, I believe they all came from Wikipedia. I think it would be nearly impossible to automatically remove them with a set of machine rules. If we would like the corpus to avoid those problems, it would require a manual process to go through all of these sentences. 

I had also inquiry with two other community members on this issue (however they prefer not to responding directly here), one is a core contributor to Mozilla and Common Voice and another one is linguistic who use our clip DB on their AI related project. The opinion is -

- "It depends, it's not that bad for their opinion. Perhaps some people will have more strict criteria", 
- "Grammar problem such as missing subject does not affect the usability of the corpus on model training at all".

**Comment by RuikangSun** [comment]
> 
> 
> According to your above evaluate, problem rate of completion problem are 6 out of 100, and grammar error rate are 5 out of 100. 11% does meet the criteria of 10% error rate when we fetch sentences last year.
> 
> For these sentences you point out, I believe they all came from Wikipedia directly withouy any modification other than convert of Traditional Chinese > Simplified Chinese (in order to fix mixed character set problem). I think it would be nearly impossible to automatically remove them with a set of machine-operational rules. It would require a manual process for native speakers to go through all of these sentences if we would like the corpus to not have those kinds of sentences.
> 
> I had also inquiry with two other community members on this issue (however they prefer not to responding directly here), one is a core contributor to Mozilla and Common Voice and another one is linguistic who use our clip DB on their AI related project. The opinion is -
> 
>     * "It depends, it's not that bad for their opinion. Perhaps some people will have more strict criteria",
> 
>     * "Grammar problem such as missing subject does not affect the usability of the corpus on model training at all".

Please check my examples again, I only gave 26 examples and there are 11 imperfect sentences. 
Certainly missing subject or object may not affect the usability, however, some of the sentences are completely wrong. What if I training a voice recognization model with sentences like "music was taken the position by Qian Zhuming"or "The name of XXX is XXX reunited"? How can machine understand human-incomprehensible sentences？

Regards

**Comment by RuikangSun** [comment]
> 
> 
> According to your above evaluate, problem rate of completion problem are 6 out of 100, and grammar error rate are 5 out of 100. 11% does meet the criteria of 10% error rate when we fetch sentences last year.
> 
> For these sentences you point out, I believe they all came from Wikipedia directly withouy any modification other than convert of Traditional Chinese > Simplified Chinese (in order to fix mixed character set problem). I think it would be nearly impossible to automatically remove them with a set of machine-operational rules. It would require a manual process for native speakers to go through all of these sentences if we would like the corpus to not have those kinds of sentences.
> 
> I had also inquiry with two other community members on this issue (however they prefer not to responding directly here), one is a core contributor to Mozilla and Common Voice and another one is linguistic who use our clip DB on their AI related project. The opinion is -
> 
>     * "It depends, it's not that bad for their opinion. Perhaps some people will have more strict criteria",
> 
>     * "Grammar problem such as missing subject does not affect the usability of the corpus on model training at all".

我的英語表達可能不夠好，請您見諒。但是11/26的錯誤比率，與“国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来”這樣明顯不符合國語規範的語句，顯然不應該出現在數據集裡面。

**Comment by irvin** [comment]
> 我的英語表達可能不夠好，請您見諒。但是11/26的錯誤比率，與“国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来”這樣明顯不符合國語規範的語句，顯然不應該出現在數據集裡面。

上面抽樣一百句的原意是要知道，以你的標準而言，錯誤率大約是多少；樣本多一點，呈現出來的結果，比較有統計上的意義。
The reason for randomly selected 100 sentences for you to check, is to evaluate how much error rate according to your criteria. Bigger samples are used to ensure it's statistic reasonable.

Common Voice 資料庫的主要目標是「收集足夠的帶文本資料的錄音，用以訓練聲音轉文字的語音辨識模型」。此一目的下，就算句子有文法問題或內容錯誤，仍然可以用以訓練 speech-to-text。因此上面有提到另一位老師的意見是「就算文法有錯誤，也沒有關係」。（對於中文來說，其實只要句庫有含括約一千五百個發音，也就足以作為語音輸入訓練之用。）

The main goal of the Common Voice database is to collect enough voice clips (with corresponding text) to train the voice to text AI model. For this application, even the sentences had grammar or content error, it won't affect the model's training. That's why another researcher had mentioned that "it's fine for those sentences with grammar error". (For Chinese STT model, in fact, it's enough for us to just cover all 1500 pronunciations.)

當然，不排除其他人會將 Common Voice 的資料庫用於其他用途，句子的合理性可能就會有影響。

Of course, if people took Common Voice to build things other than training stt model, the correction will have some negative effect.

這些字串全都擷取自維基百科，唯一能夠完全避免錯漏或難句的方法，只有人工一句一句看過進行篩選（即是繁體中文句庫目前的做法）；但是以 common voice 當時的需求（於短時間內加入 15 萬句），人工篩選顯然無法做到。

All of those sentences came from Wikipedia, the only way to avoid the misleading or sentences with grammar problems is manual review all of them one by one (that's what we keep doing for zh-tw corpus.) But for corpus size required for Common Voice at the time (add 150K sentences) manual review won't work obviously.

**Comment by RuikangSun** [comment]
> 
> 
> > 我的英語表達可能不夠好，請您見諒。但是11/26的錯誤比率，與“国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来”這樣明顯不符合國語規範的語句，顯然不應該出現在數據集裡面。
> 
> 上面抽樣一百句的原意，是想要知道以你的標準而言，句庫的錯誤率大約是多少；樣本多一點，呈現出來的結果，比較有統計上的意義。
> The reason for randomly selected 100 sentences for you to check, is to evaluate how much error rate according to your criteria. Bigger samples are used to ensure it's statistic reasonable.
> 
> Common Voice 資料庫的主要目標是「收集足夠的帶文本資料的錄音，用以訓練聲音轉文字的語音辨識模型」。此一目的下，就算句子有文法問題或內容錯誤，仍然可以用以訓練 speech-to-text。因此上面有提到另一位老師的意見是「就算文法有錯誤，也沒有關係」。（對於中文來說，其實只要句庫有含括約一千五百個發音，也就足以作為語音輸入訓練之用。）
> 
> The main goal of the Common Voice database is to collect enough voice clips (with corresponding text) to train the voice to text AI model. For this application, even the sentences had grammar or content error, it won't affect the model's training. That's why another researcher had mentioned that "it's fine for those sentences with grammar error". (For the Chinese STT model, in fact, it's enough for us to just cover all 1500 pronunciations.)
> 
> 當然，不排除其他人會將 Common Voice 的資料庫用於其他用途，句子的合理性可能就會有影響。
> 
> Of course, if people took Common Voice to build things other than training stt model, the correction will have some negative effect.
> 
> 這些字串全都擷取自維基百科，唯一能夠完全避免錯漏或難句的方法，只有人工一句一句看過進行篩選（即是繁體中文句庫目前的做法）；但是以 common voice 當時的需求（於短時間內加入 15 萬句），人工篩選顯然無法做到。
> 
> All of those sentences came from Wikipedia, the only way to avoid the misleading or sentences with grammar problems is manual review all of them one by one (that's what we keep doing for zh-tw corpus.) But for corpus size required for Common Voice at the time (add 150K sentences) manual review won't work obviously.

I tried to search these imperfect sentences on Wikipedia, it seems that sentences are not properly cut off from wikipedia.

For example:
The incorrect sentence "_国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局改组而来 (in common voice)_ " is from "_国家政治保卫总局的正式名称为苏联人民委员会国家政治保卫总局（俄语：Объединённое государственное политическое управление при СНК СССР，缩写为ОГПУ，拉丁转写为OGPU），它于1923年11月15日由国家政治保卫局（GPU）改组而来。 (in wikipedia)_ ".

The incorrect sentence _"吓跑组合演唱的歌曲 (in common voice)_ " is from _"吓跑（英语：Running Scared，也可被译为惊慌逃跑）是一首由阿塞拜疆二人组合Eldar & Nigar（也叫"Ell and Nikki）组合演唱的歌曲。 (in wikipedia)_ ".

Regards

**Comment by irvin** [comment]
It seems that the sentences came from some kind of mismatching of () at that time. 

However, I don't think it's possible to systematically filter out all of those sentences now. We will depend on the reporting from the contributor during their records.

**Comment by RuikangSun** [comment]
Close old issues.
