### ISSUE TITLE
Change the schedule on the home page

### ISSUE THREAD

**Issue by deevroman** [common-voice/common-voice#2870]
If you quickly look at this chart from the home page, you will see that there are fewer records. It seems to me that it is better to replace it with a graph of records by periods, or to use text instead of the current graph.
<img width="577" alt="Снимок экрана 2020-08-08 в 19 49 46" src="https://user-images.githubusercontent.com/25708359/89716193-b0fd8700-d9b3-11ea-9f28-4939e58950fa.png">

**Comment by phirework** [comment]
This was fixed a while ago and I forgot to check back, sorry! It now reflects the last year in 3 month intervals, so it's no longer a pseudo-logarithmic scale. Thanks for the suggestion!
