### ISSUE TITLE
"Contribution Activity" and "Top Contributors" don't display properly on mobile website dashboard

### ISSUE THREAD

**Issue by jpear1** [common-voice/common-voice#2880]
Many of the dashboard menu items don't fit in their boxes properly on the mobile website. The language select dropdown hangs out of its container, "Recorded clips" and "Validated clips" are misaligned, the times on the contribution history overlap with each other.

**To Reproduce**
1. Log in on a phone
2. Navigate to your dashboard
3. Scroll down to "Contribution Activity" and "Top Contributors"
4. Observe bug

**Screenshots**
<img src=https://user-images.githubusercontent.com/26498132/90681837-ea868b80-e218-11ea-9b06-f85334f25bfb.png width=300px>

**Device Info**
 - OS: Android 10
 - Firefox Mobile 68.11.10

**Comment by GauravPandey892** [comment]
Hi, I would like to work on this issue.

**Comment by Dnouv** [comment]
@gauravpandeypes, are you still working on this issue? If not, please let me know. I would like to work on this issue.

**Comment by gauravpandeypes** [comment]
@Dnouv I am not working on this anymore.

**Comment by Dnouv** [comment]
Thank you for your reply, @gauravpandeypes. Now then, I will resume working on this issue.
