### ISSUE TITLE
Using common voice application to collect TTS data

### ISSUE THREAD

**Issue by bayethiernodiop** [common-voice/common-voice#2883]
Hi folks, what are the modifications needed to use common voice application (After forking the project for local usage) for TTS data collection with two actors using the same text data set for recording?
Thanks

**Comment by dag7dev** [comment]
What are you talking about? Which application?

**Comment by phirework** [comment]
It sounds like you're looking to change the sentence set offered to users on your local instance, in which case you would need to modify what's inside `/server/data` (I'd recommend deleting everything but the language you want, and creating a new text file inside the relevant language folder that has your specific dataset.) You'll also need to ensure that `IMPORT_SENTENCES` is turned on (refer to [DEVELOPMENT.md](https://github.com/common-voice/common-voice/blob/main/docs/DEVELOPMENT.md) for more info). 

Please note that we do not provide support for forked or third party copies of the app, so I'm going to close this issue. Thanks!
