### ISSUE TITLE
Audio recording fails to load on clip validation

### ISSUE THREAD

**Issue by MazeChaZer** [common-voice/common-voice#2894]
**Describe the bug**
Example: https://voice-prod-clips-393eefd0cba28c270ced0f9587a4f6ae601ca91e.s3.dualstack.us-west-2.amazonaws.com/4c373add-fada-4bd2-8a09-3263fc3d596b/256b473b2f43e0ebbb9cb62380e96832a6a50dabbd532e0d422c5bdc38c0e2b8.mp3 (I removed the authentication query parameters).

The response is a 200 OK, but the console in my Firefox says "Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable."

And you probably don't see the exceptions because Sentry fails to submit the report with the error message `{"error":"Invalid origin: https://commonvoice.mozilla.org"}` and HTTP 403.

This is very unfortunate, because in the UI it looks like the sample is playing but one cannot hear anything. This could potentially lead a lot of people to discarding good samples just because the audio failed to load, which is not communicated via the UI.

**To Reproduce**
This happens randomly, I can see no pattern.

**Expected behavior**
The UI should clearly communicate that the audio file failed to load and let the user choose between retry loading and skipping the sample. Also the exception should be properly reported by Sentry.

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 80.0

**Additional context**
This problem also happened to some other people when they tried to validate samples.

**Comment by phirework** [comment]
Thanks for this detailed report @MazeChaZer! Is there a pattern to when you get these resource exceptions? For example, a common problem we're trying to resolve is that it may be when the Common Voice tab has been left alone for a long period of time and the auth token expires and I'm curious if this is part of that issue. 

Thanks for flagging that Sentry is blocked, I've fixed that on our end.

**Comment by MazeChaZer** [comment]
Unfortunately I was not able to see a pattern. I'm pretty sure expired auth tokens are not the problem, because after skipping a few recordings it was working again, I did not have to re-login to make it work.

**Comment by phirework** [comment]
Ah sorry, by "auth token" I mean the token that S3 generates for each file (i.e. the query parameters you removed from the link above). If the recordings work again after you skipped a few clips it most likely means you've gone through all the files in the cache with expired tokens and got new links. 

Thanks, I'll look into this.

**Comment by inputvalidation** [comment]
I have similar issues. Tried both the latest Chrome and Safari on macOS.

**Comment by phirework** [comment]
Hey everyone, there were some issues without AWS IAM provisions that was likely causing these issues. We've pushed a fix earlier in the year, so I'm going to close this issue for now. Feel free to reopen if you're still experiencing the problem.
