### ISSUE TITLE
Stereo (2 Channel) Data Breaking DeepSpeech

### ISSUE THREAD

**Issue by hjortnaes** [common-voice/common-voice#2906]
**Describe the bug**
There are mp3s in the Russian dataset which convert into stereo wav files. I've listed the relevant files below. This breaks common voice, where I originally reported this bug, and they sent me here. 

Breaking files: (mp3 names should be the same with different extension)

- common_voice_ru_21795256.wav
- common_voice_ru_21795273.wav
- common_voice_ru_21795390.wav
- common_voice_ru_21795397.wav
- common_voice_ru_21795399.wav
- common_voice_ru_21795400.wav
- common_voice_ru_21801847.wav
- common_voice_ru_21802110.wav
- common_voice_ru_21802116.wav
- common_voice_ru_21802126.wav
- common_voice_ru_21802132.wav

**To Reproduce**
1. Go to clips repo
2. use soxi to see the files have 2 channels

For DeepSpeech specifically:
1. Convert files with DeepSpeech's bin/import_cv2.py
2. soxi will show converted files have 2 channels
3. DeepSpeech fails to run

**Expected behavior**
Mono sound files

**Desktop or Mobile (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server 7.8 (Maipo)

**Comment by phirework** [comment]
Closing as these have been converted in the most recent version of the dataset release. Please file any further issues with data encoding to https://github.com/common-voice/cv-dataset, thanks!
