### ISSUE TITLE
Speech vs Voice Recognition [non-technical]

### ISSUE THREAD

**Issue by sirlantis** [common-voice/common-voice#291]
To people how know the difference the copy is sometimes confusing, as it uses speech recognition and voice recognition as if they were the same.

I understand for marketing reasons it might make more sense to use "voice" more often, but this inaccuracy really confused me when trying to understand the intent of the project.

On the home page:

> a project to help make voice recognition open to everyone [...] an open-source voice recognition engine

On the FAQ page:

> **Voice recognition** technology could revolutionize the way we interact with machines, but it’s expensive and proprietary. Common Voice is a project to make voice recognition technology easily accessible to everyone.

But then at the bottom of the FAQ page:

> required to train a production STT system.

I'm happy to put up a PR normalizing this, if you agree that this should be fixed.

**Comment by mikehenrty** [comment]
We would love a PR with some language suggestions!
