### ISSUE TITLE
Download My Data does not present a zip link, only a profile.txt

### ISSUE THREAD

**Issue by caseybasichis** [common-voice/common-voice#2911]
Clicking "Download My Data" in the profile page only seems to download a profile.txt

The screen remains on the profile settings "User Name" "Leaderboard Visibility" etc

What am I missing?

**Comment by dag7dev** [comment]
What's up? What is wrong? This is the behaviour expected.

**Comment by ftyers** [comment]
I think @caseybasichis means that they would like to download their recordings. I think this is a good feature, but it is not available in Common Voice at the moment.

**Comment by ftyers** [comment]
Update: #2865 appears to solve this.

**Comment by caseybasichis** [comment]
Looks like they're still talking it out.

**Comment by Heyhillary** [comment]
Hey @caseybasichis 

Thanks for your suggestion on release [1.570](https://github.com/common-voice/common-voice/releases/tag/release-v1.57.0), we rolled out a feature that allows you to download your own voice clips via your profile. If you have issues accessing your own data please feel free to re-open this request or create another.
