### ISSUE TITLE
Validation on local setup using docker and s3proxy

### ISSUE THREAD

**Issue by skanderbenalaya** [common-voice/common-voice#2916]
Hi, I came across this project and enjoyed it a lot. I wanted to install it locally and followed the contribution.md but i'm always stuck at empty listen validation message.
Tried various things, like editing host file and redirect http://s3proxy to localhost to avoid CSP issue but still nothing.
Does anyone know how to run s3proxy locally to retrieve the stored data ?

**Comment by phirework** [comment]
Hi there, when you first install it locally there's nothing in your local DB to validate. You have to record your own audio to test out validation. The app also will not let you validate your own recordings, so you have to validate from a different account (or using an incognito window) than the one you recorded on.

**Comment by skanderbenalaya** [comment]
Thank you for your answer
When i do that, i can see now the sentences that i did the recordings with, but the mp3 files are blocked by the CSP
Refused to connect to 'https://sentry.prod.mozaws.net/api/491/store/?sentry_key=4a940c31e4e14d8fa6984e919a56b9fa&sentry_version=7' because it violates the following Content Security Policy directive: "connect-src 'self' https://pontoon.mozilla.org/graphql https://*.amazonaws.com  https://*.amazon.com http://localhost:9090/ https://www.gstatic.com https://www.google-analytics.com https://sentry.io https://basket.mozilla.org https://basket-dev.allizom.org".

**Comment by phirework** [comment]
Sentry has nothing to do with MP3s or your local S3 server, it's an external monitoring and alerting system. Are you able to see the MP3 files inside of the Docker container?

**Comment by skanderbenalaya** [comment]
Yeah i tried to navigate to them using the s3proxy cli and saw them inside the corpus folder, i have also many console errors when trying to get the mp3 files like :
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://s3proxy/common-voice-corpus/7cf487f9-ef6c-4ae4-b4b2-f0647d04dba8/b0a388cbcf2a6a44cbdf63df49c5424484d11c9a38fdbe6aae2cea379fe648f6.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=local-identity%2F20181014%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20181014T150341Z&X-Amz-Expires=43200&X-Amz-Signature=32294dffdf7b6cd1bae8d78513e6a3a2e6a7fceb71b07e4e1d6a12c152ecc50e&X-Amz-SignedHeaders=host. (Reason: CORS request did not succeed).

**Comment by phirework** [comment]
Hey, sorry for the long delay, we've made a few updates to the Docker install config recently, please rebuild your images and try with the new configuration. (See [release notes](https://github.com/common-voice/common-voice/releases/tag/release-v1.43.0) if you run into an issue with MySQL versioning). Closing for now.
