### ISSUE TITLE
Correct inappropriate link text

### ISSUE THREAD

**Issue by sinumade** [common-voice/common-voice#2928]
<p>Related: <a href="https://github.com/mozilla/common-voice/issues/2911">Download My Data does not present a zip link, only a profile.txt · Issue #2911</a></p>

<p>I mentioned it in <a href="https://discourse.mozilla.org/t/download-my-data-broken/68705/4">Post #4 on "Download My Data" broken? - Common Voice - Mozilla Discourse</a>.</p>

<h2>1. Profile page, "Download My Data"</h2>
<blockquote cite="https://discourse.mozilla.org/t/download-my-data-broken/68705/4">
<p>If it says <b>Download My Data</b> people will misunderstand that it's supposed to download their own <strong><em>recordings</em></strong> (yes, sure, we're on the <strong><em>profile</em></strong> page. But how many people would care about that? And since we can delete the voice data from this page, it's only natural to assume that we can download it as well!). I'm sure there are others out there who are wondering about this.
<br>It should be <strong>reworded</strong> to say something like "Download my profile settings" and indicate that the <strong>output will be in a text file</strong>.</p>
</blockquote>

<h2>2. Recording page, "Share your clip"</h2>
<blockquote cite="https://discourse.mozilla.org/t/download-my-data-broken/68705/4">
<p>The same goes for <b>Share your clip</b> button on the recording page. It clearly says "<strong><em>clip</em></strong>". But what it <strong>actually provides is a link to promote <a href="https://commonvoice.mozilla.org/">commonvoice.mozilla.org</a></strong>.
<br>Of course this was meant to say "<em>Tell people that your clips are available</em>". But it can be <strong>misleading</strong>. Why did we make the text so confusing? Why can't we just "Share the Common Voice project"?</p>
</blockquote>

<p>Do we need a "link to promote" <strong><em>during</em> the recording</strong> in the first place?</p>

<hr>

<p>If everything is fine as it is, the designer should show <strong><em>why</em></strong>.
<br>Unnecessary designs are distracting to users and add unnecessary worry. Task execution should be the first priority.</p>

**Comment by ftyers** [comment]
There is an in-progress PR here: #2865.
