### ISSUE TITLE
add pt-PT and pt-BR to Portuguese accent

### ISSUE THREAD

**Issue by Terramoto** [common-voice/common-voice#2931]
Hello,

I would like pt-PT and pt-BR to be added as a common voice accent option for the dataset of profile in commonvoice platform as some words have different meanings, different pronunciation and also context.

**Comment by ftyers** [comment]
Portuguese is also spoken in Angola, Mozambique and Timor-Leste (among other places), and there are various accents in Brazil and Portugal too, so it might be better to go finer grained than just "BR" and "PT".

**Comment by Terramoto** [comment]
> Portuguese is also spoken in Angola, Mozambique and Timor-Leste (among other places), and there are various accents in Brazil and Portugal too, so it might be better to go finer grained than just "BR" and "PT".

This other countries use part of the portuguese with their native language while PT and BR use it all but some words have different meanings and the phonemes are different,for interpretation the whole dataset can be used,but to use in a tts environment it needs to be split.The senteces used in PT and BR are pratically the same so when it comes to implementation it's easier than all portuguese languages at the same time,this is my assumption.

**Comment by paulagoes** [comment]
I also think this is important, as the pronunciation is very different between European Portuguese and Brazilian Portuguese. It would be great if the users could self-identify their accents in the profile.

**Comment by Heyhillary** [comment]
Hey @Terramoto and @paulagoes 

Thanks for request.

As of December 2021, people can now add their accents when creating profiles. 

We recently shared with the community the opprtunity to decide variants for languages. Please [check out ](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/)the blog to learn more. 

If you are intrested in being involved in this process, please subscribe to our [weekly updates](https://discourse.mozilla.org/t/weekly-update-thread-2021-2022/84411) on discourse.

I'm going to close this issue, for now if you have any questions related to this issue please feel free message on commonvoice@mozilla.org
