### ISSUE TITLE
Fonts doesnt show central kurdish texts as normal

### ISSUE THREAD

**Issue by jwtiyar** [common-voice/common-voice#2940]
Hey
I changed the interface of common voice to central kurdish, Now the texts are misaligned correctly, the problem should the font used to render kurdish texts. Because in one page for example one paragraph is correctly rendered another part is not.
These are some screenshoot to show what i mean exactly:

[1](https://ibb.co/ZfKL6wy)
another one that part of it is correct and another not:
[2](https://ibb.co/HG1J5b5)

**Comment by phirework** [comment]
Hi, just to make sure I'm understanding correctly, in both of the paragraphs you circled in the first screenshot as well as the first paragraph in the second screenshot, the issue is that the alignment of the text is spaced out too wide? Is there another example on the site of where the font is correctly rendering?

**Comment by jwtiyar** [comment]
Yes in first screen shoot both paragraph in circle are spaced out, Second screenshoot the top circle is wrong and bottom one is correct.
Another example:
These in circle are worng rendered:
https://ibb.co/Sc9gWZ0
And this paragraph all correctlt aligned:
https://ibb.co/0KwTgsb

**Comment by jwtiyar** [comment]
This should make problem for persian also as far as i know, Because persian and central kurdish have some characters that will not be rendered correctly.

**Comment by jwtiyar** [comment]
After testing other browsers and os, Looks like it's Firefox problem to rendering correct font for kurdish.

**Comment by phirework** [comment]
Update - having discussed this with the engineers responsible for font rendering on Firefox, it's been determined the best solution would be to apply a `lang` dependent CSS rule to set a non Zilla-slab font for languages with cyrillic characters. Fix forthcoming.

**Comment by phirework** [comment]
Can you verify whether this fix on the dev server works? I've selectively enabled using Open Sans for all ckb text https://dev.commonvoice.allizom.org/ckb

If this works, it'll be deployed on production in a couple of weeks.

**Comment by jwtiyar** [comment]
> Can you verify whether this fix on the dev server works? I've selectively enabled using Open Sans for all ckb text https://dev.commonvoice.allizom.org/ckb
> 
> If this works, it'll be deployed on production in a couple of weeks.

Sorry for late reply 
Now it works on dev and stable server.
Thank you .

**Comment by phirework** [comment]
This is now on production! Thanks for reporting.
