### ISSUE TITLE
New language requests : Mossi language proposal

### ISSUE THREAD

**Issue by Yamwend** [common-voice/common-voice#2945]
**Language name : Mossi**

**Language code**
ISO-639-3 : **mos**

**Language size : nearly 30 million (2020)**

**Plural forms**
0 rocks : Pĩis zaalem (0)
1 rock : Pĩig a  yembre (1)
2 rocks : Pĩis a  yiibu (2)
3 rocks : Pĩis a tãabo  (3)
4 rocks : Pĩis a naase (4)
5 rocks : Pĩis a nu (5)
10 rocks : Pĩis piiga (10)
20 rocks : Pĩis pisi (20)
100 rocks : Pĩis  koabga (100)
1000 rocks : Pĩis tusri (1000)
I see 0 rocks on the ground : Mam nee pĩig  zaalem (0) tẽn-gãongã zugu
I see 1 rock on the ground : Mam nee pĩig a yembr (1) tẽn-gãongã zugu
I see 10 rocks on the ground : Mam nee pĩis piig (10) tẽn-gãongã zugu
I see rocks on the ground : Mam nee pĩis tẽn-gãongã zugu

**Pontoon manager**
https://pontoon.mozilla.org/contributors/cwdgzy5XMJZ2ucNImfqygXU9PyI/

**Comment by ftyers** [comment]
Dear @Yamwend, I'm just writing to let you know that Common Voice hasn't forgotten about this request. There were [changes at Mozilla last year](https://discourse.mozilla.org/t/mozilla-org-wide-updates-impacts-on-common-voice/65612/11) which meant that the project has a lot less bandwidth for taking on new language requests. And now there is a [pause until next month](https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526). Rest assured that we are very keen to support Mossi and will update here when it becomes possible with the resources we have! Thanks for your interest! :)

**Comment by mbransn** [comment]
@peiying2 I've reviewed this request and it's approved by the CV product team for ingestion with Pontoon. Thanks!

**Comment by peiying2** [comment]
@Yamwend The CV project is now enabled for [Mossi](https://pontoon.mozilla.org/mos/common-voice/), your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by Yamwend** [comment]
We are very pleased to learn that the request has been validated. Thank you
for your interest in our request. The consideration of the Mossi language
by the CV community is a huge step forward for our work.  We are delighted
to collaborate with the entire CV community and to contribute to Mozilla's
initiative to help teach machines how humans speak in general and to build
a Mossi language dataset.

Translated with www.DeepL.com/Translator (free version)

**Comment by phirework** [comment]
Thanks everyone!
