### ISSUE TITLE
The sentence is incomplete

### ISSUE THREAD

**Issue by peiying2** [common-voice/common-voice#2947]
**Describe the bug**
You can find the string here: https://pontoon.mozilla.org/it/common-voice/web/locales/en/messages.ftl/?string=217170. `... If the voice recording you hear matches the words written onscreen.`

**Expected behavior**
Missing the main part of a sentence.

**Comment by peiying2** [comment]
@phirework

**Comment by phirework** [comment]
Ha, good catch. @mbransn this was in the original spec, do you know what the copy was supposed to have been? 

![Screen Shot 2020-12-16 at 15 03 43](https://user-images.githubusercontent.com/582683/102400445-f0fef700-3faf-11eb-8d46-a07736ac8f8e.png)

**Comment by mbransn** [comment]
Ah, interesting -- human error on my end, apologies all. Here's that section with the last sentence reworked:

> If you prefer to review other people's voice contributions, click on the play icon. You’ll help confirm that recordings match the sentences written on screen.

Also updated in the [Figma spec](https://www.figma.com/file/noKMY6aOXz9vwxlkO0XZEl/Tablet-Demo-Mode-UI?node-id=0%3A2870).
