### ISSUE TITLE
Reported issues will be sent back the user to be reviewed again when a new session is started

### ISSUE THREAD

**Issue by Steinhagen** [common-voice/common-voice#2972]
**Describe the bug**
Reported issues are always first to be reviewed again. These statements are the same (including the audio voice) every time.

**To Reproduce**
1. Go to 'https://commonvoice.mozilla.org'
2. Login to your account.
3. Select your desired language (in this case Romanian since it doesn't have a lot of pending voice clips to be reviewed)
4. Click on 'Listen' (-> https://commonvoice.mozilla.org/ro/listen)

**Expected behavior**
You should always see new strings that you haven't reviewed yet.

**Observed behavior**
The first strings you are getting to review are the ones that you already reported for different reasons (offensive or bad grammar).
At the present time, in the first 40 strings I get, 4/5 of them are strings that I already reported as being wrong (grammatical issues etc)

**Desktop or Mobile (please complete the following information):**
 - OS: Linux (Fedora Silverblue)
 - Browser Firefox
 - Version 84

 - OS: Android 8
 - Browser Samsung Internet Browser

 - OS: Android 8
 - 'CV Android'

**Additional context**
I remember that a particular bad phrase (offensive + bad grammar) I received it twice on my Linux machine, once on the Android browser instance and twice on the 'CV Android' application to review. All within a 2 days span.

**Comment by phirework** [comment]
Hi there, this is fixed as of the latest release. Please let me know if you experience it again. Screening for reported clips/sentences will be tied to your profile (or the current session if you're not logged in), so if you're contributing anonymously on different devices you may still see some duplicates.
