### ISSUE TITLE
Some CV web fonts are composing words using cedilla instead of comma (like they were translated)

### ISSUE THREAD

**Issue by Steinhagen** [common-voice/common-voice#2973]
**Describe the bug**
Some 'Common Voice' fonts used for the web interface are displaying cedilla composed words instead of the comma ones (like it's correct for the Romanian language)
https://en.m.wikipedia.org/wiki/Romanian_alphabet#Comma-below_(ș_and_ț)_versus_cedilla_(ş_and_ţ)

**To Reproduce**
1. Go to 'https://commonvoice.mozilla.org/ro/speak'

**Expected behavior**
All composed comma words (ș and ț) shouldn't be displayed as their cedilla alternatives.

**Screenshots**
![web-interface](https://user-images.githubusercontent.com/4029937/103175238-28ec2100-4871-11eb-85e9-d7f42d663763.png)
![pontoon-translate-1](https://user-images.githubusercontent.com/4029937/103175248-32758900-4871-11eb-80a4-980abe724e83.png)
![pontoon-translate-2](https://user-images.githubusercontent.com/4029937/103175243-2db0d500-4871-11eb-9e2b-0673426daf61.png)

**Comment by phirework** [comment]
Can you verify whether this fix on the dev server works? Romanian should now be using Inter for sans-serif and Noto Serif for serif font faces https://dev.commonvoice.allizom.org/ro

If this works, it'll be deployed on production in a couple of weeks.

**Comment by Steinhagen** [comment]
I played a bit with it and it looks great! Thanks for fixing this.

**Comment by phirework** [comment]
This is now on production! Thanks for reporting.
