### ISSUE TITLE
the metadata files for English do not have 'male' labels

### ISSUE THREAD

**Issue by srcj** [common-voice/common-voice#2976]
I downloaded the CommonVoice Corpus 6.1 for English and I didn't find any 'male' labels in the metadata files (tsv files),  I only found entries with the label 'female' or empty label for the attribute gender. I suppose this is a bug, because the stats for this dataset indicate 47% Male data. I'd appreciate this to be fixed in order to be able to do experiments using the gender class.

**Comment by phirework** [comment]
Hello! This was an issue with the 6.0 release (released Dec 16th, 2020), which was fixed in 6.1 (released Dec 22nd, 2020).  Can you check and see the file creation date of the `*.tsv` files? If it was before Dec 17th, 2020, then I think you might have the 6.0 version still.

**Comment by srcj** [comment]
Thanks for reply. I've checked that my downloaded version seems to be 6.0.
But in the datasets download web page, the date realease of the the current dataset (named Common Voice Corpus 6.1) is 2020-12-11. I haven't tried to download again this dataset, but it may happen that the downloadable dataset file hasn't been updated to the correct version 6.1

**Comment by phirework** [comment]
Ah, I understand the confusion. The date is 12-11 for both because that is the cut-off time for recordings, i.e. nothing recorded after December 11th is in the dataset. If you try to download the latest version, the actual tar file itself will be labeled as `cv-corpus-6.1-2020-12-11.tar.gz`.
