### ISSUE TITLE
Mic settings are forgotten every time I leave the tab

### ISSUE THREAD

**Issue by wolfpurplemoon** [common-voice/common-voice#2978]
**Describe the bug**
I'm using Common Voice on Firefox on Windows 10 and whenever I click out of the tab it forgets my mic preferences and I have to delete mic permissions, refresh the page and choose the mic again

**To Reproduce**
1. Go to 'Speak'
2. Click on 'Record'
3. Click to a different tab
4. Return to Common Voice tab and find the mic icon in the URL bar is flashing red

**Expected behavior**
The site should remember my mic choice, as I tick the box that should save this option

**Screenshots**
![image](https://user-images.githubusercontent.com/10601382/103657260-97ac3700-4f61-11eb-8bbc-2bfc382a4f91.png)
![image](https://user-images.githubusercontent.com/10601382/103657330-adb9f780-4f61-11eb-95e4-ee9e89970cf8.png)
![image](https://user-images.githubusercontent.com/10601382/103657396-c75b3f00-4f61-11eb-9a4b-5c708f427a8d.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.1

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Webcam 
 - Model: Logitech C920

**Additional context**
The site also forgets my goals

**Comment by phirework** [comment]
Thanks for moving this issue here! Have you tried updating Firefox to see if it makes a difference? 85 is the latest version. The site itself doesn't handle store hardware permissions, that's a browser-level setting. 

Also, when you say the site forgets your goals, which of the following do you mean?

1. You try to create a goal, it doesn't save
2. You try to create a goal, it saves, and the goal doesn't show up in that same session 
3. You try to create a goal, it saves, the goal works in that session, and when you come back the next day it's missing

**Comment by wolfpurplemoon** [comment]
I'm now on 84.0.2 and the issues are still there, I don't have any add ons that could be causing issues that I'm aware of, and I've not had reason to allow mic settings in browser for any other sites so I don't know how other sites handle it, I do have a programme called Many Cam that emulates cam/mic though, I'll see if disabling that does anything

the goals seem to save but are gone when I come back to the dashboard and return to saying "Create a custom goal"

**Comment by wolfpurplemoon** [comment]
I've now uninstalled manycam and the browser is remembering my mic finally, the goals are still disappearing every time I navigate off the goal page though

**Comment by phirework** [comment]
Great to hear the mic settings are working. It sounds like the goals problem may be the same as #3017, so I'm going to close this issue and direct further troubleshooting to that issue so that we can keep track of it more easily.
