### ISSUE TITLE
Design and Document a Common Voice API

### ISSUE THREAD

**Issue by mbebenita** [common-voice/common-voice#298]
We've discussed this before and I wanted to capture it as an issue we can track. The idea here is to expose an API so that others can use to develop creative ways of donating voice data. To make this work, we'll need to make sure we segregate data from different sources (based on API keys) until we verify that the proper legal / privacy disclaimers are shown.

**Comment by mikehenrty** [comment]
Note: #245 would depend on this.

**Comment by poulad** [comment]
Following #245, I'd like to develop chat bots for common voice.
Is there any progress on this issue?
