### ISSUE TITLE
Non-native speaker option

### ISSUE THREAD

**Issue by TiffanySantos** [common-voice/common-voice#2983]
**Is your feature request related to a problem? Please describe.**
Many people speak other languages, they are non-native speakers.

**Describe the solution you'd like**
An option to tag yourself as a non-native speaker of a language.

**Describe alternatives you've considered**
To encourage people to contribute without feeling alienated they should be able to select language: foo, accent: non-native speaker. Else the accent option should be removed (it appears to only allow people to tag their accent in some languages anyway, not all of them).

**Additional context**
![Screenshot 2021-01-15 at 21 06 21](https://user-images.githubusercontent.com/47302131/104773617-9d7df580-5775-11eb-88aa-918a984daeca.png)

**Comment by SeinopSys** [comment]
I'm in the same boat, I have pretty great English despite not being a native but I have no clue what kind of accent to select so I'm just leaving it off my profile for now

**Comment by paulagoes** [comment]
I was thinking about this too. Maybe we could have a lable "World English"?
https://en.wikipedia.org/wiki/International_English

**Comment by JuanGrados** [comment]
Maybe an option would be to have the additional languages being tagged by the mother tongue of the speaker?
