### ISSUE TITLE
LOCALIZATION REQUEST: Adding Pashto to Pontoon

### ISSUE THREAD

**Issue by zalaan-dev** [common-voice/common-voice#2990]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
Pashto

**Language code**
ps

**Language size**
50-60 million

**Plural forms**

0 rocks  =  ۰ ډبرې
1 rock = ۱ ډبره
2 rocks = ۲ ډبرې
3 rocks = ۳ ډبرې
4 rocks = ۴ ډبرې
5 rocks = ۵ ډبرې
10 rocks = ۱۰ ډبرې
20 rocks = ۲۰ ډبرې
100 rocks = ۱۰۰ ډبرې
1000 rocks = ۱۰۰۰ ډبرې
I see 0 rocks on the ground = زه ۰ ډبرې پر ځمکه وینم
I see 1 rock on the ground = زه ۱ ډبره پر ځمکه وینم
I see 10 rocks on the ground = زه ۱۰ ډبرې پر ځمکه وینم 
I see rocks on the ground = زه پر ځمکه ډبرې وینم
_*Other contextual forms*_
The rocks are blue =  د ډبرو رنګ شین دی
The rock is blue = د ډبرې رنګ شین دی
 
**Pontoon manager**
https://pontoon.mozilla.org/contributors/JDSAcyEoJyljCWprm5ApIdebWPs/

**Comment by zalaan-dev** [comment]
**Note** 
The numbers in the Pashto translation should appear before the word as Pashto is Right - Left language. I tried but GitHub reserved the numbers. Also, Pashto uses Arabic numerals in addition to Arabic-Indic. Both number systems should appear in front of the translated words in the above examples.

**Comment by ftyers** [comment]
Dear @zalaan-dev, I'm just writing to let you know that Common Voice hasn't forgotten about this request. There were [changes at Mozilla last year](https://discourse.mozilla.org/t/mozilla-org-wide-updates-impacts-on-common-voice/65612/11) which meant that the project has a lot less bandwidth for taking on new language requests. And now there is a [pause until next month](https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526). Rest assured that we are very keen to support Pashto and will update here when it becomes possible with the resources we have! Thanks for your interest! :)

**Comment by mbransn** [comment]
@peiying2 I've reviewed this request and it's approved by the CV product team for ingestion with Pontoon. Thanks!

**Comment by zalaan-dev** [comment]
> Dear @zalaan-dev, I'm just writing to let you know that Common Voice hasn't forgotten about this request. There were [changes at Mozilla last year](https://discourse.mozilla.org/t/mozilla-org-wide-updates-impacts-on-common-voice/65612/11) which meant that the project has a lot less bandwidth for taking on new language requests. And now there is a [pause until next month](https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526). Rest assured that we are very keen to support Pashto and will update here when it becomes possible with the resources we have! Thanks for your interest! :)

**Comment by zalaan-dev** [comment]
Thanks

**Comment by peiying2** [comment]
@zalaan-dev The CV project is now enabled for Pashto. Since I don't read the Arabic script, I assume the plural and singular rules are similar to that of Farsi. Let me know if it is not, and which other language it is similar to.

You are the locale manager as well as a translator. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by zalaan-dev** [comment]
@peiying2 Thanks for sharing the additional resources. While Pashto and Farsi share some Arabic vocabulary, Pashto is grammatically or even linguistically quite different than Farsi or Arabic. Pashto shares roots with other Indo-European languages - Greek, Hindi, etc. So no, the plural and singular rules are not the same.  

I will try to encourage other folks, but the few expert translators I know are stretched across other localization projects. Rest I assure, I will be giving this translation my 100%. Years of Pashto localization work for Raspberry Pi, Moodle, Uridu, MIT Scratch, and translation work for Google Translate and Microsoft Translator has helped me prepare for projects like these. I am currently Pashto language maintainer on several large scale projects, including those mentioned above. I also find the Pontoon user interface quite intuitive compared to Crowdin or Transifex. Thanks for the support.

**Comment by peiying2** [comment]
> @peiying2 Thanks for sharing the additional resources. While Pashto and Farsi share some Arabic vocabulary, Pashto is grammatically or even linguistically quite different than Farsi or Arabic. Pashto shares roots with other Indo-European languages - Greek, Hindi, etc. So no, the plural and singular rules are not the same.

Thank you for shedding some lights on the singular/plural rules. Do you mind writing the "rocks" numbers in the initial request in English, so I can figure out where the differences are? 
> 
> I will try to encourage other folks, but the few expert translators I know are stretched across other localization projects. Rest assure, I will be giving this translation my 100%. Years of Pashto localization work for Raspberry Pi, Moodle, Uridu, MIT Scratch, and translation work for Google Translate and Microsoft Translator has helped me prepare for projects like these. I am currently Pashto language maintainer on several large scale projects, including those mentioned above. I also find the Pontoon user interface quite intuitive compared to Crowdin or Transifex. Thanks for the support.

Wow, I am, and I am sure all of us are, impressed by your experience and what you have accomplished. I will relay the message on your impression on Pontoon. We try to keep it simple and accessible. There are volunteers who help improve the feature too.

**Comment by zalaan-dev** [comment]
English = Literal Pashto translation in English 
0 rocks = 0 rocks  
1 rock = 1 rock
2 rocks = 2 rocks
10 rocks = 10 rocks
20 rocks = 20 rocks
100 rocks = 100 rocks
1000 rocks = 1000 rocks
I see 0 rocks on the ground = I see 0 rocks on the ground
I see 1 rock on the ground = I see 1 rock on the ground 
I see rocks on the ground = I see on the ground rocks

Singular and plural rules differ with each word. For instance, a feminine word like rock in Pashto takes these forms: 
ډبره singular, plural ډبرې
the letter ه  in the above examples changes to ې
In masculine sounding words, like house, the plural form changes differently: 
کور singular, plural کورونه، 
in the plural form of the word house, we add three letters ون‌ه

We can schedule a chat to go over these or if you have more questions. 

Here is a general summary of Pashto grammar from the Wikipedia that will hopefully explain the roots of the language: 

Grammar
Main article: Pashto grammar
Pashto is a subject–object–verb (SOV) language with split ergativity. Adjectives come before nouns. Nouns and adjectives are inflected for two genders (masc./fem.),[67] two numbers (sing./plur.), and four cases (direct, oblique, ablative and vocative). There is also an inflection for the subjunctive mood. The verb system is very intricate with the following tenses: present, simple past, past progressive, present perfect, and past perfect. The possessor precedes the possessed in the genitive construction. The verb generally agrees with the subject in both transitive and intransitive sentences. An exception occurs when a completed action is reported in any of the past tenses (simple past, past progressive, present perfect, or past perfect). In such cases, the verb agrees with the subject if it is intransitive, but if it is transitive, it agrees with the object,[18] therefore Pashto shows a partly ergative behaviour. Unlike most other Indo-Iranian languages, Pashto uses all three types of adpositions – prepositions, postpositions, and circumpositions.

**Comment by peiying2** [comment]
@zalaan-dev thank you for the detailed explanation! The plural rules (regardless of gender, tense, etc), the current setting should serve your localization needs. The project is written in Fluent, which allows to apply different translations based on the singular and plural forms. Let me know if you run into any issues related to this.

**Comment by zalaan-dev** [comment]
Hi all, all Pashto strings for Common Voice are now localized and quality checked. Please let me know when they can make it to the site. Let me know if you have any question. Thanks!

**Comment by peiying2** [comment]
@mbransn please help coordinate to add ps to the locale list so the language can be viewed on Dev and Staging servers before it goes to production. Thank you.

**Comment by ftyers** [comment]
@zalaan-dev the next step is to [add sentences](https://commonvoice.mozilla.org/sentence-collector/#/add) to the [sentence collector](https://common-voice.github.io/sentence-collector/). The sentences need to be in the public domain and will need to be verified by two people before they are included. The release target is 5,000 sentences. Please feel free to get in contact if you would like help processing any texts you find.

**Comment by zalaan-dev** [comment]
@ftyers Thanks, will get started on sentence collecting.

**Comment by phirework** [comment]
Closing issue as Pashto is now enabled in Pontoon, thanks everyone!

**Comment by tariqbahar** [comment]
Hello, I would like to contribute to the Pashto localization of Mozilla Common Voice. I’m ready to help improve the translations, fix existing issues, and make the system work more smoothly for Pashto speakers. Please guide me on how I can officially join and support the localization efforts.
