### ISSUE TITLE
Language Request(Malay)

### ISSUE THREAD

**Issue by IIIBlueberry** [common-voice/common-voice#3002]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Malay (Bahasa Melayu)
**Language code**
Please provide the ISO-639-1 code
ms
**Language size**
Number of active speakers of this language in the world
290 million people according to wikipedia
**Plural forms**
How would you translate the following in this language?

0 rocks(Kosong batu)
1 rock(Satu batu)
2 rocks(Dua batu)
3 rocks(Tiga batu)
4 rocks(Empat batu)
5 rocks(Lima batu)
10 rocks(Sepuluh batu)
20 rocks(Dua puluh batu)
100 rocks(Seratus batu)
1000 rocks(Seribu batu)
I see 0 rocks on the ground(Saya nampak kosong batu di tanah)
I see 1 rock on the ground(Saya nampak satu batu di tanah)
I see 10 rocks on the ground(Saya nampak sepuluh batu di tanah)
I see rocks on the ground(Saya nampak batu di tanah)

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

Edit: Just realized i made a mistake on the **Plural forms** section

**Comment by peiying2** [comment]
@IIIBlueberry if you have an account, you can request to add Common Voice project. I can enable it as it is already established in Pontoon. Let me know your account link in Pontoon and if you will be the CV project manager/translator. The community has not been active, but I can create customized setup for this project.

**Comment by ftyers** [comment]
Dear @IIIBlueberry. Malay already exists in Pontoon: 
https://pontoon.mozilla.org/ms/
I recommend contacting the team there and asking them to enable Common Voice.

**Comment by ftyers** [comment]
Also note that Bahasa Malay is already enabled in [sentence collector](https://commonvoice.mozilla.org/sentence-collector/) so you won't need to ask for it to be enabled, you can just start submitting and reviewing sentences there. You will need to add 5000 before it can be enabled in the main site. There are further details [here](https://github.com/common-voice/common-voice/blob/main/docs/LANGUAGE.md). Please feel free to contact us if you have any questions.

**Comment by IIIBlueberry** [comment]
> 
> 
> Dear @IIIBlueberry. Malay already exists in Pontoon:
> https://pontoon.mozilla.org/ms/
> I recommend contacting the team there and asking them to enable Common Voice.
there isn't lot of people active for Malay Pontoon(2 Contributor last 3/6month)


> 
> 
> @IIIBlueberry if you have an account, you can request to add Common Voice project. I can enable it as Malay is already established in Pontoon. Let me know your account link in Pontoon and if you will be the CV project manager/translator. The community has not been active, but I can create customized setup for this project.

Do i really need to be the project manager for CV? to enable CV translation for malay? because there is there is no Common Voice on the request project tab https://imgur.com/BRdHzNV

i could kinda be a project manager for CV(a bad one i guess)
here my Pontoon profile link i just registered https://pontoon.mozilla.org/contributors/h3gOL-Ia7zjArGXoAjn17s1x_Zo/

**Comment by peiying2** [comment]
@IIIBlueberry contributors tend to work on projects of their interest, like Firefox, which is a large project. For CV, you do not need to be a manager to contribute, I can make you a translator for CV, this way, you can contribute without peer review. Having said that, once you create an account, I will introduce you to the ones that are active. My hope is that you work on the project with a few others, not by yourself. It is more interesting, you can collaborate to make your work better, and you learn from one another.
You can make a request here: https://pontoon.mozilla.org/ms/. Once I am notified, I will enable the project, and make you the translator for the project.

**Comment by IIIBlueberry** [comment]
@peiying2 hi again, how do i make the request? there is no CV on the Request more projects page. i already create my mozilla account for pontoon

**Comment by peiying2** [comment]
> @peiying2 hi again, how do i make the request? there is no CV on the Request more projects page. i already create my mozilla account for pontoon

Sorry my bad. The current project setting doesn't allow new language to be added. I can do it, but I am not sure why this is disabled. 

@mbransn Can I add new language to CV project?

**Comment by IIIBlueberry** [comment]
Edited the issues, just realized i have made a mistake on the **Plural forms** section

**Comment by peiying2** [comment]
@IIIBlueberry The CV project is now enabled for Malay, your role is now a translator for the project. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by IIIBlueberry** [comment]
Cool, I will try my best. I will read the pontoon docs first.

**Comment by phirework** [comment]
Closing issue as language is enabled for Malay now, thanks everyone!

**Comment by sparsh999gupta** [comment]
Is Malay now available on commonvoice? Can't seem to find it.

**Comment by peiying2** [comment]
> Is Malay now available on commonvoice? Can't seem to find it.

https://commonvoice.mozilla.org/ms

**Comment by sparsh999gupta** [comment]
@peiying2 Malay dataset is not there right for speech tasks?
https://commonvoice.mozilla.org/en/datasets

**Comment by peiying2** [comment]
> @peiying2 Malay dataset is not there right for speech tasks? https://commonvoice.mozilla.org/en/datasets

@ftyers maybe able to help answering you.

**Comment by ftyers** [comment]
Hi @peiying2 and @sparsh999gupta, so far Malaysian has not been launched. 

![imatge](https://github.com/common-voice/common-voice/assets/449545/32cef58f-4c35-4d2b-9e41-c972d3f8c5bd)

https://commonvoice.mozilla.org/ms/languages

The interface is at 62% (it needs to be >70%) and the number of sentences is 47/750, it needs to be over 750. If you have any further questions, feel free to get in contact on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
