### ISSUE TITLE
How to configure languages supported on local deployment

### ISSUE THREAD

**Issue by jarivk** [common-voice/common-voice#3007]
I am trying to have a local deployment of the server. As importing languages takes lot of time, I wanted to enable only English as supported language. How do I do that? I didn't find any setting for that.

**Comment by jarivk** [comment]
Deleting languages not required from server/data helped.

**Comment by Rohanatskit** [comment]
Hi @virajkarandikar Can you please elaborate on what you did to run only with EN language.
