### ISSUE TITLE
Galego

### ISSUE THREAD

**Issue by a19guillermobf** [common-voice/common-voice#3008]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Galego
**Language code**
Please provide the ISO-639-1 code
gl
**Language size**
Number of active speakers of this language in the world
3221000
**Plural forms**
How would you translate the following in this language?

0 rocks
0 pedras
1 rock
1pedra
2 rocks
2 pedras
3 rocks
3 pedras
4 rocks
4 pedras
5 rocks
5 pedras
10 rocks
10 pedras
20 rocks
20 pedras
100 rocks
100 pedras
1000 rocks
1000 pedras
I see 0 rocks on the ground
Vexo 0 pedras no chao
I see 1 rock on the ground
Vexo 1 pedra no chao
I see 10 rocks on the ground
Vexo 10 pedras no chao
I see rocks on the ground
Vexo pedras no chao

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

**Comment by ftyers** [comment]
Ola, o galego xa está en Pontoon e a interfaz  [está traducida](https://pontoon.mozilla.org/gl/common-voice/). Agora só hai que engadir oracións. Iso pódese facer mediante o [colector de oracións](https://commonvoice.mozilla.org/sentence-collector/).

**Comment by a19guillermobf** [comment]
Perfecto, desculpas e obrigado pola info!
Alá vou!
