### ISSUE TITLE
Add Wolof

### ISSUE THREAD

**Issue by MyNamezal** [common-voice/common-voice#3012]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?

**Language code**
Please provide the ISO-639-1 code

**Language size**
Number of active speakers of this language in the world

**Plural forms**
How would you translate the following in this language?

0 rocks
1 rock
2 rocks
3 rocks
4 rocks
5 rocks
10 rocks
20 rocks
100 rocks
1000 rocks
I see 0 rocks on the ground
I see 1 rock on the ground
I see 10 rocks on the ground
I see rocks on the ground

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

**Comment by MyNamezal** [comment]
Hello,

Wolof is a dialect spoken in Senegal and Gambia. Its around 20 millions people in Africa. That would ve great if we could create a dataset and allow people creating machine learning models for Africa.
Regards
Saliou

**Comment by ftyers** [comment]
Hi @MyNamezal Wolof is already [in Pontoon](https://pontoon.mozilla.org/wo/), so you don't need to go through that process. You will need to request the Common Voice project in Pontoon. I think that @peiying2 might be able to help with that. I would also encourage you to get in contact with the other [contributors to Wolof](https://pontoon.mozilla.org/wo/contributors/). 

Note that, there were [changes at Mozilla last year](https://discourse.mozilla.org/t/mozilla-org-wide-updates-impacts-on-common-voice/65612/) which meant that the project has a lot less bandwidth for taking on new language requests right now. Additionally, at the moment there is a [pause until next month](https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526). 

But we are very interested in seeing Wolof in Common Voice and will work with you to get it in there as soon as possible. Note that even if Wolof is not in Pontoon, you can start [adding sentences](https://github.com/common-voice/common-voice/blob/main/docs/SENTENCES.md) to the [sentence collector](https://commonvoice.mozilla.org/sentence-collector/). You will need 5000 sentences to turn Wolof on on the main page.

**Comment by peiying2** [comment]
Thank you @ftyers for providing the basic information to get the project started. 

@MyNamezal the community as is is not active at all. You can reach out to them (once you create an account, you should be able to see their email addresses). Assuming no one replies, would you be able to get this started? Could you find others to work with you? Is your background in language? If so, I can give you "translator" role, which means your work can be used on production without peer review. Share the link to your Pontoon profile so I can add you to the language as a translator. If you are a contributor (in the case in Pontoon), you can start translating, but your work needs another person's approval. If no one is active, then your work will be stuck.

**Comment by phirework** [comment]
Hi @MyNamezal, are there any updates to @peiying2's request? Otherwise I will close this issue.

**Comment by Heyhillary** [comment]
Hey @MyNamezal,

Thanks for showing interest in adding Wolof onto Common Voice.

Are you still interested in adding Wolof onto Common Voice ? If so please respond to @peiying2 message and I can enable your request. 

If you have any questions please let me know.

**Comment by Heyhillary** [comment]
Hello, I'm closing this issues due to inactivity. If anyone would like to request Wolof to be added please craete a new form. 

Thank you
