### ISSUE TITLE
Auth0  automatically logged back in without asking the user to re-enter the credentials

### ISSUE THREAD

**Issue by taitpthomas** [common-voice/common-voice#3014]
**Describe the bug**
In my development environment, when the user logout and then login again, auth0  automatically logged back in without asking the user to re-enter the credentials. This problem does not happen on the Mozilla's common voice site. Would someone kindly point me to what may cause this issue? 

**To Reproduce**
1. Click login button and enter username password
2. After successful login, click logout button
3. Click login button again. 
4. Auth0 would not show the login page, instead, the user is automatically login back in

**Expected behavior**
Once the user logout and login again, the login page should show up allows users to enter the credentials.

**Screenshots**
N/A

**Desktop or Mobile (please complete the following information):**
 - Windows 10
 - Chrome 
 - Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by phirework** [comment]
This is related to Auth0 configurations, not the Common Voice app, so it's not something we can support. Here's an example of someone experiencing similar issues: https://community.auth0.com/t/does-not-show-user-login-prompt-anymore-after-the-first-logging-in/16504. As a workaround, I would suggest using incognito or clearing cache if you need to test a login-related problem.
