### ISSUE TITLE
Taiwanese (Taiwanese Hokkien, Taiwanese Minnan, Hokkien, Minnan)

### ISSUE THREAD

**Issue by treskro** [common-voice/common-voice#3023]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
Taiwanese (aka Taiwanese Hokkien, aka Taiwanese Minnan, aka Hokkien, aka Minnan)

**Language code**
zh-nan (for Minnan in general)

**Language size**
~16 million (Taiwanese Hokkien) < subset of ~45 million (Hokkien, all varieties) < subset of ~50 million (Minnan, all varieties)

**Plural forms**
How would you translate the following in this language?

無石頭 bô tsio̍h-thâu 
一粒石頭 tsı̍t lia̍p tsio̍h-thâu
兩粒石頭 nn̄g lia̍p tsio̍h-thâu
三粒石頭 sann lia̍p tsio̍h-thâu
四粒石頭sì lia̍p tsio̍h-thâu
五粒石頭 gōo lia̍p tsio̍h-thâu
十粒石頭 tsa̍p lia̍p tsio̍h-thâu
二十粒石頭 jī-tsa̍p lia̍p tsio̍h-thâu
一百粒石頭 tsı̍t-pah lia̍p tsio̍h-thâu
一千粒石頭 tsı̍t-tshing lia̍p tsio̍h-thâu
我佇塗跤看無石頭 guá tī thôo-kha khuànn-bô tsio̍h-thâu
我佇塗跤看著一粒石頭 guá tī thôo-kha khuànn-tio̍h tsı̍t lia̍p tsio̍h-thâu
我佇塗跤看著十粒石頭 guá tī thôo-kha khuànn-tio̍h tsap lia̍p tsio̍h-thâu
我佇塗跤看著石頭 guá tī thôo-kha khuànn-tio̍h tsio̍h-thâu

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

**Comment by peiying2** [comment]
@petercpg please help assess this request. Also since this is a request that involves deeper discussion on Chinese in written form and different in spoken from what is available on the CV site, it needs  approval from the CV team.

**Comment by petercpg** [comment]
Hello @peiying2 and welcome @treskro,

Few points from my perspective:
1. (Spoken) Language name: I'd prefer full and complete names (i.e., Taiwanese Hokkien / Taiwanese Minnan). If the varieties are not intolerable, simply use Hokkien or Minnan for inclusiveness. Using Taiwanese solely can be ambigous as Mandarin, Hakka, and Austronesian Languages are spoken by Taiwanese people.

2. There is a big divergence between Taiwanese Mandarin, the _lingua franca_ of Taiwan, and Taiwanese Hokkien on lexicon and some differences on syntax. While Taiwanese people do read Traditional Chinese, I'd say the significance of CV Recording process is equal to or more than website localization, and start collecting corpus and prepare for recording is strongly recommended.

3. CV Website L10n: There are a variety of writing systems of Taiwanese Hokkien, mostly in Chinese/Han characters or Latin letters, or mixed. Unfortunately, all these systems look quite foreign to me and I do not intend to contribute to this locale to avoid messing up translation. My recommendation is to create a [L10n Style Guide](https://mozilla-l10n.github.io/styleguides/guidelines/index.html) as a framework, to avoid further disputes.


Last but not least, feel free to join Common Voice in Taiwan community channel if you are on Telegram: https://t.me/moztwCV

to-siā,
Peter

**Comment by irvin** [comment]
Please refer to #3194, which initiate a new discussion on add Taiwanese.

**Comment by phirework** [comment]
Since this is in active discussion in the new thread which has a more fulsome discussion, I'm going to close the issue. Please provide all further comments on #3194
