### ISSUE TITLE
Please add Uyghur

### ISSUE THREAD

**Issue by gheyret** [common-voice/common-voice#3026]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Uyghur

**Language code**
Please provide the ISO-639-1 code
uig

**Language size**
Number of active speakers of this language in the world
12,000,000

**Plural forms**
How would you translate the following in this language?

0 rocks
1 rock
2 rocks
3 rocks
4 rocks
5 rocks
10 rocks
20 rocks
100 rocks
1000 rocks
I see 0 rocks on the ground
I see 1 rock on the ground
I see 10 rocks on the ground
I see rocks on the ground

0 تاش
1 تاش
2 تاش
3 تاش
4 تاش
5 تاش
10 تاش
20 تاش
100 تاش
1000 تاش
يەردە 0 تاش كۆردۈم
يەردە 1 تاش كۆردۈم
يەردە 10 تاش كۆردۈم
يەردە تاشلارنى كۆردۈم

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://pontoon.mozilla.org/contributors/OCaIrlHH2OfvB5k6OQ7_HqUJXPI/

**Comment by rustam** [comment]
Sorry, since this language is written in rtl(right to left), the translation for above plural forms would be as following. 

Plural forms
How would you translate the following in this language?
`<p dir='rtl' align='right'>
0 تاش
1 تاش 
2 تاش
3 تاش
4 تاش
5 تاش
10 تاش
20 تاش
100 تاش
1000 تاش
يەردە 0 تاش كۆردۈم
يەردە 1 تاش كۆردۈم
يەردە 10 تاش كۆردۈم
يەردە تاشلارنى كۆردۈم
</p>
`

**Comment by peiying2** [comment]
@rustam and @gheyret thank you both for filing the request. To help me better understand the plural and singular rules without  reading the language (I can eyeball it), is it safe to say there is no difference between 0-1000? In other words, there is no difference between singular and plural? 

Also, per the current process, the Common Voice team would give the approval to add the language before I add it  to Pontoon - the tool you use to localize the website.

**Comment by ftyers** [comment]
@peiying2 it is like other Turkic languages in this respect. Here is a rough transliteration:
```
0 taš
1 taš
2 taš
3 taš
4 taš
5 taš
10 taš
20 taš
100 taš
1000 taš
jɛrdɛ 0 taš kördym
jɛrdɛ 1 taš kördym
jɛrdɛ 10 taš kördym
jɛrdɛ tašlarnı kördym
```
So only the "I see rocks on the ground" has a separate plural form.

**Comment by gheyret** [comment]
@ftyers is right.
In Uyghur, Plural is not used when the number is clear.
When the number is not clear, "لار" or "لەر" are added. like تاش+لار

**Comment by rustam** [comment]
@peiying2 
Thank you , we are looking forward for approval . 
ready to start localization once be added to Pontoon

**Comment by peiying2** [comment]
Hello @gheyret and @rustam I have enabled [Uyghur](https://pontoon.mozilla.org/ug/common-voice/) in Pontoon. Normally I wait for the CV team for approval, but it meant you would have to wait a little longer.  Anyway, it's ready to go. Note the ISO-639-1 code for it is `ug`.. Let me know if you disagree and prefer to use `uig` instead.

@gheyret  your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by rustam** [comment]
@peiying2 Thank you for your prompt action to bring Uyghur Language in Pontoon.

**Comment by peiying2** [comment]
> @peiying2 Thank you for your prompt action to bring Uyghur Language in Pontoon.

You are most welcome. Let me know if you are also involved in website localization. I  can add you to Pontoon as a translator if you can share your profile link. Otherwise, you can wait for gheyret to give you the proper access right.

**Comment by rustam** [comment]
@peiying2 

> > @peiying2 Thank you for your prompt action to bring Uyghur Language in Pontoon.
> 
> You are most welcome. Let me know if you are also involved in website localization. I can add you to Pontoon as a translator if you can share your profile link. Otherwise, you can wait for gheyret to give you the proper access right.

appreciate if you could add me as translator , following is my profile link, thank you in advance. 
https://pontoon.mozilla.org/contributors/HliynNZwLYoY4npR3BZmbWUWYqU/

**Comment by peiying2** [comment]
> appreciate if you could add me as translator , following is my profile link, thank you in advance.
> https://pontoon.mozilla.org/contributors/HliynNZwLYoY4npR3BZmbWUWYqU/
Done!

**Comment by phirework** [comment]
Thanks for taking care of this @peiying2!

**Comment by Sahran** [comment]
> Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).
> 
> Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.
> 
> **Language name** What language would you like to add? Uyghur
> 
> **Language code** Please provide the ISO-639-1 code uig
> 
> **Language size** Number of active speakers of this language in the world 12,000,000
> 
> **Plural forms** How would you translate the following in this language?
> 
> 0 rocks 1 rock 2 rocks 3 rocks 4 rocks 5 rocks 10 rocks 20 rocks 100 rocks 1000 rocks I see 0 rocks on the ground I see 1 rock on the ground I see 10 rocks on the ground I see rocks on the ground
> 
> 0 تاش 1 تاش 2 تاش 3 تاش 4 تاش 5 تاش 10 تاش 20 تاش 100 تاش 1000 تاش يەردە 0 تاش كۆردۈم يەردە 1 تاش كۆردۈم يەردە 10 تاش كۆردۈم يەردە تاشلارنى كۆردۈم
> 
> **Pontoon manager** Please link to the Pontoon account of the person who should be listed as the community manager of this language https://pontoon.mozilla.org/contributors/OCaIrlHH2OfvB5k6OQ7_HqUJXPI/

Uyghur language is Arabic letters based language, writes by right to left. 8 to 11 million speakers, For more details please visit http://en.wikipedia.org/wiki/Uyghur_language and http://en.wikipedia.org/wiki/Uyghur_language


 Uyghur language:


http://www.loc.gov/standards/iso639-2/php/code_list.php
ISO 639-2 Code: uig
ISO 639-1 Code: ug
English name of Language: Uyghur;Uighur 
French name of Language: ouïgour
Uyghur name of Language: ئۇيغۇر، ئۇيغۇرچە

Microsoft Windows vista and higher version
language name: Uyghur
MS locale ID: 1152
MS locale ID (Hex): 480
iso-code: ug
Symbolic: Uyghur
Locale name: ug_CN

Uyghur language plural forms:

http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

ئۇيغۇرچە

Uyghur
UG

ug	Uyghur	nplurals=1; plural=0;

Thanks.
