### ISSUE TITLE
Bulgarian Sentence Bank

### ISSUE THREAD

**Issue by izcatoriz** [common-voice/common-voice#3028]
Today I started contributing to the Bulgarian voice recordings and I noticed that quite a few of the sentences were outdated and awkward sounding. I did report grammatical mistakes or awkward sounding phrases but I do get the feeling that there are still quite a few sentences from old books that are representative of a particular time period and aren't too relevant nowadays. Is there a way I can contribute to the sentence bank? Or translate sentences from English to help improve it?

**Comment by MichaelKohler** [comment]
Thanks for reaching out and offering your help!

> Is there a way I can contribute to the sentence bank? Or translate sentences from English to help improve it?

You can contribute new sentences through the Sentence Collector at https://commonvoice.mozilla.org/sentence-collector/. Please note that all submitted sentences need to be [Public Domain](https://en.wikipedia.org/wiki/Public_domain), as we can't publish a dataset with copyright infringements. As it's quite hard to get a large number of copyright-free sentences, older books are quite present, so any help in getting more sentences would be highly appreciated!
