### ISSUE TITLE
Language Localization Request For Shilha

### ISSUE THREAD

**Issue by Warmaksan01** [common-voice/common-voice#3032]
**Language name**
Shilha/Taclḥit

**Language code**
ISO-639-3 : shi

**Language size**
~7,200,000 (2016)

**Plural forms**

0 rocks: Amya n uẓru
1 rock: Yan uẓru
2 rocks: Sin iẓran
3 rocks: Kraḍ iẓran
4 rocks: Kkuẓ iẓran
5 rocks: Semmus iẓran
10 rocks: Mraw iẓran
20 rocks: Sin id mraw n iẓran
100 rocks: Timiḍi n iẓran
1000 rocks: Ifḍ n iẓran
I see 0 rocks on the ground: Ẓriɣ amya n uẓru ɣ wakal
I see 1 rock on the ground: Ẓriɣ yan uẓru ɣ wakal
I see 10 rocks on the ground: Ẓriɣ mraw iẓran ɣ wakal
I see rocks on the ground: Ẓriɣ iẓran ɣ wakal

**Pontoon manager**
https://pontoon.mozilla.org/contributors/WgWPQYLbgwBfh1U2jU5NZsTce9A/

**Comment by peiying2** [comment]
Hello @Warmaksan01, I have enabled [Shilha](https://pontoon.mozilla.org/shi/) in Pontoon. Normally I wait for the CV team for approval, but it meant you would have to wait a little longer. Anyway, it's ready to go. 

Your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by Warmaksan01** [comment]
Ty

**Comment by peiying2** [comment]
This issue needs to be reopened so the dev team can process their part to make sure the language is properly supported. Let's wait to hear back from them. In the meantime, you can keep working on the website localization.
