### ISSUE TITLE
Bashkir is ready to be launched on commonvoice.mozilla.org

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3036]
Bashkir(**ba**) is now localized and has over 5000+ sentences. This is a request to have it launched on the main site.
Thank you

**Comment by AigizK** [comment]
Could someone provide an info when this issue will be done?

**Comment by ftyers** [comment]
Hi @AigizK the Common Voice team is still on break, I don't know exactly how long it will be, but hopefully before the end of the month.

**Comment by AigizK** [comment]
Hi Francis,

Thanks for the info

**Comment by ftyers** [comment]
https://commonvoice.mozilla.org/ba \o/

**Comment by AigizK** [comment]
Yes, I saw it today by accident and have already started doing tasks. Thank you very much.

**Comment by phirework** [comment]
🎉  Sorry for the delay folks, we're back in action.
