### ISSUE TITLE
ambiguity of sentences in Arabic languages due to Al-Harakat ( Arabic diacritics )

### ISSUE THREAD

**Issue by Nounousal9atil** [common-voice/common-voice#3041]
Hello everybody,
I am a native arabic speaker, I noticed that during the contribution, the sentences to read are sometimes ambiguous.
The reason for this ambiguity is that in Arabic, there is no vowel, so we ,Arabic speakers, know how to pronouce a word/sentece depending on the context and the grammar!
Indeed, there are quite a few words in Arabic that are written in the same way, but with completely different pronunciation and in this case a completely different definition !
So, to remedy to this, it existes in arabic Al-Harakat ( Arabic diacritics ) that can, as vowels, shows us how to pronouce a word/sentence ! ( https://en.wikipedia.org/wiki/Arabic_diacritics )
I can give an Example : أنس can be read : Anas, Ouns, Anis, Annassa, etc...
With the harakat we can distinguish the prononciations and then the meening : أَنَسْ for Anas,أُنْسْ for Ouns,أَنِسْ for Anis, أَنَّسْ for Annassa, etc...
The arabic sentences in the CV Project are sentences with out the Harakat, so for some senteces it is ambigous and hard to know how to read ! especially most of the senteces are poeme lines and some of them aged from the Medieval ages !
Thank you

**Comment by ftyers** [comment]
Dear @Nounousal9atil this is a common problem in many languages, even in English, if you see the word "record" out of context, you don't know if the stress should be on the first syllable /ˈɹɛkɔːd/ (noun) or the second /ɹɨˈkɔːd/ (verb). A similar situation with the word *wound* is it /wuːnd/ or /waʊnd/? 

In any case the solution is just to make the pronounciation that you feel is most likely. In the end Common Voice is largely for speech to text, so a bit of non-determinism in that direction is not a problem (e.g. multiple sequenceso of sounds mapping to the same sequence of characters). Hope this answers the question!

**Comment by Nounousal9atil** [comment]
Hi @ftyers, I can understand what do you mean !
But English and Arabic are two very different languages, for the example you gave, even if the pronouciation is (slightly) different, but the meaning still the same !
For Arabic, the pronouciation is VERY different (as the examples i've gave) and the Meannings are completly different as well (some of the words are verbs others are nouns for example) ! In arabic it is important to read something correctly with the right Vowels so the text can be understood correctly !
I hope I explained the issue well this time !
Thank you for answering

**Comment by ftyers** [comment]
In the second example the meaning is different. The first word means "an injury" and the second is the past participle of "wind" /ˈwɪnd/. In fact *wind* itself is also ambiguous in terms of the vowel between /ˈwɪnd/ "the force of nature" and /ˈwaɪnd/ "turn coils of something".

I could give multiple examples from other languages of a similar process (Russian *замок*, Swedish *tomten*). In the end some languages are more or less ambiguous, but it should not be a problem for the models in the end. If you think it is necessary to continue the conversation, we can continue it on [Discourse](https://discourse.mozilla.org/c/voice/239) :)

**Comment by phirework** [comment]
Thanks for the conversation folks - @ftyers is right, structural and phonetic ambiguity is a common part of many languages and something that computers will necessarily need to deal with. Another example is Mandarin Chinese, where the same phoneme with the same tone can mean any of a dozen different things. 

If you're not sure how you would pronounce a certain sentence, feel free to skip it. If you find that a sentence is straight up wrong without certain diacritics, you can also report it as incorrect and it will be removed from the queue.
