### ISSUE TITLE
Language Request: Maithili

### ISSUE THREAD

**Issue by jha-vikas** [common-voice/common-voice#3043]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Maithili

**Language code**
Please provide the ISO-639-1 code
bh

**Language size**
Number of active speakers of this language in the world
34 million

**Plural forms**
How would you translate the following in this language?

0 rocks : शून्य पाथर
1 rock : एकटा पाथर
2 rocks: दूटा पाथर
3 rocks: तीनटा पाथर
4 rocks: चारिटा पाथर
5 rocks: पाँचटा पाथर
10 rocks: दसटा पाथर
20 rocks: बीसटा पाथर
100 rocks: एक सौ पाथर
1000 rocks: एक हजार पाथर
I see 0 rocks on the ground: हम जमीन पर एकौटा पाथर नहीं देख रहल छी।
I see 1 rock on the ground: हम जमीन पर एकटा पाथर देख रहल छी।
I see 10 rocks on the ground: हम जमीन पर दसटा पाथर देख रहल छी।
I see rocks on the ground: हम जमीन पर पाथर देख रहल छी।

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://pontoon.mozilla.org/contributors/cJnub4bI1XS5jAwGIWG8hHCU_2Q/

**Comment by peiying2** [comment]
Hello @jha-vikas The language exists in Pontoon: https://pontoon.mozilla.org/mai/. I can add Common Voice to the project list.

**Comment by peiying2** [comment]
Hello @jha-vikas  I have enabled [Maithili](https://pontoon.mozilla.org/projects/common-voice/) in Pontoon. Normally I wait for the CV team for approval, but I am sure you are ready to start as soon as possible.

The community as a whole has not been active for more than a year. I have made you a translator for the Common Voice project. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by phirework** [comment]
Thanks @peiying2!
