### ISSUE TITLE
Language Request: Papiamento

### ISSUE THREAD

**Issue by pknothing** [common-voice/common-voice#3044]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
Papiamento from Aruba

**Language code**
pap AW

**Language size**
150,000

**Plural forms**
How would you translate the following in this language?

0 rocks: 0 piedra
1 rock: 1 piedra
2 rocks: 2 piedra
3 rocks: 3 piedra
4 rocks: 4 piedra
5 rocks: 5 piedra
10 rocks: 10 piedra 
20 rocks: 20 piedra
100 rocks: 100 piedra
1000 rocks: 1000 piedra
I see 0 rocks on the ground: Mi ta wak 0 piedra riba vloer
I see 1 rock on the ground: Mi ta wak 1 piedra riba vloer
I see 10 rocks on the ground: Mi ta wak 10 piedra riba vloer
I see rocks on the ground: Mi ta wak piedra riba vloer

**Pontoon manager**
https://pontoon.mozilla.org/contributors/K2tmcFG6DkVmHU-STelDIpOJxTQ/

**Comment by peiying2** [comment]
@pknothing is it possible to enable Papiamento without the Aruba extension? The goal is to make a generic one, not country specific. To give you an example, we currently have one Spanish version for the website. Will it be a problem for Papiamento?

**Comment by pknothing** [comment]
Hi! thanks for the quick reply. I suppose it's not necessary to separate them, but given that Papiamento (Aruba) and Papiamentu (Curaçao) have completely different spelling rules, I thought I would put them separately. Papiamento uses etymological spelling (website) and Papiamentu uses phonetic spelling (wépsait). Both are pronounced pretty much exactly the same when spoken, but the written text is very different. But after reading the accent strategy more thoroughly I understand the approach, so it makes sense to put all of the variants under one language. How is this dealt with when in Aruba the language name is Papiamento and in Curaçao it's Papiamentu? Should it then be called Papiamento/u?

**Comment by peiying2** [comment]
Thank you for providing context. 

@ftyers what do you suggest? Or we should wait until the team gets back.

**Comment by ftyers** [comment]
Hi both! 

This is a very interesting question and is something we will continue to come across as continue expanding linguistically. 

My thought is that this should be a single language code for the purposes of Common Voice, but two language codes in Pontoon (one for each variant). The two variant orthographies have state support, and are sufficiently different for the purposes of localisation. In addition a person would want to be able to use the CV website localised in their own variant (although I would argue this for en-IE too).

If we have no-one who wants to work on the Curaçao variant at the moment, then, given the lead time (I'm not sure when the team will be back, as it has passed the 15th March), I think it's probably best to continue with the pap-AW code. But when someone who comes along who wants to contribute to Papiamento/u in the Curaçao variant we will need to address it then, and I think from the point of view of audio collection, it should be a single code, `pap`.

**Comment by pknothing** [comment]
That makes a lot of sense! Thanks for clarifying the logic behind Pontoon and Common Voice as well as their differences. Perhaps I did not read the doc thoroughly enough. 😅

I'll be pending for any action or if I can help in any way in the meantime I'd be glad to. i'll try and see if there is anyone I know willing to work on the Pantoon Papiamentu (Curaçao) variant in the meantime, if that's ok!

**Comment by ftyers** [comment]
That sounds great! And the docs are in a bit of flux at the moment, with all the changes, so I'm sure it's not something you missed, just is not well documented enough yet :)

**Comment by peiying2** [comment]
Thank you @ftyers for providing valuable input. I always trust your knowledge and insight on this. 

Hello @pknothing  I have enabled [Papiamento](https://pontoon.mozilla.org/pap-AW/common-voice/) in Pontoon. 

Your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!

**Comment by phirework** [comment]
Closing the issue as everything seems to be resolved now, thanks everyone for your patience and collaboration!
