### ISSUE TITLE
LOCALIZATION REQUEST: Interlingue

### ISSUE THREAD

**Issue by Carmina16** [common-voice/common-voice#3047]
**Language name**
Interlingue

**Language code**
ie

**Language size**
N/A

**Plural forms**
How would you translate the following in this language?

0 petres
1 petre
2 petres
3 petres
4 petres
5 petres
10 petres
20 petres
100 petres
1000 petres
Yo vide 0 petres sur li terre
Yo vide 1 petre sur li terre
Yo vide 10 petres sur li terre
Yo vide petres sur li terre

**Pontoon manager**
https://pontoon.mozilla.org/contributors/XSjvSghaY9mHkBkx1lMchoFAvl0/

**Comment by Heyhillary** [comment]
Hey @Carmina16 

Thanks for your request. Interlingua is available on Common Voice and is ready for voice collections.

https://commonvoice.mozilla.org/ia/speak

**Comment by Heyhillary** [comment]
Hey @Carmina16 ,

Thanks for your localisation requests dn apologies for the delay.

I'm currently enabling Interlingue onto Pontoon and wanted to ask if you were aware of the plural rules for your language ?

**Comment by Carmina16** [comment]
Same as English: `nplurals=2; plural=(n != 1)`

**Comment by Heyhillary** [comment]
Thank you !

https://pontoon.mozilla.org/ie/

I have now enabled Interlingue onto Pontoon and assigned you as manager.  The role of a manager means all your work will go to staging (and later to production) without peer review. 

I hope through your work, there would be others joining you to collaborate on the different phases of this project. 
Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[ Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

**Next Steps...**

Newly translated strings will automatically show up on our dev server every few days (https://dev.commonvoice.mozilla.org).  New languages will be visible on the Common Voice platform once 95% of the language is localised, and are released to production (main website) every two weeks.

Also just so you are aware in the most [recent weekly update](https://discourse.mozilla.org/t/weekly-update-thread-2021/84411) we announced the following: 

To support all language communities to take part in this process we will be publishing the Common Voice Contribution Agreement form for pre-existing that are not under a public license. Read more about how to use the form on the [Common Voice Community Playbook](https://github.com/common-voice/community-playbook/blob/draft/sub_pages/cc0waiver_process.md). 

This will help to launch your language onto Common Voice for voice data collection. 

If you have any other questions please feel free to ask.

All the best, 

Hillary
