### ISSUE TITLE
Recorded sentences are not played back in full

### ISSUE THREAD

**Issue by deevroman** [common-voice/common-voice#3048]
**Describe the bug**
Recorded sentences are not played back in full

**To Reproduce**
1. Record the sentence
2. Try to play it back
3. Only the first few seconds are played

 - OS: macOS
 - Browser Firefox
 - Version 87

**Comment by guojimhuang** [comment]
Same bug here on
OS: ubuntu 20.10
Browser Firefox
Version 87.0

**Comment by phirework** [comment]
This appears to be a duplicate of #3018, closing this one and will do additional troubleshooting in that earlier issue.

**Comment by phirework** [comment]
Nvm - after troubleshooting it looks like the issue might be isolated to FF 87 specifically, will re-open and update as I find out more.

**Comment by zitr0y** [comment]
Same issue here.
OS: Windows 10 Pro 20H2
Browser: Firefox 87.0 (64-Bit) 
Language: German and English recording (haven't tried others)
Microphone: AT 2020+ USB

**Comment by nikolockenvitz** [comment]
Same here.
OS: Windows 10
Browser: Firefox 87.0 (64-bit)

**Comment by zitr0y** [comment]
The dev server version works perfectly for me 👍

**Comment by stefangrotz** [comment]
Works fine for me as well 👍

**Comment by deevroman** [comment]
It works for me too 👍

**Comment by nikolockenvitz** [comment]
Yes, works perfectly fine! Thanks

**Comment by phirework** [comment]
The hotfix is out on production, thanks everyone!
