### ISSUE TITLE
Remove incorrect senteces for Asturian languange

### ISSUE THREAD

**Issue by palonso** [common-voice/common-voice#3055]
Hi!
We have identified a bunch of sentences with problems for Asturian, and we would like to remove them in order to fix them and re-upload via the sentence collector.

I've opened a [PR](https://github.com/common-voice/common-voice/pull/3054) with the changes in case this can be directly merged.

Thank you for the amazing work,
Pablo.

**Comment by MichaelKohler** [comment]
Thanks for filing this. That can't be handled through a PR, but I'll remove them. I will need to remove some other sentences as well, will report back here once done. I'll also close the PR once done.

**Comment by MichaelKohler** [comment]
The sentences have been removed from the Sentence Collector. You can now upload the corrected sentences. Thanks for reporting!

**Comment by palonso** [comment]
Thanks for the fast reply @MichaelKohler.
