### ISSUE TITLE
Kannada(ಕನ್ನಡ) Language Request

### ISSUE THREAD

**Issue by harshithsk** [common-voice/common-voice#3056]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Kannada**

**kn**

**43 million** (by 2011 according to wiki)

**Plural forms**
How would you translate the following in this language?

0 rocks - 0 ಬಂಡೆಗಳು
1 rock - ೧ ಬಂಡೆ
2 rocks - ೨ ಬಂಡೆಗಳು
3 rocks - ೩ ಬಂಡೆಗಳು
4 rocks - ೪ ಬಂಡೆಗಳು
5 rocks - ೫ ಬಂಡೆಗಳು
10 rocks - ೧0 ಬಂಡೆಗಳು
20 rocks - ೨0 ಬಂಡೆಗಳು
100 rocks - ೧00 ಬಂಡೆಗಳು
1000 rocks - ೧000 ಬಂಡೆಗಳು
I see 0 rocks on the ground - ನಾನು ನೆಲದ ಮೇಲೆ 0 ಬಂಡೆಗಳನ್ನು ನೋಡುತ್ತೇನೆ
I see 1 rock on the ground - ನಾನು ನೆಲದ ಮೇಲೆ ೧ ಬಂಡೆಯನ್ನು ನೋಡುತ್ತೇನೆ
I see 10 rocks on the ground - ನಾನು ನೆಲದ ಮೇಲೆ ೧0 ಬಂಡೆಗಳನ್ನು ನೋಡುತ್ತೇನೆ
I see rocks on the ground - ನಾನು ನೆಲದ ಮೇಲೆ ಬಂಡೆಗಳನ್ನು ನೋಡುತ್ತೇನೆ

**[Harshit S K](https://github.com/harshithsk)**

**Comment by Heyhillary** [comment]
Hey @harshithsk,

Thanks for showing interest in adding Kannada to Common Voice.

Are you still interested in adding Kannada ? I am happy to enable the Common Voice project for translation.

To enable this please also share with me the [Pontoon Account](https://pontoon.mozilla.org/) for who you would like to be included as the Pontoon Manager/translator? 

Many thanks,

Hillary

**Comment by harshithsk** [comment]
Hey,

Thanks. Yes loved to do it.
My Pontoon Account email id is ***@***.***

Regards,
Harshit






Regards,
Harshit S K


*“CONFIDENTIALITY NOTICE This e-mail message and any attachments are only
for the use of the intended recipient and may contain information that is
privileged, confidential, or exempt from disclosure under applicable law.
If you are not the intended recipient, any disclosure, distribution, print,
or other use of this e-mail message or attachments is prohibited. If you
have received this e-mail message in error, please delete it and notify the
sender immediately. Thank you.”*

**Comment by Heyhillary** [comment]
Hey @harshithsk,

Thanks for the response 

Due to the privacy settings of our GitHub. I am unable to see your account details.

Could you share with me the URL address of your pontoon profile? You can access this via the main menu, under your user profile (this is usually just your initials when you log-in). You will have to click your user profile twice to see your URL address. 

Many thanks,

Hillary

**Comment by harshithsk** [comment]
Hi @Heyhillary ,

Sorry I didn't notice that. Here you go my profile link -> https://pontoon.mozilla.org/contributors/7N7_XbFrApj0xMvgfppGZlpeZBE/

Regards,
Harshit S K
