### ISSUE TITLE
Can't use Cyrillic symbols in the username 

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3057]
**Describe the bug**
When you use Cyrillic characters in your name, your name will look like this: ?????

1. Go to https://commonvoice.mozilla.org/en/profile/info
2. Set new user name 'Айгиз'
3. Click to SAVE
4. Refresh page
5. The filed username will contains only symbols of ????

<img width="903" alt="username" src="https://user-images.githubusercontent.com/1628540/112792454-efe46800-907c-11eb-87b6-5412f6095cc6.png">

**Comment by phirework** [comment]
This has been fixed in [release 45](https://github.com/common-voice/common-voice/releases/tag/release-v1.45.0)
