### ISSUE TITLE
Only the first second of the recording is audible

### ISSUE THREAD

**Issue by stefangrotz** [common-voice/common-voice#3060]
**Describe the bug**
When you donate your voice only the first second (maybe just halve a second?) is recorded and the rest is cut down. I tested it on Firefox and Chrome on OS X and I also heard cut records from others when validating. 

**To Reproduce**
Record your voice on the browser version of CV and listen to it

**Expected behavior**
Longer recordings

**Comment by phirework** [comment]
Thanks! This is a known issue with FF87.0 and is a duplicate of #3018 so I'm gonna close this. (Working on a fix rn)
