### ISSUE TITLE
404 for my language

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3064]
https://commonvoice.mozilla.org/ba
bashkort language's page is not found. What is  it?

**Comment by AigizK** [comment]
Guys, you moved my language back to the InProgress. Why? I created a team(265+ members), they recorded more 20 hours, checked more 8 hours for a week. Our community one of active for current time in CommonVoice.
<img width="1258" alt="Screenshot 2021-03-31 at 09 59 34" src="https://user-images.githubusercontent.com/1628540/113092912-577aee80-9208-11eb-878c-e651d61c6341.png">

**Comment by AigizK** [comment]
Could someone give an information? When will restored? can you recover our data?

**Comment by ftyers** [comment]
Hi @AigizK, I don't know what is going on, but the Galician community has reported the same problem on Matrix. I'm sure the data is still there and that the team is working on recovering it. Hang in there and I'm sure they'll get back soon with an answer!

**Comment by phirework** [comment]
Hey folks, sorry about this. I pushed a hotfix yesterday to deal with a FF87 bug and that seems to have rolled back a language setting for Bashkir. I'm testing a new build that will fix that right now and there will be another release later this evening. 

Rest assured, there's no data loss, all 17k clips that have been recorded so far are safe in the db.

**Comment by phirework** [comment]
Alright, we're all back to normal https://commonvoice.mozilla.org/ba Again, sorry about that!

**Comment by AigizK** [comment]
Thank you very much. Your team is BEST!
