### ISSUE TITLE
No Accents for the Italian language

### ISSUE THREAD

**Issue by gabriele-cannizzaro** [common-voice/common-voice#3065]
**Describe the bug**
Not sure this is a bug or simply a lack of information in setup, but the dropdown to select the Accent after setting the language to Italian is empty.

**To Reproduce**
1. Register a new profile or open the Profile settings page (https://commonvoice.mozilla.org/en/profile/info)
2. Select "Italiano" from the Language dropdown
3. Open the Accent dropdown
4. The dropdown is empty

**Expected behavior**
A list of Italian accents should appear in the dropdown.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.90 (Official Build) (64-bit)

**Comment by ftyers** [comment]
Accents may not have been defined for Italian yet.  [This post](https://github.com/common-voice/common-voice/issues/3046) discusses some of the issues, e.g. for languages which don't have them yet it might be worth waiting for the new accent and variant strategy to come online before defining them. But as @phirework says 
> "... if you can demonstrate consensus from linguists/other experts for a list of regions in Italy/the diaspora that align with the Language and Accent strategy, I'd be happy to take a look at a pull request (see [Galician](https://github.com/common-voice/common-voice/pull/3045) as a recent example)."
