### ISSUE TITLE
Stats and voices api return 500 Internal Server Error

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3076]
The stat and voice dashboards are broke
https://commonvoice.mozilla.org/api/v1/clips/stats
https://commonvoice.mozilla.org/api/v1/clips/voices

![image](https://user-images.githubusercontent.com/1628540/113819571-ed77c180-9792-11eb-9557-7a2bb7e2d839.png)

are also broken:
https://commonvoice.mozilla.org/api/v1/language_stats
https://commonvoice.mozilla.org/api/v1/clips/leaderboard
https://commonvoice.mozilla.org/api/v1/clips/votes/leaderboard
https://commonvoice.mozilla.org/api/v1/contribution_activity?from=everyone

**Comment by phirework** [comment]
Those endpoints all load for me - those values are cached and it's possible you caught them during cache refresh?

**Comment by AigizK** [comment]
yes, it currently works, but I tried opening in incognito mode and on my smartphone and got 501 everywhere. i tried throughout the day, the result was the same.

**Comment by phirework** [comment]
I will take a look at our logs, thanks!
