### ISSUE TITLE
CV website fonts Not supporting many languages

### ISSUE THREAD

**Issue by ibrahimasarr** [common-voice/common-voice#3077]
**Describe the bug**
Hi all
There is an issue displaying many characters that are in Latin Etended and IPA blocks of the Unicode standard.
Many African languages use those and the fonts Mozilla uses are often limited to Basic Latin, yet many languages use glyphs from Extended Latin A and B and IPA extensions.
![Screenshot_20210408-015752_Firefox](https://user-images.githubusercontent.com/2011371/114005221-9ee42900-985f-11eb-9d12-db735a91b56c.jpg)

Common Voice website uses many fonts that don’t support those languages including Fulah.
Characters that aren’t supported are substituted with another font disrupting harmony.
**To Reproduce**
1. Go to 'Common Voice dev website '
2. Click on 'languages'
3. Scroll down to 'Pulaar-Fulfulde'
4. See characters in single words with different fonts

**Expected behavior**
Characters ɗ ŋ ƴ ɓ Ɗ Ŋ ƳƁ should be displayed in the same fonts.

**Screenshots**

**Comment by phirework** [comment]
Do you know off the top of your head of font families that do support the Latin Extended B and IPA blocks? None of the usual systems fonts (Arial, Georgia, etc.) seems to render these correctly either. What font family are you using on your computer?

**Comment by ibrahimasarr** [comment]
Hi
Thanks
There are hundreds actually:
From Google fonts:
 Andika
Andika New Basic
Anton
Arimo
Cousine
David Libre
Didact Gothic
EB Garamond
Fira Sans
Fira Sans Condensed
Fira Sans Extra Condensed
Gentium Basic
Gentium Book Basic
Gothic A1
Inter
Judson
M PLUS Rounded 1c
M PLUS 1p
News Cycle
Noto Sans
Noto Serif
Nunito
Questrial
Sawarabi Gothic
Tinos

And...
All fonts that support these Unicode blocks
 
Latin Extended-A U+0100..U+0148, U+014A..U+017F 
Latin Extended-B U+0180..U+024F 
IPA Extensions U+0250..U+02AF 

Thanks
Ibrahima



 
 
 Le vendredi 9 avril 2021 à 18:36:23 UTC+2, JZ ***@***.***> a écrit : 







Do you know off the top of your head of font families that do support the Latin Extended B and IPA blocks? None of the usual systems fonts (Arial, Georgia, etc.) seems to render these correctly either. What font family are you using on your computer?

**Comment by ibrahimasarr** [comment]
You can use the following sentence as a test to display all the characters needed for most African languages!
Ɗaɓɓooɓe ŋeñema ƴoɓe ǧur'aana ɲ ƊAƁƁOOƁE ŊEÑEMA ƳOƁE ǦUR'AANA Ɲ
Cheers

**Comment by phirework** [comment]
Can you verify whether this fix on the dev server works? Fulah should now be using Inter for sans-serif and Noto Serif for serif font faces https://dev.commonvoice.allizom.org/ff 

If this works, it'll be deployed on production in a couple of weeks. I'm enabling font family switching on a case by case basis, so if there are other languages you are aware of that need this treatment, please let me know.

**Comment by ibrahimasarr** [comment]
Thanks a lot.
Big headings seem to be working fine. I have to check with computer because it's late night, and mo am im bed.
However, default text is not good as we see fonts being substituted. See attachment.
Cheers
     Le samedi 10 avril 2021 à 00:25:06 UTC+2, JZ ***@***.***> a écrit :  
 
 


Can you verify whether this fix on the dev server works? Fulah should now be using Inter for sans-serif and Noto Serif for serif font faces https://dev.commonvoice.allizom.org/ff

If this works, it'll be deployed on production in a couple of weeks. I'm enabling font family switching on a case by case basis, so if there are other languages you are aware of that need this treatment, please let me know.

**Comment by ibrahimasarr** [comment]
![Screenshot_20210410-014707_Firefox](https://user-images.githubusercontent.com/2011371/114250966-b75b5d00-999f-11eb-80d2-517875fc84d9.jpg)

**Comment by phirework** [comment]
Thanks! I've adjusted the weight of the font face, can you check again?

**Comment by phirework** [comment]
Hi there, this should be on production in full. As I mentioned, this font is enabled on a case-by-case basis, so if there are other languages currently available on CV besides Fulah that should have this switched on please let me know. I'm going to close this issue as the original problem has been addressed.
