### ISSUE TITLE
Who can add an accent for my language

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3079]
My language a Bashkort(ba) and it has 3 accents:
1. көньяк
2. көнсығыш
3. төньяҡ-көнбайыш

Who can add them?

**Comment by ftyers** [comment]
Hi Aigiz! [This post](https://github.com/common-voice/common-voice/issues/3046) discusses some of the issues, e.g. for languages which don't have them yet it might be worth waiting for the new accent and variant strategy to come online before defining them. But as @phirework says 
> "... if you can demonstrate consensus from linguists/other experts for a list of regions in Italy/the diaspora that align with the Language and Accent strategy, I'd be happy to take a look at a pull request (see [Galician](https://github.com/common-voice/common-voice/pull/3045) as a recent example)."

**Comment by Heyhillary** [comment]
Hey @AigizK 

Thanks for request, as of [December 2021 people](https://github.com/common-voice/common-voice/releases/tag/release-v1.61.0) can now add in their accents via their profiles. 

![image](https://user-images.githubusercontent.com/85501774/149160929-417f8a19-5789-4c77-b0cb-993111db15a5.png)

We will be doing a review of the accents submitted to come up as auto-suggestions. Please subscribe to the [weekly updates ](https://discourse.mozilla.org/t/weekly-update-thread-2021-2022/84411) through the watch button, for when we annouce the review. 

Learn more about the changes to languages, variants and accents via [this blog](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/).
