### ISSUE TITLE
Statistics on the frontpage are displayed wrongly on certain display sizes.

### ISSUE THREAD

**Issue by stefangrotz** [common-voice/common-voice#3085]
**Describe the bug**
On small screens the statistics are displayed wrongly, they are much wider than they should:
<img width="799" alt="Bildschirmfoto 2021-04-11 um 12 15 48" src="https://user-images.githubusercontent.com/5982239/114300314-04365500-9ac0-11eb-89fa-3ffae00fb8a1.png">

**Desktop or Mobile (please complete the following information):**
- Firefox and Chrome on macOS and Android

**Comment by phirework** [comment]
Thanks for reporting! This was a bug accidentally introduced in the last release and will be fixed in the next: dev.commonvoice.allizom.org/

**Comment by phirework** [comment]
This has been fixed in [release 45](https://github.com/common-voice/common-voice/releases/tag/release-v1.45.0)
