### ISSUE TITLE
Maori language request

### ISSUE THREAD

**Issue by waymousa** [common-voice/common-voice#3092]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
Maori

**Language code**
639-1: mi, 639-2/B: mao, 639-2/T and 639-3: mri

**Language size**
125,000

**Plural forms**
How would you translate the following in this language?

0 rocks - kore toka
1 rock - kotahi toka
2 rocks - e rua nga toka
3 rocks - e toru nga toka
4 rocks - e wha nga toka
5 rocks - e rima nga toka
10 rocks - Tekau nga toka
20 rocks - rua tekau nga toka
100 rocks - kotahi rau toka
1000 rocks - kotahi mano toka
I see 0 rocks on the ground - ka kite au i nga toka kore i te whenua
I see 1 rock on the ground - kite ahau i tetahi toka i runga i te whenua
I see 10 rocks on the ground - kite au i nga toka tekau i runga i te whenua
I see rocks on the ground - ka kite au i nga toka i te whenua

**Pontoon manager**
sam.waymouth@gmail.com

**Comment by ftyers** [comment]
Hi @waymousa thanks for your interest! Are you in contact with Te Hiku Media? Specifically they have the [Kōrero Māori](https://papareo.nz/#mahi) project for collecting speech data in Māori. You can find the app [here](https://koreromaori.com/).

**Comment by waymousa** [comment]
Hi there,  thanks for reaching out!  No I had not heard of them before and it sounds like an interesting project.  I'll take a look at this shortly.  Are they intending to build this on the common voice as well?  I am interested in developing keyword apps.  There are a number of homes for elderly Maori being built in NZ and they usually have Alexa built in to control the lights and heating  but alas my employer Amazon could not be convinced to add Maori to the supported languages.  Too expensive to train and little commercial value - only 125000 Maori speakers globally.  I'm currently working on the TinyML courses from Harvard edx and wanted to build a Maori keyword app for my first project.  I'll reach out to Te Hiku and see if this is something they would be interested in collaborating on.  In the meantime, is it possible to add Maori as a project in Common Voice?  I like the licensing model which is very permissive.  I'm a keen educator as well so I want to set up courses in TinyML for Maori children in my home tribal area of Otago.  If I can teach kids how to build their own TinyML applications in their own language it opens up a world of possibility for inclusiveness and native peoples everywhere.  Once a language is in the cloud then it can grow.

**Comment by ftyers** [comment]
Hi there! It is not my position to say (I do not work for Mozilla or NVIDIA) but I would guess that the team would be reluctant to add a language if there were a community that was against it.

In terms of what you can do to get Amazon to step up, I would suggest campaigning for legal protections for Maori and requirements for technology in New Zealand to support it. Large companies are legally required to, as you mentioned, maximise commercial value. So, they will generally only invest if it has commercial value (either in terms of getting money or valuable data from people or in terms of publicity) or to comply with legal requirements. 

My impression is that the permissiveness of the licence is one of the reasons that the community does not want to be involved (if you check out the video they are quite explicit), but I leave it up to someone from the community to comment themselves. 

I think Common Voice has great potential for use in education, but I do not believe that it is necessary for the community to allow companies like Amazon to extract profit from them. That just reeks of extractive colonialism.

**Comment by waymousa** [comment]
Hi there Francis, I had a message from Keoni (Te Hiku Media) this morning.  I haven't had time to write back to him yet but I agree with his point of view about CV and the licensing model.   I've also been in touch with the AI/ML team at Waikato University Computer Science faculty and have a meeting with them in May to find a way forward.  Thanks for your views, its been interesting to hear some different perspectives on OpenSource.   Speaking for myself, I'm looking at this in my capacity as a New Zealander, Ngai Tahu and computer geek.  As such, my interest is teaching the next generation of Maori computer geeks AI/ML and in their own language.  Education is something I'm passionate about and I've lead workshops in Hour-of-Code the the last 4 years. Its also true I'm an Amazonian and that's what lets me make my hobby my career and pays the bills.  To be clear, I wouldn't agree with any Big Tech owning the language of a people.  That's why I think that teaching the next generation of Maori computer scientists is the right approach to maintaining that ownership, giving opportunity to Maori to enter the field of computer science as well as making the field more inclusive.  If I can help others get into the industry via an easier path than I followed then my mission is complete :-)

**Comment by ftyers** [comment]
Sounds great, happy to hear you are in contact ! :) And I look forward to hearing about your work! :D I definitely agree that the future is in speakers having the tools and knowledge to work on their own languages. It shouldn't be necessary to rely on handouts!

**Comment by KathyReid** [comment]
Kia ora @waymousa. 
I think there is a broader conversation here around how Common Voice approaches the collection of languages for which there are issues of sovereignty or _tino rangatiratanga_. For example, in Australia there are Indigenous language protocols that are specific to different language and family groups. 

Ngā mihi, Kathy

**Comment by phirework** [comment]
Thanks for the discussion here folks! The timing seems rather fortuitous as [Wired has been writing about this](https://www.wired.co.uk/article/maori-language-tech) as well. As everyone here seems in agreement about the conflicts between CV's licensing model and the goals of the community I'm going to close the issue. Feel free to reach out if you come to a different consensus after discussing with Te Hiku.

**Comment by OliverDeBrisbane** [comment]
It’s worth noting there are macrons in Māori:
- ā
- ē
- ī
- ō
- ū
