### ISSUE TITLE
[UI mobile website] flowchart

### ISSUE THREAD

**Issue by StanislasG** [common-voice/common-voice#3098]
**Describe the bug**

**To Reproduce**
1. go to https://commonvoice.mozilla.org/en/about
2. resize the windows to get the mobile version (I did it with opening expect element tool on firefox)
3. Scroll down to the flowchart
4. See error number appear on the flow chart from 1 to 6.2

**Expected behavior**
`<div class="number">01</div>`
should not appear when resizing the window

**Screenshots**
![Screenshot_2021-04-22 Common Voice by Mozilla](https://user-images.githubusercontent.com/48719820/115629480-b4972b00-a302-11eb-8a1c-dbd70854dbee.png)

**Desktop or Mobile (please complete the following information):**
 - OS: windows 10
 - Browser firefox
 - Version 87.0 (64 bits)

**Comment by phirework** [comment]
Hi there, this is actually expected behaviour for the mobile design. I believe the intention is that on a long scroll people may find it difficult to keep track of which step in the flow chart they're in, and the numbers are meant to help with that. Can you confirm @mbransn?

**Comment by mbransn** [comment]
@phirework thanks for the tag in, yes, this is expected to help guide through the flow on smaller screens. Thanks for checking in about it @StanislasG.
