### ISSUE TITLE
Getting "Internal Server Error" on confirmation to sign in to commonvoice.mozilla.org.

### ISSUE THREAD

**Issue by fnielsen** [common-voice/common-voice#3104]
**Describe the bug**
Getting "Internal Server Error" on confirmation to sign in to commonvoice.mozilla.org and not able to sign in to Common Voice.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/da
2. Enter email and press Enter
3. Press "Send me an email to continue"
4. Read email and click on "Sign in to com..."
5. See error "Internal Server Error"  on https://sso.mozilla.com/forbidden

**Expected behavior**

I expected to be logged in.

**Desktop or Mobile (please complete the following information):**
 - OS: Linux
 - Browser: Mozilla Firefox  for Ubuntu canonical 1.0
 - Version 88.0 (64-bit)
- Privacy Badger installed, but disabled on auth0.com and sso.mozilla.com

**Further informatoin**
I am getting 302 on two calls to auth.mozilla.auth0.com and then a 500 on sso.mozilla.com and finally a 200 on sso.mozilla.com for the favicon.ico. The 500 is https://sso.mozilla.com/forbidden?error=eyJ....&state=g6F...

**Comment by fnielsen** [comment]
Managed to login via "Log in with Firefox". I do not know whether that is related?

**Comment by phirework** [comment]
For passwordless login, the email link needs to be opened in the same browser where the request originated from. Is your email client opening up a new window / an internal browser, by any chance?

**Comment by fnielsen** [comment]
My click in the link in the email spawns a new window with the same browser in the same session.

**Comment by phirework** [comment]
Unfortunately I'm still not able to replicate this. Do you know if your email provider is adding any sort of redirect on the link in the email (to scan for malicious links or whatever)? Do you also get a 500 forbidden error if you copy/paste the URL underneath the button instead of clicking the link?

**Comment by fnielsen** [comment]
I cannot reproduce the error anymore. I get to https://commonvoice.mozilla.org/da/profile/info alright now. The link in the email wa not mangled, - as far as I can check.

Perhaps this was a one off oddity that can be closed.
