### ISSUE TITLE
I need to know how many entries have been rejected for an account

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3117]
To attract more users, I launched a contest. According to the terms of the competition, it was necessary to record the voices.

**Problem:**
Someone sends empty recordings, audio takes a little more than 2 seconds, but nothing is recorded there. And the statistics show, as if the person read the text and recorded his voice. I need to exclude such people from my list.

**Possible solutions:**
1. Show information (you can show only in the API) how many votes of  this person had rejected after checking

In this case, I can easily find the crackers. This option is perfect for me

2. You on your side will check whether the audio is empty or not. This can be done for example using webrtcvad. And such empty records should not be taken into account.

But here he can write another random text. So it is not best solution.

**Comment by ftyers** [comment]
I think the easiest thing in this case is to wait for the dataset release in June and then do the checking yourself. I don't expect the guys at NVIDIA have enough capacity to do this kind of thing on an ad hoc/per language basis.

**Comment by AigizK** [comment]
Created by me a contested will be finished on May 31. And I should know on this time that the winner is a "good" people, he didn't use a hack. So the way "Show information how many votes of this person had rejected after checking" i think a best way

**Comment by ftyers** [comment]
I think that this is unlikely to happen, you'll probably need to work around it on your end. There is only one person working on Common Voice and they are unlikely to have the time to work on something outside their given list of work tasks (which are endless). Potentially if you made a PR you might get it merged in time, but it's 13 days... so not much time for review. 

Probably the best thing to do is to extend the contest notification until the dataset release, you can just tell people you need to validate the winner and it is a manual process. Of course it would have been better to work this all out before starting the competition ;)

**Comment by AigizK** [comment]
there is another solution. there is a ready PR(https://github.com/common-voice/common-voice/pull/2865) that will allow you to download  all the your audio files. if this PR was merged, i could ask from winner to send all his files and check them myself

**Comment by AigizK** [comment]
Wow. It is very cool! Thank you very much for that.
