### ISSUE TITLE
Guaraní ready for collection

### ISSUE THREAD

**Issue by ftyers** [common-voice/common-voice#3120]
Guaraní now has the interface at 100% and over 5000 validated sentences in sentence-collector! Could it be enabled for collection on the main site ? :D

**Comment by MichaelKohler** [comment]
The next automatic export will be in about 9 hours so with the next Common Voice website release it will be enabled.

**Comment by MichaelKohler** [comment]
FWIW, there is no manual steps needed to enable it, if the conditions are fulfilled it will work.

**Comment by ftyers** [comment]
Is there a way to check that everything is ok before the export? The stats update rarely and it says that there are still 280 to validate, but when I click "Validate" it says "none to review":
![imatge](https://user-images.githubusercontent.com/449545/118687167-9dae0080-b7fc-11eb-940b-a77f0a680da3.png)

But I don't know if that's because we hit the mark or if I just validated everything and someone else needs to also validate.

**Comment by MichaelKohler** [comment]
Stats are only updated every 6 hours maximum.

**Comment by ftyers** [comment]
Looks like we're fine:

![imatge](https://user-images.githubusercontent.com/449545/118690518-0cd92400-b800-11eb-8541-90b7829f84ec.png)

**Comment by phirework** [comment]
Happy launch day folks! https://commonvoice.mozilla.org/gn
