### ISSUE TITLE
Khmer language

### ISSUE THREAD

**Issue by metasy** [common-voice/common-voice#3136]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add? 
Khmer

**Language code**
Please provide the ISO-639-1 code
km

**Language size**
Number of active speakers of this language in the world

19 milliions

**Plural forms**
How would you translate the following in this language?

0 rocks : ថ្ម​០
1 Rock ​: ថ្ម១
2 rocks : ថ្ម២
3 rocks : ថ្ម៣
4 rocks : ថ្ម៤
5 rocks : ថ្ម៥
10 rocks : ថ្ម១០
20 rocks : ថ្ម​២០
100 rocks : ថ្ម១០០
1000 rocks : ថ្ម១០០០
I see 0 rocks on the ground : ខ្ញុំឃើញថ្ម ០ នៅលើដី
I see 1 rock on the ground : ខ្ញុំឃើញថ្ម ១ នៅលើដី 
I see 10 rocks on the ground : ខ្ញុំឃើញថ្ម ១០ នៅលើដី
I see rocks on the ground : ខ្ញុំឃើញថ្មនៅលើដី

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

me(?)

**Comment by ftyers** [comment]
Hi  @metasy! Thanks for your interest. Khmer is [already on Pontoon](https://pontoon.mozilla.org/km/) so you don't need to request a new language on Pontoon, you just need to request a new project. I suggest getting in contact with the [team lead](https://pontoon.mozilla.org/km/info/) or the other [contributors](https://pontoon.mozilla.org/km/contributors/) to ask them to add Common Voice to Khmer on Pontoon. In the meantime, you can also start collecting sentences through the [sentence collector](https://common-voice.github.io/sentence-collector/). Thanks again and welcome!

**Comment by Heyhillary** [comment]
Hey @metasy, thanks for showing interest in adding Khmer onto Common Voice. 

I'm happy to add the project, is it possible if you could share with me your pontoon account link ?

Many thanks,

Hillary

**Comment by galbiati** [comment]
Hey @Heyhillary, I don't see Common Voice on Khmer's pontoon page for either enabled or request-able projects. I'm guessing this conversation didn't go anywhere?

<img width="998" alt="image" src="https://user-images.githubusercontent.com/6351133/148076872-5db2c58c-e58a-4352-bd62-5b8e16302c4f.png">

If nobody else is staying on top of Khmer for Common Voice, I'd be willing to get more involved. Let me know what's needed? [Pontoon](https://pontoon.mozilla.org/contributors/JrW147eJYTUiYSKiUHgqazjzIuA/)

**Comment by Heyhillary** [comment]
Hey @galbiati 

Welcome to Common Voice and thanks for offering to be involved in our project. I have now enabled the Common Voice project for [Khmer.](https://pontoon.mozilla.org/km/common-voice/).

Would it be possible if you could create or/and share your pontoon account, so I can give you translator access ? 
Once I have your details, I can connect you with the Khmer manager and onboard you. 

All the best, 

Hillary

**Comment by galbiati** [comment]
Thanks, Hillary! Absolutely: https://pontoon.mozilla.org/contributors/JrW147eJYTUiYSKiUHgqazjzIuA/

**Comment by Heyhillary** [comment]
Thank you @galbiati 

I have now added you as Manager for Khmer and Translator for Common Voice.

A team managers role means all your work will go to staging (and later to production) without peer review. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

If you have any questions join us on the [community chat](https://chat.mozilla.org/#/room/#common-voice:mozilla.org), also if you would like any community support I'm happy to share ideas and support you.

For more support on onboarding please check out this [slide deck](https://docs.google.com/presentation/d/1FVTWmWYZCfmjkfASm3EVImMrY-Hu__C3z8XZ8f4VyNk/edit?usp=sharing) or [Community Support Desk](https://discourse.mozilla.org/t/introducing-community-support-desk/88158). 

Thank you and welcome to Common Voice community!
