### ISSUE TITLE
Request for Addition of Yoruba Language

### ISSUE THREAD

**Issue by QueenBuki** [common-voice/common-voice#3137]
**Language name**
What language would you like to add?
Yoruba/Yórùbá

**Language code**
Please provide the ISO-639-1 code
ISO 639-3 | yor
Glottolog: http://glottolog.org/resource/languoid/id/yoru1245

**Language size**
Number of active speakers of this language in the world
28 million (2007)

**Plural forms**
How would you translate the following in this language?

0 rocks  àpáta òdo
1 rock àpáta kàn
2 rocks àpáta mejì
3 rocks àpáta mẹ́ta
4 rocks àpáta mẹ́rin
5 rocks àpáta máàrún
10 rocks àpáta mẹ́wá
20 rocks àpáta oguń
100 rocks àpáta ọgọ́rùn
1000 rocks àpáta ẹ́gbèrún
I see 0 rocks on the ground      Mo ri àpáta òdo ní ilẹ̀
I see 1 rock on the ground        Mo ri àpáta kàn ní ilẹ̀
I see 10 rocks on the ground    Mo ri àpáta mẹ́wá ní ilẹ̀
I see rocks on the ground         Mo ri àpáta ní ilẹ̀

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
[community manager] (https://pontoon.mozilla.org/contributors/TNxJTzgFTMCq5ABDaONawRnHIHM/)

**Comment by ftyers** [comment]
Hi  @QueenBuki ! Thanks for your interest. Yoruba is [already on Pontoon](https://pontoon.mozilla.org/yo/) so you don't need to request a new language on Pontoon, you just need to request a new project. I suggest getting in contact with the [contributors](https://pontoon.mozilla.org/yo/contributors/) to ask them to add Common Voice to Yoruba on Pontoon. The manager is [Umegbewe](https://pontoon.mozilla.org/contributors/uY6fuhBMWWrSGSs8V2FrSKf7HrI/). In the meantime, you can also start collecting sentences through the [sentence collector](https://common-voice.github.io/sentence-collector/). Thanks again and welcome! Do let us know if you have any questions about the process! We're available also on Matrix at [#CommonVoice:mozilla.org](https://app.element.io/#/room/#common-voice:mozilla.org)

**Comment by Heyhillary** [comment]
Hey @QueenBuki, I have Common Voice added onto [Yoruba team](https://pontoon.mozilla.org/yo/common-voice/)and have given you translator permission for Common Voice. 

Translators can submit translations directly in a specific locale, and review other contributors’ suggestions. Therefore will be able to start translating the web side of the project. 

Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

By any chance have you been able to reach out to Umegbewe ? At the moment I haven't given you manager responsibilities, I was I would like to ensure that Umegbewe is aware of another manager being added to the Yourba Team

If you have any questions, please let me know.

**Comment by QueenBuki** [comment]
Hi,

Thanks for the resources. I will go through them over the next few days
and get back to you if I have any questions.
I've not gotten a response from Umegbewe though.

**Comment by Heyhillary** [comment]
Hey @QueenBuki,

Thanks for the response and for reaching out to Umegbewe. 

I've just noticed Umegbewe, hasn't been active for a while on Pontoon. I have now made you the manager of Yoruba Pontoon. This means all your work will go to staging (and later to production) without peer review.

All the best,

Hillary

**Comment by QueenBuki** [comment]
Okay, thanks for the update.
