### ISSUE TITLE
Add clear instructions in the speak section.

### ISSUE THREAD

**Issue by VirkSaab** [common-voice/common-voice#3138]
**Is your feature request related to a problem? Please describe.**
I cannot find the instructions for what my speaking speed should be or do I have to give pause between words.

**Describe the solution you'd like**
It will very easy for a user to have the instructions on the *speak* page itself. Maybe add a link to a set of instructions like *Instructions on how to give a quality speech.*

**Describe alternatives you've considered**
I am hoping to find the following instructions:
1. Do you need to have a quiet background or just natural background you are sitting in?
2. What should be the speed of speaking? Do I need to speak in a natural way or a little slower?
3. Do I need to pause between words?

This will bring more consistency to the labeling process.
Please let me know if you need more clarification.
Thank you.

**Comment by Fooftilly** [comment]
You should look at his community post where this was discussed: https://discourse.mozilla.org/t/discussion-of-new-guidelines-for-recording-validation/36465

**Comment by VirkSaab** [comment]
Got it. Thanks!
