### ISSUE TITLE
List of places to get in contact with different language communities

### ISSUE THREAD

**Issue by ftyers** [common-voice/common-voice#3148]
Many language communities are self organising and have their contact channels on diverse systems. It would be cool to keep a list of them so that when someone wants to get in contact they know where to go. Here are a couple to start with:

* General:
  * [#Common Voice](https://app.element.io/#/room/#common-voice:mozilla.org) on Matrix
  * Common Voice on Telegram: https://web.telegram.org/#/im?p=@mozilla_common_voice
* Bengali (`bn`): 
  * [#bn-common-voice:mozilla.org](https://app.element.io/#/room/#bn-common-voice:mozilla.org)
* Catalan (`ca`):
  * https://t.me/softcatala_tecnologiesparla 
* Czech (`cs`):
  * http://t.me/MozillaCZ
* Dhivehi (`dv`):
   * https://dhivehi.ai/ 
   *  https://discord.com/invite/5ZdTHsN8Mn 
* Guaraní (`gn`):
  * https://t.me/joinchat/Y7QOWuaTw8dhMzli 
* Italian (`it`):
  * https://t.me/joinchat/QzLbqUl_P06IWojE 
* Traditional Chinese (`zh-TW`):
  * https://chat.mozilla.org/#/room/#common-voice-tw:mozilla.org  
  * https://t.me/moztwcv
  * https://bit.ly/cv-line 
* Turkic (`cv`, `tt`, `ky`, `kk`, `tr`, `sah`):
  * https://t.me/joinchat/WRFz62nYdmJ1uo1L

**Comment by ftyers** [comment]
You're welcome! And sure, although maybe a link from the playbook to somewhere in the repository [docs/](https://github.com/common-voice/common-voice/tree/main/docs) for example, so that it can be easily editted/PRd against.  @phirework what do you think?

**Comment by Mozinet-fr** [comment]
French https://chat.mozilla.org/#/room/#common-voice-fr:mozilla.org

**Comment by phirework** [comment]
This is great, thanks for kicking it off Francis! As far as the repo/I'm concerned this can live in `/docs` with a link to it from the top-level README under "How to contribute". Would you like to submit a PR? 

It should definitely be part of the playbook at some point but I'm not sure what the ownership status of that document is right now.

**Comment by ftyers** [comment]
Done :)
