### ISSUE TITLE
Request new language - Twi (Ghana)

### ISSUE THREAD

**Issue by DanielAgyeman** [common-voice/common-voice#3157]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Twi
**Language code**
Please provide the ISO-639-1 code
tw
**Language size**
Number of active speakers of this language in the world
17-18 million
**Plural forms**
How would you translate the following in this language?

0 rocks - abotan ohunu
1 rock - ɔbotan baako
2 rocks - abotan mmienu
3 rocks - abotan mmiɛnsa
4 rocks - abotan ɛnan
5 rocks - abotan enum
10 rocks - abotan edu
20 rocks - abotan aduonu
100 rocks - abotan ɔha
1000 rocks - abotan apem
I see 0 rocks on the ground - mehu abotan ohunu fam
I see 1 rock on the ground - mehu ɔbotan ohunu fam
I see 10 rocks on the ground - mehu abotan edu fam
I see rocks on the ground - mehu abotan fam

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://pontoon.mozilla.org/contributors/5FNm_P0yMBbQS5lycBtCMfozK84/

**Comment by ftyers** [comment]
Hi @DanielAgyeman thanks for your interest in Common Voice! @peiying2 could you take a look at this? While Twi is being set up in Pontoon, you can start adding sentences to the [sentence collector](https://commonvoice.mozilla.org/sentence-collector/#/), Twi is already enabled there for collection. If you have any questions or would like help with sentence collection or processing, please feel free to get in touch with us on [Common Voice Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) or [Discourse](https://discourse.mozilla.org/c/voice/239).

**Comment by peiying2** [comment]
@Heyhillary let's connect so you know how to set things up in Pontoon.

**Comment by peiying2** [comment]
> Hi @DanielAgyeman thanks for your interest in Common Voice! @peiying2 could you take a look at this? 

Thank you for the request. Moving forward, @Heyhillary would be working in Pontoon to address this type of requests. I will be working behind the scene to support her.

**Comment by Heyhillary** [comment]
Hey @peiying2 , I have followed up via slack to arrange a walkthrough

**Comment by DanielAgyeman** [comment]
Hello! I hope you're well. I was wondering if you could provide an update on this please? Thank you!

**Comment by Heyhillary** [comment]
Hey Daniel, sorry for the delay. I and Peiying are meeting up early next week. Once I've gone through the walkthrough of Pontoon (I recently joined the team), I will add your Twi.

**Comment by DanielAgyeman** [comment]
Hey Hillary. Thanks for the quick reply. No problem at all! Thanks for the update and hope you're settling in well to the team. I look forward to hearing from you. Thanks!

**Comment by Heyhillary** [comment]
Hello @DanielAgyeman  we have just enabled [Twi](https://pontoon.mozilla.org/tw/common-voice/) in Pontoon.
Your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

**Comment by DanielAgyeman** [comment]
Hi Hillary. Sorry for the delay in getting back to you. I saw your email asking whether I would still like to work on the Twi language. Please could you explain what I need to do to move this forward? I’m afraid it has been a while and I have lost track of this - but I would like to start it up again. Thanks. I look forward to hearing from you. Daniel

**Comment by Heyhillary** [comment]
Hello @DanielAgyeman 

No worries and thanks for showing interest in the project.

I would like to suggest two routes you can take depending on your availability.

**Route 1: Build Community first** 
- Reach out to Twi-speaking people who would be interested in building community with you on this project. We recently had a [social media campaign](https://discourse.mozilla.org/t/community-social-media-campaign-launching-6th-october/86546/13) that has some assets you can use to talk about the project.
- You can divide some roles such as localising pontoon, sentence collection for more details please check the Common Voice Community playbook (https://common-voice.github.io/community-playbook/) 
- You can also use Common Voice channels such as matrix and discourse to bring your community together. 
- You might even want to reach out to funders such as [Lacuna Fund ](https://t.co/rtgyqJWlnd?amp=1) who are supporting the development of the African Language Dataset (please note the deadline is 2nd Nov). That can support your community efforts such as future campaigns. 

**Route 2: Start localisation, then build community**
- Using the [L10N] (https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)guide you can start localising Common Voice Website 
- You may want to start reaching out to people who could help you in your local community 
- Once localisation is complete start focusing on building community

If you need any support please let me know.

**Comment by DanielAgyeman** [comment]
Hello @Heyhillary I hope you're well. I have now finally got 5,003 validated sentences for Twi, and the website is now 76% localized. Please could you confirm if this is enough for the Twi language to be live on the website and accept recording/reviews? I have had a look on the website and it is showing '1/750' for the Sentences section (see attached). Please could you confirm what this means?

<img width="394" alt="Screenshot 2022-08-15 at 09 59 33" src="https://user-images.githubusercontent.com/86248032/184606952-7e2e67cd-5231-4c93-ab1d-c79ab1624ae1.png">

Thanks,

Daniel

**Comment by Heyhillary** [comment]
Hey @DanielAgyeman ,

Congratulations on this fantastic milestone!

@mozgzh - when will the next release be as Twi might be the 100th Language on the platform  today !

**Comment by DanielAgyeman** [comment]
Thanks @Heyhillary - looking forward to hearing from you

**Comment by Heyhillary** [comment]
Hey @DanielAgyeman 

Last night a release was made to the platform to add your sentences. 

The data regarding sentence counts/language progression may take some time to show up since the data is cached. 

I will update you soon ! Thank you so much for making this happen !

Would you be interested in a short interview in English and Twi to commemorate that Twi is 100th Language ?

**Comment by DanielAgyeman** [comment]
Hey @Heyhillary 

Thank you for the update. I have since added a whole host of new sentences. Do you know when the next release will be after this one?

Glad to hear that Twi is now the 100th language on the platform :) that's very exciting! 

Would this be a written interview or an audio/video interview? Also do you know kind of questions will be asked? Thanks!

**Comment by Heyhillary** [comment]
I think lets do a written interview - and thank you !

1.  About you and your experience of Twi in voice technology ?

2. Why did you join the Common Voice Project and who did you work with?

3. What do you wish for the data to be used for ?

Could you share this by Monday to my email which is hillary@mozillafoundation.org please ?

**Comment by DanielAgyeman** [comment]
Hi @Heyhillary okay no problem - I will get back to you by Monday.

The sentences have updated now but it is still appearing under 'In Progress' (see attached). Do you know when it will come under the 'launched' list and when it will be possible to start recording?

<img width="1515" alt="Screenshot 2022-08-19 at 16 41 35" src="https://user-images.githubusercontent.com/86248032/185656275-6b173d32-0a10-4565-ae91-42ef763c3317.png">


Thanks

**Comment by Heyhillary** [comment]
Hey @DanielAgyeman 

Twi is now available on Common Voice. Thanks for your patience !

Congratulations !!!
