### ISSUE TITLE
Request for new language: Nias

### ISSUE THREAD

**Issue by sslaia** [common-voice/common-voice#3160]
Nias language community, mainly active on Nias Wikipedia (nia.wikipedia.org) and Nias Wiktionary (nia.wiktionary.org), would like to contribute voices in Nias language, which is not available as a language of choice on Common Voice.

**Language name**
**Nias** (or the natives call it **Li Niha**)

**Language code**
**nia** (ISO 639-3 code)
Glottolog: **https://iso639-3.sil.org/code/nia**
SIL: **https://iso639-3.sil.org/code/nia**

**Language size**
Over 800.000 people.

**Plural forms**
How would you translate the following in this language?

0 kara
1 kara
2 kara
3 kara
4 kara
5 kara
10 kara
20 kara
100 kara
1000 kara
U'ila 0 ngawua gara tou ba danö
U'ila 1 ngawua gara tou ba danö
U'ila 10 ngawua gara tou ba danö
U'ila oya gara tou ba danö

Like other languages in Indonesia, Nias don't have plural forms. Plural will be formed either with the numbers in front of it or/and a grouping word, like in the example above by adding word **ngawua** in front **gara** (which mutates from root word **kara** in a sentence).

**Pontoon manager**
Sirus Laia
https://pontoon.mozilla.org/contributors/5yx-gps936D2tE5rxFXovuKtuI0/

**Comment by ftyers** [comment]
Hi @sslaia, welcome to Common Voice! @phirework isn't the person to assign to this kind of request. The best person to assign is @Heyhillary. While you are waiting for Pontoon to get set up, you could also ask @MichaelKohler to set up Nias on the [sentence collector](https://common-voice.github.io/sentence-collector/) too.

**Comment by MichaelKohler** [comment]
Please ping me once added to Pontoon.

**Comment by sslaia** [comment]
> Hi @sslaia, welcome to Common Voice! @phirework isn't the person to assign to this kind of request. The best person to assign is @Heyhillary. While you are waiting for Pontoon to get set up, you could also ask @MichaelKohler to set up Nias on the [sentence collector](https://common-voice.github.io/sentence-collector/) too. We have a channel [#commonvoice:matrix.org](https://app.element.io/#/room/#common-voice:mozilla.org) on Matrix, you can join us there too. We'll be happy to help with any questions you have!

Thank you @ftyers and @MichaelKohler Sorry to have assigned the request to @phirework I didn't even realise it, as I had just followed the link from the [language template link](https://github.com/common-voice/common-voice/blob/main/docs/LANGUAGE.md). Does it mean I have to open a new request to @Heyhillary ? Sorry for my confusion.

**Comment by ftyers** [comment]
No need to open a new request, the team will reassign this when they get to it :)

**Comment by Heyhillary** [comment]
Hello @sslaia we have just enabled [Nias](https://pontoon.mozilla.org/nia/common-voice/) in Pontoon. 

Your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!
