### ISSUE TITLE
kurmancî

### ISSUE THREAD

**Issue by ferid180** [common-voice/common-voice#3162]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add? Kurdish

**Language code**
Please provide the ISO-639-1 code

**Language size**
Number of active speakers of this language in the world
30 million

**Plural forms**
How would you translate the following in this language?

0 kevir
1 kevir
2 kevir
3 kevir
4 kevir
5 kevir
10 kevir
20 kevir
100 kevir
1000 kevir
Ez li 0 keviran dibînim 
Ez li erdê 1 kevirî dibînim 
Ez li erdê 10 keviran dibînim 
Ez li erdê keviran dibînim 

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

**Comment by ftyers** [comment]
Dear @ferid180, Kurmanji Kurdish is [already enabled](https://commonvoice.mozilla.org/kmr) :)

**Comment by Heyhillary** [comment]
Accidently closed issue, opened to enable dev-side.
