### ISSUE TITLE
Scots is missing

### ISSUE THREAD

**Issue by scruss** [common-voice/common-voice#3166]
**Describe the bug**
Scots - as a separate dialect - is missing as a native language

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Profile
2. Click on 'Native'
3. Scroll down to 'Scots' - past Cymraeg, Gaeilge, and Kernowek, other British non-English languages
4. See that it's not there

**Expected behaviour**
Scots being included, like Cymraeg, Gaeilge, and Kernowek. This is different from English - Accent: Scottish.

**Desktop or Mobile (please complete the following information):**
 - OS: Linux
 - Browser : Firefox
 - Version : 89.0.2

**Comment by ftyers** [comment]
Hi @scruss thanks for getting in contact! Is the issue that you want to be able to select Scots (`sco`) as a native language in the profile page? If so, I think the only languages in that you can select are [the ones](https://commonvoice.mozilla.org/languages) for which Common Voice is enabled. If you want to enable Common Voice for your language you can check out [LANGUAGE.md](https://github.com/common-voice/common-voice/blob/main/docs/LANGUAGE.md). We are around on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) if you have any questions.

**Comment by scruss** [comment]
Yes, it is. But I don't have the means or spoons to set this up.
There is now an active Firefox Scots translation
I don't do Matrix

**Comment by ftyers** [comment]
Feel free to pass on the information to people you know interested in Scots, in order to enable Common Voice for a language, the minimum requirements are an interface translation (around 600 strings) and 5000 sentences in the public domain. I think this should be possible, and doesn't require any particular spoons, just ability to write Scots. In any case, glad to see there is an interest!

**Comment by ftyers** [comment]
I'm going to close this issue. It can be opened when there is interest from the Scots speaking community.
