### ISSUE TITLE
Taiwanese Localization Request

### ISSUE THREAD

**Issue by TongcyDai** [common-voice/common-voice#3194]
**Language name**
English name: Taiwanese
Local name: 臺語 / Tâi-gí / Tâi-gú
Other English name: Taiwanese Hokkien, Taiwanese Minnan
Other local name: 臺灣話 / Tâi-oân-ōe, 臺灣閩南語 / Tâi-oân Bân-lâm-gí

**Language code**
ISO-639-1 code : zh
ISO-639-3 code : nan
(nan is shared with other Hokkien varieties)

**Language size**
More than 16M speakers (2015).

**Plural forms**
How would you translate the following in this language?

0 rocks: 0 粒石頭 / 0 lia̍p chio̍h-thâu
1 rock: 1 粒石頭 / 1 lia̍p chio̍h-thâu
2 rocks: 2 粒石頭 / 2 lia̍p chio̍h-thâu
3 rocks: 3 粒石頭 / 3 lia̍p chio̍h-thâu
4 rocks: 4 粒石頭 / 4 lia̍p chio̍h-thâu
5 rocks: 5 粒石頭 / 5 lia̍p chio̍h-thâu
10 rocks: 10 粒石頭 / 10 lia̍p chio̍h-thâu
20 rocks: 20 粒石頭 / 20 lia̍p chio̍h-thâu
100 rocks: 100 粒石頭 / 100 lia̍p chio̍h-thâu
1000 rocks: 1000 粒石頭 / 1000 lia̍p chio̍h-thâu
I see 0 rocks on the ground: 我佇塗跤看著 0 粒石頭 / Góa tī thô͘-kha khòaⁿ-tio̍h 0 lia̍p chio̍h-thâu
I see 1 rock on the ground: 我佇塗跤看著 1 粒石頭 / Góa tī thô͘-kha khòaⁿ-tio̍h 1 lia̍p chio̍h-thâu
I see 10 rocks on the ground: 我佇塗跤看著 10 粒石頭 / Góa tī thô͘-kha khòaⁿ-tio̍h 10 lia̍p chio̍h-thâu
I see rocks on the ground: 我佇塗跤看著石頭 / Góa tī thô͘-kha khòaⁿ-tio̍h chio̍h-thâu

**Pontoon manager**
https://pontoon.mozilla.org/contributors/RtEVSXcsJMLzCoIBBzI90MeQhAc/
https://pontoon.mozilla.org/contributors/k9EiPdIZphM1WHt8BLecuKxIw_Q/

**Language Script**
Latin (Pe̍h-ōe-jī, Tâi-uân Lô-má-jī Phing-im Hong-àn), Han characters

**Comment by irvin** [comment]
The local community had begun the exploration on the following issues regard add Taiwanese to Common Voice,

- How to structure the text corpus with current multiple Romanian and writing systems, including POJ, Tâi-lô, and Chinese script
- Strategy on multiple Taiwanese accents (and the work way to include the info at text corpus) 
- The issue of single ISO-639-3 "nan" code sharing between both Taiwanese and Minnan (Hokkien)

Welcome to join the discussion on Telegram channel - 
![33c5dbe57775f4ac0a232307c03387867331701a](https://user-images.githubusercontent.com/165936/127191125-1a93c6ae-df48-48c1-a4cf-bd8ff6288433.jpeg)

**Comment by irvin** [comment]
This is the current plan we put together (again, welcome to join the discussion)
https://hackmd.io/@moztw/cv-taiwanese-plan

**Comment by ftyers** [comment]
I think the preferred option for the corpus will be very difficult from a technical and processing point of view. I'm also a bit concerned, what is the motivation for having the additional pronunciation guides? Is it that people are not able to determine the pronunciation from the context based on the MOE orthography? Is this related to [this issue](https://discourse.mozilla.org/t/furigana-for-japanese-example-sentences/83347)

I would say that where there is an officially recognised orthography it should be used *as is*, unless a large proportion of the potential users are not willing to write in that orthography.

**Comment by TongcyDai** [comment]
@ftyers The dictionary of MOE only contains 20k+ "frequency-used" entries — that's quite a small number, some words in my daily usage is even not in the dictionary, and they don't appear in the so-called orthography. And there will always be words that are not-so-frequency-used, only locally used or  ambiguous in pronunciations, and Han characters alone make it difficult for people to determine how to read the sentence. As a result, it is necessary to specify the pronunciations sometimes, but the others can be omitted actually. I've fixed the examples in HackMD, please take a look.

Also, it's a great idea if we can add pronunciations on Han characters, but I am not sure if it's technically possible.

**Comment by irvin** [comment]
> Is it that people are not able to determine the pronunciation from the context based on the MOE orthography? Is this related to [this issue](https://discourse.mozilla.org/t/furigana-for-japanese-example-sentences/83347)?

There are several reasons that we need to add additional pronunciation guides,

- Taiwanese doesn't have an officially standard orthography until very recently ([MOE standard was published in 2007](https://en.wikipedia.org/wiki/Taiwanese_Southern_Min_Recommended_Characters) and only include 700 characters, compared to [4800 "Common National Characters" published in 1982](https://en.wikipedia.org/wiki/Chart_of_Standard_Forms_of_Common_National_Characters) for Mandarin Chinese. As @TongcyDai said, the standard only includes a little amount of vocabulary. 

- Most of the Taiwanese speakers don't have education on reading/writing Taiwanese. The education system added Taiwanese and other mother languages (aboriginal languages for example) to second languages only in the last decade. I can estimate 99% of the native Taiwanese speaker don't have any relative knowledge of standard orthography (including myself). Many Han chars used in Taiwanese writing is not the common character in Mandarin Chinese, and we often don't know how to pronouncee them. Pronunciation guides can help a lot. In this case, it's pretty similar to furigana for Japanese for sure.

For usage of the database, if all the pronunciation guides are added following the same rule, such as wrap with () in our plan, they can easily strip out before used to training model or do any other things,

**Comment by irvin** [comment]
one of the opinions is that we should build a text corpus that includes not only pronunciation guides on some difficult chars, but the whole sentences. I personally don't agree that is good practice on Common Voice, but it's one of the major arguments amount Taiwanese research/education community.

**Comment by Heyhillary** [comment]
Hey everyone, thanks so much for discussing how we can localise Taiwanese. I have started to create the locale on Pontoon but need to double-check are the CLDR plural rules 5/other ?

**Comment by Heyhillary** [comment]
Hey @TongcyDai 

[Taiwanese (Minnan)](https://pontoon.mozilla.org/nan-tw/common-voice/) is now available on Pontoon.

To help get you started, here is some valuable information to help you as a manager for the language.The role of a manager means all your work will go to staging (and later to production) without peer review.

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you so much for your patience and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

**Comment by irvin** [comment]
Hi, what is the proper way to request the locale added to Sentences Collector? 

On "[Submit and review more sentences from other sources](https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530/1)" in [Readme: How to see my language on Common Voice](https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530/1) there is no info regards add a new locale to Sentences Collector.

And doesn't find the info on [Community Playbook](https://common-voice.github.io/community-playbook/sub_pages/text.html) neither.

**Comment by MichaelKohler** [comment]
@irvin Usually I take care of it. I would get to that in the next few days, but feel free to do a PR adding it here: https://github.com/common-voice/sentence-collector/blob/main/server/lib/languages.js#L141(would be great to link the issue as done 2 entries below that)

Eventually I will need to automate this..

**Comment by irvin** [comment]
@MichaelKohler done, thanks!
