### ISSUE TITLE
When it's not available the choosing of "Accent" this select tag should be hidden

### ISSUE THREAD

**Issue by Sav22999** [common-voice/common-voice#3206]
**Is your feature request related to a problem? Please describe.**
It's useless a select which is empty

**Describe the solution you'd like**
Hide that tag and set the "Language" tag with "width: 100%".

![immagine](https://user-images.githubusercontent.com/32335378/127483724-5b3b5453-94d3-4fb5-8c0d-7f4205e04054.png)
becomes
![immagine](https://user-images.githubusercontent.com/32335378/127484170-042394a7-100e-4d99-9fe5-9d0cf3181ad8.png)

**Comment by phirework** [comment]
Hey @Sav22999, this is a great idea, but we're actually working on revamping that entire page and expect to be rolling out changes to how we handle accents shortly (more info on [Discourse](https://discourse.mozilla.org/t/weekly-update-20th-august-accent-workflow-slides-from-roadmap-session/84821)), so we won't be making any short-term updates to this page. Look out for better accent handling soon!
