### ISSUE TITLE
Unintended Fluent message references

### ISSUE THREAD

**Issue by TheoChevalier** [common-voice/common-voice#3208]
Hi,

While translating the new criteria page, I noticed that in the following strings, { Sneeze }, { cough } & { crackle } are treated as Fluent [message references](https://projectfluent.org/fluent/guide/references.html), but of course the messages don’t exist. Most locales are leaving these words untranslated.

Would it be possible to escape the brackets (though tbh I’m not sure how it’s achievable in Fluent), and generate new string IDs please?

https://github.com/common-voice/common-voice/blob/124cd2eddfce3918bff94b6e677dca15b631591c/web/locales/en/messages.ftl#L937-L940

The console on https://dev.commonvoice.allizom.org/fr/criteria is throwing warnings
<img width="564" alt="Capture d’écran 2021-07-30 à 10 08 11" src="https://user-images.githubusercontent.com/1294206/127622405-fd7f8e78-4782-4ba4-a03f-ab3554c3764d.png">

Many thanks!

CC @phirework

**Comment by phirework** [comment]
Ah good catch! We could just swap them out for different braces, thoughts @mbransn?

**Comment by mbransn** [comment]
Ah yeah, makes sense. Perhaps just `[ ]` brackets all around? I did a run through of the content and confirmed brackets are also used in the example sentence string elsewhere.

**Comment by phirework** [comment]
Hey @TheoChevalier, I forgot to circle back but these should be fixed, can you confirm on your end?

**Comment by TheoChevalier** [comment]
Yes, can confirm! Thank you!
