### ISSUE TITLE
New Criteria for Listen/Speak

### ISSUE THREAD

**Issue by Sav22999** [common-voice/common-voice#3209]
**Describe the bug**
The examples of new Criteria are not clear, and probably there are some issues.

I mean this page: https://commonvoice.allizom.org/en/criteria

![immagine](https://user-images.githubusercontent.com/32335378/127742132-e1ad6964-51be-412c-a1ba-aaf3c2483c5b.png)

The last three examples are all wrong but they referred to another example, but there is the original sentence

It should be something like this:

![immagine](https://user-images.githubusercontent.com/32335378/127742181-bd695d96-83cb-4ace-a848-f2729287dafa.png)

**Comment by phirework** [comment]
@mbransn can you take a look at this?

**Comment by mbransn** [comment]
This is a great catch, we're missing the correct example of the coffee sentence preceding those incorrect examples. The update @Sav22999 suggests is almost correct, just needs to be moved up one more row. I've attached a screenshot here and it's also now updated in the NSC UI @phirework -- this was absolutely design oversight error on my part. Apologies and thanks Sav!
![Screen Shot 2021-08-10 at 4 04 04 PM](https://user-images.githubusercontent.com/18686986/128946011-430462a7-7aca-4cb4-8ede-b5e8a6913517.png)

**Comment by Sav22999** [comment]
@mbransn _the correct sentence_ (1) and _the first wrong one_ (2) are identical, so why it's "mismatched content"? 🙂 maybe you should change also the second sentence (the sentence (2))

**Comment by mbransn** [comment]
Well that's embarrassing, doing too many things at once as usual. Thanks for the quick catch! Here's the updated visual, also updated in the design doc @phirework.
![Screen Shot 2021-08-10 at 4 41 20 PM](https://user-images.githubusercontent.com/18686986/128948645-afcb9875-3604-430c-a0fa-db075e816fa0.png)

**Comment by phirework** [comment]
This has been deployed on prod, thanks again Sav!
