### ISSUE TITLE
Santali language to be included in the list of languages in sentence collector list

### ISSUE THREAD

**Issue by psubhashish** [common-voice/common-voice#3214]
**Describe the bug**
The [Santali language](https://en.wikipedia.org/wiki/Santali_language) (ISO 639-2: "sat") is not currently included in the list of languages in the sentence collector list.

**To Reproduce**
1. Go to 'https://commonvoice.mozilla.org/sentence-collector/#/profile'
2. Click on 'Add a language you want to contribute to'
3. Scroll down to 'select languages'
4. Santali is not found in the list. Please note that "Santali" and "Santhali" (with an "h") are two commonly used spellings native Santali speakers generally use if typing in Latin, else, "ᱥᱟᱱᱛᱟᱲᱤ" is used in the Ol chiki writing system)

**Expected behavior**
The list of languages should display Santali for anyone to choose from.

**Screenshots**
NA

**Desktop or Mobile (please complete the following information):**
This is not a browser or platform specific issue but used for this purpose FF 90.0.2.

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**

**Comment by Heyhillary** [comment]
Hey @psubhashish ,

Thanks for raising the issue. Would it be possible to include this on the [sentence collector](https://github.com/common-voice/sentence-collector/issues) repo, please ?

**Comment by MichaelKohler** [comment]
@Heyhillary looks like Santali is not in Pontoon yet. Let's treat this like a normal language request. I can easily add it later on if there are no objections.

**Comment by Heyhillary** [comment]
Hey,

@MichaelKohler, thanks, apologies I didn't notice this. 

@psubhashish - Currently Santil is available for other Mozilla products. The current version available for Santil is Santali (Ol Chiki script). Would you like to localise in this script ?

Many thanks,

Hillary

**Comment by psubhashish** [comment]
Hi @Heyhillary @MichaelKohler: than you both. I am reaching out to a few friends including @Prasanta-Hembram and @hpnrt, and requesting them to explore more how the localization can start.

**Comment by Prasanta-Hembram** [comment]
Hi everyone, Thanks @psubhashish dada for adding me in this discussion. I'm in pontoon for Santali language for nearly a year and it's a great experience to translate and see Santali language in Firefox products. I'm happy to get involved in this localization. Waiting for @hpnrt and @Cloud-Prakash reply. I think @Heyhillary, it would be good idea to add Santali language in Pontoon.

**Comment by Heyhillary** [comment]
Hey everyone, 

Thanks for contributing to the conversation.I have now enabled Santali onto Pontoon.  

As Santali, already exists on Pontoon there is already a dedicated manager. The role of a manager means all your work will go to staging (and later to production) without peer review. However, I can if agreed by you all to include more people as managers. 

I hope through your work, there would be others joining you to collaborate on the different phases of this project. 
Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[ Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

**Next Steps...**

Newly translated strings will automatically show up on our dev server every few days (https://dev.commonvoice.mozilla.org).  New languages will be visible on the Common Voice platform once 95% of the language is localised, and are released to production (main website) every two weeks.

Also just so you are aware in the most [recent weekly update ](https://discourse.mozilla.org/t/weekly-update-thread-2021/84411) we announced the following: 

To support all language communities to take part in this process we will be publishing the Common Voice Contribution Agreement form for pre-existing that are not under a public license. Read more about how to use the form on the [Common Voice Community Playbook](https://github.com/common-voice/community-playbook/blob/draft/sub_pages/cc0waiver_process.md). 

This will help to launch your language onto Common Voice for voice data collection. 

If you have any other questions please feel free to ask.

All the best, 

Hillary

**Comment by Prasanta-Hembram** [comment]
Thanks @Heyhillary . Yes right i will add more managers and promote other translators to Managers. Many more will join soon as translator and I'll tell them about it. I will also take a look at those documents and Common Voice Contribution Agreement form and weekly update. Again thanks @Heyhillary and others for helping us bring Santali language to Common Voice.

**Comment by Prasanta-Hembram** [comment]
Hi, @Heyhillary @MichaelKohler  can we now add sentences to Sentence Collector for Santali language now.

**Comment by MichaelKohler** [comment]
@Prasanta-Hembram yes, you should be able to add Santali to your profile in the Sentence Collector.

**Comment by Prasanta-Hembram** [comment]
ok @MichaelKohler.

**Comment by Heyhillary** [comment]
Thanks, everyone. I'm closing this issue. if you have any questions please feel free to reach out to me on [matrix ](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)or [discourse](https://discourse.mozilla.org/c/voice/239). my user name is heyhillary
