### ISSUE TITLE
Incorrect plural form specified for Cantonese

### ISSUE THREAD

**Issue by graphemecluster** [common-voice/common-voice#3236]
According to the [specification](http://cldr.unicode.org/index/cldr-spec/plural-rules), if a language only has a single plural form, the value `other` should be used instead of `one`.

![Cantonese Plural Form](https://user-images.githubusercontent.com/53967830/129475112-9d0241cb-9c51-4691-89e7-62a1f3c3be61.jpg)

That's all.

**Comment by Heyhillary** [comment]
Hey @graphemecluster 

Thank you for raising this issue. 

I have now changed the settings with the right information regarding the plural forms.
