### ISSUE TITLE
Validated hours number not expected validate hours

### ISSUE THREAD

**Issue by dag7dev** [common-voice/common-voice#3238]
**Describe the bug**
Validated hours != declared hours in past

**Expected behavior**
Since we have reached 300 validated hours before 20th July 2021, the website should print 300 (or more).

**Source** (we've reached 300 validated hours):
Marcos Box (in italian) https://www.marcosbox.org/2021/07/raggiunto-lobiettivo-di-300-ore.html
Mozilla Italia account: https://twitter.com/mozillaitalia/status/1417055231586746369 

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/44711271/129944497-9605cd35-92a2-48a4-acde-338e4143fde1.png)

After:
![image](https://user-images.githubusercontent.com/44711271/129941632-ce895ce3-0747-47fd-8371-f4c441cabe90.png)

<details>
  <summary>Hours before:</summary>

![image](https://user-images.githubusercontent.com/44711271/129946916-db21900e-4bc6-494a-83f8-8db82939b9c4.png)

![image](https://user-images.githubusercontent.com/44711271/129946933-b15aa802-5338-43bd-a2f2-f49746e900b8.png)
  
</details>

(it is not a "diet cure", I promise)

**Desktop or Mobile (please complete the following information):**
Everywhere.

**Comment by phirework** [comment]
Hi @dag7dev, the lower number is the more accurate one. Our platform does not actually have an exact duration for every clip recorded, as that would be too resource-intensive. Instead, it calculates an estimate based on the average duration of clips for each language in the most recent dataset release, and this naturally fluctuates slightly with every release. In the last dataset release the [average value](https://github.com/common-voice/common-voice/commit/1031993f85c4ba25129bfa02df4dbc8082f3900c) for Italian went from 5.558s to 5.34s, which was a pretty normal variation but which has unfortunately impacted this milestone. Sorry about that!
