### ISSUE TITLE
Localization request for Tahitian (ty - French Polynesia)

### ISSUE THREAD

**Issue by teriiehina** [common-voice/common-voice#3250]
**Language name**
Tahitian

**Language code**
ty

**Language size**
68 000

**Plural forms**
How would you translate the following in this language?

0 rock : aore 'ōfa'i
1 rock : hō'ē 'ōfa'i
2 rocks : piti 'ōfa'i
3 rocks : toru 'ōfa'i
4 rocks : maha 'ōfa'i
5 rocks : pae 'ōfa'i
10 rocks : 'ahuru 'ōfa'i
20 rocks : piti ahuru 'ōfa'i
100 rocks : hanere 'ōfa'i
1000 rocks : tauatini 'ōfa'i
I see 0 rocks on the ground : aore au i īte i te 'ōfa'i i raro
I see 1 rock on the ground : tē ite nei au i te 'ōfa'i i raro 
I see 10 rocks on the ground : tē ite nei au 'ahuru 'ōfa'i i raro 
I see rocks on the ground : tē ite nei au i te tahi mau 'ōfa'i i raro 

**Pontoon manager**
https://pontoon.mozilla.org/contributors/ys8NdoPbhIgI5jAwynzskq6kHiM/

**Language Script**
latin

**Comment by ftyers** [comment]
Hi @teriiehina ! Welcome to Common Voice and thanks for your interest :) Tahitian isn't yet in Pontoon, so will need to be enabled, @Heyhillary can help with that. In the meantime you can start collecting sentences through [sentence collector](https://commonvoice.mozilla.org/sentence-collector/) and join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) if you would like help in real time. 

In addition, I have a question about encodings, should the ʻeta be encoded as:
* `U+02BC` ʼ MODIFIER LETTER APOSTROPHE,
* `U+02BB` ʻ MODIFIER LETTER TURNED COMMA, or
* `U+0027` ' APOSTROPHE 

?

**Comment by teriiehina** [comment]
Hello @ftyers , thank you for the welcome and the fast reply. 

The 'eta should be encoded as an apostrophe, aka `U+0027`.

**Comment by Heyhillary** [comment]
Hey @teriiehina ,

Thanks so much for making the request. I would like to encourage you to consult with some of your language community members as we begin the process of adding Tahitian onto Common Voice.

I am currently making Tahitian available via Pontoon and would like to ask if you aware of the plural rules and CLDR rules for your language ?

**Comment by ftyers** [comment]
Judging by the example sentences, the plural form should be just `other`. Although I think that articles inflect for number in Tahitian. What would `I see the rock` and `I see the rocks` be? @teriiehina

**Comment by Heyhillary** [comment]
Hey @teriiehina ,

Is it possible if you could provide an update please to the above question ?

**Comment by teriiehina** [comment]
Hello @Heyhillary,

sorry, I was afk. I’m not familiar with the «plural rules» nor the «CLDR rules». I did read what I could on https://cldr.unicode.org/ but unfortunately https://cldr.unicode.org/index/cldr-spec/minimaldata is not a valid URL anymore.

From my understanding, @ftyers is right, the plural form for tahitian is `other` as the noun form does not change when it’s plural, e.g.:

`I see the rock` : `tē ite nei au i te 'ōfa'i`
`I see the rocks` : `tē ite nei au i te tahi mau 'ōfa'i`

**Comment by Heyhillary** [comment]
Hey @teriiehina 

Thank you !

[Tahitian](https://pontoon.mozilla.org/ty/common-voice/) is now available on Pontoon. If we need to change the CLDR rules please let me know. 

To help get you started, here is some valuable information to help you as a manager for the language. The role of a manager means all your work will go to staging (and later to production) without peer review.

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Can I also suggest that you and community members you contribute with create a style guide to help communicate when validating translations ?

Thank you so much for your patience and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

Hey @MichaelKohler - is it possible to add Tahitian to the sentence collector, please ?

**Comment by teriiehina** [comment]
thank you @Heyhillary

**Comment by Heyhillary** [comment]
Hey @teriiehina,

How are you finding the project so far ? Do you have any questions or need any advice ?

**Comment by teriiehina** [comment]
Hi @Heyhillary,

there have been a delay in my availability regarding this project as we are working on an iOS and Android keyboards offering tahitian auto-suggestions 🎉 

But I’m still interested and I found somebody to help me. I’ll keep you updated.
