### ISSUE TITLE
Kikuyu

### ISSUE THREAD

**Issue by gichukijim** [common-voice/common-voice#3251]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add? Kikuyu

**Language code**
Please provide the ISO-639-1 code: KI

**Language size**
Number of active speakers of this language in the world
6.6 million (2009 census)[1]

**Plural forms**
How would you translate the following in this language?

0 rocks - Hatire Mahiga
1 rock - Ihiga
2 rocks - Mahiga Meri
3 rocks - Mahiga matatu
4 rocks - Mahiga manna
5 rocks - Mahiga matano
10 rocks - Mahiga Ikumi
20 rocks - Mahiga mirongo iri
100 rocks - Mahiga igana
1000 rocks - mahiga giri emwe
I see 0 rocks on the ground - Ndirona mahiga haha thi
I see 1 rock on the ground - Ni ndirona ihiga rimwe
I see 10 rocks on the ground -  Ni ndirona mahiga ikumi haha thi
I see rocks on the ground - Ni ndirona mahinga haha thi

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://pontoon.mozilla.org/contributors/iDbCrET7S4Qgm6IfClK5obxwlaI/
**Language Script**
What is the name of the language scripts used to write your language?  Kikuyu

**Comment by ftyers** [comment]
Dear @gichukijim, welcome to Common Voice and thanks! The team wil start the process of enabling the language on Pontoon. In the meantime you can add sentences to the [sentence collector](https://commonvoice.mozilla.org/sentence-collector/) and join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) if you need any further help.

One clarification question: Is the script used to write Kikuyu Latin-based ? And what is the name of the language in the language? *Gĩgĩkũyũ*?

**Comment by Heyhillary** [comment]
Hey @ftyers ,

Thanks for reaching out yo @gichukijim, is it possible if you could help me with the plural forms and CLDR plurals ?

And I should be able to add onto Pontoon.

Many thanks,

Hillary

**Comment by ftyers** [comment]
@Heyhillary to my knowledge, plural should be `one, other`, the same as Swahili. I'm guessing the CLDR rules should be the same.

**Comment by Heyhillary** [comment]
Hey @ftyers,

Thank you !

@gichukijim - [Kikuyu](https://pontoon.mozilla.org/ki/common-voice/) is now available on Pontoon. If we need to change the CLDR rules please let me know. 

To help get you started, here is some valuable information to help you as a manager for the language. The role of a manager means all your work will go to staging (and later to production) without peer review.

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you so much for your patience and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

Hey @MichaelKohler - is it possible to add Kikuyu to the sentence collector, please ?

**Comment by MichaelKohler** [comment]
> Hey @MichaelKohler - is it possible to add Kikuyu to the sentence collector, please ?

It's available, I think we can close this issue here. If I understood correctly that's the last step :)

**Comment by Heyhillary** [comment]
Awesome, thank you ! @MichaelKohler
