### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by tled128** [common-voice/common-voice#3256]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Yiddish

**Language code**
Please provide the ISO-639-1 code
yi

**Language size**
Number of active speakers of this language in the world
1.5 million

**Plural forms**
How would you translate the following in this language?

0 rocks נול שטיין
1 rock אײנ שטיין
2 rocks צװײ שטיינער
3 rocks דרײַ שטיינער
4 rocks פֿיר שטיינער
5 rocks פֿינף שטיינער
10 rocks צען שטיינער
20 rocks צוואַנציק שטיינער
100 rocks הונדערט שטיינער
1000 rocks טויזנט שטיינער
I see 0 rocks on the ground 
איך זע נול שטײן אויף דער ערד
I see 1 rock on the ground
איך זע אײנ שטײן אויף דער ערד
I see 10 rocks on the ground
איך זע צען שטיינער אויף דער ערד
I see rocks on the ground
איך זע שטיינער אויף דער ערד

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
ledfordtom@gmail.com

**Language Script**
What is the name of the language scripts used to write your language ? e.g latin, Devanagari
Hebrew

**Comment by MichaelKohler** [comment]
FYI: Yiddish is already enabled in the Sentence Collector.

**Comment by Heyhillary** [comment]
Hey @tled128 

Apologies for the delay,

[Yiddish ](https://pontoon.mozilla.org/yi/common-voice/)is now available on Pontoon for localisation onto Common Voice. 
Can I double-check with you that the plural forms for Yiddish are (n=2) ?

Your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

**Comment by Heyhillary** [comment]
Closing the issue, found the correct plural form.

**Comment by ShloimeRosenblum** [comment]
Please change the writing direction to Right-to-left
