### ISSUE TITLE
[Request] Change the order in Contribute link

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3265]
**Is your feature request related to a problem? Please describe.**

We have two major problems:
* People are recording too much
* They do not spend time on listening and the queue piles up

This is supported by the interface by showing the record tab first.
On the other hand the dataset gets biased, sometimes poisoned.

**Describe the solution you'd like**
A simple change in the UI which shows listen tab first will help a lot.

**Describe alternatives you've considered**
Preventing/throttling people who record too much might be another solution but needs major changes.

**Additional context**
Please see the Community Health discussion:
https://discourse.mozilla.org/t/community-strategy-what-does-community-health-mean-to-you/84146

**Comment by jiya-singhal** [comment]
hey @HarikalarKutusu can you please assign this issue to me

**Comment by HarikalarKutusu** [comment]
Hey @jiya-singhal, first of all, I'm not a team member, so I do not assign anything :) Usually people just PR simple stuff like CSS errors and if the team finds it appropriate, they will merge them. For major changes, it would be advisable to contact/ask the team so that the efforts don't go down the drain.

Regarding this issue: It is from 3 years ago and it was not a simple thing, meaning it should have been a huge decision (to br,ng one part of workflow in front of another). But, in the meantime the UI changed a lot with the inclusion of sentence collection among the voice related ones. So, I'm closing this as it is not a valid request anymore (I mean the UI part, the other problems still exist).

Thank you for reminding me...
bozden
