### ISSUE TITLE
Upload of this clip keeps failing, keep retrying

### ISSUE THREAD

**Issue by jmukiibi** [common-voice/common-voice#3272]
We are getting complaints from the Luganda Common Voice community since yesterday: This happens when a contributor tries to upload voice clips after reading the 5 sentences and clicks submit. 

**Issue**: Failure to upload clips and also even when the uploads are done, the number of uploads doesn't change

Details in screenshot 

![IMG-20210923-WA0001](https://user-images.githubusercontent.com/5118790/134459911-9cb89d4a-4851-4aaf-ad21-e73666d82f61.jpg)
.

**Comment by phirework** [comment]
Thanks for reporting this, this was a bug that went out with yesterday's release and has been reverted.
