### ISSUE TITLE
Can't play sound clips

### ISSUE THREAD

**Issue by SMR76** [common-voice/common-voice#3273]
Hi.
I tried to validate some sound clips, After some validation sounds didn't play when I clicked the play button.
I tried to skip sound clips, but It didn't solve the issue, and I had to refresh the page.

When I open the console and got these errors:
```
GET https://voice-prod-clips-393eefd0cba28c270ced0f9587a4f6ae601ca91e.s3.dualst ... e4fe4726a54854df2d4bf6d1f91f95cc6d849dd5eff5b&X-Amz-SignedHeaders=host 400 (Bad Request)

Access to fetch at 'https://sentry.prod.mozaws.net/api/491/store/?sentry_key=4a940c31e4e14d8fa6984e919a56b9fa&sentry_version=7' 
from origin 'https://commonvoice.mozilla.org' has been blocked by ![bug](https://user-images.githubusercontent.com/51415059/134497625-818f6e2c-4814-43bc-9550-cbb14702f0e6.png)
![bug](https://user-images.githubusercontent.com/51415059/134497802-fd29de7a-5f02-4a73-8aa1-f465b73bb07d.png)
policy:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with ![bug](https://user-images.githubusercontent.com/51415059/134497625-818f6e2c-4814-43bc-9550-cbb14702f0e6.png)disabled.

POST https://sentry.prod.mozaws.net/api/491/store/?sentry_key=4a940c31e4e14d8fa6984e919a56b9fa&sentry_version=7 net::ERR_FAILED
```
**Screenshots**

![bug](https://user-images.githubusercontent.com/51415059/134497942-07077eab-b021-4837-b8b2-e58104d62368.png)

---
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 93.0.4577.82

**Comment by phirework** [comment]
Hi, thanks for making this report! We had a few other issues with the platform this morning and we've since reverted, and I just want to make sure that this wasn't another symptom. Can you check if this is still happening?

**Comment by SMR76** [comment]
Hi, I check it, and it happens again.
It happening randomly, almost after 10 or 15 sound clips validation.

**Comment by Heyhillary** [comment]
Hey @SMR76 ,

I'm messaging to ask if you are still experincing this issue - if not please let me know so I can close the issue request.
