### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by chrisemezue** [common-voice/common-voice#3274]
**Language name**
Igbo

**Language code**
ig

**Language size**
42 million speakers (source [Wikipedia](https://en.wikipedia.org/wiki/Igbo_language))

**Plural forms**
How would you translate the following in this language?

0 rocks Nkiti okwute / Onweghi okwute di 
1 rock Ofu okwute
2 rocks okwute abụọ
3 rocks okwute atọ
4 rocks okwute anọ
5 rocks okwute ise
10 rocks okwute iri
20 rocks okwute iri abụọ
100 rocks narị okwute
1000 rocks puku okwute
I see 0 rocks on the ground Onweghi okwute di n'ala
I see 1 rock on the ground Ana m ahụ okwute otu n'ala
I see 10 rocks on the ground Ana m ahụ okwute iri n'ala
I see rocks on the ground Ana m ahụ okwute n'ala

**Pontoon manager**
chris.emezue@gmail.com
adaeze.adigwe@helsinki.fi

**Language Script**
Latin  (source - [Wikipedia](https://en.wikipedia.org/wiki/Igbo_language) )

**Comment by Heyhillary** [comment]
Hey @chrisemezue 

[Igbo ](https://pontoon.mozilla.org/ig/common-voice/ )is now available on Pontoon for localisation onto Common Voice. 

Your role is the manager for the language. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions join us on the [community chat](https://chat.mozilla.org/#/room/#common-voice:mozilla.org). 

@MichaelKohler - could you include igbo onto the sentence collector please ?

**Comment by MichaelKohler** [comment]
> @MichaelKohler - could you include igbo onto the sentence collector please ?

Igbo is already enabled.

**Comment by chrisemezue** [comment]
Quick question about the sentence collector @MichaelKohler 
Since Igbo has already been enabled do I need to do anything more or just wait for the Sentence Collector to automatically extract the sentences and then [review them](https://commonvoice.mozilla.org/sentence-collector/#/review)?

**Comment by ftyers** [comment]
Dear @chrisemezue you will need to add sentences for Igbo on the sentence collector before you can review them. If you'd like more info on how to do this, please feel free to get in contact on [Discourse](https://discourse.mozilla.org/c/voice/239) or [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
