### ISSUE TITLE
[Bug] Privacy and Terms pages not working...

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3281]
Please check:
https://commonvoice.mozilla.org/tr/privacy
https://commonvoice.mozilla.org/tr/terms

They show only the spinner, started yesterday. Valid for any language...

I think that information is somewhat critical for the upcoming campaign...

**Comment by marifeitosa** [comment]
Na pagina: Configurando um ambiente de desenvolvimento local disponível em:  https://github.com/common-voice/common-voice/blob/main/docs/DEVELOPMENT.md  dispõe de um links porém esses não estão acessíveis como:  http: // localhost: 9000

**Comment by phirework** [comment]
I've released a hotfix for this and we're back online, thanks so much for reporting + @Heyhillary for flagging with me!
