### ISSUE TITLE
Tigrinya language voice

### ISSUE THREAD

**Issue by tadeze** [common-voice/common-voice#3300]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add? 
Tigrinya
**Language code**
Please provide the ISO-639-1 code: 
ti
**Language size**
Number of active speakers of this language in the world
 ~11 million
**Plural forms**
How would you translate the following in this language?
0 rocks  ዜሮ ኣእማን
1 rock ሓደ እምኒ
2 rocks ክልተ ኣእማን
3 rocks ሰለስተ ኣእማን
4 rocks ኣርባዕተ ኣእማን
5 rocks ሓሙሽተ ኣእማን
10 rocks ዓሰርተ ኣእማን
20 rocks ዒስራ ኣእማን
100 rocks ሚእቲ ኣእማን
1000 rocks ሺሕ ኣእማን
I see 0 rocks on the ground ዜሮ  ኣእማን ኣብ ባይታ ይሪኢ ኣለኹ
I see 1 rock on the ground ሓደ ኣእማን ኣብ ባይታ ይሪኢ ኣለኹ
I see 10 rocks on the ground 10 ኣእማን ኣብ ባይታ ይሪኢ ኣለኹ
I see rocks on the ground ኣእማን ኣብ ባይታ ይሪኢ ኣለኹ

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://github.com/tadeze
**Language Script**
What is the name of the language scripts used to write your language? 
Geez script

**Comment by MichaelKohler** [comment]
@Heyhillary This is already enabled in the Sentence Collector, so there is nothing to do here from my side.

**Comment by fsbat0** [comment]
t appears to have been forgotten. Can someone please review it? No one has looked at it for over a year!

**Comment by ftyers** [comment]
Dear @fsbat0, thanks for your interest in Common Voice. As you mentioned, Common Voice is enabled for [Tigrinya](https://pontoon.mozilla.org/ti/common-voice/). So the next steps are finish the translation and add public domain sentences. If you'd like help, please feel free to get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by fsbat0** [comment]
Could you please approve my localization as I was the sole active contributor on the Tigrinya Common Voice platform?
