### ISSUE TITLE
[bug] changing email address for subcriptions not possible in CV settings (smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3318]
**Describe the bug**
I successfully changed my login identy for CV. The original email account was compromised and i deactivated it completely. Changing the email address for email subscriptions is not possible, the old (deactivated) email is displayed and cannot be changed.

**To Reproduce**
1. Go to 'CV settings when logged into the account
2. Tap on Manage subscriptions
3. Deactivate all subscriptions and save
4. Try to change the email address for email subscriptions
5. No way to edit and change the old email subscription to a new one

**Expected behavior**
Changing to new email address for email subscriptions is possible, after unsubscribing all pointing to the old email.

**Screenshots**
![Screenshot_20211022-175310](https://user-images.githubusercontent.com/92784377/138486733-31ac1521-3ded-4152-ae15-68175cdfe5c7.png)

**Mobile (please complete the following information):**
 - OS: Android 10
 - Browser Fx mobile stable
 - Version 93.2.0 (Build #2015839747)
AC: 93.0.12, e39f5dba3f
GV: 93.0-20210927210923
AS: 82.1.0

 **Hardware :**
 -  Fairphone 3 plus

**Additional context**
Picture is showing the not changable (old deactivated) email address for email subscriptions

**Comment by phirework** [comment]
So that's a Mozilla-wide email management system that the Common Voice team has no control over. What I CAN do is scrub the link between your new email and the settings for the old email, so that you need to resubscribe with the new email. Would that work?

**Comment by robovoice1** [comment]
Scub it !!! (and thanks 4 the help) 😃
