### ISSUE TITLE
[req] third section for contributor on CV  main page

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3321]
**Is your feature request related to a problem? Please describe.**

2 processes can be chosen from the contributer and are straight forwarded. The other ways of participating (contributing new sentences/text for CV project for existing and newly started languages, translating ui for newly started languages are missing.

A third new section (e.g. new text or new sentences) on CV main page could be the beginning to show the contributor of a new forwarded adding new sentences/text process.
Basically the 3 click or tap rule: In 3 clicks or taps you are there what you want to do.

**Describe the solution you'd like**

Contributor chooses the new third section on CV main page. A new page pops up with following possibilities:
Add new sentences - link to common voice sentence collector add section
Review sentences - link to common voice sentence collector review section
Add larger text files - link to add larger text files and explanation what criteria is needed to do so.
Translating UI - direct link to languages in progress -  to translate CV page. see picture
Sentence extractor -? not sure about this one!

**Additional context**

With this new section a constant flow of new sentences/text is forwarded. The CV project shows all ways of particition from the start.

![Screenshot_20211023-220148](https://user-images.githubusercontent.com/92784377/138570085-a0fdfade-c357-4d78-8f05-6537dcbb43f7.png)

**Comment by Heyhillary** [comment]
Hey @robovoice1 ,

Thanks for your feedback.

Our team has been working on updating and re-desiging the about page, to include some of the requested For example including sentence collection and localization.

If you are intrested in viewing these changes please [click here](https://docs.google.com/presentation/d/1Fe0poRtqrZz83vxbTcLdv7keOBzLt9bUM3NeJ_HPyC8/edit?usp=sharing). Please note the survey is currently closed. but there will be future opprurtunites

**Comment by Heyhillary** [comment]
Hey @robovoice1 ,

Thanks again for submitting the issue - I wanted to follow up now that the about page is live. Does the new content respond to your original request ?

**Comment by robovoice1** [comment]
With the detailed info in the new about page i am closing this one.
