### ISSUE TITLE
[req] More detailed value displayed for all recorded and validated clips 

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3333]
**Is your feature request related to a problem? Please describe.**
Since the last two months i can see no visible progress in the current way of displaying the value for recorded/validated clips (all and languages) see also pic1 and 2.

**Describe the solution you'd like**
A more detailed value is shown to the contributer

**Describe alternatives you've considered**
none

**Additional context**
![Screenshot_20211103-170041](https://user-images.githubusercontent.com/92784377/140100159-f0031785-bdee-4c2e-b9ef-2c11ae1f02fe.png)
![Screenshot_20211103-170022](https://user-images.githubusercontent.com/92784377/140100222-2c72b12d-dac1-476d-bdfd-ca84b47707dd.png)

**Comment by robovoice1** [comment]
@phirework 

When is this reaching CV Website from testserver?
![Screenshot_20220110-204709_1](https://user-images.githubusercontent.com/92784377/148829605-7fc4fe17-283d-4585-a46c-6ee2738ba9d7.png)

**Comment by MichaelKohler** [comment]
This was implemented in the tooltip. So not gonna be showing on mobile:

![image](https://user-images.githubusercontent.com/330324/148830673-2688176e-51bf-4d05-be6e-a3f82a0da2d8.png)

**Comment by robovoice1** [comment]
just wondering, thank you for the info
