### ISSUE TITLE
Meetei

### ISSUE THREAD

**Issue by AwangbaMangang** [common-voice/common-voice#3336]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
Meetei

**Language code**
ISO-639-3 mni

**Language size**
2 million

**Plural forms**
How would you translate the following in this language?

0 rocks ꯅꯨꯡꯖꯥꯎ ꯰
1 rock ꯅꯨꯡꯖꯥꯎ ꯱
2 rocks rock ꯅꯨꯡꯖꯥꯎ ꯲
3 rocks ꯅꯨꯡꯖꯥꯎ ꯳
4 rocks ꯅꯨꯡꯖꯥꯎ ꯴
5 rocks ꯅꯨꯡꯖꯥꯎ ꯵
10 rocks ꯅꯨꯡꯖꯥꯎ ꯱꯰
20 rocks ꯅꯨꯡꯖꯥꯎ ꯲꯰
100 rocks ꯅꯨꯡꯖꯥꯎ ꯱꯰꯰
1000 rocks rock ꯅꯨꯡꯖꯥꯎ ꯱꯰꯰꯰
I see 0 rocks on the ground ꯑꯩꯅ ꯂꯩꯕꯥꯛꯇ ꯅꯨꯡꯖꯥꯎ ꯰ ꯎꯏ
I see 1 rock on the ground ꯑꯩꯅ ꯂꯩꯕꯥꯛꯇ ꯅꯨꯡꯖꯥꯎ ꯱ ꯎꯏ 
I see 10 rocks on the ground ꯑꯩꯅ ꯂꯩꯕꯥꯛꯇ ꯅꯨꯡꯖꯥꯎ ꯱꯰ ꯎꯏ
I see rocks on the ground ꯑꯩꯅ ꯂꯩꯕꯥꯛꯇ ꯅꯨꯡꯖꯥꯎꯁꯤꯡ ꯎꯏ

**Pontoon manager**
https://pontoon.mozilla.org/contributors/0ICwT_GwL26DB_K_sb-OIbPOvas/

**Language Script**
Meetei Mayek

**Comment by AwangbaMangang** [comment]
proposal of Language viz  Meetei 
(Reference: https//:mni.wikipedia.org

**Comment by Heyhillary** [comment]
Hey @AwangbaMangang 

Thanks for your request.

To help me fulfil your request, is it possible if you could fill out all of the questions in the language request form please ?

**Comment by AwangbaMangang** [comment]
> Hey @AwangbaMangang
> 
> Thanks for your request.
> 
> To help me fulfil your request, is it possible if you could fill out all of the questions in the language request form please ?

is it ok.

**Comment by Heyhillary** [comment]
Thanks 

> > Hey @AwangbaMangang
> > Thanks for your request.
> > To help me fulfil your request, is it possible if you could fill out all of the questions in the language request form please ?
> 
> is it ok.

Thanks for adding your details. The only one missing is the pontoon account. Could you please create on here: https://pontoon.mozilla.org/

**Comment by AwangbaMangang** [comment]
@Heyhillary I have completed

**Comment by Heyhillary** [comment]
Thank you @AwangbaMangang 

I noticed there are varying ways to say your language e.g Meitei and Manipur. 

I wanted to double-check the spelling and your preference before I start to enable your language ?

Also I noticed in your response to the plural forms question you gave the following response:

5 rocks rock 5
10 rocks rock 10 

Is this correct, as it seems to be translated in English rather than Meetei?

**Comment by AwangbaMangang** [comment]
I can translate in Meetei language
5 rocks ꯅꯨꯡꯖꯥꯎ ꯵
10 rocks ꯅꯨꯡꯖꯥꯎ ꯱꯰
we can make plural by adding or suffixions ꯁꯤꯡ (Sing) to the term. 
But in numbers we don't add ꯁꯤꯡ(Sing). 
Also in some terms such as Months, Days, Years, we don't add ꯁꯤꯡ(sing) only numerals make plural or singular.  Manipur is the name of state. 
Meetei/Meitei is major community name settlesettled in Manipur. 
MeeteiLon (ꯃꯤꯇꯩꯂꯣꯟ) /MeiteiLon is the language spoken by Meetei community. 
I prefer Meetei Lon.

**Comment by AwangbaMangang** [comment]
@Heyhillary is there any steps missing.

**Comment by Heyhillary** [comment]
Hey @AwangbaMangang ,

Thanks for the information.

Your language, Meetei Lon, is currently syncing with the Common Voice platform  https://pontoon.mozilla.org/mni/.

Could share with me your Pontoon profile name or URL link so I can give you manager permission, please ?

Also , I noticed when adding the plural rules for your language that you also use - "khoi (for personal pronouns and human proper nouns)".  @AwangbaMangang and @ftyers   - is it possible if you could help me verify if the plural rules are n = 2,3

Many thanks,

Hillary

**Comment by AwangbaMangang** [comment]
My Pontoon account :Yaibeelen Mangang
https://pontoon.mozilla.org/contributors/0ICwT_GwL26DB_K_sb-OIbPOvas/

**Comment by Heyhillary** [comment]
Thank you !

Welcome to the Common Voice Community 😊 !

Meetei Team on Pontoon has [now synced with Common Voice](https://pontoon.mozilla.org/mni/common-voice/) and is available for localisation. 

I have also now made [Meetei](https://pontoon.mozilla.org/mni/) available on Pontoon, once you have Pontoon account you will be able to become a manager. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. 

Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions join us on the [community chat](https://chat.mozilla.org/#/room/#common-voice:mozilla.org), also if you would like any community support I'm happy to share ideas and support you.

All the best,

Hillary, Common Voice Community Manager.

**Comment by MichaelKohler** [comment]
Meetei Lon is now also available on the [Sentence Collector](https://commonvoice.mozilla.org/sentence-collector/). I think that's the last step, so I'm closing this issue. Feel free if there is something else that needs to be done.
