### ISSUE TITLE
LOCALIZATION REQUEST: Tigre Language

### ISSUE THREAD

**Issue by bbeshir** [common-voice/common-voice#3338]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add? 
Tigre: ትግረ ( https://en.wikipedia.org/wiki/Tigre_language )

**Language code**
Please provide the ISO-639-1 code
ISO 639-2 Code is "tig"

**Language size**
Number of active speakers of this language in the world
4 million 

**Plural forms**
How would you translate the following in this language?

0 rocks: sefer ubenet
1 rock: hate ubenet
2 rocks: kele ubenet
3 rocks: seles ubenet
4 rocks: arba ubenet
5 rocks: hamus ubenet
10 rocks: asur ubenet
20 rocks: eshreen ubenet
100 rocks: miet ubenet
1000 rocks: alef ubenet
I see 0 rocks on the ground: Ubenet yerekoni
I see 1 rock on the ground: hat ubenet reko
I see 10 rocks on the ground: ase ubenet reyko
I see rocks on the ground: Uben hela dib ared

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
bbeshir@yahoo.com

**Language Script**
What is the name of the language scripts used to write your language ? e.g latin, Devanagari
Ge'ez ( https://en.wikipedia.org/wiki/Ge%CA%BDez )

**Comment by MichaelKohler** [comment]
Sentence Collector issue: https://github.com/common-voice/sentence-collector/issues/530

**Comment by Heyhillary** [comment]
Hello @bbeshir 

Thanks for your message Tigre, has been created under the name Tigrinya.

If you would like to contribute please use the following steps.

1. Create a pontoon account 
2. Help translate strings, via the resource links on this page  https://pontoon.mozilla.org/ti/common-voice/ 
3. Help with sentence collection by contributing via the sentence collector or bulk submitting content -> https://common-voice.github.io/community-playbook/sub_pages/text.html 

You can meet other contributors for Tigrinya via this link https://pontoon.mozilla.org/ti/common-voice/contributors/

**Comment by Heyhillary** [comment]
Hey @bbeshir,

Apologies I closed the issue and shared the wrong details. I will help set this up Tigre and will provide the details to you.

Thanks

Hillary

**Comment by bbeshir** [comment]
great thanks Hilary, as you know these are two separate lanaguages.
do you know what the ETA is for having it ready, my team is asking


    On Monday, November 8, 2021, 01:44:08 PM EST, Hillary ***@***.***> wrote:  
 
 


Hey @bbeshir,

Apologies I closed the issue and shared the wrong details. I will help set this up Tigre and will provide the details to you.

Thanks

Hillary

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Heyhillary** [comment]
Hey @bbeshir 

I incorrectly crossed the check, and sorry for any offence caused. 

I have created the [Tigre Team on pontoo](https://pontoon.mozilla.org/Tig/) and it's currently syncing with the Common Voice platform. This should take a few minutes. 

Is it possible to confirm with you that the plural rules, are 1,5 (One and other) ?

Kind regards,

Hillary

**Comment by bbeshir** [comment]
Hillary,
no worries and thank you for the quick turnaround time.
I apologize I didnt' quite understand your question "Is it possible to confirm with you that the plural rules, are 1,5 (One and other) ?"If you don't mind elaborating.


-Beshir



    On Monday, November 8, 2021, 01:58:28 PM EST, Hillary ***@***.***> wrote:  
 
 


Hey @bbeshir

I incorrectly crossed the check, and sorry for any offence caused.

I have created the Tigre Team on pontoon and it's currently syncing with the Common Voice platform. This should take a few minutes.

Is it possible to confirm with you that the plural rules, are 1,5 (One and other) ?

Kind regards,

Hillary

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Heyhillary** [comment]
Hello @bbeshir 

Tigre Team on Pontoon has [now synced with Common Voice](https://pontoon.mozilla.org/Tig/common-voice/) and is available for localisation. 

I have also now made [Tigre](https://pontoon.mozilla.org/tig/) available on Pontoon, once you have Pontoon account you will be able to become a manager. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. 

Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

[- Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
[- Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
[- Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
[- Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions join us on the [community chat](https://chat.mozilla.org/#/room/#common-voice:mozilla.org), also if you would like any community support I'm happy to share ideas and support you.

All the best,

Hillary, Common Voice Community Manager.

**Comment by bbeshir** [comment]
Thank you Hilary, I see it on Pontoon but not on
https://commonvoice.mozilla.org/en/languages

is it supposed to show up here.
-Beshir

    On Monday, November 8, 2021, 02:24:13 PM EST, Hillary ***@***.***> wrote:  
 
 


Hello @bbeshir

Tigre Team on Pontoon has now synced with Common Voice and is available for localisation.

I have also now made Tigre available on Pontoon, once you have Pontoon account you will be able to become a manager. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project.

Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- Pontoon user guide
- Roles and responsibilities
- Localizing in Fluent
- Common Voice web part project info

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions join us on the community chat, also if you would like any community support I'm happy to share ideas and support you.

All the best,

Hillary, Common Voice Community Manager.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bbeshir** [comment]
Hilary, as I mentioned below, I still don't see it on https://commonvoice.mozilla.org/en/languages 
do you know why.
-Beshir



    On Monday, November 8, 2021, 02:39:15 PM EST, B. A. Beshir ***@***.***> wrote:  
 
  Thank you Hilary, I see it on Pontoon but not on
https://commonvoice.mozilla.org/en/languages

is it supposed to show up here.
-Beshir

    On Monday, November 8, 2021, 02:24:13 PM EST, Hillary ***@***.***> wrote:  
 
 


Hello @bbeshir

Tigre Team on Pontoon has now synced with Common Voice and is available for localisation.

I have also now made Tigre available on Pontoon, once you have Pontoon account you will be able to become a manager. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project.

Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- Pontoon user guide
- Roles and responsibilities
- Localizing in Fluent
- Common Voice web part project info

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions join us on the community chat, also if you would like any community support I'm happy to share ideas and support you.

All the best,

Hillary, Common Voice Community Manager.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ftyers** [comment]
@bbeshir I think that is because it only happens with each new release. For example, every two weeks. You can still start contributing translations and sentences in the meanwhile.

**Comment by MichaelKohler** [comment]
Tigre is now added to the Sentence Collector as well.

**Comment by bbeshir** [comment]
Thank you so much, I just tested it and it is now working for me.


    On Tuesday, November 9, 2021, 01:58:13 PM EST, Michael Kohler ***@***.***> wrote:  
 
 


Tigre is now added to the Sentence Collector as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bbeshir** [comment]
FYI,  for testing purpose I added couple of sentences, reviewed and approved them fine.
However when I went to https://commonvoice.mozilla.org/en/languages 

I couldn't see the language ( Tigre ) in the list under "In Progress"
Would you be able to help

-Beshir

    On Tuesday, November 9, 2021, 02:38:11 PM EST, B. A. Beshir ***@***.***> wrote:  
 
  Thank you so much, I just tested it and it is now working for me.


    On Tuesday, November 9, 2021, 01:58:13 PM EST, Michael Kohler ***@***.***> wrote:  
 
 


Tigre is now added to the Sentence Collector as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MichaelKohler** [comment]
See what @ftyers said above, that was 100% correct.

**Comment by Heyhillary** [comment]
Hiya @bbeshir,

Tigre is now live on the common voice website. I am now closing this GitHub issue. If you need any help please let me know.

**Comment by bbeshir** [comment]
1. when I go to commonvoice.mozilla.org I still don't see it on the drop down list box menu on the right hand side of the page
2. please change "Tig" to "tig", it looks like this is causing some issue.


    On Thursday, November 25, 2021, 08:50:02 AM EST, Hillary ***@***.***> wrote:  
 
 


Hiya @bbeshir,

Tigre is now live on the common voice website. I am now closing this GitHub issue. If you need any help please let me know.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Heyhillary** [comment]
Hey @bbeshir ,

Thanks for the message, languages that are launched appear in the list you refer to. 

As Tigre, is an in-progress language it will not show up on the list. For a language to be launched currently it needs 90% localisation and 5,000 public license sentences.  

Currently, Tigre does show up on the languages page under in [progress languages.](https://commonvoice.mozilla.org/languages) 

If you need any help or advice on for community efforts I'm happy to help and share what other language communities have done ?

**Comment by bbeshir** [comment]
For "Tigre" language
"Statistics" section of https://commonvoice.mozilla.org/sentence-collector/#/en/stats is showing there are 5,382⁩ validated sentences.On the other hand if you select "Tigre" on the link  https://commonvoice.mozilla.org/en/languages it show Sentences:    0 / 5000
Is there anything else we need to do to go live with this language?


    On Tuesday, November 30, 2021, 07:25:41 AM EST, Hillary ***@***.***> wrote:  
 
 


Hey @bbeshir ,

Thanks for the message, languages that are launched appear in the list you refer to.

As Tigre, is an in-progress language it will not show up on the list. For a language to be launched currently it needs 90% localisation and 5,000 public license sentences.

Currently, Tigre does show up on the languages page under in progress languages.

If you need any help or advice on for community efforts I'm happy to help and share what other language communities have done ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MichaelKohler** [comment]
I will have a look at the export from Sentence Collector. I think I know what is going wrong.

**Comment by MichaelKohler** [comment]
Could it be that these got approved in the past week? From the export view it seems to be ok. The next export is gonna run in about 6 hours. I will have a look at the export result tomorrow. If that works, CV will know about the sentences. However new sentences won't appear until the next deployment of the Common Voice website. That release happens every 2 weeks.

If everything works out (I can tell you tomorrow), with the next website release Tigre would be enabled for contribution.

**Comment by MichaelKohler** [comment]
Export has happened and > 5000 sentences got exported. Additionally Tigre got marked to be enabled on Common Voice. This means that with the next website release (should be sometime within the next 2 weeks) Tigre will be enabled for voice contribution.
