### ISSUE TITLE
Turkmen language localization request

### ISSUE THREAD

**Issue by berkesas** [common-voice/common-voice#3340]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add? Turkmen

**Language code**
Please provide the ISO-639-1 code: tk

**Language size**
Number of active speakers of this language in the world: 11 million

**Plural forms**
How would you translate the following in this language?

0 rocks - 0 daş
1 rock - 0 daş
2 rocks - 2 daş
3 rocks - 3 daş
4 rocks - 5 daş
5 rocks - 5 daş
10 rocks - 6 daş
20 rocks - 20 daş
100 rocks - 100 daş
1000 rocks - 1000 daş
I see 0 rocks on the ground - Ýerde 0 daş görýärin
I see 1 rock on the ground - Ýerde 1 daş görýärin
I see 10 rocks on the ground - Ýerde 10 daş görýärin
I see rocks on the ground - Ýerde daşlary görýärin

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
https://pontoon.mozilla.org/contributors/SNg843tatvAALLYFhdkmvvkv17s/

**Language Script**
What is the name of the language scripts used to write your language ? Latin

**Comment by ftyers** [comment]
Note that the plurals for Turkmen should be the same as Turkish and the other Turkic languages, i.e. ` one, other `

**Comment by berkesas** [comment]
@ftyers In general I agree that there are similarities in grammar rules. But can you elaborate on your comment?

**Comment by ftyers** [comment]
There are different plural rules in Pontoon based on the behaviour of agreement in numeral expressions. For example in English we have "1 stone", "2 stone**s**", "no stone**s**", "a stone", "many stone**s**" etc. In Russian, Welsh and other languages they have different agreement for different numbers, so you would say один камень, два кам**ня**, пять кам**ней** etc. For Russian the plural rules are ` one, few, many `, for Welsh they are ` zero, one, two, few, many, other `. For Turkmen they are the same as in Turkish and the other Turkic languages. This is a techno-grammatical decision.

**Comment by MichaelKohler** [comment]
FYI: this is already enabled on Sentence Collector.

**Comment by ndocx** [comment]
@berkesas hi, I also want to contribute to this project. Let me know if you need any help.

**Comment by Heyhillary** [comment]
Hi @berkesas,

Thanks for your request to join Common Voice !

I have now added Turkmen into our localising tool called [Pontoon](https://pontoon.mozilla.org/tk/ ) and given you the manager role. If @ndocx would also like to join please provide your pontoon account link and I can add you. 

To help get you started, here is some valuable information to help you as a manager for the language.The role of a manager means all your work will go to staging (and later to production) without peer review.

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

Kind regards,

Hillary

**Comment by Heyhillary** [comment]
Hey @berkesas and @ndocx,

Congratulations on reaching 87% on localisation. Your language is not too far from being launched for voice data collection. You need 1900 of CC0 sentences to be launched.

Learn how you can [add more sentences](https://commonvoice.mozilla.org/en/about?tab=how-add-sentences#playbook) and join us on our [chat](https://chat.mozilla.org/#/room/#common-voice:mozilla.org) if you have questions.
