### ISSUE TITLE
Tigre is added as "Tig" on Pontoon

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/common-voice#3341]
Tigre was requested in https://github.com/common-voice/common-voice/issues/3338. I see it has been added as "Tig" instead of "tig" in Pontoon: https://pontoon.mozilla.org/Tig/common-voice/

![image](https://user-images.githubusercontent.com/330324/141531682-357b4796-d283-4e98-88bf-59a5e68eeb15.png)

@Heyhillary was this on purpose? If so, I didn't see that before and added it as "tig" in the Sentence Collector, so I would need to change that.

**Comment by Heyhillary** [comment]
Hey Micheal, thanks for pointing this out. I have changed it to lowercase now.
