### ISSUE TITLE
Problem regarding zh-hk language code [Chinese (Hong Kong)]

### ISSUE THREAD

**Issue by c933103** [common-voice/common-voice#3368]
1. Currently, this Common Voice project have already launched [Chinese (Hong Kong)]\<zh-hk>, and is incubating [Cantonese]\<yue>.
2. However, Chinese \<zh> is a macrolanguage.
3. In most of the world, the Standard Chinese variant is generally regarded as Mandarin \<cmn>, and the data in [Chinese (China)]\<zh-cn> as well as [Chinese (Taiwan)]\<zh-tw> also use Mandarin in their Chinese recording.
4. However, in Hong Kong, as reflected in text already translated into [Chinese (Hong Kong)]\<zh-hk>, as well as voice already being recorded, they are in local variant of [Cantonese]\<yue>.
5. For proper language identification, it might be desirable to tag it as [Cantonese (Hong Kong)]\<yue-hk> instead, but that would create several problems.
5.a. Including the fact that Cantonese, despite being mutually non-intelligible to Mandarin Chinese, is still part of the Chinese macrolanguage, and Chinese text can be speak in Cantonese language directly. tagging this under a different language code could create usability problem, for instance a program designed to accept Chinese \<zh> language might not recognize language being tagged as [Cantonese]\<yue> (Like how Google have TTS for Cantonese, but failed to provide such function for Chinese books in Google Books due to it being treated as different language), and users might not be able to immediately locate the locale they want to either since users are accustomed to describe their literary language as Chinese\<zh>.
5.b. Also, a number of software in the world, including Microsoft Windows, Android, Chromium, do not recognize the language code of \<yue> and only recognize \<zh-hk> for the Cantonese variant of Chinese spoken in Hong Kong.
6. As such, I hope Mozilla can weight in on the matter and decide how to handle the situation.

**Comment by c933103** [comment]
(Sorry for didn't noticing #2761 and #2926 existing before this request)

**Comment by c933103** [comment]
Note that this is different from previously-discussed situation of \<zh-hk> vs \<yue>, but instead whether \<zh-hk> should be coded \<yue-hk>, or something else

**Comment by irvin** [comment]
There were some technical restrictions in the early days that we needed to name it zh-HK (from to website localization system) instead of yue or yue-hk, and I think we should leave it as it. It’s much easier to change the offline database after you download it than to modify the online system.

**Comment by sammyfung** [comment]
Thanks to @irvin to summarise my opinions.

**Comment by ftyers** [comment]
Gvien the recent work on [supporting variants](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/), it might be worth revisiting this issue.

**Comment by c933103** [comment]
> Gvien the recent work on [supporting variants](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/), it might be worth revisiting this issue.

The blogpost mentioned "currently MCV assumes a 1:1 relationship between spoken word and written word" have been identified as an issue, but the solution proposed - "We plan to build out support for multiple orthographies for a single language" - is not sufficient to address the differences between Spoken/Written Cantonese and Standard Written Chinese, as Cantonese users, when writing in Standard Chinese, do not change the orthography, but instead what need to be changed is the grammar and word choice, sometimes also involve changing sentence structure when writing down Spoken Cantonese into Standard Written Chinese, a process which can be treated as translation.

**Comment by ftyers** [comment]
Dear @c933103 I don't think anyone is suggesting that Mandarin and Cantonese should be maintained within the same language code. Perhaps 'Chinese' is a bit vague for this usage, what do you think?

**Comment by c933103** [comment]
> Dear @c933103 I don't think anyone is suggesting that Mandarin and Cantonese should be maintained within the same language code. Perhaps 'Chinese' is a bit vague for this usage, what do you think?

It is indeed vague to use the word "Chinese" to cover both Mandarin Chinese and Cantonese. However, the standard written language in Hong Kong is still "Chinese", which is functionally a written version of Mandarin, despite Written Cantonese is also being used in a comparatively limited but still relatively widespread scope. And thus, in use cases like speech synthesis or speech recognition, it is not uncommon for people to feed such Mandarin Chinese text into software, and expect it to produce Cantonese voice, or feed Cantonese voice into software and expect Mandarin output. This is in addition to people feeding actual Written Cantonese text into the engine and expect Cantonese voice or speaking Cantonese and expect Written Cantonese text output.

In actual use case, that mean if I open up a page written in [Mandarin] Chinese, which for example have a sentence like "我的名字是小明" (My name is Xiao Ming), a Cantonese speaker would expect the Cantonese voice engine to be able to render the sentence as audio output of [Ngo dit ming ji si siu ming] (appx.), while the natural way to translate and speak the sentence into Cantonese would be "我個名叫小明" [Ngo go maan giu siu ming] (appx.). The most ideal case would be feeding the Mandarin sentence into the engine being able to produce Cantonese in natural Cantonese speaking order, like how human would read out a written sentence, but I recognize that it seems to be out of scope for a voicebank that simply collect people's voice. Given such situation, I think the voice bank should at least enable program using its voice data to produce Cantonese output for written Mandarin sentences in Mandarin vocabulary and word order, if the separation of Cantonese and Mandarin is being emphasized.

**Comment by ftyers** [comment]
I think this is somewhat out of scope for the project at the current time. What you are talking about is a text to speech translation system. 

In that case probably the best thing to do is to collect a parallel corpus of public domain texts in Mandarin and Cantonese and add the sentences to Mandarin and Cantonese Common Voice respectively. Then once the sentences are recorded, they can be matched and you can produce e.g. Mandarin sentence → Cantonese voice.  

I'm going to close this now as not planned, but please feel free to get back in touch if you'd like more information on how to proceed with the suggestion.

**Comment by c933103** [comment]
> What you are talking about is a text to speech translation system.

Note that I am talking about two things at the same time. One is translation and the other is not.

One is having a natural Mandarin Chinese text input and have natural Cantonese output. The other is having natural Mandarin Chinese text input but have Cantonese output that follow Mandarin Chinese grammar.

The first is translation, the second is not.

But the question here is, even if it is determined that #1 is currently not technologically possible, how do we tag the voice data to allow the #2 type of contribution, and how do we deal with the two sets of Cantonese data that are already in Mozilla Common Voice.

**Comment by ftyers** [comment]
They both count as translation. A word-for-word translation is still a translation.

If the sentences are in Cantonese you can add them to `yue` and `zh-HK`. If they are in Mandarin you can add them to `zh-TW` or `zh-CN` or both. 

The alignment would have to be done as a postprocess after the dataset release, but this should be fairly straightforward to do.

**Comment by ftyers** [comment]
"Different phonetic values" means different words no? E.g. I can translate Portuguese to Spanish by providing different phonetic values for the words in Portuguese, which would provide a similar experience I imagine. It seems that there is nothing specific to Mandarin/Cantonese about this, aside from the writing system, which if we take words as atomic units as opposed to sequences of characters would still apply.

**Comment by c933103** [comment]
> "Different phonetic values" means different words no? E.g. I can translate Portuguese to Spanish by providing different phonetic values for the words in Portuguese, which would provide a similar experience I imagine. It seems that there is nothing specific to Mandarin/Cantonese about this, aside from the writing system, which if we take words as atomic units as opposed to sequences of characters would still apply.

In Chinese they are same word. Some Chinese dictionaries would list every single Chinese word with different reading in all different Chinese languagess. It is possible that this is due to writing system affecting people's conception of what count as same word and what count as a different word, but it is used in a number of situation in real life like when one want to read aloud a printed text without applying personal interpretation or preserving lingulistic element of the original written text.

I think the different with, e.g. Portuguese to Spanish is whether speakers of the language actually do so in their daily life and whether they are accustomed to this.

**Comment by ftyers** [comment]
Sure you can read out Portuguese as if it were Spanish, I guess this is more likely in bilingual situations though, so maybe more likely with Catalan and Spanish for example.

**Comment by c933103** [comment]
Aren't Spanish and Catalan have some degree of intelligibility though?

An example from Mozilla Common Voice website,

> Common Voice is a publicly available voice dataset, powered by the voices of volunteer contributors around the world. People who want to build voice applications can use the dataset to train machine learning models.
> 
> At present, most voice datasets are owned by companies, which stifles innovation. Voice datasets also underrepresent: non-English speakers, people of colour, disabled people, women and LGBTQIA+ people. This means that voice-enabled technology doesn’t work at all for many languages, and where it does work, it may not perform equally well for everyone. We want to change that by mobilising people everywhere to share their voice.

The Chinese translation, if read using standard Mandarin, would be like this:

> Common Voice shì yītào yóu láizì shìjiè gèdì de shèqún gòngxiàn zhì gōng suǒ tígōng, kě gōngkāi shǐyòng de yǔyīn zīliàojí, xiǎng yào dǎzào yǔyīn yìngyòng chéngshì de rén kěyǐ shǐyòng cǐ zīliàojí lái xùnliàn jīqì xuéxí móxíng.
>
> Mùqián dàbùfèn de yǔyīn zīliàojí dōu yóu èshā chuàngxīn de dà qǐyè suǒ yǒngyǒu. Gèzhǒng yǔyīn zīliàojí yě guòdù jiāqiángle shuō yīngyǔ de báirén nánxìng de yǔyīn bǐlì. Zhè dàibiǎo yǔyīn jìshù gēnběn wúfǎ yòng yú mǒuxiē yǔyán, jiùsuàn kěyǐ shǐyòng, yě bùjiàn dé duì měigèrén dōu néng yǒu yīyàng hǎo de xiàoguǒ. Wǒmen xiǎng yào tòuguò dòngyuán shìjiè gè jiǎoluò rénmen zhǔdòng fēnxiǎng yǔyīn de fāngshì, lái niǔzhuǎn zhège xiànxiàng.

If this Mandarin text is read in Cantonese then it would be like this:

> Common Voice sih yāttou yàuh lòihjih saigaai gokdeih dīk séhkwàhn gunghin ji gūng só tàihgūng, hó gūnghōi síyuhng dīk yúhyām jīlíujaahp, séung yiu dájouh yúhyām yingyuhng chìhngsīk dīk yàhn hóyíh síyuhng chí jīlíujaahp lòih fanlihn gēihei hohkjaahp mòuhyìhng.
> 
> Muhkchìhn daaihbouhfahn dīk yúhyām jīlíujaahp dōu yàuh āksaat chongsān dīk daaih kéihyihp só yúngyáuh. Gokjúng yúhyām jīlíujaahp yáh gwodouh gākèuhnglíuh syut yīngyúh dīk baahkyàhn nàahmsing dīk yúhyām béilaih. Jéh doihbíu yúhyām geihseuht gānbún mòuhfaat yuhng yū máuhsē yúhyìhn, jauhsyun hóyíh síyuhng, yáh bātgin dāk deui múihgoyàhn dōu nàhng yáuh yātyeuhng hóu dīk haauhgwó. Ngóhmùhn séung yiu taugwo duhngyùhn saigaai gok goklōk yàhnmùhn jyúduhng fānhéung yúhyām dīk fōngsīk, lòih náujyun jéhgo yihnjeuhng.

If it is native Cantonese it would be like this:

> Common Voice haih yātgo gūnghōi ge yúhyām sougeuijaahp, kéuih haih kaau saigaai gokdeih ge jiyuhnjé gunghin chēut jihgéi bá sēng làih kausìhng ge. Séung jihgéi jíng yúhyām yingyuhng ge goyàhn tùhng tyùhntái dōu hóyíh yuhng nīfahn sougeuijaahp làih fanlihn dī gēihaaih hohkjaahp mòuhyìhng.
> 
> Muhkchìhn daaihbouhfahn yúhyām sougeuijaahp dōu haih dāk daaih gūngsī sīn yúngyáuh, gámyéung wuih jóngoih chongsān. Yìhché hóudō yúhyām sougeuijaahp dōu fātsihjó fēi yīngyúh yàhnsih, yáuhsīk yàhnjúng, chàahnjeung yàhnsih, néuihsing, LGBTQIA+ dáng yàhnkwàhn ge sougeui. Gám douhji jó yáuh hóudō yúhyìhn dī yúhyām geihseuht dōu m̀hjīwùhn, waahkjé jauhsyun haih jīwùhn jó dōu m̀hhaih deui sóyáuhyàhn ge haauhgwó dōu yātyeuhng gamhóu. Ngóhdeih séung dáng daaihgā dōu hóyíh hóufōngbihn gám gunghin chēut jihgéi bá sēng, làih góibin nīgo yihnjohng.
