### ISSUE TITLE
A question on renaming bulk submission files

### ISSUE THREAD

**Issue by somerandomguyontheweb** [common-voice/common-voice#3369]
Hi @phirework, I have a question: Would it be safe to send a PR to rename certain bulk submission files for Belarusian? Or would it cause any complications on the database side?

Let me provide some context behind this question. Two of the bulk submissions for Belarusian have been contributed by independent media (Euroradio and Novy Chas), which are currently under pressure, due to ongoing political crisis in Belarus. It is possible that all their content may be proclaimed "extremist" by the Belarusian authorities in the future, thus imposing blanket ban on sharing online any texts that originate from these sources. Potentially it could mean that the Belarusian community of Common Voice might be held accountable for violating the Belarusian law. To prevent this, it would be helpful if we could obscure the origin of texts, at least by renaming the submission files (e.g. changing `euroradio` to `er` in the filename, or doing ROT13-encoding). Of course the Belarusian law enforcement officers can still view the commits log; however, the assumption is that they're not particularly tech-savvy, and obscuring the filenames would probably reduce the contributors' attack surface.

Could you please let me know if this is feasible? If yes, would it be as easy as renaming the files, or additional steps are required, such as database migrations?

Thanks in advance for any comments.

**Comment by phirework** [comment]
That should be fine - the sentences are identified by a hash of the sentence text, so as long as the contents of the file don't change, changing the filename shouldn't make a difference.
