### ISSUE TITLE
[Bug] Hidden text of leaderboard visibility in CV profile settings (de)(es)(smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3376]
**Describe the bug**
The chosen selection of leaderboard visibility in CV profile settings (german language, too long string) is displayed partially hidden.

**To Reproduce**
1. Log into your cv account
2. Change to german language
3. Go to settings, preferences, profile
4. Result is shown in pic1

**Expected behavior**
Full readable text is presented to the contributor
in cv settings profile german and spanish.
Shorter text string or moving the rest of the page with a flexible routine depending on the text string length a little bit down

**Screenshots**
![Screenshot_20211202-181553](https://user-images.githubusercontent.com/92784377/144473567-576cc619-a450-4104-8d05-fb9d3d68f941.png)
![Screenshot_20211202-181455](https://user-images.githubusercontent.com/92784377/144473619-d8421d66-3e70-4b94-82d2-47c74aa2f2a5.png)

**Mobile (please complete the following information):**
 - OS: Android 10
 - Browser: Kiwi (chrome based)
 - Version 96.0.4664.46
 - also on latest Fx mobile browser:
 - Version: 94.1.2 (Build #2015844587)

 **Hardware:**
 Fairphone 3 plus

**Additional context**
i also added the pic of the english section to compare (pic2).

**Comment by robovoice1** [comment]
![Screenshot_20211208-133422](https://user-images.githubusercontent.com/92784377/145235598-2369b9ad-ba2b-4244-a274-1e9cbeafcde6.png)

i added a pic (spanish profile settings)

**Comment by phirework** [comment]
This should be fixed by 1.61.0

**Comment by robovoice1** [comment]
![Screenshot_20211216-115603](https://user-images.githubusercontent.com/92784377/146366923-b372c352-ddd6-4dc8-a427-144ec684343b.png)
![Screenshot_20211216-115249](https://user-images.githubusercontent.com/92784377/146366975-52a50f2c-b921-4649-87a5-f81e9bc45802.png)

**Comment by robovoice1** [comment]
@phirework see pics and date

**Comment by phirework** [comment]
Hm, I wonder if your phone browser has a cached version of the frontend? Can you hard refresh? This is what I see:

![Screen Shot 2021-12-16 at 12 00 06 PM](https://user-images.githubusercontent.com/582683/146415533-1e6ae415-c3de-4edb-a4c6-6c9e035edb30.png)

**Comment by robovoice1** [comment]
![Screenshot_20211216-185119](https://user-images.githubusercontent.com/92784377/146423682-3b717fb4-33b3-42a6-a2fc-2e4e101519ba.png)
yes, that was the reason. Thanks
