### ISSUE TITLE
Getting the error as Cannot GET /

### ISSUE THREAD

**Issue by Nihalkumbhalkar** [common-voice/common-voice#3377]
**Describe the bug**
After installing all the packages as per the readme file of development environment . Then I run the command yarn start it is showing server started on localhost:9000 But still not able to see any response it is showing Cannot GET / response on front end
![image](https://user-images.githubusercontent.com/61318030/144550317-50ae45c7-2c72-407d-aa11-9458f38cb2e8.png)
![image](https://user-images.githubusercontent.com/61318030/144550327-5336588e-5cac-4dff-862e-be4b01d6f0ba.png)
![image](https://user-images.githubusercontent.com/61318030/144551675-17da28bb-3f52-431f-b18e-be08402fa679.png)

**Comment by phirework** [comment]
You don't have a frontend running - it looks like you may have removed the part of the run script that goes into `/web` and starts it up. If you only have the backend running, there is no API endpoint that corresponds to `/` - see routes in `server.ts` and `api.ts`

**Comment by Heyhillary** [comment]
hello @Nihalkumbhalkar,

I'm going to close the bug, if you are still facing an issue please re-open this bug.
