### ISSUE TITLE
[req] limited validation rights in CV website

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3378]
The idea of this request is:

The contributer, who is not submitting (useful!) clips for the (selected) languages and/or dialects cannot validate for that language and/or dialect. (based on the displayed languages in CV settings profile and stats, your languages, see pic1)

Not selected languages in CV website cannot be reached for a speak/validating session. (see pic2)
Submitting useful clips is the proof of speaking and understanding the selected language(s).

Some other things to think of:
Are these limitations for newbies only or permanent?
Has the non native speaker the right to judge on submitted native speaker clips?
Is this request improving the validation process/results of validation or just adding new obstacles to the contributor?

This request could prevent "messing around" in language sections, which the contributor is not able to speak or understand.

**Additional context**
![Screenshot_20211203-091220](https://user-images.githubusercontent.com/92784377/144571886-2ad85ef7-910e-4aac-871f-098ab492ba93.png)
![Screenshot_20211203-092232](https://user-images.githubusercontent.com/92784377/144571958-fa7a4123-a6c9-4ddf-a0ec-4a210a5c6ff3.png)

**Comment by Heyhillary** [comment]
Hey @robovoice1 

Thanks for your suggestions. 

Can suggest maybe including the wider community on your idea - to understand if there is some consensus ?

Please feel free to make a discourse topic on this. 

Many thanks,

Hillary

**Comment by robovoice1** [comment]
The chance of abusing this with ai is too high on a 2nd thought.
Closing this " brilliant" request!
