### ISSUE TITLE
[bug] Too long log out button when logging out of languages (smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3380]
**Describe the bug**
see pics
log out button is way too long presented to contributor. (android smartphone, horizontal and landscape mode)

**To Reproduce**
1. log into cv account
2. tap on your avatar (top right corner)
3. tap on languages,  see pic1
4. tap again on your avatar, top right
5. result is pic2 and 3

**Expected behavior**
A log out button that fits the screen is presented to the contributor, log out screen is fixed

**Screenshots**
![Screenshot_20211204-060910](https://user-images.githubusercontent.com/92784377/144698938-e2a460af-66c0-4b28-8fa0-8c67aff491d0.png)
![Screenshot_20211204-060846](https://user-images.githubusercontent.com/92784377/144698948-290dabc9-983e-437e-a59d-cbe565747b43.png)
![Screenshot_20211204-063654](https://user-images.githubusercontent.com/92784377/144698954-971035a2-52bc-48f1-ab0a-1b403f89822f.png)

**Mobile (please complete the following information):**
 - OS: Android10
 - Browser Fx mobile stable
 - Version 94.1.2 (Build #2015844587)
AC: 94.0.12, e5eb726f81
GV: 94.0-20211028161635
AS: 85.4.0

 **Hardware:**
 Fairphone 3 plus

**Additional context**
none

**Comment by robovoice1** [comment]
On a pixel 4a with Android12/Graphene Os the log out button is ok.
![Screenshot_20220116-142857](https://user-images.githubusercontent.com/92784377/149662087-47ec1275-10bb-4b05-ae8c-2149b80331be.png)

**Comment by robovoice1** [comment]
Log out button now with correct size with Fairphone3 Android10!

**Comment by robovoice1** [comment]
Regression on this one.
Please see pic 
![Screenshot_20220203-172042](https://user-images.githubusercontent.com/92784377/152384110-5797c765-a970-4588-b806-b82fdf14f8dd.png)

**Comment by robovoice1** [comment]
Picture shot on Pixel 6 pro
Android 12/ Graphene Os (latest beta channel)
Fx nightly mobile android
98.0a1 (Build #2015861163), e73deb23a+
AC: 98.0.20220202143123, c3b551957a
GV: 98.0a1-20220202093701
AS: 90.0.1

**Comment by quartesa37** [comment]
#3518
