### ISSUE TITLE
[bug] Whole log out screen can be moved up+to the right out of view (Languages)(smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3384]
**Describe the bug**
Please watch the screen recording!
The whole log out screen can be moved up and right until only white screen is displayed.

**To Reproduce**
1. Log into cv
2. Tap on the avatar, top right
3. Select languages
4. Tap again on the avatar, top right
5. Swipe up and to the right!
6. Result: the whole log out screen can be moved until just  a white screen is displayed.
7. You can also see the too long log out button i filed a bug here: #3380

**Expected behavior**
This log out page must be fixed.

**Screenrecording**

https://user-images.githubusercontent.com/92784377/144740987-846c6b2c-6e9c-4df6-9cdb-d88953ed99e4.mp4

**Mobile (please complete the following information):**
 - OS: Android 10
 - Browser Fx mobile stable
 - Version 94.1.2 (Build #2015844587)
AC: 94.0.12, e5eb726f81
GV: 94.0-20211028161635
AS: 85.4.0

 **Hardware:**
 Fairphone 3 plus

**Additional context**

**Comment by robovoice1** [comment]
swiping to the right also possible. Nothing is displayed there just white screen

**Comment by robovoice1** [comment]
This is the result with Android 12!

**Comment by quartesa37** [comment]
#3632
