### ISSUE TITLE
[bug] Swiping up + down in "Speak" and "Validate" (all languages)(smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3386]
**Describe the bug**
see screen recording.
Moving up and down of Speak and Validate screens is possible

**To Reproduce**
1. Log in CV 
2. Go to speak section
3. Swipe up and down
4. Go to validate section
5. Swipe up and down
6. Change to another language
7. Repeat step 2 - 6

**Expected behavior**
Fixed screens in Speak and Validate.
Placing the two (Report and Skip) buttons a little bit higher (visual reasons), they can be accessed better.

**Screenrecording**

https://user-images.githubusercontent.com/92784377/145232758-0cceb6a2-0ee1-481c-8b83-9a884d34fe0e.mp4

**Mobile (please complete the following information):**
 - OS: Android 10
 - Browser Fx mobile 
 - Version 94.1.2 (Build #2015844587)
AC: 94.0.12, e5eb726f81
GV: 94.0-20211028161635
AS: 85.4.0

 **Hardware :**
 - Type: Fairphone
 - Model: 3 plus

**Additional context**
recorded in english, german, spanish and french Speak and Validate section. With the no more clips to validate message the screen is totally fixed.

**Comment by robovoice1** [comment]
On a Pixel 4a with Android 12/GrapheneOs the page is fixed!

**Comment by janvi01** [comment]
Hey, @Heyhillary I would like to fix this.

**Comment by robovoice1** [comment]
Closing this one
