### ISSUE TITLE
[bug] Languages page can be completely swiped to left side (all languages)(smartphone)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3387]
**Describe the bug**
see screen recording

**To Reproduce**
1. Log in CV account
2. Tap on avatar, top right
3. Select "Languages"
4. Swipe to left and then down

**Expected behavior**
Fixed Languages page, no moving around possible.

**Screenrecording**

https://user-images.githubusercontent.com/92784377/145290104-f37575cf-5c48-4187-9cf3-5bf28ed4e5af.mp4

**Mobile:**
 - OS: Android 10
 - Browser Fx mobile
 - Version 94.1.2 (Build #2015844587)
AC: 94.0.12, e5eb726f81
GV: 94.0-20211028161635
AS: 85.4.0

 **Hardware:**
 Fairphone 3 plus

**Additional context**
.... .................. ¯\_(ツ)_/¯ ................................

**Comment by robovoice1** [comment]
Also with pixel 4a Android 12/GrapheneOs

**Comment by RiyaGupta89** [comment]
Hey @phirework  @Heyhillary, can you guys please help me learn more about the issue so that I should work on it and fix it.

**Comment by Heyhillary** [comment]
Thanks @robovoice1 for adding the link. 

@riyaGupta89 - to start please review our [development doc](https://github.com/common-voice/common-voice/blob/main/docs/DEVELOPMENT.md) for instructions on setting up a local development environment.

If you would like to connect with the wider community feel free to[ chat to us on Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)/

**Comment by janvi01** [comment]
Hey, @Heyhillary I would like to work on this bug.

**Comment by janvi01** [comment]
Sure @Heyhillary Thanks, I will start a PR if there is no response from her.
