### ISSUE TITLE
[Bug] Request to remove trash sentences in the Cantonese locale (yue)

### ISSUE THREAD

**Issue by laubonghaudoi** [common-voice/common-voice#3392]
**Describe the bug**
There are too many trash sentences in the Cantonese (yue) locale. Worse still they are all validated by unknown people. We are requesting to remove them.

**To Reproduce**
See [yue/sentence-collector.txt](https://github.com/common-voice/common-voice/blob/main/server/data/yue/sentence-collector.txt)
Many lines are either:
1. Single characters or words, which are not sentences at all.  Or
2. Mandarin sentence, not Cantonese

**Example screenshot**

![image](https://user-images.githubusercontent.com/11172180/147400110-e4964974-24ac-4046-b06c-8215c49059e6.png)

**Proposed Solution**
There are currently 542 sentences. After our close examination, only <100 sentences are valid and usable. So we proposed to remove everything so as to start over with clean sentences.

**Comment by MichaelKohler** [comment]
Handled with https://github.com/common-voice/sentence-collector/commit/3273693edcde55fd5edaff63c2c72a72ef24d6aa. The next export (in about 6 hours) will also delete them from the Common Voice repo file. Thanks for reporting!

**Comment by laubonghaudoi** [comment]
That's great, thank you!

**Comment by MichaelKohler** [comment]
Oh, if there are no sentences, there is also no export for it. So it will be removed with the first export that will have some data in it. But for now that's fine, it won't be enabled until then anyway.

**Comment by laubonghaudoi** [comment]
But we can still add sentences in the sentence collector, and export them after validated, right?

**Comment by MichaelKohler** [comment]
Yes! And once Sentence Collector has validated sentences the next export will correctly write the file with only those.
