### ISSUE TITLE
Removing top bar possible in log out screens (android12)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3404]
**Describe the bug**
Please see screen recording!
Recorded in selected "languages" log out screen.
Moving the top bar up and to the left is possible.

https://user-images.githubusercontent.com/92784377/149661168-0348b103-d33a-4166-a33f-bfa86a7fbfa3.mp4

**To Reproduce**
1. log into CV
2. tap on avatar and select languages
3. tap again on avatar (top right)
4. swipe up, swipe left
5. Result is shown in screen revording!

**Expected behavior**
Fixed top bar 

**Screenshots**

**Mobile (please complete the following information):**
 - OS: Android 12/GrapheneOs
 - Browser firefox nightly android
 - Version 98.0a1 (Build #2015857707), 5e63aa734+
AC: 98.0.20220114190159, f0562815cd
GV: 98.0a1-20220114093102
AS: 87.2.0

 **Hardware**
 - Type: Pixel
 - Model: 4a

**Additional context**

**Comment by robovoice1** [comment]
Also in Datasets and About log out screen!

**Comment by mozgzh** [comment]
Thanks for filling the issue! I can reproduce this bug as well. 
Setting a `overflow-x: hidden` on `body` for mobile seems to fix the issue. Will need to test if it breaks other pages/elements, and ideally find out what is causing the app to overflow when using a smaller screen.

**Comment by mozgzh** [comment]
This is related to #3387

**Comment by robovoice1** [comment]
I filed a seperate report https://github.com/common-voice/common-voice/issues/3387
Is with Android 10
This filed issue Android 12.

**Comment by mozgzh** [comment]
Need to set CSS for the to something like `position: fixed;
top: 0;
left: 0;
width: 100%;
z-index: 100000;` for the navbar, but only when the menu is open, or if thats not desirable, set it to fixed everywhere, but include enough `margin` so the navbar doesn't overlay on top of content.

**Comment by rotimi-babalola** [comment]
Hello, @robovoice1 I would like to ask if you are still experiencing this behaviour? I'm trying to reproduce with the steps you gave but I am unable to reproduce at the moment. I'm attaching 2 videos that  I try to reproduce but I am unable to

https://user-images.githubusercontent.com/24937453/188882999-5e098d18-25e9-4fb7-94c1-d61f1290b4d4.mov


https://user-images.githubusercontent.com/24937453/188883074-06144aec-581f-4ae8-bc5e-bc09e0438208.mov

**Comment by robovoice1** [comment]
This is what i experience right now:

https://user-images.githubusercontent.com/92784377/188909734-25d43450-1432-42d7-b610-481dc053da54.mp4

Removing status bar by swiping up possible in all log out screens
Removing to the left side not possible any more in About and Languages log out. 
A "stretch effect" to the left side in Datasets log out.

Pixel 6 pro
Android 13 GOS TP1A.220905.004.2022090600

Latest Firefox nightly
106.0a1 (Build #2015902251), 3d1924eb9+
AC: 106.0.20220904143128, a12017fdad
GV: 106.0a1-20220904093956
AS: 94.1.0

**Comment by rotimi-babalola** [comment]
> Removing status bar by swiping up possible in all log out screens
>  A "stretch effect" to the left side in Datasets log out.

Please could you send screenshots (or a recording) of these scenarios?

**Comment by robovoice1** [comment]
https://user-images.githubusercontent.com/92784377/188928641-5bf5c5f8-81e3-4e98-972a-941f5e1cfb09.mp4

**Comment by robovoice1** [comment]
https://user-images.githubusercontent.com/92784377/188929330-4e494098-d452-4824-8351-4b9ba31ff4d1.mp4

**Comment by robovoice1** [comment]
https://user-images.githubusercontent.com/92784377/188930847-5c608149-9c4a-43d7-9b51-42aaa4b82395.mp4

**Comment by robovoice1** [comment]
https://user-images.githubusercontent.com/92784377/188983509-4de8e060-166c-4ff1-a5ee-7783dc461056.mp4

And here: Stats/Goals/Awards:
To the left side not possible any more, but swiping up moves the top of the site.

**Comment by robovoice1** [comment]
No more moving  possible in Android 13 with the new code release 👍😎👍

**Comment by robovoice1** [comment]
It is possible again to remove the top of the log out screens

https://user-images.githubusercontent.com/92784377/200434559-0bf096d7-c3c6-487b-963c-4c0744ac7d13.mp4

Google Pixel 6 pro
Android 13 GrapheneOS latest beta
Ff nightly 
108.0a1 (Build #2015914347), 3b85861a0+
AC: 108.0.20221106143258, d9f43f22c5
GV: 108.0a1-20221105092350
AS: 94.3.2

**Comment by moz-rotimib** [comment]
Thanks for mentioning this @robovoice1 this issue should be fixed when this [PR](https://github.com/common-voice/common-voice/pull/3841/files) is merged
