### ISSUE TITLE
[BUG] X to exit Leaderboard Visibility is hidden in (de) language (android)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3413]
**Describe the bug**
In selected german language in CV, the x to exit leaderboard visibility is hidden. German text is overlapping the x.

**To Reproduce**
1. Log into Cv
2. Select german language
3. Tap on the eye symbol 
4. Result is pic1
5. To compare see pic2 of selected english language.

**Expected behavior**
The " x" is visible at first sight in all selected languages

**Screenshots**
![Screenshot_20220119-104807](https://user-images.githubusercontent.com/92784377/150108118-0d2359fa-4622-4c54-8d81-e887ee4a6570.png)
![Screenshot_20220119-104843](https://user-images.githubusercontent.com/92784377/150108183-1670b1ae-00fb-4ce0-be75-7af18e023970.png)

**Mobile (please complete the following information):**
 - OS: Android12 with GrapheneOS
 - Browser Fx nightly mobile android
 - Version 98.0a1 (Build #2015858283), af5b2c94d+
AC: 98.0.20220118143334, 6f60a8a44b
GV: 98.0a1-20220117035808
AS: 87.2.0

 **Hardware **
 - Type: Pixel
 - Model: 4a

**Additional context**
Also on Fairphone 3 plus android 10

**Comment by robovoice1** [comment]
Suggested to change:
"Sichtbarkeit in der Rangliste" to
"Ranglistensichtbarkeit" in pontoon.
@MichaelKohler

**Comment by MichaelKohler** [comment]
@robovoice1 while my name is veeeery similar to that of the DE Pontoon Locale Manager, that's a different person ;)

**Comment by robovoice1** [comment]
I can see it ...... now ... two dots are the difference ... sorry

**Comment by robovoice1** [comment]
String has been shortened in de language.
https://pontoon.mozilla.org/de/common-voice/web/locales/en/messages.ftl/?string=190813

Thanks to MK for approving :-)

**Comment by robovoice1** [comment]
Fixed :-)
