### ISSUE TITLE
Bengali/বাঙালা

### ISSUE THREAD

**Issue by Raj7912** [common-voice/common-voice#3414]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Bengali
**Language code**
Please provide the ISO-639-1 code
bn
**Language size**
Number of active speakers of this language in the world
230 million (2011–2017) L2 speakers: 37 million
**Plural forms**
How would you translate the following in this language?

0 rocks
শূন্য শিলা/পাথর

1 rock
একটি শিলা/পাথর
2 rocks
দুটি শিলা/পাথর
3 rocks
তিনটি শিলা/পাথর
4 rocks
চারটি শিলা/পাথর
5 rocks
পাঁচটি শিলা/পাথর
10 rocks
দশটি শিলা/পাথর
20 rocks
কুড়িটি শিলা/পাথর
100 rocks
একশটি শিলা/পাথর
1000 rocks
হাজারটি শিলা/পাথর
I see 0 rocks on the ground
আমি মাটিতে শূন্যটি শিলা/পাথর দেখি
I see 1 rock on the ground
আমি মাটিতে একটা শিলা/পাথর দেখি
I see 10 rocks on the ground
আমি মাটিতে দশটা শিলা/পাথর দেখি
I see rocks on the ground
আমি মাটিতে  শিলা/পাথর দেখি
**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

**Language Script**
What is the name of the language scripts used to write your language ? e.g latin, Devanagari
বাংলা বর্ণমালা

**Comment by Heyhillary** [comment]
Dear @Raj7912,

Thanks for your message request to include Bengali. 

Currently Bengali is in progress to be included onto Common Voice. In order for Bengali to be included the site needs 75% localisation and an increase in cc0 sentences. 

If you are intrested in taking part consider contributing via the[ sentence collector](https://commonvoice.mozilla.org/sentence-collector/#/lu) or by[localising](https://pontoon.mozilla.org/bn/common-voice/) for Bengali. 

Learn more about how [Common Voice Works on the platform](https://commonvoice.mozilla.org/en/about).

If you have any questions please feel free to ask.
