### ISSUE TITLE
[BUG] Malformed link tag in new About page content

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3416]
**Describe the bug**

I hit that during translation. "</ctaLink" is not closed correctly.

```
about-playbook-what-is-language-content-3 = Some languages have enormous variation in grammar, vocabulary and pronunciation. For this reason, we are <ctaLink>introducing ‘Variants’</ctaLink in 2022. This gives communities a way to distinguish their languages within the larger dataset.
```

**Comment by zaccolley** [comment]
Thanks for the issue, just megred in #3421 and #3420 which fix some of these tags that weren't closed.

I'm new to the project so let me know if you need a release to fix this bug. Otherwise let me know if it's now fixed!

**Comment by HarikalarKutusu** [comment]
Thank you, it is OK now on Pontoon :)
The sentences on Pontoon are not reviewd yet for Turkish, so I cannot see the result even on the staging server.

**Comment by bluedaze** [comment]
Should this issue be closed now @zaccolley?

**Comment by zaccolley** [comment]
Yep will close for now, feel free to reopen if it hasn't fixed the issue. Thanks both
