### ISSUE TITLE
[BUG] Picture displayed over text (new about page)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3417]
**Describe the bug**
Please see pic!
In the new about page scroll dow n and tap on :
How do i record a high quality voice clip
Result is screenshot

**Expected behavior**
Fully readable text with no pic aboeve

**Screenshots**
![Screenshot_20220121-115828](https://user-images.githubusercontent.com/92784377/150517569-2a0130b2-cc1f-4b87-aec1-dd947c77746d.png)

**Mobile (please complete the following information):**
 - OS: Android12 Graphene OS
 - Browser Firefox nightly mobile android
 - Version 98.0a1 (Build #2015858667), 12347c999+
AC: 98.0.20220120143203, d203b9b3b8
GV: 98.0a1-20220120100401
AS: 87.2.0

 ** Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Pixel phone
 - Model:4a

**Additional context**

**Comment by zaccolley** [comment]
This was released in 1.66.1 https://github.com/common-voice/common-voice/releases/tag/release-v1.66.1

Thanks @robovoice1!
