### ISSUE TITLE
[BUG] new about page not fully translated in selected (de) language

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3418]
**Describe the bug**
Please see screenshot!

**To Reproduce**
1. Go to cv website
2. select about
3. change to (de) language
4. scroll/swipe down
5. result is pic

**Expected behavior**
Fully translated about page

**Screenshots**
![Screenshot_20220121-125110](https://user-images.githubusercontent.com/92784377/150523167-92ed3cc7-0fc9-43ed-b649-38ef0e485e6a.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Android12 Graphene OS
 - Browser Fx nightly mobile android
 - Version 98.0a1 (Build #2015858667), 12347c999+
AC: 98.0.20220120143203, d203b9b3b8
GV: 98.0a1-20220120100401
AS: 87.2.0

 ** Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: pixel
 - Model:4a

**Additional context**

**Comment by Heyhillary** [comment]
Hey @robovoice1 ,

Thanks for reporting the issue. I have found that this is also happening for other languages - I will flag this with the team. 

Many thanks,

Hillary

**Comment by robovoice1** [comment]
Fixed :-)
