### ISSUE TITLE
[BUG] Validation process stops after valitating one sentence

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3429]
**Describe the bug**
Please watch the screenrecording!
A) just one sentence is presented to the contributor
B) After validating the single sentence the no more clips screen is shown (after every validated sentence)
C) Nothing happens 
D) Reloading the tab is needed to continue validation.
This is a constant behavior (always 1 sentence, no more clips message)

**To Reproduce**
1. Log into cv
2. Start a validation
3. Result is screen recording
4. Reload the tab to continue validation

**Expected behavior**
The next sentence is presented automatically without reloading browser tab!

**Screenrecording**

https://user-images.githubusercontent.com/92784377/151350016-140ae92a-ba6f-4958-87e3-451351973003.mp4

**Mobile (please complete the following information):**
 - OS: Android 12 Graphene Os
 - Browser Fx nightly mobile android
 - Version 98.0a1 (Build #2015859819), 46a228796+
AC: 98.0.20220126143158, be27a8afbe
GV: 98.0a1-20220126065618
AS: 90.0.1

 **Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Pixel
 - Model: 4a

**Additional context**

**Comment by zaccolley** [comment]
@robovoice1 I think we fixed this issue with the 1.65.2 release. Could you check if this is fixed for you?

**Comment by robovoice1** [comment]
Yes. :-) closing this one.
