### ISSUE TITLE
Translation error on the french about page

### ISSUE THREAD

**Issue by Oxey405** [common-voice/common-voice#3434]
# The translation error
Hello ! There is a problem of missing translation in the **french about page** of common voice.
See here : https://commonvoice.mozilla.org/fr/about 
The point number 3 is still written in english : "Sentences are collected for people to read aloud." 
# Fixed translation proposition
The text translated could be : 
> "Les phrases sont collectées pour que les gens les lisent à voix haute".

**Comment by stefangrotz** [comment]
Hey @Oxey405 the translations are not done in the source code but on a website called pontoon. Here is a link to the french version, where you can fix the error yourself:
https://pontoon.mozilla.org/fr/common-voice/

**Comment by Oxey405** [comment]
Thanks stefan ! I'll check it out
