### ISSUE TITLE
speak page

### ISSUE THREAD

**Issue by ranaawni** [common-voice/common-voice#3437]
**Describe the bug**
Tried to deploy the common voice repo using ngrok but in speaking page it give me We’re sorry, your platform
is not currently supported.
otherwise if I open it locally (localhost) it's working normal

**Screenshots**
![Screenshot from 2022-01-31 15-59-15](https://user-images.githubusercontent.com/17303446/151806866-5cf65d16-fcf5-4268-89d0-09cf88f61c07.png)

**Comment by zaccolley** [comment]
Hi @ranaawni, It might be that we're incorrectly blocking your browser. Could you let us know:
+ Operating System
+ Browser (including version)

**Comment by ranaawni** [comment]
Hi @zaccolley 
Ubuntu 21.04
Chrome Version 96.0.4664.110 + Firefox 96.0

**Comment by zaccolley** [comment]
So it looks like we show this message when we think we can't record audio. https://github.com/common-voice/common-voice/commit/b59b97e49d21b9eda4df599135cf18e75ef0d4c3

I'm wondering if the APIs for recording voice require HTTPS to work. Could you try adding https:// to your ngrok link?

**Comment by ranaawni** [comment]
@zaccolley  Thank you it's working

**Comment by zaccolley** [comment]
I'll close for now, let us know if you need anything else!
