### ISSUE TITLE
Saraiki

### ISSUE THREAD

**Issue by mpQadir** [common-voice/common-voice#3449]
**Language name**
Saraiki
**Language code**
Skr
**Language size**
30M
**Plural forms**

١ پتھر
٢پتھر
٣پتھر
٤پتھر
٥پتھر
١٠ پتھر
٢٠ پتھر
١٠٠پتھر
١٠٠٠ پتھر
میں زمین تے ہک پتھر ݙٹھے
میں زمین تے ݙاہ پتھر ݙٹھن
میں زمین تے پتھر ݙٹھن
**Pontoon manager**
https://pontoon.mozilla.org/contributors/_e4HP0y6NUnhYnpmEDmrBiXd2fo/
**Language Script**
Arabic

**Comment by ftyers** [comment]
Hi there, thanks for your language request! For the Pontoon plurals would ` one, other ` be fine?

**Comment by mpQadir** [comment]
Dear, ftyers, yes.
For the Pontoon plurals would one, other is fine.

**Comment by Heyhillary** [comment]
Hello @mpQadir ,

Thanks for your request and for sharing the CLDR Plural, I've nearly [finished](https://pontoon.mozilla.org/skr/) setting up Saraiki on Pontoon.

I'm struggling to find the plural rule for Saraiki in the form of (plural= string), I usually use this source to help me find the [plural rule](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html) but Saraiki is not listed, by any chance do you know what it is for Saraiki ?

*please note this is different from the CLDR plural.

**Comment by mpQadir** [comment]
Dear, It is same as 
Sindhi language.

**Comment by Heyhillary** [comment]
Hello @mpQadir,

Thank you for providing further details. 

[Saraiki ](https://pontoon.mozilla.org/skr/common-voice/)is now available on Common Voice Pontoon Page. 

Your role on Pontoon has been set to manager for Saraiki.  To help get you started, here is some valuable information to help you as a manager for the language. The role of a manager means all your work will go to staging (and later to production) without peer review. 

If you would like to learn how to use Pontoon please [check out this video.](https://drive.google.com/file/d/1YVyHUPaw2oiVdZZ7_pg607cIMq0YDMcw/view?usp=sharing)

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

Kind regards,

Hillary
