### ISSUE TITLE
Phoneme information

### ISSUE THREAD

**Issue by harpavatkeerti** [common-voice/common-voice#3451]
**Is your feature request related to a problem? Please describe.**
Is there any available dataset for phoneme information? Most datasets I have found are based on speech and its corresponding text, is there anything where one can get more information about the audio itself, i.e the phonemes which make up the audio.

**Describe the solution you'd like**
An aligned dataset consisting of English audio clips along with its phonetic transcription. It can be a single spoken word with its phonemes or a sentence with its phonemes.

**Comment by ftyers** [comment]
This does not exist, but you can use [epitran](https://github.com/dmort27/epitran) to phonemise the transcripts (based on [CMUdict](http://www.speech.cs.cmu.edu/cgi-bin/cmudict) I think). It will of course be lossy. For other languages [commonvoice-utils](https://github.com/ftyers/commonvoice-utils) has some rudimentary g2p systems.

**Comment by harpavatkeerti** [comment]
Thanks for the prompt reply, I will look into the links you provided.
