### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by fu-lab** [common-voice/common-voice#3455]
Hi everybody.
I'm translating https://pontoon.mozilla.org/mhr / into the Meadow Mari language.
Please give me admin rights so that I can approve translations.
Thanks.
Andrey Chemyshev

**Comment by ftyers** [comment]
Hi @fu-lab is this you: https://pontoon.mozilla.org/contributors/6Ql2TVCWQqB1LXtAsKctJPiK2h0/ ?

**Comment by fu-lab** [comment]
Yes, it's me.

вт, 8 февр. 2022 г. в 18:43, Francis Tyers ***@***.***>:

**Comment by Heyhillary** [comment]
Hey @fu-lab,

Thanks for your request, I have now made you a manager - this means all your work will go to staging (and later to production) without peer review. Managers can change team permissions and edit other settings like team description.

I would encourage you to consider making a style guide or adding communtiy details onto the pontoon team

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org).

Kind regards,

Hillary

**Comment by fu-lab** [comment]
Thanks.

вт, 8 февр. 2022 г. в 20:08, Hillary ***@***.***>:
