### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by fu-lab** [common-voice/common-voice#3459]
Hi!
How to include the Mari Meadow language in Common Voice https://commonvoice.mozilla.org/?
I translated the necessary. I have prepared 5000 offers.
Andrey.

**Comment by Heyhillary** [comment]
Hey @fu-lab ,

Firstly are the sentences under creative commons zero ? If the sentences are not you can initate the [cc0 zero process with the copyright owners of the texts.](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html)

Secondly, there are two ways in which you can add the sentences either via [bulk submission ](https://github.com/common-voice/common-voice/blob/main/docs/SENTENCES.md#bulk-submission) or the [sentence collector](https://commonvoice.mozilla.org/sentence-collector/#/) 

If you need any help please feel free to reach out via our [community chat room ](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

**Comment by ftyers** [comment]
Dear Andrey, you don't need to change the licence, you can just fill out [this form](https://github.com/common-voice/community-playbook/blob/draft/sub_pages/Common%20Voice%20ContributionAgmt%20-%20%5B1722573%5D%20-%20Template.pdf) and upload it here.

**Comment by ftyers** [comment]
Можно заполнить [тот форм](https://github.com/common-voice/community-playbook/blob/draft/sub_pages/Common%20Voice%20ContributionAgmt%20-%20%5B1722573%5D%20-%20Template.pdf) ? Это способ, чтобы дать книгу в CC-0. 

@Heyhillary is there a version of the form in other languages? e.g. in Russian?
