### ISSUE TITLE
[BUG] Languages stuck at "Loading..."

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3464]
**Describe the bug**
Probably you are aware of this. After the last update the languages summaries got stuck on loading:

![image](https://user-images.githubusercontent.com/8849617/153760287-43bd5df7-0657-4bf9-9410-a646bdbf8af3.png)

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/languages

**Comment by mozgzh** [comment]
Thanks for taking the time create this issue - we've merged the fix to this in the last release, and the page stats are loading as expected! 

With that in mind, I'll close this issue. Thanks again :rocket:
