### ISSUE TITLE
[BUG]Misplaced top bar when trying to log in CV (with new server info)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3484]
**Describe the bug**
With the new message in CV website (see pic1) after trying to log in, the top bar is misplaced and hiding "languages" section (see pic2)

**To Reproduce**
1. Go to  CV website
2. Tap on the three dots (top right)
3. Result is screenrecording
4. Top bar can be moved above the selections

**Expected behavior**
No overscrolling top bar 

**Screenshots**
![Screenshot_20220224-195839](https://user-images.githubusercontent.com/92784377/155591600-4989bded-29a4-41b0-b3e9-ee7c40f3f68c.png)
![Screenshot_20220224-195858](https://user-images.githubusercontent.com/92784377/155591635-f7e55fff-da0f-41bc-bb44-5eb0c5311789.png)

https://user-images.githubusercontent.com/92784377/155591675-de7a6aa6-9d74-4628-9a4f-5a8b32e64f72.mp4

**Mobile (please complete the following information):**
 - OS: Android 12 GrapheneOS
 - Browser Firefox nightly mobile
 - Version 99.0a1 (Build #2015865195), f7d317fb4+
AC: 99.0.20220223143136, 22dcd7deaa
GV: 99.0a1-20220223093800
AS: 91.1.0

 **Hardware :**
 - Type: Google Pixel 
 - Model: 6 pro

**Additional context**

**Comment by zaccolley** [comment]
Thank you, will try and fix this soon!
