### ISSUE TITLE
[BUG] Not translated Message with bookmarked CV (de)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3485]
**Describe the bug**
Please see pic

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/de
2. Message (Server overload) is displayed in english
And the german bookmarked cv page is in german

**Expected behavior**
Fully translated website is presented 

**Screenshots**
![Screenshot_20220224-203238](https://user-images.githubusercontent.com/92784377/155594987-186722e3-e23b-46b0-9704-d6a97be03c39.png)

**Mobile (please complete the following information):**
 - OS: Android 12 Graphene OS
 - Browser Firefox nightly mobile Android 
 - Version 99.0a1 (Build #2015865195), f7d317fb4+
AC: 99.0.20220223143136, 22dcd7deaa
GV: 99.0a1-20220223093800
AS: 91.1.0

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by ftyers** [comment]
@robovoice1 Thanks for the report, @Heyhillary has requested localisations for that. You can get in contact with her, see the [post](https://discourse.mozilla.org/t/common-voice-platform-status-page/93726) on Discourse.

**Comment by robovoice1** [comment]
Thanks for the info.

**Comment by ftyers** [comment]
I'm going to close this as I don't think it makes sense to have one issue for every missing language, and it's better to deal with it through Discourse. If you feel differently please feel free to reopen.

**Comment by robovoice1** [comment]
Releasing the english server message(s) on pontoon to translate would do the trick (for all languages)
I contacted @Heyhillary
