### ISSUE TITLE
Request to add Azeri Turkish (Iranian Turkish language)

### ISSUE THREAD

**Issue by nimafanniasl** [common-voice/common-voice#3498]
**This language is different from Azerbaijani, I speak Azeri Turkish of Iranian Turks.**
https://en.wikipedia.org/wiki/Azerbaijani_language

**Language name**
Azeri Turkish (Iranian Turkish language)

**Language code**
az

**Language size**
There is no certainty about the Turkic-speaking population in Iran, and the collective statistics can only be estimated. The Central Intelligence Agency (CIA) estimates that the total population of Azeris and Turkic-speaking people is 18% of the total population of Iran.

**Plural forms**
How would you translate the following in this language?

0 rocks صیفر دنه داش
1 rock بیر دنه داش
2 rocks ایکی دنه داش
3 rocks اوچ دنه داش
4 rocks دورت دنه داش
5 rocks بش دنه داش
10 rocks اون دنه داش
20 rocks ایگیرمی دنه داش
100 rocks یوز دنه داش
1000 rocks مین دنه داش
I see 0 rocks on the ground من صیفر دنه داش یئر ده گورییم
I see 1 rock on the ground من بیر دنه داش یئر ده گورییم
I see 10 rocks on the ground من اون دنه داش یئر ده گورییم
I see rocks on the ground من داش یئر ده گورییم

**Pontoon manager**
fanniasl

**Language Script**
Persian

**Comment by ftyers** [comment]
Dear @nimafanniasl thank you very much for your interest. The `az` language code is already used for Azerbaijani from Azerbaijan in [Pontoon](https://pontoon.mozilla.org/az/common-voice/). There are separate language codes for `azj` (North Azerbaijani) and `azb` (South Azerbaijani).

Common Voice has recently been working on [adding support for linguistic variants](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/) and it remains to be seen if there should be a single Azerbaijani language with variants for North/South/Latin/Perso-Arabic or if they should be included as separate languages.

This is an ongoing question that effects many languages, and we would like to see as many community members involved as possible. Both from Azerbaijan and South Azerbaijan.
