### ISSUE TITLE
[BUG] Toki Pona reportedly has no sentences, but over 5000 are validated

### ISSUE THREAD

**Issue by gregdan3** [common-voice/common-voice#3504]
**Describe the bug**

Toki Pona has gone live on the main section of the site as of today, but there are no sentences available to record despite there being sufficient sentences validated in Sentence Collector.

**To Reproduce**

1. Go to https://commonvoice.mozilla.org/tok/speak
2. Observe the error message: sitelen pi toki ni li lon ala. ni la sina ken ala kalama awen e ona. "This language has no sentences. You cannot record."
3. Go to https://commonvoice.mozilla.org/sentence-collector/#/tok/stats
4. Observe that there are over 5000 sentences already validated in Toki Pona

**Expected behavior**

As sentence collector shows >5000 sentences validated for Toki Pona, there should be sentences available to record.

**Comment by MichaelKohler** [comment]
By now it seems that https://commonvoice.mozilla.org/tok/speak is showing sentences. Can you confirm? (I have no idea why though)

**Comment by gregdan3** [comment]
Can confirm- there are definitely sentences now, and we are able to contribute. Not sure what happened, but now that it's resolved, no big deal. Thanks!
