### ISSUE TITLE
[BUG] Too small blue button in translated cv-ui

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3635]
**Describe the bug**
A clear and concise description of what the bug is
The blue button in the new about section is too small to display the german/french translation.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en
2. Select about (the 3 dots, top right)
3. Select the 2nd question: how does site localisation work?
4. change cv website ui from english to german and afterwards to french ui
5. See screenshot 1 + 2

**Expected behavior**
Fully readable blue button in other translated languages

**Screenshots**
![Screenshot_20220326-134014](https://user-images.githubusercontent.com/92784377/160244645-0d660277-02bf-4cf9-84a5-ddc8d901c17a.png)
![Screenshot_20220326-134121](https://user-images.githubusercontent.com/92784377/160244660-936b205a-0fdd-47ad-9b59-9db929876524.png)

**Mobile (please complete the following information):**
 - OS: Android 12 GrapheneOS 
 - BrowserFx nightly android
 - Version 100.0a1 (Build #2015870955), 0b981dde5+
AC: 100.0.20220325145327, c522ea6eab
GV: 100.0a1-20220325093814
AS: 91.1.1

 **Hardware :**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by mozgzh** [comment]
Also broken in English on mobile, a simple solution is to just replace the text with "Watch video" or the like as that would reduce the change of creating new line break.

**Comment by Heyhillary** [comment]
Hey @robovoice1 ,

Thanks for raising the issue. 

Would you be happy to create a PR  please based on Mozgh suggestion? 

Kind regards,

Hillary
