### ISSUE TITLE
[BUG] 1 sentence instead of 5 in Speak

### ISSUE THREAD

**Issue by hellosct1** [common-voice/common-voice#3647]
**Describe the bug**
when I want to speak, I have only 1 sentence instead of 5

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/speak
2. See 1 sentence

**Expected behavior**
I want to see 5 sentences in any language

**Screenshots**
![image](https://user-images.githubusercontent.com/182199/161065944-cf828d31-b8c9-48b1-a084-dca48bb415f8.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Linux, Android, Windows
 - Browser Firefox Nightly - Firefox - Firefox beta
 - Version All

**Comment by robovoice1** [comment]
Today morning, i had the same problems.
Now, it is working again as expected. Pixel 6 pro Android12.
![Screenshot_20220331-171933](https://user-images.githubusercontent.com/92784377/161091329-88bb715c-2091-49ff-945d-2bc3f3f4bbe6.png)

**Comment by hellosct1** [comment]
the tests have shown that everything is back to normal and I close the issue
