### ISSUE TITLE
Requesting to add Khmer in common voice

### ISSUE THREAD

**Issue by ksoky** [common-voice/common-voice#3666]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Khmer
**Language code**

km

**Language size**

Over 16 million

**Plural forms**

**Pontoon manager**

soky.kak@gmail.com
**Language Script**

Khmer

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
It is a low-resource language in NLP.
2. [optional to share] Would you like to have a follow up conversation regarding community building ?
Yes

**Comment by Heyhillary** [comment]
Dear Ksoky,

Thanks for your request. 

Khmer language speakers have requested the language previously to be part of Common Voice. Khmer is currently an in-progress language. 

If you would like to contribute to Khmer I would like to suggest the following:

1. Common Voice dataset includes sentences that are read about by voice contributors. Currently, Khmer requires 5,000 sentences that are [creative commons zero](https://creativecommons.org/choose/zero/).  You can help with sentence collection by:

a. (No code required) - Contributing via Common Voice Sentence Collector 
b. (Knowledge of Github and Reviews) - Contributing via a Bulk Submission with a copyright owner who would like to dedicate their texts to Creative Commons Zero
c. (Code-required) - Contributing via the Common Voice Sentence Extractor 

Learn more on [the playbook](https://common-voice.github.io/community-playbook/sub_pages/text.html)

2. Please create a Pontoon profile and help with [translating strings](https://pontoon.mozilla.org/km/common-voice/web/locales/en/messages.ftl/?string=176567). This will help Khmer speakers engage with the content of the website as it will be in their language. 

3. Connect with the other [Khmer contributors](https://pontoon.mozilla.org/km/contributors/) to understand or create a strategy for Common Voice Khmer. I'm happy to help with advice for community building.

If you have any questions please let me know!
