### ISSUE TITLE
Hill Mari language

### ISSUE THREAD

**Issue by fu-lab** [common-voice/common-voice#3667]
Hi.
Can you give me the rights of a Manager for mrj? Hill Mari language: https://pontoon.mozilla.org/mrj/
Andrey.

**Comment by ftyers** [comment]
Hi @fu-lab could you let us know what your Pontoon user is. Just link to your profile page. Thanks!

**Comment by fu-lab** [comment]
https://pontoon.mozilla.org/contributors/6Ql2TVCWQqB1LXtAsKctJPiK2h0/

вт, 19 апр. 2022 г. в 19:31, Francis Tyers ***@***.***>:

**Comment by Heyhillary** [comment]
Hey Audrey,

Sorry for the delay in response.

You should now have manager access. 

This guide should help with understanding [Pontoon](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)If you have any questions please feel free to reach out to us on the Community Chat on [Element/Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org).

All the best,
