### ISSUE TITLE
New Language Localization Request: Sesotho

### ISSUE THREAD

**Issue by RoneWie** [common-voice/common-voice#3678]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
>Sesotho</p>

**Language code**
>I don't know where to find the language codes.</p>

**Language size**
>3.8 million</p>

**Plural forms**
>0 majoe
1 lefika
2 majoe
3 majoe
4 majoe
5 majoe
10 majoe
20 majoe
100 majoe
1000 majoe
Ke bona majwe a 0 fatshe
Ke bona lefika le le leng fatshe
Ke bona majoe a 10 fatše
Ke bona mafika fatshe</p>

**Pontoon manager**
>rone@viva-afrikaans.org</p>

**Language Script**
<Latin</p>

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [X] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
>As a linguist I would like to assist with the creation and development of language data sets for research purposes.</p>
2. [optional to share] Would you like to have a follow up conversation regarding community building ?
>Yes, please</p>

**Comment by Heyhillary** [comment]
Hey @RoneWie 

Is it possible to confirm if Sesotho is also another way to say Southern Sotho please ?

As I was starting to find the plural forms and noticed the Souther Sotho name.

Kind regards,

Hillary

**Comment by RoneWie** [comment]
Dear Hillary

 

Yes, Sesotho is the term we use for Sothern Sotho in South Africa.

 

Thank you for checking in. My apologies for the confusion.

 

Kind regards

Roné

**Comment by Heyhillary** [comment]
Hey @RoneWie ,

Thanks for confirming - Sesotho is now syncing with the platform -> https://pontoon.mozilla.org/st/.

The onboarding information is available via https://github.com/common-voice/common-voice/issues/3679#issuecomment-1122245666 

Kind regards,

Hillary

**Comment by RoneWie** [comment]
Dear Francis 

 

Thank you for your response. 

 

My Pontoon details are: ***@***.*** ***@***.***> 

 

Kind regards

Roné
