### ISSUE TITLE
New Language Localization Request: Northern Sotho

### ISSUE THREAD

**Issue by RoneWie** [common-voice/common-voice#3679]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
<Northern Sotho</p>

**Language code**
>I don't know where to find the language codes</p>

**Language size**
<4.7 million</p>

**Plural forms**
< mafsikeng
Tee Lefsika
Pedi mafsikeng
Tharo mafsikeng
Nne mafsikeng
Hlano mafsikeng
Lesome mafsikeng
mafsikeng
tše lekgolo mafsikeng
tše sekete mafsikeng

**Pontoon manager**
>rone@viva-afrikaans.org</p>

**Language Script**
>Latin</p>

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [X] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
>As a linguist I am interested in creating language data sets for research purposes</p>
2. [optional to share] Would you like to have a follow up conversation regarding community building ?
>Yes, please</p>

**Comment by ftyers** [comment]
Dear @RoneWie, Northern Sotho is already on Pontoon, you can find it [here](https://pontoon.mozilla.org/nso/) under the language code `nso`. There appears to be no manager, so you could take it over. Please let us know what your Pontoon username is (see e.g. the instructions [here](https://github.com/common-voice/common-voice/issues/3663#issuecomment-1100231619)).

**Comment by RoneWie** [comment]
Dear Francis 

 

Thank you for your email.

 

I would love to be a part of the Northern Sotho and Afrikaans teams. Afrikaans is my first language and I am an Afrikaans linguist. I therefore hope to expand the Afrikaans and Northern Sotho data sets considerably. Could you please provide me with access to both language communities etc.

 

My Phontoon account is: ***@***.*** ***@***.***> 

 

Kind regards

Roné

**Comment by Heyhillary** [comment]
Dear @RoneWie 

Thanks for your localisation request to include Northen Sotho in the project.

I will follow up with your email regarding community building. 

Secondly, I have made you and Febe the [Pontoon Managers for Northen Sotho.](https://pontoon.mozilla.org/nso/ ). The role of a manager means all your work will go to staging (and later to production) without peer review. 

If you would like to learn how to use Pontoon please [check out this video.](https://drive.google.com/file/d/1YVyHUPaw2oiVdZZ7_pg607cIMq0YDMcw/view?usp=sharing)

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

Kind regards,

Hillary
