### ISSUE TITLE
Localization Request for Tshivenda

### ISSUE THREAD

**Issue by fdw42** [common-voice/common-voice#3680]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
Tshivenda

**Language code**
ve

**Language size**
1.3 million 

**Plural forms**
No idea. I will have to find out.

**Pontoon manager**
Febe de Wet

**Language Script**
Latin script with five additional accented letters.

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [X] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ? I would like to see all South Africa's official languages participating in the digital future: leave no voice behind.

3. [optional to share] Would you like to have a follow up conversation regarding community building ? No, not at this stage, thank you.

**Comment by ftyers** [comment]
Hi @fdw42, thanks for your interest in Common Voice! Are you a speaker of Tshivenda? Typically people who are assigned as Pontoon managers for a given language are speakers of the language. If you are running a team, do you have team members who are speakers? In addition, you'll need the plural forms, and your Pontoon profile link.

**Comment by fdw42** [comment]
Dear Francis,

My Pontoon profile link is:
https://pontoon.mozilla.org/contributors/lxO22PaXFScgoRfc1s3fg0sSft4/

I do not speak Tshivenda, but I will be overseeing the localization project.

Regards,
Febe

**Comment by ftyers** [comment]
Dear Febe, could you also provide links to the Pontoon profiles of the Tshivenda speakers who are on the team? Thanks!

**Comment by Heyhillary** [comment]
I have now added Tshivenda into our localising tool [Pontoon](https://pontoon.mozilla.org/ve/) and given you the manager role help get you started, here is some valuable information to help you as a manager for the language. The role of a manager means all your work will go to staging (and later to production) without peer review. 

If you would like to learn how to use Pontoon please [check out this video.](https://drive.google.com/file/d/1YVyHUPaw2oiVdZZ7_pg607cIMq0YDMcw/view?usp=sharing)

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

Kind regards,

Hillary
