### ISSUE TITLE
Localization request for Xitsonga

### ISSUE THREAD

**Issue by fdw42** [common-voice/common-voice#3681]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
Xitsonga

**Language code**
ts

**Language size**
3.7 million native speakers
3.4 million L2 speakers

**Plural forms**
No idea. I will have to find out.

**Pontoon manager**
Febe de Wet

**Language Script**
Latin but, certain sounds are spelled using a combination of letters, which either do not exist in [Indo-European languages](https://en.wikipedia.org/wiki/Indo-European_languages), or may be meant to distinguish the language somewhat.

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [X] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ? I would like to see all South Africa's official languages participating in the digital future: leave no voice behind.

2. [optional to share] Would you like to have a follow up conversation regarding community building ? No, not at this stage, thank you.

**Comment by ftyers** [comment]
Hi @fdw42, thanks for your interest in Common Voice! Are you a speaker of Xitsonga? Typically people who are assigned as Pontoon managers for a given language are speakers of the language. If you are running a team, do you have team members who are speakers? In addition, you'll need the plural forms, and your Pontoon profile link.

**Comment by Heyhillary** [comment]
Hey @ftyers 

I believe @fdw42 and another github members are part of Febe's team, who has a grant to localise South African Languages. So it should be okay.

**Comment by Heyhillary** [comment]
Hey @fdw42 

Thanks for your request - https://pontoon.mozilla.org/ts/ Xitsonga page on Pontoon is currently syncing with the Common Voice strings. Is it possible if you could share with me the Pontoon Manager profile URL please ?

This can be accessed via clicking on your profile. See screenshot for further details. 

<img width="1171" alt="Screenshot 2022-05-10 at 11 28 38" src="https://user-images.githubusercontent.com/85501774/167608559-e3c8aa4e-a278-409c-b82b-139ee0c34a9b.png">

**Comment by Heyhillary** [comment]
Hey @fdw42 ,

I found your pontoon account from your following requests. I have now made you a manager for [Xistonga on Pontoon](https://pontoon.mozilla.org/ts/). Onboarding details are the same as : https://github.com/common-voice/common-voice/issues/3680#issuecomment-1122218433 

If you have any questions please drop me a email.

**Comment by fdw42** [comment]
Dear Francis,

My Pontoon profile link is:
https://pontoon.mozilla.org/contributors/lxO22PaXFScgoRfc1s3fg0sSft4/

I do not speak Xitsonga, but I will be overseeing the localization project.

Regards,
Febe
