### ISSUE TITLE
[BUG] Request to remove pornographic sentences in yue / Cantonese

### ISSUE THREAD

**Issue by laubonghaudoi** [common-voice/common-voice#3712]
Some unknown people have added numerous sentences that contain pornographic contents (sexually suggestive) to the [Cantonese corpus](https://github.com/common-voice/common-voice/blob/main/server/data/yue/sentence-collector.txt). These sentences have been displaying in https://commonvoice.mozilla.org/yue and are very disturbing to voice contributors. We request to remove these sentences.

```txt
2264 其實閪係越屌越緊嘅 鬆咗係代表條女老咗啫
2265 其實阿瑩已經做好咗同阿勝生bb嘅心理準備 但阿勝就係到家下都冇畀個名份佢
4229 大波瑤好易潮吹 俾我插兩嘢就噴到成床都係
4230 大波瑩個籮柚唔小心掂到後面個阿勝 搞到佢碌鳩當堂硬咗
6012 我真係唔知原來有鳩骨嘅喎
6715 搞咗半粒鐘 阿勝終於用盡全力 將呢一個月嘅量全部射晒入大波瑩嘅子宮度
7695 當阿成隻手指插入佢個閪嗰剎那 一種又痛但係又好想要嘅感覺充滿佢全身
9106 閪俾人屌得多就梗係臭㗎喇
9118 阿勝啲精從阿瑩個閪度慢慢咁流咗出嚟 阿瑩知道 阿勝就係專登唔戴套同佢扑嘢
9119 阿勝抽插咗一陣 大波瑩個閪流咗好多白色嘅泡沫狀液體出嚟
9120 阿勝越插越勁 瑩女就快嗌到沙聲 下體就嚟要噴嘢出嚟咁
```

We hope that there would be simpler ways to remove sentences from the corpus. Right now we can't prevent outsiders from dumping junk sentences that contaminate the data set. Is there a way to track who added these sentences?

**Comment by MichaelKohler** [comment]
The sentences are attributed to a specific user. The database holds that information, however we do not expose that anywhere due to privacy reasons.

@mozgzh is there a way to block users on the Auth0 level? As I do not have access to the DB, I can't help out with gathering the user email used for these sentences. If you look these sentences up, could you also drop them from the table? Note that the numbers in the original comment are not the primary keys though.

If there are recorded clips for these, we might also want to drop them from the CV DB/AWS.

**Comment by mozgzh** [comment]
@MichaelKohler can you send the account information via commonvoice@mozilla.com?

**Comment by MichaelKohler** [comment]
> @MichaelKohler can you send the account information via [commonvoice@mozilla.com](mailto:commonvoice@mozilla.com)?

@mozgzh which account information?

**Comment by mozgzh** [comment]
Ah, I misread the above. No worries. We're looking into it. Thanks for the bug report @laubonghaudoi

**Comment by hfhchan** [comment]
We'd like to at least remove the sentences quoted above, if implementing better moderation tools are going to take time.

**Comment by alex-the-man** [comment]
These are very sexually explicit  descriptions of sex acts. I asked a couple of female friends to contribute to the Cantonese common voice project. They encountered these sentences and are now questioning the legitimacy of Common Voice.

Could we please remove these sentences? Thank you.

**Comment by mozgzh** [comment]
Thanks for bringing this issue up to the team. Unfortunately removing sentences is a bit of a time consuming process for our team. However, with that said, the offending sentences have been removed. If any others are found, feel free to open a new issue. Thanks again.

**Comment by laubonghaudoi** [comment]
@mozgzh Thank you! However, we expect such sentences to appear again in the future because ultimately we don't have control over who can add what sentences to the sentence collector. The current approach of opening issues to request sentence removals seems unscalable, and we would like to have a feature to remove sentences directly from the UI. Does common voice have any plan for supporting this feature?
