### ISSUE TITLE
New Language Localization Request: isiZulu

### ISSUE THREAD

**Issue by RoneWie** [common-voice/common-voice#3721]
# Welcome to the Common Voice Community!

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**isiZulu**

**ISO-639-3**

**12 million**

**amatshe ayiqanda/awuziro
itshe elilodwa
amatshe amabili
amatshe amathathu
amatshe amane
amatshe amahlanu 
amatshe ayishumi 
amatshe angamashumi amabili 
amatshe ayikhulu 
amatshe ayizinkulungwane 
ngibona amatshe ayiqanda/awuziro phansi
ngibona itshe elilodwa phansi
ngibona amatshe ayishumi phansi
ngibona amatshe phansi**

**Andiswa.Bukula@nwu.ac.za**

**Latin**

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Dear @RoneWie, [isiZulu](https://pontoon.mozilla.org/zu/) is already enabled on Pontoon. However, there appears to be no manager. Would you like to be manager and for Common Voice to be enabled? Are you a speaker of isiZulu? If so, please paste your profile link here.

**Comment by RoneWie** [comment]
Dear Francis

 

I am not a speaker of isiZulu. My colleagues and I are running a project where we are hiring translators who are native speakers to do the website localization and initial sentence collection to get all of the South African languages launched on Common Voice. 

 

Would you mind giving ***@***.*** ***@***.***>  and ***@***.*** ***@***.***>  access to the Pontoon account for isiZulu, isiXhosa and isiNdebele. My colleague Andiswa is a native speaker of the Nguni languages and we will be managing the project together and assisting the translators on Pontoon. We will also be uploading the setences for all of these languages.

 

Kind regards

Roné

**Comment by ftyers** [comment]
That's a fairly unusual situation, we'll have to look into it. It would be nice to hear more about the project if you are willing.

In the meantime, the translators will need accounts on Pontoon and you will need to give the links to the Pontoon profile pages. You can find some instructions [here](https://github.com/common-voice/common-voice/issues/3663#issuecomment-1100231619). When you reply to GitHub using email the email addresses are blanked out, but we don't need them in any case, we need the Pontoon profile links.

**Comment by RoneWie** [comment]
Dear Francis

 

I would be happy to chat with you regarding our project. Our goal is to establish the South African languages on Common Voice in order to make it easier for language communities and organisations to develop their languages’ datasets.

We have already met with Hillary and discussed our approach. 

 

At the moment we are still getting quotes from translators but once we have appointed translators I will get in touch with you regarding their set up on Pontoon.

**Comment by Heyhillary** [comment]
Heya - I have enabled iziZulu on Pontoon Common Voice Project
