### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by RoneWie** [common-voice/common-voice#3722]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**IsiNdebele**

**ISO-639-1 nr**

**1.1 million**

**0 rocks- amatje alize (does not make sense with direct translation) 
 1 rock-Ilitje linye
 2 rocks-Amatje amabili 
 3 rocks-Amatje amathathu 
 4 rocks-amatje amane 
 5 rocks-amatje amahlanu 
 10 rocks-amatje alitjhumi
 20 rocks-amatje amatjhumi amabili 
 100 rocks-amatje alikhulu
 1000 rocks-amatje ayikulungwane
 I see 0 rocks on the ground-Ngibona ilize lamatje phasi (direct translation does not make sense in a way) rather Angiboni nalinye ilitje phasi (I don’t see even 1stone on the ground) 
 I see 1 rock on the ground-Ngibona ilitje linye phasi
 I see 10 rocks on the ground Ngibona amatje alitjhumi phasi
 I see rocks on the ground Ngibona amatje phasi**

**andiswa.bukula@nwu.ac.za**

**Latin**

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by Heyhillary** [comment]
Hey Rone, 

I noticed on CLDR that there is Southern and Northern IsiNdebele, which have two[ separate ISO codes ](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html).

The one you have requested is South Ndebele, are you happy with me adding the name of the language with brackets (South), to ensure future contributors can have their language added as well / plus also to reduce confusion ?

**Comment by RoneWie** [comment]
Hi Hillary

 

That would be perfect. Thank you for your consideration. 

 

Kind regards

Roné

**Comment by Heyhillary** [comment]
Cool - it's currently being synced. -> https://pontoon.mozilla.org/projects/common-voice/

**Comment by Heyhillary** [comment]
would also want the North Ndebele as well ?

**Comment by Heyhillary** [comment]
Hey Rone, 

I have enabled South IsiNdebele which you can access via the link  https://pontoon.mozilla.org/nr/

I have also enabled [IsiNdebele (North) ](https://pontoon.mozilla.org/nd/

**Comment by RoneWie** [comment]
Thank you!

**Comment by RoneWie** [comment]
Hi Hillary

 

We only need the Southern Ndebele.

 

Thank you for your enquiry.

 

Kind regards

Roné
