### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by RoneWie** [common-voice/common-voice#3723]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**isiXhosa**

**ISO-639-2 xho**

**8.7 million**

**0 rocks- awekho amatye
1 rock- ilitye elinye
2 rocks- amatye amabini
3 rocks- amatye amathathu
4 rocks- amatye amane
5 rocks- amatye amahlanu
10 rocks- amatye alushumi
20 rocks- amatye alishumi anesibini
100 rocks- amatye alikhulu
1000 rocks- amatye aliwaka
I see 0 rocks on the ground- Andiboni litye phantsi
I see 1 rock on the ground- Ndibona ilitye elinye phantsi
I see 10 rocks on the ground- Ndibona amatye alishumi phantsi
I see rocks on the ground- Ndibona amatye phantsi**

**andiswa.bukula@nwu.ac.za**

**Latin**

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Dear @RoneWie, [isiXhosa](https://pontoon.mozilla.org/xh/) is already enabled on Pontoon. However, there appears to be no manager. Would you like to be manager and for Common Voice to be enabled? Are you a speaker of isiXhosa? If so, please paste your profile link here.

**Comment by Heyhillary** [comment]
Hey Rone, I have added Andiswa to Xhosa team on Pontoon and enabled the common voice project on the locale.
