### ISSUE TITLE
Amharic

### ISSUE THREAD

**Issue by aklilu-et** [common-voice/common-voice#3725]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

**Language code**

**Language size**

**Plural forms**

**Pontoon manager**

**Language Script**

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Dear @aklilu-et , it appears that Amharic is [already enabled for Common Voice on Pontoon](https://pontoon.mozilla.org/am/common-voice/). If you'd like further help please let us know.

**Comment by Heyhillary** [comment]
Just to follow up if you are struggling to make an account to help localise please check out this [video explainer ](https://drive.google.com/file/d/1YVyHUPaw2oiVdZZ7_pg607cIMq0YDMcw/view?usp=sharing)of how to use Pontoon. I will be closing the issue, feel free to reach out to us via github or [a community chat. ](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)
