### ISSUE TITLE
Incorrect link to the goals page[BUG]

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3726]
**Describe the bug**
The page https://commonvoice.mozilla.org/mhr/listen contains a link /goals without localisation key, so when i click i open a page with the default localisation from my web browser

**To Reproduce**
1. Go to [listen](https://commonvoice.mozilla.org/mhr/listen)
2. listen 5 samples
3. Click to "Шумлык гыч тӱҥал"(Get started with goals) - /goals
4. The Goals opens first, then redirect to /**web_browser_local**/dashboard/goals

![image](https://user-images.githubusercontent.com/1628540/172010272-c88a07b5-d1bc-4927-8513-9c19b3514420.png)

**Comment by Heyhillary** [comment]
Hey @AigizK 

Thanks for reporting this bug. As part of our triage process, I test to see if I can reproduce this.

Unfortunately, I don't speak your language so I am unable to go through the steps.

Would it be possible to please make a screen recording of this ? 

Thank you

**Comment by AigizK** [comment]
Hey @Heyhillary 
Yes of course.
1. you should authorise
2. check 5 sentences(time: 0:00-0:04)
3. after it you will see the page 0:04 with the black button and text **Шумлык гыч тӱҥал**(or english version is **Get started with goals**)
4.  a href attribute value of this button is **/goals** without language code. But should be **current_lang_code**/goals. For example: **mhr/goals**
5. due to the fact that the link does not contain information about the language, it redirects me to the wrong page(time: 0:33-0:43).
expect: https://commonvoice.mozilla.org/mhr/dashboard/goals [**mhr**/dashboard/goals]
actual: https://commonvoice.mozilla.org/en/dashboard/goals [**en**/dashboard/goals]

https://user-images.githubusercontent.com/1628540/176601571-82dc2c5f-a1a5-4a84-a260-ce212b048c4f.mp4

.

**Comment by Heyhillary** [comment]
Hey @AigizK 

Thanks so much for taking the time to record the issue. 

I will flag this to the team.
