### ISSUE TITLE
[BUG] Can't listen and speak for MRJ

### ISSUE THREAD

**Issue by AigizK** [common-voice/common-voice#3727]
**Describe the bug**
I didn't see a speak button and listen button. when I switch the language to another, then for a few milliseconds I see these buttons

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/mrj

**Screenshots**
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1628540/172013164-cecc856b-ca76-4730-89bb-4c9c23044e7e.png">

https://user-images.githubusercontent.com/1628540/172013352-5ad5d79e-3790-4e2e-b27f-01c21971f8de.mov

**Comment by mozgzh** [comment]
Thanks for posting. Were you able to contribute before? I don't believe MRJ has fully launched (allows contributions), so the speak/listen pages are hidden.

**Comment by AigizK** [comment]
Hi, thank you. About MRJ, the web interface has been translated and suggestions have been added. So I don't understand why speak/listen pages are hidden

**Comment by mozgzh** [comment]
The issue has been fixed. Thanks again for bringing up the issue.

**Comment by AigizK** [comment]
Thank you
