### ISSUE TITLE
[Corrupted dataset] Very low variability in Catalan

### ISSUE THREAD

**Issue by Huguet57** [common-voice/common-voice#3728]
The Catalan sentence dataset is corrupted by a big dataset of the same words over and over again: https://github.com/common-voice/common-voice/blob/main/server/data/ca/frases_agenda.txt. Aproximately 50% of the sentences to record are with repeated words and can bring a big bias into the algorithms trained.

What can be done in these situations? Can this dataset be erased? Or are now the datasets sealed once it's in production?

**Comment by Huguet57** [comment]
@c-armentano es podrien trobar datasets més variats per substituir aquest?

**Comment by Huguet57** [comment]
From the paper: "Collecting text for reading aloud is the second step of adding a new language to Common Voice. For languages with more than 500,000 Wikipedia articles, text sentences are extracted from Wikipedia using community provided rule-sets per language."

@c-armentano did you use the [CV's Sentence Extractor](https://github.com/common-voice/cv-sentence-extractor) to extract the sentences of the wikipedia datasets?

**Comment by c-armentano** [comment]
We are working to find new sentences, but it's difficult. Yesterday a [new PR](https://github.com/common-voice/common-voice/pull/3719) with +50k sentences was approved.
About wikipedia, it's [already done](https://github.com/common-voice/common-voice/blob/main/server/data/ca/wiki.ca.txt).
Regarding this sentences, it would be great to remove them without removing the ones who have been already recorded. Is it possible?

**Comment by Huguet57** [comment]
50.000 frases aniran perfecte! Sobre no perdre totes les que s'han gravat de la base de dades corrupta, si fem ara que no surtin més, tindran menys veus que la resta de datasets així que estarien doble esbiaixats. Jo votaria per perdre les frases i les gravacions d'aquest dataset.

50k new sentences will be of great help. However, on not losing all the recorded data of the corrupted dataset, if we remove them from showing up now, in the long run they will have less recordings than the ones from other datasets (therefore, being doubly-biased).

I would vote to lose all setences and recordings of this dataset. As seen [here](https://github.com/common-voice/common-voice/blob/main/docs/SENTENCES.md#flagging-problematic-sentences), modifying the text files should be enough. I will now open a pull request to erase the file.

**Comment by jmontane** [comment]
I don't agree with "corrupted" term, may be "biased" is a better one.

Recorded sentences must be preserved. Always. Sentences from frases_agenda.txt are grammatically correct, and their recorded clips are good too. And they are good (but biased) data. If it's desired, these sentences can be easy filtered when using published CV dataset.

Said that, we have more sentences awaiting to be recorded now, so, if Common Voice staff can remove unrecorded sentences from frases_agenda.txt, I agree with it.

**Comment by Huguet57** [comment]
I celebrate this is getting discussed then! A couple of things to take in care:
1. If we stop showing these sentences now, they will have less recordings than the rest. Won't this cause yet another bias?
2. Given that the other datasets are fine and represent a good distribution of the Catalan language, why should we try to keep (partially, at least) such a distorted distribution of sentences? (My stance to be clear, is that keeping "some" of this sentences still makes this dataset extremely biased, there are several 3-grams repeated in 10% of the dataset)

My proposition is in the pull request, so I will keep the discussion going.

**Comment by Huguet57** [comment]
Thank you for having the discussion,
For this particular issue, a review of the frequency of words in the submission would had helped the dataset quality.

Gràcies a tots per l'esforç comunitari en resoldre això
