### ISSUE TITLE
[BUG] No data on "languages" section

### ISSUE THREAD

**Issue by Huguet57** [common-voice/common-voice#3736]
**Describe the bug**
There is no data in the Languages section. Shows 0 or 1 hour recorded in every language.

**To Reproduce**
1. Go to [https://commonvoice.mozilla.org/ca/languages](https://commonvoice.mozilla.org/ca/languages)

**Expected behavior**
It should show the hours recorded for each language.

**Screenshots**
![No data shown](https://user-images.githubusercontent.com/6130834/173388374-f3478849-7ace-424c-b4df-03c205cb0744.png)

**Comment by mozgzh** [comment]
Thanks for creating the issue! There's been a deploy with a partial fix, sentence counts now appear correctly for all languages. Work is still continuing on the total daily hours.
