### ISSUE TITLE
Sentence fix in English

### ISSUE THREAD

**Issue by agonzalezd** [common-voice/common-voice#3761]
File `server/data/en/sentence-collector.txt` has a Cyrillic character `а` with Unicode number U+0430 instead of Latin character `a` at line 44210:

```
This was а kind of box or pulpit projecting out of the wall.
```

Third word

**Comment by Heyhillary** [comment]
Hey @agonzalezd,

Thanks for flagging this !

**Comment by agonzalezd** [comment]
You have it on #3765
