### ISSUE TITLE
[BUG] Impossible to access audio file array

### ISSUE THREAD

**Issue by saraPicc** [common-voice/common-voice#3763]
I'm trying to use the Common Voice Italian dataset loaded through the Hugging Face load_dataset function, it works well except that it seems no longer possible to access the decoded audio clips. Once the dataset is loaded, all the features are accessible except for the ['audio'] one.
I'm working on Google Colab, I used the same dataset about a month ago and I didn't have any issue.

1. Installings

!pip install transformers
!pip install 'datasets==2.0' --q
!pip install datasets[audio]
!pip install soundfile --q
!pip install pyctcdecode --q
!pip install librosa
!pip install jiwer
!pip install torchaudio

from datasets import load_dataset, load_metric, Audio

2. Dataset load

common_voice_train = load_dataset("common_voice", 'it' , split="train[:10%]", download_mode='force_redownload')

4. Check dataset

common_voice_train.features

>>> {'audio': Audio(sampling_rate=48000, mono=True, decode=True, id=None),
 'path': Value(dtype='string', id=None),
 'sentence': Value(dtype='string', id=None)}

common_voice_train['path'][0]

>>> /root/.cache/huggingface/datasets/downloads/extracted/375e33abf1689e333837c5d7f9cab23ad8655f80bf0326b3dec16f7b2c81b290/cv-corpus-6.1-2020-12-11/it/clips/common_voice_it_17415771.mp3

common_voice_train['sentence'][0]
>>> "Il marchese aveva già moglie in quell'epoca?"

common_voice_train['audio'][0]
>>> throws following error

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-44-8754162912fb>](https://localhost:8080/#) in <module>()
----> 1 common_voice_train['audio'][0]

11 frames
[/usr/local/lib/python3.7/dist-packages/torchaudio/backend/sox_io_backend.py](https://localhost:8080/#) in load(filepath, frame_offset, num_frames, normalize, channels_first, format)
    212             # For the special BC for mp3, we handle mp3 differently.
    213             if format == "mp3":
--> 214                 return _fallback_load_fileobj(filepath, frame_offset, num_frames, normalize, channels_first, format)
    215             ret = torchaudio._torchaudio.load_audio_fileobj(
    216                 filepath, frame_offset, num_frames, normalize, channels_first, format

NameError: name '_fallback_load_fileobj' is not defined

**Expected behavior**
common_voice[0]["audio"]
>>> {'array': array([ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
    -8.8930130e-05, -3.8027763e-05, -2.9146671e-05], dtype=float32),
'path': '/root/.cache/huggingface/datasets/downloads/extracted/05be0c29807a73c9b099873d2f5975dae6d05e9f7d577458a2466ecb9a2b0c6b/cv-corpus-6.1-2020-12-11/tr/clips/common_voice_tr_21921195.mp3',
'sampling_rate': 48000}

 - OS: Google Colab 
 - Browser: Chrome
 - Version: 103.0.5060.134

**Additional context**
If I convert the Dataset object into a pandas dataframe I can visualize the information related to each dataset feature and in the ['audio'] column there are two keys: 'bytes' (I guess instead of 'array') and 'path'.
I get the same error when I try to access the elements of the dataset in this order
common_voice_train[0]['path'] instead of common_voice_train['path'][0].

Thanks in advance!

**Comment by Heyhillary** [comment]
Hey @mozgzh 

Is there any way you can help please?

**Comment by mozgzh** [comment]
This issue might be better suited on Coqui's GH https://github.com/coqui-ai as this repo pertains to the platform level, not the ingestion of the dataset which I think this code is looking to do.
