### ISSUE TITLE
[REQUEST}] Pls HELP me out 

### ISSUE THREAD

**Issue by sanjayk0508** [common-voice/common-voice#3774]
So yesterday i cloned the repo in my local IDE, i have been trying to understand what all commands to be passed in terminal so that i can run the website on the local host.
I'm quite new to open source, but willing to learn and contribute to this projects(Frontend / UI of the website)
Pls help me out, what all commands do i need to pass in the terminal???(step by step)

**Comment by mozgzh** [comment]
Please review the development docs https://github.com/common-voice/common-voice/blob/main/docs/DEVELOPMENT.md - if there are specific issues please feel free to open a new issue. Thanks.
