### ISSUE TITLE
[BUG] Layout problem in About page

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3801]
**Describe the bug**
There is a layout problem in about page under one item as the screenshot shows. I checked a couple of locales, all had the same problem.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/about?tab=how-grow-language#playbook

**Screenshots**
![image](https://user-images.githubusercontent.com/8849617/190529956-e8a16b70-b08d-4a4f-874f-3526596daa21.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Win 10 x64
 - Browser: Checked on Chrome, Opera, Firefox, Vivaldi, Edge - all same
 - Version: All latest as of 2022-09-16

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: 1920x1080 notebook

**Comment by robovoice1** [comment]
Also on mobile:
Android13 GrapheneOs latest beta
Google Pixel 6 pro 
Vanadium Browser 

![Screenshot_20220916-214847](https://user-images.githubusercontent.com/92784377/190721630-487aef65-e762-4cdd-acb1-eea2a261ad54.png)

**Comment by Shashank-Jha** [comment]
I would like to work on the issue.

**Comment by chnuessli** [comment]
I think you can close the issue.
