### ISSUE TITLE
[BUG] Stats graph tooltip "on the run"(android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3807]
**Describe the bug**
Please watch the screen recording

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en
2. Tap on the green or red dot in graph stats 
3. Result is seen in screen recording
4. Tap the 3 dots (top right) twice to deactivate the stats graph tooltip !

**Expected behavior**
Fixed stats graph tooltip
This is a regression and was functioning before latest cv code update!

**Screenrecording**

https://user-images.githubusercontent.com/92784377/191348857-6ae66a77-0912-49ca-bba2-c38148f6dd15.mp4

**Mobile (please complete the following information):**
 - OS: Android13 GrapheneOs (latest beta)
 - Browser Vanadium
 - Version 105.0.5195.124

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by robovoice1** [comment]
Also with a freshly installed mobile firefox nightly browser
107.0a1 (Build #2015905323), 74cb0679e+
AC: 107.0.20220920190143, a8f53e4989
GV: 107.0a1-20220920092542
AS: 94.2.0

![Screenshot_20220921-190717](https://user-images.githubusercontent.com/92784377/191569644-6b323c9b-4f90-485e-ad81-9bb81f6edf3b.png)

**Comment by mozgzh** [comment]
As always, thanks for the detailed and well supported issue @robovoice1!

**Comment by robovoice1** [comment]
Fixed
