### ISSUE TITLE
[BUG] Fluent missing string: request-language-text-learn

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3821]
I met this one when I opened the console on languages page: https://commonvoice.mozilla.org/tr/languages
```
[@fluent/react] Error: The id "request-language-text-learn" did not match any messages in the localization bundles.
```

**Comment by mozgzh** [comment]
Thanks for the issue. Looks like some old translated strings are being called in one of the components on that page. Solution is to remove the infringing elements.
