### ISSUE TITLE
"Back to Top" link does not work

### ISSUE THREAD

**Issue by taylorhelene** [common-voice/common-voice#3822]
**Describe the bug**
The link at the footer of the website labelled "Back to Top" does not scroll my page back to the top.

**To Reproduce**
1. Go to  https://commonvoice.mozilla.org/en 
2. Scroll down to the footer
3. Click on 'Back to Top'

**Expected behavior**
I expect the page to scroll up after clicking the link

**Screenshots**

**Desktop or Mobile (please complete the following information):**
 - OS: [Android]
 - Browser [chrome]
 - Version [81.0.4044]

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**

**Comment by mozgzh** [comment]
Note: I've tested this on desktop (Firefox) and it works, tried it on android (Firefox) and it does not.

**Comment by dbmohit** [comment]
can i work on this

**Comment by tony83033** [comment]
HII I am new to open source,  can I work on This Issue

**Comment by robovoice1** [comment]
Tested with:
Vanadium, Bromite, FF nightly mobile/android13 and works now 😀

**Comment by Adarsh9306** [comment]
#3822  is it still open ? I am working on this issue

**Comment by ftyers** [comment]
This is now fixed.
