### ISSUE TITLE
LOCALIZATION REQUEST: udm

### ISSUE THREAD

**Issue by bogdananf** [common-voice/common-voice#3828]
Good afternoon! My name is Bogdan Anfinogenov. I'm going to translate the Common Voice interface into Udmurt. ISO 639-3 code: udm. Please give me moderator rights. Thanks.

**Comment by ftyers** [comment]
Dear @bogdananf, thank you for your request, we will get to it as soon as possible.

**Comment by ftyers** [comment]
Udmurt is already [enabled for Common Voice](https://pontoon.mozilla.org/udm/common-voice/) in Pontoon. You can start localisation. After that you will need a minimum of 750 sentences under public domain licence. @rueter do you have anything?

**Comment by ftyers** [comment]
Dear @bogdananf, you should now have translator rights. Please check and let me know.

**Comment by bogdananf** [comment]
Good afternoon! Thank you very much! And how can I check if I have rights?

**Comment by bogdananf** [comment]
That's it, I understood how, thank you, I checked

**Comment by ftyers** [comment]
Dear @bogdananf , please can you confirm it is working for you. You may need to change from "suggest" to "translate" or "review".

**Comment by ftyers** [comment]
Dear @bogdananf, 
![image](https://user-images.githubusercontent.com/449545/198694443-b1fa7744-98a0-43a3-aa0b-7b9e252addb2.png)
You appear to have submitted a blank translation (for "Contribute"). Please could you submit a translation for this.

**Comment by bogdananf** [comment]
Sorry, I've already fixed it

**Comment by ftyers** [comment]
Great!
