### ISSUE TITLE
[BUG] Unclosed tag in language string.

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3829]
**Describe the bug**
Found this in Pontoon. Could not locate in the source yet tough (pulled changes)...

**Looking for previous dataset releases? Email <emailLink> { $email } </emailLink**

GROUP COMMENT Datasets Page
CONTEXT download-dataset-access
RESOURCE [Common Voice](https://pontoon.mozilla.org/tr/common-voice/)•[web/locales/en/messages.ftl](https://pontoon.mozilla.org/tr/common-voice/web/locales/en/messages.ftl/)

**Comment by mozgzh** [comment]
Thanks for the find :rocket:
