### ISSUE TITLE
LOCALIZATION REQUEST: Bambara

### ISSUE THREAD

**Issue by roca77** [common-voice/common-voice#3830]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

**Language name**

Bambara

**Language code**

bm

**Language size**

15 million

**Plural forms**

**Pontoon manager**

https://pontoon.mozilla.org/contributors/9TGj0ZNoy3mb1_X71FE8HJTC4ZA/

**Language Script**

N'ko

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x ] Band C

1. [optional to share] Why do you want to take part in Common Voice ? I would like to take part in this initiative to save languages, and to make knowledge accessible to those who are not speakers of languages that currently hold it

**Comment by ftyers** [comment]
Dear @roca77 thank you, we have received your request and will get to it as soon as possible. For Bambara, is the N'ko script desired or the Latin script? I know one of the [biggest corpora](http://cormand.huma-num.fr/) of Bambara is written in Latin script...

**Comment by ftyers** [comment]
Bambara is now available for contribution [here](https://pontoon.mozilla.org/bm/common-voice/). Please suggest a translation and I will add you as a translator to the project.

**Comment by Malamine-Diabira** [comment]
Hello @roca77 
I am delighted for the opening of this project around the Bambara language which is my mother tongue.
As a malian data scientist , I suggest using the Latin Bambara alphabet and not the Bambara N'ko
Indeed the Latin Bambara is appropriate for several reasons:
It is much more used by Malians
-It is recognized by the Malian government
-One of the [biggest corpora](http://cormand.huma-num.fr/) of Bambara is written in Latin script as mentioned by @ftyers 
-It is easier to learn for Malians who already understand French and it is close to the French alphabet

**Comment by roca77** [comment]
> Bambara is now available for contribution [here](https://pontoon.mozilla.org/bm/common-voice/). Please suggest a translation and I will add you as a translator to the project.

Hello, 

> Dear @roca77 thank you, we have received your request and will get to it as soon as possible. For Bambara, is the N'ko script desired or the Latin script? I know one of the [biggest corpora](http://cormand.huma-num.fr/) of Bambara is written in Latin script...

Hello Tyler, yes, please use the Latin alphabet, as the N'ko is used by a smaller subset of the population.

**Comment by roca77** [comment]
> Hello @roca77 I am delighted for the opening of this project around the Bambara language which is my mother tongue. As a malian data scientist , I suggest using the Latin Bambara alphabet and not the Bambara N'ko Indeed the Latin Bambara is appropriate for several reasons: It is much more used by Malians -It is recognized by the Malian government -One of the [biggest corpora](http://cormand.huma-num.fr/) of Bambara is written in Latin script as mentioned by @ftyers -It is easier to learn for Malians who already understand French and it is close to the French alphabet

Hello Malamine, je suis content de voir un autre Malien qui est interesse a ce genre de projet.

**Comment by Malamine-Diabira** [comment]
Comment vas tu mon frère @roca77 ? Donne moi ton contact pour qu'on bosse plus ensemble sur le projet en Bamanankan 
Voici mon compte linkedIn : https://www.linkedin.com/in/malamine-diabira-505491117/

**Comment by Malamine-Diabira** [comment]
Hi Dear @afroalgo.
That's okay .I have suggest 2 translations.
I would like to know if it's possible to add mp3 audio in bambara with the
traduction in French.
