### ISSUE TITLE
LOCALIZATION REQUEST: Mədʉ̂mbὰ (byv)

### ISSUE THREAD

**Issue by math-alpha** [common-voice/common-voice#3846]
## Pontoon Set-up

**Language name:** Mə̀dʉ̂mbὰ (Medumba)  

**Language code:** byv  

**Language size:** ~300000

**Plural forms**

- Nasalisation with N and M
- Duplicating the stem e.g Ngòn -> Ngǒnngòn
- Cardinal + Noun
- Consonant transformation e.g Mɛ̀n -> bɛ̀n, lòŋ -> ndòŋ

**Pontoon manager**

**Language Script**

## Sentence Collection Requirements

**Sentence Requirement Band**

- [x] Band A

- [ ] Band B

- [ ] Band C

**Comment by ftyers** [comment]
Hi @math-alpha thanks for your interest in Common Voice! By plural forms, we mean how many plurals are there as in contexts, how would you translate:

* I see one stone
* I see zero stones
* I see many stones
* I see two stones
* I see three stones
* I see ten stones

**Comment by ftyers** [comment]
So it looks like there are three plural forms: 1, 0, other

Thanks!

**Comment by ftyers** [comment]
@math-alpha I've enabled Medumba on Pontoon: https://pontoon.mozilla.org/byv/common-voice/ Can you try making a couple of translation suggestions so I can add you as a translator?

**Comment by ftyers** [comment]
Hi @math-alpha, thanks! I have added you as a translator! Good luck! :)

**Comment by Ngue-Um** [comment]
Dear  @math-alpha,

My name is Emmanuel Ngue Um and I am currently leading a voice data collection project for under-served African languages. We are planning an [event](https://inhunumaf.hypotheses.org/964) in Yaoundé, Cameroon, very soon. The event will bring together participants representing different languages across Africa for a six-day intensive on-site data collection. Medumba has been selected as one of the languages in question. As we will be using Common Voice as the data-collecting interface, and given that you already requested Medumba to be created on Mozilla's Pontoon, we would be grateful if you would be willing to collaborate with us in this initiative. We have a team of two young enthusiasts and indigenous language champions from the Medumba community who will be joining us. They have already compiled sentences which will be used as prompts in the interface and are also working on translating the interface. We believe your collaboration in this endeavour would be invaluable, and we look forward to hearing from you.

**Comment by math-alpha** [comment]
Dear Professor, all,

I am very positive to continuing the localisation project but due to
professional constraints, I can't dedicate the required time.

Asynchronously, I will keep with the effort.

Best,
Ngadou Yopa
