### ISSUE TITLE
[BUG] Report button almost not reachable in Speak/Listen section(Vanadium)(android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3852]
**Describe the bug**
The report button is hard to reach and almost completely out of view in the "submit a report" screen.

**To Reproduce**
1. Start a record/listen session
2. Tap the report button (bottom left)
3. Screenshot 1 is presented to the contributor
4. Swipe up
5. Screenshot 2 shows fully swiped up screen on mobile

**Expected behavior**
The report button is fully visible and reachable after swiping up "submit a report" screen

**Screenshots**
![Screenshot_20221104-085236](https://user-images.githubusercontent.com/92784377/199923555-4e396389-83b4-40e3-a6e5-ed51788d9624.png)
![Screenshot_20221104-085255](https://user-images.githubusercontent.com/92784377/199923642-dee64145-5e4c-481e-933f-f118c64ef143.png)

**Mobile (please complete the following information):**
 - OS: Android 13 GrapheneOS TP1A.221005.002.2022102800
 
 - Browser Vanadium
 - Version 107.0.5304.91

 *Hardware
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

Tapping the blue top line results in going back to record /validate screen

**Comment by moz-rotimib** [comment]
Hello, @robovoice1 thanks for creating this issue. I have tried to reproduce this issue on several mobile devices but it seems I am unable to. I'm able to see the blue line but I'm still able to see the Report button when I scroll.

Could you maybe share a screen recording of this bug?

**Comment by robovoice1** [comment]
Here is a recording with vanadium and activated visible finger taps

https://user-images.githubusercontent.com/92784377/200294062-c5869054-1286-4384-9f18-2b1aec4aeef8.mp4

**Comment by robovoice1** [comment]
Also with a new installed ffnightly
108.0a1 (Build #2015914347), 3b85861a0+
AC: 108.0.20221106143258, d9f43f22c5
GV: 108.0a1-20221105092350
AS: 94.3.2


https://user-images.githubusercontent.com/92784377/200298651-4e1ff19d-9c63-43d2-bdae-24376743d7e0.mp4

**Comment by robovoice1** [comment]
To make the confusion perfect (for me):
With the newest ff nightly android swiping further is possible now 
108.0a1 (Build #2015915403), 3d1e6b4ee+
AC: 108.0.20221112143158, 3a2ecddad8
GV: 108.0a1-20221112094729
AS: 95.0.1
.....but with vanadium the prob still exists -=> changed the title.

**Comment by robovoice1** [comment]
Report button is now fully reachable with Vanadium browser by swiping  up (and readable) since update 1.86
