### ISSUE TITLE
[BUG] Languages string not translated in CV, missing in pontoon

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3853]
**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/languages
2. Change to another language 
3. Repeat step 2

**Expected behavior**
The string Languages is translated for all languages

**Screenshots**
![Screenshot_20221107-234422](https://user-images.githubusercontent.com/92784377/200432188-4165a058-a5ec-4aec-9f43-eba9a35c0f6a.png)
![Screenshot_20221107-234404](https://user-images.githubusercontent.com/92784377/200432267-850c26f5-2415-4f3c-aa71-1011ba9c4106.png)
![Screenshot_20221107-234340](https://user-images.githubusercontent.com/92784377/200432314-38f0a6b8-221c-4681-9988-3359dd163749.png)
![Screenshot_20221107-234312](https://user-images.githubusercontent.com/92784377/200432405-8ce7b656-8613-4066-8cfd-6a142cdc5dc4.png)
Screenshots en,de,es,fr

**Additional context**
I could not find this string in pontoon. The search gave the name of every language, also downloaded the 2 files from pontoon, but text editor crashes on smartphone 🤬

**Comment by mozgzh** [comment]
Thanks for the detailed bug report @robovoice1! This specific string `Languages` isn't properly rendered (Not making use of our localization component). It can be found here: https://github.com/common-voice/common-voice/blob/dd61df63e1e081accc4ce8f3d390d116b58ab99f/web/src/components/pages/profile/info/languages/languages.tsx#L82


The fix would look something like this: 
 ``` HTML
<Localized id="languages">
    <h2 />
  </Localized>
```
