### ISSUE TITLE
[BUG] Double speed clips recorded with smartphone (Vanadium)(android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3855]
**Describe the bug**

Recently i have !massive! problems contributing clips for CV. Usually the last 2 out of the 5 recorded clips are at double speed (full clip in double speed or starting to change the speed in the middle of the recorded clip) in the gernan section or when re-recording a sentence in the english section.
Sounds funny, but useless for the corpus.
This behavior is constant, so 3 clips max contributing is possible without this effect.

**To Reproduce**
1. Record 5 sentences https://commonvoice.mozilla.org/en/speak
2. Listen to your 5 recordings
3. Usually clip 4 and 5 are at double speed in the german section
4. Re-recording clip 4 and 5 does not solve this (new recorded clip also at double speed)
5. In english section on re-recording a sentence this effect appears

**Expected behavior**
5 clips are recorded and replayed at normal speed with android smartphones

**Screenshots**

**Mobile (please complete the following information):**
 - OS: [e.g. iOS] Android 13 GrapheneOS latest beta
 TP1A.221105.002.2022110800
 - Browser Vanadium
 - Version [e.g. 22] 107.0.5304.91

 **Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Google Pixel
 - Model:6 pro
 No headphones/BT plugs used 

**Additional context**

This can also be Google Pixel related. In the past there have been issues with mic/bt.
In validation i downvoted many double speed clips in the english language from about 4 different other contributers.
No additional apps/add ons/voice scramblers used on my side.

**Comment by robovoice1** [comment]
Here an example/screenrecording of this effect in german language with captured audio


https://user-images.githubusercontent.com/92784377/200864315-e387fd7d-c77a-47ef-9b1b-06b612eb121b.mp4

**Comment by robovoice1** [comment]
Here an example with a new installed Ff nightly android- no add ons activated and no headphones/bt plugs used

108.0a1 (Build #2015915115), fbea76df7+
AC: 108.0.20221110143111, f6b2e4c032
GV: 108.0a1-20221110092309
AS: 95.0.1

https://user-images.githubusercontent.com/92784377/201341246-a65ac90f-afc0-47aa-a990-ee8121ad35ab.mp4

**Comment by orrc** [comment]
I have a similar problem in Chrome 107 (arm64) on macOS 12.6 (21G115).

After making five or six recordings, playing back any of those clips sounds garbled and as if they're at ~1.5x speed — i.e. not the incredibly fast speed from the [first video](https://github.com/common-voice/common-voice/issues/3855#issuecomment-1308893526) above. But otherwise similar.

Subsequently playing back clips that were recorded earlier, they remain unaffected.

Refreshing the page fixes this recording issue, typically for the next five recordings.

**Comment by robovoice1** [comment]
Thanks for the feedback 👍
Chrome and Vanadium are both based on Chromium.

**Comment by robovoice1** [comment]
Also reported in bugs.chromium.org -=> Status Assigned(open), pri 3 😀

**Comment by razmikb** [comment]
I have encountered a few similar issues when listening to the Georgian recordings.

**Comment by robovoice1** [comment]
The core funtion (contributing voice clips) is functioning again for me since the latest GOS beta channel OTA update TQ1A.221205.011.2022121400! Just donated 200 clips with Vandium browser (108.0.5359.128) without reloading Cv or any tempo effects 😁
