### ISSUE TITLE
[BUG] (en) message displayed with Firefox in (de) speak/listen when reporting an error (Firefox)(android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3859]
**Describe the bug**
Please watch  Screenshot 1+2, ttaken with latest Firefox nightly browser

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/de/speak
2. Report an error in a sentence
3. After reporting the english " Success" message is displayed for 1 second, screenshot 2
4. After Success message a green circle with a hook is presented to the contributor, screenshot 1
5. Same behavior in german listen section with Firefox nightly android browser

**Expected behavior**
1. No "Success" message is displayed ( like with Vanadium browser) or
2.  A translated message is displayed

**Screenshots**
![Screenshot_20221112-184516](https://user-images.githubusercontent.com/92784377/201488904-d1f54713-8b7d-467f-bb95-e63a927e5a51.png)
![Screenshot_20221112-184459](https://user-images.githubusercontent.com/92784377/201488914-490e7bc4-64a8-40a5-bc4b-0e168cc9dcc8.png)

**Mobile (please complete the following information):**

 - OS: [e.g. iOS] Android13 GrapheneOS
 TP1A.221105.002.2022111000
 - Browser Firefox nightly android
 - Version [e.g. 22]108.0a1 (Build #2015915307), 2aa79d30d+
AC: 108.0.20221111143147, 3c7d5a08ba
GV: 108.0a1-20221111093717
AS: 95.0.1

 *Hardware :**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**
In Vanadium the screen  is displayed without "Success" message, only the green circle with hook

**Comment by moz-dfeller** [comment]
Awesome work @robovoice1 ! What you saw, was the `alt` attribute of the image tag. It shows up, when the image doesn't load. In the future there will be a translated description! This issue is fixed by #3902
