### ISSUE TITLE
[BUG] sha256 checksum in Datasets is way too long to fit the page (android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3860]
**Describe the bug**
Watch the screenrecording

**To Reproduce**

1. Go to https://commonvoice.mozilla.org/en/datasets
2. Go down the page to sha256 checksum
3. Swipe to the right

**Expected behavior**

0efd86ca6b40641b55d1411b7d3b1f1ab8626de4b207504953706df201d198a5
Is fitting the page and light brown box without swiping to the right. (Like the copy and pasted checksum in this textbox right here on gihub when filing a bug) 

Or another possibility could be:
Make the "sha256 checksum" a blue link.
When tappin/clicking on it,  the checksum is copied to the clipboard. The copied  checksum can be pasted in a text editor to compare.

**Screenrecording**

https://user-images.githubusercontent.com/92784377/201498310-00950e15-df23-4cbe-8532-bdc808e39d59.mp4

**Mobile (please complete the following information):**
 - OS: Android 13 GrapheneOs latest beta channel
 - Browser [e.g. chrome, safari] All tested browsers vanadium, ff nightly, bromite
 - Version [e.g. 22] latest versions

 **Hardware :**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by mozgzh** [comment]
Thanks for the issue! 

A possible solution could be to wrap the SHA in a X-axis scrollable component so it wouldn't overflow (which is causing the whole page to be horizontally scrollable).

**Comment by moz-rotimib** [comment]
This issue has been fixed in this PR #3901
