### ISSUE TITLE
LOCALISATION REQUEST:  Wolof Language

### ISSUE THREAD

**Issue by DerXter** [common-voice/common-voice#3861]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
Wolof

**Language code**
wo

**Language size**
16 millions of speakers (according to Wikipedia)

**Plural forms**
0 rocks -> Tus ci xeer (no rocks)
1 rock -> Benn xeer
2 rocks -> Ñaar i xeer
3 rocks -> Ñett i xeer
4 rocks -> Ñent i xeer
5 rocks -> Juróom i xeer
10 rocks -> Fukk i xeer
20 rocks -> Ñaar fukk i xeer
100 rocks -> Téeméer i xeer
1000 rocks -> Junni i xeer
I see 0 rocks on the ground -> Gisuma benn xeer ci suuf (I see no rocks on the ground)
I see 1 rock on the ground -> Gisnaa benn xeer ci suuf
I see 10 rocks on the ground -> Gisnaa fukk i xeer ci suuf
I see rocks on the ground -> Gisnaa ay xeer ci suuf

**Pontoon manager**
[Derguene MBAYE](https://pontoon.mozilla.org/contributors/Derguene/)

**Language Script**
- Latin: Left to right (official script)
- Wolofal (Ajami): Right to Left (based on Arabic script, first script for writing Wolof, less used)

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
 * With the growing interest in AI and Natural Language Processing, we want to put Wolof on the NLP map and contribute to the development of NLP research in this language.
 * Also, since Wolof is not taught at school in Senegal, the language has long attracted little interest. However, a renewed interest has been noted in recent years and we wish to contribute to the development of this language through the creation of resources.

3. [optional to share] Would you like to have a follow up conversation regarding community building ?
 * Yes

**Comment by ftyers** [comment]
Dear @DerXter, I have added Common Voice to Wolof on Pontoon: https://pontoon.mozilla.org/wo/common-voice/ Please suggest a translation and I will add you as translator. You might want to get in contact with one of the [existing translators](https://pontoon.mozilla.org/contributors/1GSCvzIgu4cLD5vtRxqFD83BBWM/). Also feel free to join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by ftyers** [comment]
I've added you as a translator, you should now be able to make translations directly. You will also need to add 2000 Wolof sentences that are public domain to [sentence collector](https://commonvoice.mozilla.org/sentence-collector/) and review them. Please feel free to get in contact if you have any questions.

**Comment by DerXter** [comment]
Roger,
Thank you very much.
