### ISSUE TITLE
LOCALISATION REQUEST: Tuvan language

### ISSUE THREAD

**Issue by gaydmi** [common-voice/common-voice#3862]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
Tuvan 

**Language code**
tyv

**Language size**
240000

**Plural forms**
One, other

**Pontoon manager**
https://pontoon.mozilla.org/contributors/je7vcpLg4CFRj_E0aIsPMU4pirQ/

**Language Script**
Cyrillic

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Dear @gaydmi are you a speaker of Tuvan, or do you have a Tuvan speaker involved? Could you ask them to comment here?

**Comment by gaydmi** [comment]
Hello, I'm helping them with the text corpus. Yes, it's a speaker of Tuvan from Tuvan Institute for Humanitarian and Applied Research.

**Comment by ftyers** [comment]
Ok great, could you ask them to make a couple of translations so I can add them as manager? Also, please feel free to join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) and there are also two Turkic working groups on Telegram: [Turkic Interlingua](https://t.me/joinchat/WRFz62nYdmJ1uo1L) and [Turkic++ LR](https://t.me/+4Rlr3cfhhig1NWM8) that you both might like to join -- English, Russian and Turkish are working languages.

**Comment by gaydmi** [comment]
Hey, script should be cyrillic, not latin

**Comment by ftyers** [comment]
Well spotted, thanks fixed.

**Comment by ftyers** [comment]
I saw you added some translations, could you ask the translator to also add some? Thanks!

**Comment by gaydmi** [comment]
@ftyers He just did some translations.

**Comment by ftyers** [comment]
I have added him as a translator, he should now be able to add translations directly. Good luck and see you on Matrix!
