### ISSUE TITLE
[BUG] Translated recorded hours in Datasets overlapping the amount of recorded hours (de)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3866]
**Describe the bug**
The gernan translation "Aufgenommene Stunden" (recorded hours) is overlapping the 22.
Screenshot1

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/datasets
2. Swipe to Version - Common Voice Delta 11.0 (light blue box)
3. Change from english CV ui to german
4. Result is Screenshot 1

**Expected behavior**
Clear readable amount of recorded hours -=> 22

**Screenshots**
![Screenshot_20221120-212757_1](https://user-images.githubusercontent.com/92784377/202926209-53667015-9f2a-477e-b500-99f32f89513e.png)
![Screenshot_20221120-214524_1](https://user-images.githubusercontent.com/92784377/202926240-2eea4edb-1f31-4c52-9871-4f6819e9d39d.png)

**Mobile (please complete the following information):**
 - OS: Android13 GrapheneOS latest beta channel release
 - Browser Vanadium
 - Version 107.0.5304.105

 **Hardware **
 - Type: Google Pixel
 - Model:6 pro

**Additional context**

Due to the fact that i do not know a shorter term for "recorded hours" in german, moving everything a little bit to the right could do the trick. Please see screenshot 2!

**Comment by robovoice1** [comment]
Just found and proposed a shorter string for recorded hours. Instead of:
Aufgenommene Stunden
Erfasste Stunden 

https://pontoon.mozilla.org/de/common-voice/web/locales/en/messages.ftl/?search=Aufgenommene&string=189635

Waiting for approval 😃

**Comment by koehlermichael** [comment]
Thanks @robovoice1, I just approved your suggestions, hopefully it works.

**Comment by robovoice1** [comment]
Solved
