### ISSUE TITLE
LOCALISATION REQUEST: 

### ISSUE THREAD

**Issue by clcneogeek325** [common-voice/common-voice#3879]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

nahuatl

**Language code**

nah

**Language size**

1,651,958

**Plural forms**

yoncë tetl
cë tetl
öme tetl
ëyi tetl
nähui tetl
mäcuïlli tetl
mahtlactli tetl
cem-pöhualli tetl
mäcuïl-pöhualli tetl
mil tetl
nikita yoncë tetl ipan in tlali
nikita cë tetl ipan in tlali
nikita mahtlactli tetl ipan in tlali
nikita tetl ipan in tlali
**Pontoon manager**

https://pontoon.mozilla.org/contributors/8y8O3gK1T58oSx7IAzwX7eXe9mc/
**Language Script**

Latin

## Sentence Collection Requirements

>On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

Band B

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
   Because I speak nahuatl and not exist any dataset for nahuatl text-audio.
2. [optional to share] Would you like to have a follow up conversation regarding community building ?
Yes.

**Comment by ftyers** [comment]
Dear @clcneogeek325 thanks for your interest in Common Voice. I suggest band A for the sentence requirement, that would be 750 sentences. As per our conversation on Matrix I have added `nhe`, Eastern Huasteca Nahuatl instead of the `nah` macrolanguage. You should be able to start making translations [here](https://pontoon.mozilla.org/nhe/common-voice/). Tasokamatiktsin por mointeres!

**Comment by clcneogeek325** [comment]
@ftyers tnx for all.
