### ISSUE TITLE
[BUG] Clip upload error message not fully translated, no search results in pontoon (de)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3888]
**Describe the bug**

Not fully translated clip upload error message (de)
Also no search results of this string in pontoon/cv
"Upload of this clip keeps failing, keep retrying?"
-=> see screenshot

**Expected behavior**

Fully translated error message in selected german language

**Screenshots**
![Screenshot_20221217-165003](https://user-images.githubusercontent.com/92784377/208251061-07221075-3620-4818-8f3f-976962210426.png)

**Mobile (please complete the following information):**
 - OS: Android13 GrapheneOS latest beta channel release
 - Browser Vanadium
 - Version 108.0.5359.128

 *Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by mozgzh** [comment]
Missing translation strings that needs to be added and updated in the component

**Comment by farhanalws4u** [comment]
hello @robovoice1, I hope you are doing well. can I work on this issue?

**Comment by AAYUSH-droid** [comment]
Hey can you explain this issue again.

**Comment by emlewjong** [comment]
I'm the Product Lead for Common Voice - thank you so much for your patience. We will have more community support joining in a couple of weeks, and their first priority will be making sure your request is followed up!

**Comment by moz-dfeller** [comment]
Hey! Thank you for reporting @robovoice1! The issue should be fixed once the code changes in #3902 go live 🚀
