### ISSUE TITLE
LOCALISATION REQUEST: Náhuatl de la Sierra oeste de Puebla

### ISSUE THREAD

**Issue by Lguyogiro** [common-voice/common-voice#3889]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Náhuatl de la Sierra oeste de Puebla

**Language code**

nhi

**Language size**

17,100

**Plural forms**

0 rocks = amo tlen titl
1 rock = ce titl
2 rocks = ome titl
3 rocks = yeyi titl
4 rocks = nahui titl
5 rocks = macuil titl
10 rocks = mahtlactl titl
20 rocks = cempoal titl
100 rocks = macuil cempoal titl
1000 rocks = ome tzontli huan mahtlactl cempoal titl
I see 0 rocks on the ground = amo tlen niquita in titl ich in tlali
I see 1 rock on the ground = niquita ce titl ich in tlali
I see 10 rocks on the ground = niquita mahtlactl titl ich in tlali
I see rocks on the ground = niquita titl ich in tlali

In many Nahuatl varieties, inanimate nouns are not pluralized. In order to demonstrate the plural form, see similar sentences below with an animate noun (dog).

0 dog = amo tlen itzcuintli
1 dog = ce itzcuintli
2 dogs = ome itzcuimeh
I see 0 dogs on the ground = amo tlen niquita in itzcuintli ich in tlali
I see 1 dog on the ground = niquita ce itzuintli ich in tlali
I see 10 dogs on the ground = niquita mahtlactl itzcuimeh ich in tlali
I see dogs on the ground = niquimita itzcuimeh ich in tlali

**Pontoon manager**

https://pontoon.mozilla.org/contributors/U5ydx6QSh3xmwPHAR7HyKdMIIxQ/

**Language Script**

Latin

_Orthography_ The orthography used in the above examples (and that planned for the localization and CV sentences) follows the written standards established by a joint effort of nhi-speaking communities in and around San Miguel Tenango, Zacatlán, and the Summer Institute of Linguistics (SIL) in 2003. Its distinguishing characteristics are the following:

- "s" for /s/
- "c" and "qu" for /k/
- "h" for /h/
- "u" for /w/
- "tz" for /ts/
- "cu" for /kw/

This orthography is also consistent with the subsequent literature published by indigenous authors in collaboration with the SIL in the 2000s and 2010s.

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x ] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. Why do you want to take part in Common Voice? To promote the development of open, inclusive language technology and data.  

2. Would you like to have a follow up conversation regarding community building? Yes.

**Comment by emlewjong** [comment]
I'm the Product Lead for Common Voice - thank you so much for your patience. We will have more community support joining in a couple of weeks, and their first priority will be making sure your request is followed up!

**Comment by ftyers** [comment]
Hi @Lguyogiro it's [set up in Pontoon](https://pontoon.mozilla.org/nhi/common-voice/) and I see you are already localising. Let me know if you have any questions!
