### ISSUE TITLE
[BUG] Error messages with validation and recording

### ISSUE THREAD

**Issue by adina-v** [common-voice/common-voice#3890]
We are having issues with validating voice clips in Galician. Users who are reviewing a larger amount of clips get a message in Galician (and, more recently, Portuguese) stating that there are no more clips available for review.
Usually, switching between reviewing and recording did the trick and new clips were available again, but recently we are getting error messages in English and users have to log out and then log back in in order to be able to get more audios to review.

![Erro portugués_tras varios_esgotamos os fragmentos](https://user-images.githubusercontent.com/96519317/209479077-a720b027-2c4c-4b6a-83d8-555602a4104f.jpg)

Other error messages in English and Galician come up while recording (page crashing):

![erro 2](https://user-images.githubusercontent.com/96519317/209479017-74739790-d543-449d-b404-3e30f2ce0ee9.jpg)
![erro 3](https://user-images.githubusercontent.com/96519317/209479020-9df01071-d224-41d9-95dd-2220b295d0ee.jpg)

Is there any way to get rid of these bugs?

p.d.: Updated to remove user data from screenshots.

**Comment by robovoice1** [comment]
Since the 1.86 CV update, also the english and german validation process is slowed down.
After every 5 validated clips there is the no more clips and result page displayed.

**Comment by AigizK** [comment]
For Bashkir and Mari we also get a message that there are no more entries to check.
You can play like this:
- listen to 5 examples
- after 5 records, you had to press the send record button before. now this page is shown for a short time and then disappears. the text "Out of recorded voices" is shown instead

**Comment by Ramblurr** [comment]
> Users who are reviewing a larger amount of clips get a message in Galician (and, more recently, Portuguese) stating that there are no more clips available for review.
> Usually, switching between reviewing and recording did the trick and new clips were available again, but recently we are getting error messages in English and users have to log out and then log back in in order to be able to get more audios to review.

I am experiencing the same thing for English.

**Comment by emlewjong** [comment]
I'm the Product Lead for Common Voice - thank you so much for your patience. We will have more community support joining in a couple of weeks, and their first priority will be making sure your request is followed up!

**Comment by emlewjong** [comment]
Hey - I'm EM, I lead MCV over at Mozilla :) Thanks everyone - I'll triage investigation into this into the coming sprint.
