### ISSUE TITLE
[BUG] Cannot resume to download large datasets.

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3891]
**Describe the bug**

This happens when you try to download a large dataset with not so great connection. The cause is the new AWS tokens and their timeout duration.
I've been using (and want to continue to use) a download manager for automatic continuation in case of line drops. I have 100 Mbps cable Internet, but it can have short drops randomly, no internal reasons. The download manager tries to continue after a few seconds, but because of the token timeout, it errors out. One needs to restart the download, giving away a lot from their quota. It also prevents queuing a couple of languages you are working on.

Please fix this, not everyone has speedy and super-stable connections. I'm trying to download the French dataset for the fourth time.

**To Reproduce**

1. Use a slow connection or slow down your connection via developer tools.
2. Start downloading a large dataset.
3. After the timeout period (20 min?) disconnect the connection temporarily and reconnect.
4. See the 400 error 

Better method: Use a download manager and slow down your speed.

**Expected behavior**

Datasets should be downloadable regardless of the user's connection capacity and quality. The resume feature is a must for large datasets.

**Screenshots**

(From Free Download Manager)

![image](https://user-images.githubusercontent.com/8849617/209020753-541f8677-1916-4a0a-b885-4457c0cb90e0.png)

![image](https://user-images.githubusercontent.com/8849617/209019000-658c8fb0-0a12-4dd1-a215-1359a6726cd4.png)

**Comment by HarikalarKutusu** [comment]
I'm solving my issue by staying at the computer for a long time (and updating the link every time the error occurs) and also upgrading my package to unlimited. But, here are some calculations.

Suppose:
- You have a 3G connection or a shared Internet where your DL is limited to 3 MB/sec
- There are intermittent disconnections to the server (for any reason)
- You are downloading English v12.0 dataset (which is  75.4 GB) to see the current limit
- You are using a DL manager to overcome disconnection and continue the download with resume support

Download without any interruptions and ignoring package overhead, the download will take ~430 minutes (>7h).
If the token time is 20 min, there is a possibility for you to re-enter the DL link 21-22 times.
For this, you need to stay in front of your computer, see the error, browse to the dataset, regenerate a new link, copy it and enter that into the "Update download" link given in the above image.

Until now, I did not work with larger datasets and did not encounter this problem. But whenever I started to work on a multi-lingual project, I had to DL major western languages, which became a pain.

**Comment by emlewjong** [comment]
I'm the Product Lead for Common Voice - thank you so much for your patience. We will have more community support joining in a couple of weeks, and their first priority will be making sure your request is followed up!

**Comment by HarikalarKutusu** [comment]
After the Google Cloud migration, this bug become irrelevant.
Closing.
