### ISSUE TITLE
[BUG] In the new DL page, AWS tokens are sometimes not generated

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#3892]
**Describe the bug**
This happens on the new dataset download page, when trying to download an older version.
It happens sometimes (~10% of the time).
The generated DL link is in the format `https://<server>/<path-to-dataset>?<AWS-token-info&parameters>`
When this happens, only the server link is generated, thus if clicked, it opens an information page on AWS.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/datasets
2. Fill your info
3. Select among the older datasets (en, es, etc) to get a larger list to work on
4. Click on older versions
5. Check the link visually by hovering the DL button.
6. Repeat 3-5 until you see a link without the necessary full DL link

It seems there is a problem with timing / a race condition, e.g. await etc.

**Expected behavior**
A working DL link should be generated.

**Comment by emlewjong** [comment]
I'm the Product Lead for Common Voice - thank you so much for your patience. We will have more community support joining in a couple of weeks, and their first priority will be making sure your request is followed up!

**Comment by HarikalarKutusu** [comment]
After the Google Cloud migration, this bug become irrelevant.
Closing.
