### ISSUE TITLE
[BUG] Sentence Collector export failing due to push permissions

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/common-voice#3897]
The Sentence Collector export to the CV repo is failing since this week due to a 403 when trying to push: https://github.com/common-voice/sentence-collector/actions/runs/3834882810

This worked in last weeks export job.

Might it be that I'm missing write permissions now? Happy to adjust this if you wanna do another way of doing this.

**Comment by moz-dfeller** [comment]
Hey @MichaelKohler ! I changed your permissions. Could you try again?

**Comment by MichaelKohler** [comment]
Hi there, thanks for the change. Looks like that helped:

- Action: https://github.com/common-voice/sentence-collector/actions/runs/3856964128/jobs/6573812974
- Commit: https://github.com/common-voice/common-voice/commit/0c9ff25cf2de84e278e976f48c8c74a8d89b8152
