### ISSUE TITLE
[BUG] rare disappearing of the 5 recorded sentences when going back in summary (mobile)(android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3905]
**Describe the bug**

During a record session i recorded 5 sentences in the german section. After tapping the back button instead of submitting (left arrow, top left) the sentences "disappear".
I managed to record this, this effect is rare, but i had this with Fenix and Vanadium browser while recording  
100 clips with each, and within this 100 recorded clips this happened once.
For some reason the screen, where the contributor can choose to continue, submit or delete the clips is not always displayed.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/de/speak
2. Record 5 sentences
3. Tap the back button
4. Sentences are gone (but not always!)

**Expected behavior**
The screen to choose to continue recording, submit the clips or delete the recorded clips is always shown when going back!

**Screenrecording**

https://user-images.githubusercontent.com/92784377/212164088-69ca7178-937e-4025-bd93-ff094b4d593b.mp4

**Mobile (please complete the following information):**
 - OS: Android13 GrapheneOs latest beta release
 - Browser Firefox nightly android
 - Version 110.0a1 (Build #2015927019), 98f1c9c8b+
AC: 110.0.20230112011408, d574f83dd2
GV: 110.0a1-20230111215657
AS: 96.2.1

 ** Hardware :**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**
Also happened with Vanadium browser latest version (also rare)

**Comment by moz-rotimib** [comment]
Thanks for reporting this bug. At the moment I'm not really able to reproduce but I'll try to run this flow repeatedly to see if I have any luck reproducing

**Comment by robovoice1** [comment]
This is now solved for me with 1.88 release.
