### ISSUE TITLE
[BUG] CV faq link broken

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3921]
**Describe the bug**
When tapping  on faq on the left bottom of cv the resulult is pic1

**To Reproduce**
1. Go to '...'https://commonvoice.mozilla.org/en/faq

**Expected behavior**
Working link to the cv faq

**Screenshots**
![Screenshot_20230120-171251](https://user-images.githubusercontent.com/92784377/213755858-09ad5b03-82cb-4eec-b005-2381c056ddb6.png)

**Comment by moz-rotimib** [comment]
@robovoice1 thank you for reporting this issue. The FAQ page has been removed from Common Voice and now redirects to the About page. You can find out more in the [release notes](https://github.com/common-voice/common-voice/releases/tag/release-v1.88.1)
