### ISSUE TITLE
[BUG] v12 dataset release for `en` does not include accent data from speakers

### ISSUE THREAD

**Issue by KathyReid** [common-voice/common-voice#3942]
**Describe the bug**
In the v12 release of the Common Voice dataset in English (`en`) - I haven't checked for other languages, there is is no **accent** data in the `validated.tsv` files, or any of the other split files (such as `train.tsv`). I am using the accent data for research purposes. 

If I compare to the v11 release, the accent data for `en` is provided in a field of the `validated.tsv` file in comma separated form, e.g.: 

```
'United States English, Midwestern United States English'
```

None of this data is provided in the v12 dataset release. 

I identified this by working in `pandas` - my working Jupyter notebook is at: 
[https://github.com/KathyReid/cvaccents](https://github.com/KathyReid/cvaccents)

There is a 0 row count for "rows with accents" in v12, compared with 

v12 `validated.tsv` file in a `pandas` dataframe:
```
# rows that have accent metadata 
len(df[df['accents'].notna()])
0
```

same in v11 `validated.tsv` file: 
```
# rows that have accent metadata 
len(df[df['accents'].notna()])
861134
```

**To Reproduce**
As described above, please compare `validated.tsv` for v11 versus v12 of the `en` corpus.

**Expected behavior**
Accent data to be included in `validated.tsv`, please 😄 🙏🏾 

**Screenshots**
Not needed here, but can provide if needed.

**Desktop or Mobile (please complete the following information):**
Not applicable to this bug. 

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
Not applicable

**Additional context**
I am researching voice accent data, and want to replicate my workflow on v12 of the data (I have a workflow for examining v11 of the `en` dataset).

**Comment by HarikalarKutusu** [comment]
I checked last few Turkish datasets. There is no accent data on v12, but previous ones had them.

As it is (freehand), it is not much of a use for me, at least for Turkish thou...

**Comment by KathyReid** [comment]
Thank you for confirming the bug is present for `tr`, @HarikalarKutusu.

**Comment by KathyReid** [comment]
@HarikalarKutusu the work I am doing is designed to help with freehand / freely specified accents, and applies a set of heuristics to make working with them easier: 

https://github.com/KathyReid/cvaccents

**Comment by HarikalarKutusu** [comment]
@KathyReid, very interesting indeed, thank you for sharing. For Turkish we don't have so many different entries yet, but some are like "good" (might mean Istanbul Turkish), or "I cannot pronounce r" (speech deficiency), "g k problem" (locates the user to Central Anatolia) . Only a few have location references... In fact, a look-up table can easily re-map them in our case - probably with some help from local linguists - I'm not a linguist myself...

Maybe this is not the place for a discussion, but we have many immigrants, Turkish citizens having Turkish as a second language etc. L1/L2 & double L1 languages etc are more of a concern here. The dataset also reflects this (many apparently Slavic origin users, Germans etc). If you don't mind, I'll jump into your Discussion area after I analyzed the code.

**Comment by KathyReid** [comment]
I warmly welcome your feedback and discussion! 
Our hope is that this taxonomy / heuristics can also be helpful for other languages.

**Comment by jessicarose** [comment]
Hello! There is indeed a bug in the current dataset, where accent data has not been included. We've investigated this and found that this is a valid bug, impacting multiple language sets. Our engineers are currently working to address this and we hope to have the bug fixed in upcoming releases. 

I understand that bugs impacting data availability can make things especially challenging for researchers and I do apologize for the delay in making this data available to you.

We'll aim to get this fixed as quickly as possible. I really appreciate you raising this issue.

**Comment by KathyReid** [comment]
Thank you so much, @jessicarose! 🎉

**Comment by jessicarose** [comment]
Thanks so much again for raising this issue, helping make us aware of the missing accent data. We've just pushed the 13.0 dataset which should have fixed this bug and has accent data available in the new dataset. Thank you so much for your patience and I'll close this as resolved.

**Comment by KathyReid** [comment]
Thanks so much @jessicarose, I am confirming this bug is successfully squashed from my side too: 

```
# rows that have accent metadata 
len(df[df['accents'].notna()])
907238
```

This figure is as expected. Thank you team! 🎉
