### ISSUE TITLE
Tibetan language request

### ISSUE THREAD

**Issue by kaldan007** [common-voice/common-voice#3943]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Tibetan

**Language code**

Bo

**Language size**

8 million

**Plural forms**

0 rocks=>རྡོ་ཀླད་ཀོར།
1 rock=>རྡོ་གཅིག།
2 rocks=>རྡོ་གཉིས།
3 rocks=>རྡོ་གསུམ།
4 rocks=>རྡོ་བཞི།
5 rocks=>རྡོ་ལྔ།
10 rocks=>རྡོ་བཅུ།
20 rocks=>རྡོ་ཉིཤུ།
100 rocks=>རྡོ་བརྒྱ།
1000 rocks=>རྡོ་ཆིག་སྟོང།
I see 0 rocks on the ground=>ངས་ས་སྟོང་ལ་རྡོ་ཀླད་སྐོར་མཐོང་བྱུང།
I see 1 rock on the ground=>ངས་ས་སྟོང་ལ་རྡོ་གཅིག་མཐོང་བྱུང།
I see 10 rocks on the ground=>ངས་ས་སྟོང་ལ་རྡོ་བཅུ་མཐོང།
I see rocks on the ground=>ངས་ས་སྟོང་ལ་རྡོ་མཐོང་བྱུང།

[**Pontoon manager**](https://pontoon.mozilla.org/contributors/kaldan007/)

**Language Script**

Tibetan script 

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
I am Tenzin Kaldan. I am a Tibetan refugee residing in India. I am currently working for a Tibetan language Technology company called Monlam. At Monlam, we are planning to train a Tibetan speech-to-text model. Collecting training data on our own is becoming way too expensive. Hence we would like to collaborate with your company and request our community to contribute. 

2. [optional to share] Would you like to have a follow up conversation regarding community building ?
Yes

**Comment by ftyers** [comment]
Dear @kaldan007, the good news is that Tibetan is [already in](https://pontoon.mozilla.org/bo/) Pontoon. I have added Common Voice to the Tibetan team, and you can access it [here](https://pontoon.mozilla.org/bo/common-voice/).  

You will need to collect 2000 public domain sentences and add them to [sentence collector](https://commonvoice.mozilla.org/sentence-collector). 

Please feel free to get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
