### ISSUE TITLE
Request for isiZulu dataset

### ISSUE THREAD

**Issue by bonaventuredossou** [common-voice/common-voice#3958]
Hello,

Is there a way I can access, and download the isiZulu dataset on Common Voices? I could see it here https://pontoon.mozilla.org/zu/common-voice/ but I do not know how to download it

**Comment by ftyers** [comment]
Dear @bonaventuredossou , thanks for your interest in Common Voice. Zulu is not yet available for collecting contributions. The interface has been translated, but we are still waiting for sentences to be added. There are currently around 0 sentences validated in sentence collector and 1396 total sentences. You can participate in the validation of sentences in [sentence collector](https://commonvoice.mozilla.org/sentence-collector/). Please get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) or on [Discourse](https://discourse.mozilla.org/c/voice/239) if you have any further questions.
