### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by dmatekenya** [common-voice/common-voice#3962]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>
The language has already been setup on Pontoon: https://pontoon.mozilla.org/ny/

**Language name**: *Chichewa* or *Chinyanja*. Here I would like to suggest that the name be changed to Chichewa as thats how its indicated in ISO and also majority of people who speak the language call it that. 

**Language code**: ny 

**Language size**: 20-25 million. I'm accessing data to get a more exact number. 

**Plural forms**: Please check Pontoon url 

**Pontoon manager**:  Refer to https://pontoon.mozilla.org/ny/

**Language Script**: Refer to https://pontoon.mozilla.org/ny/

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**: Band C

- [ ] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?2. 
I'm a native speaker of this language-Chichewa. I come from Malawi. I'm currently leaving in the USA. I'm a Data Scientist and I'm very interested in Speech Recognition technology as a hobby at this point and would like to contribute to advancement of ASR models for this language.
3. [optional to share] Would you like to have a follow up conversation regarding community building ?
Yes, I would love that.

**Comment by ftyers** [comment]
Dear @dmatekenya , thank you for your interest in Common Voice. I have enabled Chichewa [on Pontoon](https://pontoon.mozilla.org/ny/common-voice/). Please feel to get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) for further assistance!
