### ISSUE TITLE
[BUG] Pashto (ps) import into CV database failed

### ISSUE THREAD

**Issue by ihanif** [common-voice/common-voice#3965]
**Describe the bug**
We have around 1053 validated sentences for the Pashto language in the sentence collector. They were imported into CV data folder via this PR:
https://github.com/common-voice/common-voice/commit/beded84af8fa6a45632b98762b1327294946cb59#diff-f4f1cb32ce5a2d3138755d8920d9fbdee10e4c44b257e7cc16dac743cd268cce

After that import, these sentences should be available in the CV, but it's not the case. CV still shows only three valid sentences, rather than all of 1053.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/languages
2. Enter `ps` in the search bar on the right
3. Scroll down to see `Pashto` as "In Progress"
4. See the number of sentences i.e. 3/750

**Expected behavior**
It should show the actual number of validated sentences. Pashto should be available for voice clip recordings

**Screenshots**
N/A

**Desktop or Mobile (please complete the following information):**
 - OS: Mac Monterey
 - Browser: Brave 
 - Version: 1.48.158

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: N/A
 - Model: N/A

**Additional context**

**Comment by moz-dfeller** [comment]
Thank you @ihanif for the effort. We could fix the bug that caused a problem with the sentence import. The language statistics are updated and reflect now the current state:
![image](https://user-images.githubusercontent.com/119537889/223412345-557262d5-70b6-4b1a-821c-323d1e6323fa.png)
🎉

**Comment by ihanif** [comment]
Thanks a lot, @moz-dfeller, for the fix and the update. It now shows the correct number of validated sentences.

However, not sure if I need to raise another bug or if it's related to this same issue. Pashto is still shown as 'In Progress' and not a 'Launched' language. It's also not available for voice clip recordings. It has met all the requirements (Pontoon translated: 100%, valid sentences: 1054/750), but is still not launched.

**Comment by ftyers** [comment]
@ihanif this is not a bug, it will be available in the next release.
