### ISSUE TITLE
[BUG] - Can't validate clips in Catalan

### ISSUE THREAD

**Issue by mmarimon** [common-voice/common-voice#4013]
**Describe the bug**
When attempting to listen to and validate Catalan clips, I receive an error message stating: "No hi ha cap més tall per validar en aquesta llengua" (EN: We may have run out of clips - please refresh the page or try again later). Despite switching browsers and refreshing the page, the issue persists. However, after testing the platform with Spanish and English clips, I can confirm that it works without any problems.

**To Reproduce**
2. Language CA
3. Go to 'Col·laboreu-hi'
4. Click on 'Escolta'

**Expected behavior**
Get 5 clips to validate

**Screenshots**
<img width="705" alt="Screenshot 2023-04-24 at 09 52 45" src="https://user-images.githubusercontent.com/44234867/233940284-94b56105-bafd-4bfd-b900-dfc8cd913644.png">

**Desktop or Mobile (please complete the following information):**
I have attempted to access the platform using various devices, operating systems, and browsers.:

- Windows: Microsoft Edge, Google, Chrome
- Android: Chrome and Opera
- iPhone SE: Chrome, Safari
- MacBook Air: Chrome, Firefox, Safari
- iPhone SE & Mac (Chrome & Safari) 
- Tablet: Opera
- Android: Mobile App

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**

**Comment by moz-rotimib** [comment]
Hello, @mmarimon thanks for filing this issue. We will look into this bug and try to fix this as soon as possible.

**Comment by raivisdejus** [comment]
We had similar issue a while back in Latvian. Relaod of the page usually helped, so use that as a workaround while this gets fixed

**Comment by jmontane** [comment]
In my case, reloading the page doesn't help.

**Comment by ftyers** [comment]
https://github.com/common-voice/common-voice/issues/2746#issuecomment-1527884354 gives the same report.

**Comment by c-armentano** [comment]
Hello!
Is there any update about this issue?
To my knowledge, two important Catalan cultural organizations are currently running campaigns to promote Common Voice in Catalan, so we expect an increase in participation, also for validation...
- [https://www.plataforma-llengua.cat/que-fem/noticies/5745/el-catala-supera-les-3000-hores-de-gravacio-a-common-voice-i-ja-es-la-segona-llengua-amb-mes-minuts-enregistrats-i-validats](https://www.plataforma-llengua.cat/que-fem/noticies/5745/el-catala-supera-les-3000-hores-de-gravacio-a-common-voice-i-ja-es-la-segona-llengua-amb-mes-minuts-enregistrats-i-validats)
- [https://parlam.omnium.cat/](https://parlam.omnium.cat/)
Thank you!
Carme

**Comment by ftyers** [comment]
So the problem appears to be with the single-recording-per-sentence limit, as @moz-dfeller points out:

> it can't be 100% for those language because we don't show clips to a specific sentence anymore as soon as it has only one valid clip. So the extreme case: we only have one sentence for locale x. This sentence accumulated 4 recordings. When we validate clips we get one of those clips by chance. Then we say that clip is fine. So now the sentence has a validated clip and the other 3 recordings will not be shown anymore to the user. So allClips=4 and validatedClips=1, means we only have 25% validation rate for locale x with one sentence.

This was introduced in order to increase the variability for training acoustic models with DeepSpeech and to avoid having 100s of recordings of the same clip for languages with a lot of speakers and resources. Things in machine learning have moved on since then. 

We will try removing the limit for Catalan and if it does not cause problems, we will do the same for other languages.

**Comment by c-armentano** [comment]
That's great! Thank you!

**Comment by ftyers** [comment]
@c-armentano can you check and let us know if everything is ok and we can close this issue... Thanks!

**Comment by c-armentano** [comment]
Hi!
I've been trying it and asking other validators I know, and we all agree it's working fine. Thank you a lot!

**Comment by moz-dfeller** [comment]
Fixed in #4026
