### ISSUE TITLE
[BUG] Sentence Collection guidelines can't be linked to

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/common-voice#4033]
**Describe the bug**
Go to https://commonvoice.mozilla.org/en/guidelines and switch over to the Sentence Collection tab. Click on "Citing Sentences" in the menu. Now the URL is https://commonvoice.mozilla.org/en/guidelines#citing-sentences. Take the URL and open it in another tab which fails as it does not switch to the Sentence Collection tab.

**Expected behavior**
It should also switch to the Sentence Collection tab and show the correct section. This would enable linking to it.

**Comment by moz-rotimib** [comment]
This has been fixed in #4102
