### ISSUE TITLE
[BUG] Top left 3 dots missing when logged in german CV (speak,listen,write,review) [android13][de][nl]

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4038]
**Describe the bug**
Logged in german smartphone contributors are trapped without activated 2 or 3 point navigation on android os level (3 top left dots are not displayed)

**To Reproduce**
1. Log into your CV-moz account
2. Change the language from english to german
3. Go for example to the write section of the new sentence  -collector
4. https://commonvoice.mozilla.org/de/write
5. Change from write to the other contribution sections(listen, speak, review) 
6. Result is: in all 4 contribution sections the top left 3 dots are missing 

**Expected behavior**
Top left 3 dots are visible and functional

**Screenshots**

**Mobile (please complete the following information):**
 - OS: Android 13 GrapheneOS
 - Browser Firefox nightly android
 - Version 115.0a1 (Build #2015950051), 4e2cb82a71+
GV: 115.0a1-20230511213213
AS: 115.20230511050427

 *Hardware **
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**
Also tested with Vanadium browser latest version with the same result.
Pic 2 is a screenshot not logged in cv and with accessible top left 3 dots in de language

**Comment by robovoice1** [comment]
![Screenshot_20230512-171337_1](https://github.com/common-voice/common-voice/assets/92784377/ab66335b-2c5b-4d58-8c10-60ad6b62a223)
![Screenshot_20230512-171151](https://github.com/common-voice/common-voice/assets/92784377/c1c20be9-34cb-4ef3-b475-fd27ef2846ac)

**Comment by robovoice1** [comment]
![Screenshot_20230512-180526](https://github.com/common-voice/common-voice/assets/92784377/6e9a2209-63e8-474f-8d0b-e3a8020bb803)
![Screenshot_20230512-180514](https://github.com/common-voice/common-voice/assets/92784377/b095a6eb-ee0d-4ea6-9dc7-d2b6ad27dea5)
![Screenshot_20230512-180501](https://github.com/common-voice/common-voice/assets/92784377/5989ea4c-5769-4219-8dee-0f7bf76f1d4a)

**Comment by robovoice1** [comment]
It looks like too long (translated) strings are breaking the ui of the contribtion section.
Here another example for the (nl) language
![Screenshot_20230517-170313](https://github.com/common-voice/common-voice/assets/92784377/16773027-d3cd-4829-a5cb-4dd26da493e3)

**Comment by robovoice1** [comment]
I suggest shorter (german) strings for (de) language on pontoon:
Anhören changed to Hören (hear)
https://pontoon.mozilla.org/de/common-voice/web/locales/en/messages.ftl/?search=Anhören&string=179069

and

Überprüfen changed to Prüfen (review)

https://pontoon.mozilla.org/de/common-voice/web/locales/en/messages.ftl/?search=Überprüfen&string=279490

@koehlermichael: could you please check. (Especially if this are the correct strings)
Thanks

**Comment by koehlermichael** [comment]
Thanks @robovoice1, I just approved your suggestions and we’ll see if it works.

**Comment by robovoice1** [comment]
With the latest release the 3 top left dots are back in the (de) contribution section 😃 (logged in) 😃.
![Screenshot_20230519-150146](https://github.com/common-voice/common-voice/assets/92784377/b615f439-bbab-4377-89f3-2883575a9d84)
