### ISSUE TITLE
Website code reuse and thanks !

### ISSUE THREAD

**Issue by hugolpz** [common-voice/common-voice#4054]
Note: This is not a bug, it's a *thank you* note.

Hello everyone ! I'm Yug, one of the initiators of Wikimedia's https://Lingualibre.org which focus on recording individual words from all languages of the world under open licenses to be reused by wiktionaries and other dictionaries.

First, all my admiration to your team. We started around the same time, but your project is more elegant and amassing more data.

Second, I'm pushing within Wikimedia France so we reuse code from Common Voices and explore convergence of efforts. Today I forked [Common Voice Languages page](https://commonvoice.mozilla.org/en/languages). FWIW, there is how I credit your project :

![Screenshot from 2023-05-20 15-43-21](https://github.com/common-voice/common-voice/assets/1420189/67ef4ca9-d8ac-47bd-91b4-a79a783c1362)

`Webpage's code forked from <a class="link" href="https://commonvoice.mozilla.org/en/languages">Common Voice Language gallery</a>, shared under <a class="link" href="https://github.com/common-voice/common-voice/blob/main/LICENSE">MPL (Mozilla Public License) 2.0</a>, adaptation by Yug.</p>`
`
The page will be online later this weekend.

**Comment by hugolpz** [comment]
Your code is reused in https://lingualibre.org/LanguagesGallery/ . Thank to the team !

**Comment by jessicarose** [comment]
Really exciting to see this, I'll share this off to the rest of the team and thanks so much for letting us know about the project. If you ever want to chat you can reopen this issue or reach us directly at commonvoice@mozillafoundation.org to get me or the team. I hope you and your contributors are all going to have the easiest weekend, this looks so impressive and it's such exciting work!
