### ISSUE TITLE
[BUG] Too narrow column for menu

### ISSUE THREAD

**Issue by nesnera** [common-voice/common-voice#4055]
**Describe the bug**
Menu item text does not fit in the column (icon is overlaid)

**To Reproduce**
1. Open link in browser https://commonvoice.mozilla.org/cs or https://commonvoice.mozilla.org/ru
2. Click "PŘISPĚT" ("ПРИНЯТЬ УЧАСТИЕ") at the top
3. The ▶️ icon is overlaid

**Expected behavior**
Visible icon

**Screenshots**
![image](https://github.com/common-voice/common-voice/assets/1737463/122ae76c-28bc-482e-afe8-a7eeccaff129)

**Desktop or Mobile (please complete the following information):**
 - OS:  Linux 6.2.7 NixOS
 - Browser: Mozilla Firefox 111.0

**Comment by CYBWEBALI** [comment]
Hey, I can fix this issue. Can you assign it to me.

**Comment by CYBWEBALI** [comment]
I can fix this issue.

**Comment by moz-rotimib** [comment]
Hello @CYBWEBALI if you're still interested in fixing this issue please feel free to raise a PR to the common voice repo with your solution ❤️

**Comment by moz-rotimib** [comment]
This has been fixed in this [PR](https://github.com/common-voice/common-voice/pull/4125) and will be released in the next release so I am closing this
