### ISSUE TITLE
LOCALISATION REQUEST: 

### ISSUE THREAD

**Issue by raivisdejus** [common-voice/common-voice#4060]
# Welcome to the Common Voice Community!

## Pontoon Set-up

**Language name**

Latgalian (latgalīšu) 
https://en.wikipedia.org/wiki/Latgalian_language

**Language code**

`ltg`

**Language size**

200 000

**Plural forms**

The same as Latvian (lv)

**Pontoon manager**

This is already set up on Pontoon, no additional changes needed.

**Language Script**

Latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [X] Band A
- [ ] Band B
- [ ] Band C

## Creating Community 

No help from Mozilla is needed for community building at this time. As Latgalian is closely linked with Latvian for voice collection needs common community channels will be used as well as existing Latgalian community spaces and communication channels

**Comment by ftyers** [comment]
Hey there, we've added Common Voice to the Latgalian locale on Pontoon. You can find it [here](https://pontoon.mozilla.org/ltg/common-voice/). Thanks for your interest!
