### ISSUE TITLE
Allow browsers to remember  Sentence Collector - Write values

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4062]
**Is your feature request related to a problem? Please describe.**
When you post a sentence and add a citation/source, it is remembered by the browser, so if you add multiple sentences from the same resource, you need to write it again (or perform a second copy-paste).

**Describe the solution you'd like**
We could just select from the browser's feature which shows the most recently/frequently used ones (whatever their algorithm).

**Comment by moz-rotimib** [comment]
Resolved in this PR #4103
