### ISSUE TITLE
Forbid or Limit TTS usage in license

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4068]
We all volunteered our voices for being used in STT models, where the voices become some numbers in a model.

On the other hand, with few-shots models out in the TTS arena, cleanly recorded utterances can be used for replicating our voices.

With the CC0 license, and with only the limitation of "do not try to find persons' identities", Mozilla does allow our voices to be used to be replicated. That would be a big violation of our rights and against laws in many jurisdictions.

So, please **forbid TTS usage** explicitly in any legally binding documents/website phrasing (e.g. download page).

**Comment by KathyReid** [comment]
@HarikalarKutusu I feel like this is a Discourse discussion, and that the the _outcome_ of the Discourse discussion would result in an Issue or a PR, rather than this being an Issue on the GitHub repository itself.

**Comment by HarikalarKutusu** [comment]
Thank you for the input @KathyReid.

This is a "feature request", not a bug report, and I think one is allowed to post such requests, also according to [Mozilla Common Voice Governance Framework v1.0](https://docs.google.com/document/d/1QHDhdJzBQzWRzjw88Br674OINtok09znq0vmpgVBZQo).
Plus, I think this is a very much valid request pointing to an important problem.

But I understand that such a step would be a major one and should be discussed at multiple levels.

Debate on how to handle this problem and how to implement a solution can be discussed [in the Discourse topic I already opened](https://discourse.mozilla.org/t/explicitly-forbidding-tts-usage/115072/2), and the result can be closing this one as not-implemented, or through a PR... The workflow is already very well defined in the mentioned [Governance Framework](https://docs.google.com/document/d/1QHDhdJzBQzWRzjw88Br674OINtok09znq0vmpgVBZQo)... 

PS: This time I skipped the first step (writing to the team via an e-mail) because [it seems to be behind a firewall](https://github.com/common-voice/common-voice/issues/4069).

**Comment by jessicarose** [comment]
Thanks so much for raising this. As this is a question about licensing, I've passed this along to legal for review. I'm so sorry that your reply on the linked issue #4069 is going to look very similar due to the legal nature of both of these issues,

**Comment by jessicarose** [comment]
Hello! After checking in with legal, and the discussion focus of this topic, I'm going to direct folks interested in this (including myself) to your ongoing [Discourse thread](https://discourse.mozilla.org/t/explicitly-forbidding-limiting-tts-usage/115072/3) on the topic.

This is because additional restrictions cannot be added to Creative Commons licenses, meaning this topic is better addressed as a future policy issue than a discreet technical issue.
