### ISSUE TITLE
Last Pontoon translations not available on the website

### ISSUE THREAD

**Issue by Txopi** [common-voice/common-voice#4077]
On may 30st and the following days I have been translating the content of this page to Basque:
[https://commonvoice.mozilla.org/eu/guidelines](https://commonvoice.mozilla.org/eu/guidelines)

15 days later it should be completely in Basque but it seems my work on Pontoon isn't loaded on the website. I have made this translations in the same way I did all the other translations to Basque. Time ago the update was once a week or perhaps every two weeks. We have been talking about this in the Matrix room but we don't know/remember how is this working right now.

Someone mentioned that perhaps the translations are not updated until the website code doesn't change.

I don't know what's going on. I ask for an update of the website regarding all the strings coming from Pontoon. And if possible, the **automation of this task every week**.

It would be great if this frequency was mentioned in the Playbook of the project or any other easy place to find. Thank you!

**Comment by moz-rotimib** [comment]
Hello @Txopi thanks for filing this issue. The reason for this is that the new Pontoon translations were not deployed to production. We have deployed the latest translations and now the site is localized in Basque.

I'll go ahead and close this issue since this seems to be fixed. If you have any other comments or questions feel free to respond in the thread.

**Comment by Txopi** [comment]
OK, thank you.

So when are Pontoon translations deployed to production? If I do new translations when I should expect to see them online? In 24 hours or less? Every Wednesday?

**Comment by jessicarose** [comment]
New translations are generally deployed with each release, so will generally go live (roughly) once every two weeks, though there's no fixed repeatable date of the week  for releases at this time.

New translations done today should go live in roughly 2 weeks, unless a need for a release comes in sooner.
