### ISSUE TITLE
[BUG] Sentence validation gets stuck sometimes.

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4091]
**Describe the bug**
During sentence validation, sometimes YES/NO buttons do not work. The small green popup saying Yes/No appears but the record does advance.
After a page refresh, it might work, sometimes even this does not work.

**Video**

[Click for a short OSB video presenting the issue](https://drive.google.com/file/d/1o8JEvVl2HxiA2F08bTqCRB5H2wAbufgs/view?usp=sharing).

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10x64
 - Browser: Tried on the latest Chrome flavors only (Opera, Vivaldi, etc)

**Comment by HarikalarKutusu** [comment]
OK, when this happens, if I wait for a while and try hitting the buttons, it works.

It seems like rate-limiting. Is there any?

If so the limit needs some adjustment. If each sentence has a couple of words one can read it in a couple of seconds and make a decision.

**Comment by moz-rotimib** [comment]
Hello, @HarikalarKutusu thanks for reporting this issue. 

Next time you get this error could you send a screenshot of your browser dev tools? There should be an error message there and that could help us to figure out what could be causing this. Thanks

**Comment by HarikalarKutusu** [comment]
Here it is (the first 3 are from my ad-blocker), it is rate-limiting as I mentioned above.

![image](https://github.com/common-voice/common-voice/assets/8849617/6c9d74b6-8547-47af-b8ad-aca18f2f706b)

One can rapidly check many short sentences and/or obvious spam sentences (e.g. from another language or bad resource).

Or think of this scenario: In our workflow, I check each sentence one by one - and multiple times! But I want it to be checked by one other person - to reach our 0 error goal. I add my sentences and want to give the first vote (as OK). I add 100 such sentences but with rate-limited voting 10/min, I have to spend 10-15 min to give the first vote.

Bülent

**Comment by moz-rotimib** [comment]
@HarikalarKutusu Thanks for the screenshot and the comments. As you said this seems to be an issue with rate limiting and we will look into possible solutions for this.

**Comment by HarikalarKutusu** [comment]
This should be fixed by https://github.com/common-voice/common-voice/pull/4118 ... Closing

**Comment by kwikwag** [comment]
I think this should remain open until there is a pull request which displays an error once the rate limit is reached.

**Comment by HarikalarKutusu** [comment]
@kwikwag, you are right. Maybe a feature request is in order...

It has been a pain.
I have several thousand sentences imported, from which only ~10% can be acceptable (unprocessed support chat dump).
I'm sure some of that junk got into the dataset.

**Comment by HarikalarKutusu** [comment]
The error message is here with the new v1.101.0 release. In fact, with 30 sentences/min I could not hit that wall either.

https://github.com/common-voice/common-voice/releases/tag/release-v1.101.0
