### ISSUE TITLE
[BUG] Latvian is missing sentences to validate

### ISSUE THREAD

**Issue by raivisdejus** [common-voice/common-voice#4104]
**Describe the bug**
Latvian should have a lot of sentences to validate (screenshot 1),
but in the validation section, we have a note that possibly all sentences have been validated (screenshot 2)

**To Reproduce**
1. Go to the Latvian listen section https://commonvoice.mozilla.org/lv/listen
4. See error and no sentences to validate

**Expected behavior**
Sentences to validate for Latvian available to be validated

**Screenshots**
![attels](https://github.com/common-voice/common-voice/assets/5319134/6f8b5c7c-ea29-476b-beda-e8527b8ac58a)
![attels2](https://github.com/common-voice/common-voice/assets/5319134/deb95cf5-9429-4bc8-b00c-f328e8ed443a). 

**Desktop or Mobile (please complete the following information):**
 Any and all environments

**Comment by moz-rotimib** [comment]
Hello @raivisdejus thanks for reporting this issue. From my experience with this error message,  it's usually the case that there aren't any new clips to validate for the language.

One thing you can try (if you haven't) is to record some clips in the speak section and see if other users can validate your clips. If you still experience this error message after trying this, please give an update in the thread.

Best,

Rotimi

**Comment by raivisdejus** [comment]
@moz-rotimib I recorded 5 sentences from my account. Clips showed up in the graph of "my contribution" on the dashboard, but none of them showed up for an anonymous account for validation.

Also, from the Screenshot of recorded and validated clips for Latvian, we can see that the amount of recorded clips is several tens of hours more than the amount of validated sentences.

**Comment by moz-rotimib** [comment]
Thanks for your response. We will look into this and let you know when this is resolved.

Thanks for your patience

**Comment by raivisdejus** [comment]
Issue is fixed. Thanks!
