### ISSUE TITLE
[BUG] Sentence collector: citation source displayed as question marks

### ISSUE THREAD

**Issue by kwikwag** [common-voice/common-voice#4108]
**Describe the bug**
When adding Hebrew (possible non-Latin) text in the citation source field, it is displayed, during the Sentence Review phase, as question marks.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/he/write
2. Under the citation source box (ציטוט מקור) add Hebrew text, for instance one that specifies self-citation (ציטוט עצמי)
3. Submit some Hebrew sentence, for instance the sentence "This is an example sentence and it shouldn't be read" is "זהו משפט לדוגמא ולא צריך לקרוא אותו"
4. Go to https://commonvoice.mozilla.org/he/review - the sentence citation source will be displayed with question marks.

**Expected behavior**
The text should appear as typed.

**Screenshots**
<img width="556" alt="image" src="https://github.com/common-voice/common-voice/assets/392199/055a901b-2098-4ffb-9c6f-cee1e80a4b52">

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10/11, Android 13
 - Browser Chrome
 - Version 114

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: N/A
 - Model: N/A

**Additional context**
N/A

**Comment by moz-rotimib** [comment]
Hello. Thanks for filing this issue. We have a [PR](https://github.com/common-voice/common-voice/pull/4111) to fix this and this will be deployed soon.

**Comment by moz-rotimib** [comment]
Closing this because this issue should be resolved by this [PR](https://github.com/common-voice/common-voice/pull/4113).

Something to note: Any sentence added **_before_** this PR was merged will still have the ???? in the source field. Future sentences should not have this issue
