### ISSUE TITLE
[BUG] Sentence collector: Review process produces 429 Too Many Requests too quickly with no clear error indication

### ISSUE THREAD

**Issue by kwikwag** [common-voice/common-voice#4109]
**Describe the bug**
When reviewing sentences, the server rather quickly switches to rejecting Yes/No verdicts given by the user due to rate limiting (with HTTP error 429 Too Many Requests) - this happened to me after 10 requests within 30 seconds. The page itself doesn't give any indication whatsoever that an error occurred, or what the user needs to do to mitigate the error. 

**To Reproduce**
1. Go to [Sentence Review](https://commonvoice.mozilla.org/he/review).
2. Make 10 Yes/No determinations within 30 seconds
3. The Yes/No buttons will seem like they don't respond any more
4. If you have Developer Tools open you'll see HTTP 429 responses coming in.

**Expected behavior**
1. In case an error is encountered (429 or otherwise), the user should be notified with proposals for remediating actions.
2. Under reasonable conditions, I can approve/reject sentences at a rate of 2-3 seconds/sentence, that is 0.5 requests/second.

**Screenshots**
![commonvoice-sentence-collector-429](https://github.com/common-voice/common-voice/assets/392199/0b57a4a9-bcaf-4f41-8839-9f8a971992e0)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 114

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: N/A
 - Model: N/A

**Additional context**
N/A

**Comment by kwikwag** [comment]
I should add I see this as a severe bug as it is currently limiting the rate at which we can approve sentences for my language!

**Comment by moz-rotimib** [comment]
Hello @kwikwag thanks for filing this issue.

This is not a bug but something we did intentionally to limit the rate at which the API is called when reviewing sentences. The limit with which you can call the API is one every 3 seconds so try to keep your contributions within that limit.

Thanks

**Comment by kwikwag** [comment]
Hey @moz-rotimib - something must be wrong in your calculation - currently the rate is set at 12 requests per 60 seconds, which is one request every 5 seconds. This is seriously limiting the throughput and discourages participation. The rate should be limited according to how normal people work. I does not take 5 whole seconds to read a short (under 15 words) sentence and decide if it is valid. If you stop people before even a minute elapses they will quickly become discouraged and stop volunteering. 

Was there any preliminary work done to check what's the distribution of request times for most users to see how this might negatively impact current users?

It seems to be quite simple and sensible to reduce this limit to one request every 2 seconds. Intuitively it should support most use-cases without compromising the limits required to maintain service quality. Especially when it comes to the Sentence Review part.

**Comment by kwikwag** [comment]
I just now performed a session of sentence review. First request Sat, 15 Jul 2023 21:09:36 GMT. The 11th request at Sat, 15 Jul 2023 21:10:24 GMT received a 429 Too Many Requests with Retry-After: 12. That is, I need to wait for a minute to elapse in order to complete 11 requests. That's actually 10 requests per 60 seconds, which is 6 seconds between requests - double the interval from what you wrote...

**Comment by kwikwag** [comment]
Adding a screenshot to help visualize this. Notice the timeline and the position of the failing request.

<img width="369" alt="image" src="https://github.com/common-voice/common-voice/assets/392199/f7128b2e-789e-48e2-9ade-db321846e565">

**Comment by kwikwag** [comment]
Oh and last P.S. @moz-rotimib the bug is also the fact that there is no indication of error on the page whatsoever (see original screen recording)

**Comment by moz-dfeller** [comment]
Hi @kwikwag , thank you for putting so much effort into this issue. We adjusted the rate limit to 2s for sentence reviews as suggested (#4118). It will go live with the next release 🎉

**Comment by moz-rotimib** [comment]
> 

Thanks for also pointing this out. We have created a ticket to fix this and we will work on this in the coming weeks

**Comment by moz-rotimib** [comment]
> Oh and last P.S. @moz-rotimib the bug is also the fact that there is no indication of error on the page whatsoever (see original screen recording)

Thanks for also pointing this out. We have created a ticket to fix this and we will work on this in the coming weeks

**Comment by kwikwag** [comment]
Thank you for your efforts and for listening!

**Comment by HarikalarKutusu** [comment]
I had that reported also here: https://github.com/common-voice/common-voice/issues/4091 , so I'm closing that one.
