### ISSUE TITLE
[BUG] RTL layout issues in desktop and mobile websites

### ISSUE THREAD

**Issue by kwikwag** [common-voice/common-voice#4110]
**Describe the bug**
There are several issues with icon/glyph/text positioning for the RTL version of Common Voice website, specifically in Hebrew.

**To Reproduce**
1. Open the [Hebrew website](https://commonvoice.mozilla.org/he) in a desktop browser
2. Hover over contribution (תרומה). You'll notice the menu opens up at an incorrect position. Also the small triangle menu indicator is missing the margin from text.
3. Go to the Sentence collector write link (כתיבה)
4. The active page indicator, menu expander are out of alignment.
5. Switch to mobile view (e.g. iPhone 11 Pro iOS 14.6 profile on Firefox, or Pixel 5 profile on Chrome)
6. Open the navigation menu
7. The icons aren't aligned, the horizontal margin is missing around the text, the menu button is overlapping with logo and the active page indicator isn't aligned

**Expected behavior**
The spacing and position of icons and text should look similar between LTR and RTL versions of the website.

**Screenshots**

![image](https://github.com/common-voice/common-voice/assets/392199/0bff411f-dac0-4cbe-836c-a19850fa3142)
compare with
![image](https://github.com/common-voice/common-voice/assets/392199/c82b64c3-ef47-4459-8d81-df8240e0b2be)
---
![image](https://github.com/common-voice/common-voice/assets/392199/593091c9-742b-4962-b91a-da79f532ab1f)
compare with
![image](https://github.com/common-voice/common-voice/assets/392199/ca37261f-14ee-45ae-abb9-a5f27abd2337)
---
![image](https://github.com/common-voice/common-voice/assets/392199/9beee351-00d5-43ba-a365-21c561e50ccd)
compare with
![image](https://github.com/common-voice/common-voice/assets/392199/2069f1e8-0dff-4955-bbd5-9f74dea08e79)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 114, Firefox 114

**Comment by moz-rotimib** [comment]
Thanks for filing this issue. We are aware of this bug and we will have a fix for this soon.

**Comment by moz-rotimib** [comment]
This has been fixed in this [PR](https://github.com/common-voice/common-voice/pull/4125) and will be released in the next release so I am closing this issue
