### ISSUE TITLE
Require assistance: Large unsuitable corpus *blocking* sentence review in Hebrew

### ISSUE THREAD

**Issue by kwikwag** [common-voice/common-voice#4121]
This is not a feature request nor a bug. I'm in touch with Francis and they suggested I post the issue here.

**Description**
Someone submitted - with the best of intentions I believe - a large corpus of sentences from the Hebrew Bible including very complex diacritics (called Hebrew cantillation). These sentences are archaic, not in any means whatsoever spoken language, and terribly hard to read. This becomes too much of a burden and quite redundant for volunteers to reject each of these sentences, and I would dare to say this is a blocker for contributions for the Hebrew language altogether.

**Describe the solution you'd like**
I would like your help in removing sentences from this source (all from The Westminster Leningrad Codex) from the Hebrew corpus altogether.

**Describe alternatives you've considered**
Have volunteers I am trying to recruit to add more sentence go over all these sentences - this is unfortunately a no-go and seems redundant.

I can also suggest adding a button to report a given source. With enough votes disqualifying data from a specific source, this can aid in future, similar issues. However, I suspect this is seldom the case. In addition, the source can easily vary - if for each batch of sentences a different citation was used, for instance, if the chapter number was mentioned for each bunch of sentences from that chapter in a public domain text.

**Additional context**
This is how it looks like for a user coming in to volunteer in sentence review:

![image](https://github.com/common-voice/common-voice/assets/392199/e5b35a50-8ad5-47eb-93ba-de666776b62b)

What you see here is a sentence from the Hebrew Bible, with a mix of regular diacritics ([niqqud](https://en.wikipedia.org/wiki/Niqqud)) and special diacritics that appear only in the bible ([cantillation](https://en.wikipedia.org/wiki/Hebrew_cantillation)). Though the sentence is intelligible to modern Hebrew speakers, it is light-years from being spoken language and thus often very difficult to read properly.

**Comment by kwikwag** [comment]
Thank you for this update. We now have a similar problems with sentence coming from the source `book of proverbs`. In order to not reiterate this for additional sources, I thought it would be beneficial to introduce a validator for Hebrew.

I spent some time putting together an inclusive validator, meaning a regular expression that only accepts a subset of characters (rather than disallowing characters).  In short, this includes all previously valid punctuation, fancy Unicode punctuation, valid Hebrew diacritics and all the Hebrew letters.

`/[\x20-\x22\x24\x26\x27\x2c-\x2e\x3a\x3b\x3d\x3f\x40\x5c\x5f\x60\p{Zs}\x2010-\u2015\ufe58\ufe63\u2047-\u2049\u2018-\u201f\u2039\u203a\u2e42\u301d\u00bb\u00ab\u05d0-\u05ea\u05b0-\u05bc\u05bE\u05c1\u05c2\u05f3\u05f4]/u`

Is it possible for you (or me?) to test this pattern quickly on all existing sentences for Hebrew, giving for each source the count of mismatching sentences? And perhaps a few examples from each source (if there aren't too many)?

I don't know if the pattern above is refined enough - I might need to see some example sentences that fail in order to understand if I should include more ranges. Is there a place where I can download the current list of Hebrew sentences or are you able to upload these so that I can do this analysis myself and just come to you with the list of sources/sentences (and justification for their removal)?

**Comment by kwikwag** [comment]
P.S. I can confirm this works in filtering the first 50 sentences presented to a new user. The only "bad" source in that batch is indeed `book of proverbs`.

**Comment by kwikwag** [comment]
Update: I noticed that there is a file under `server/data/he/sentence-collector.txt` and I ran the pattern. Seems like I needed to add an ellipsis (which I did by editing the previous comment - so it's there already). Now the pattern filters out a total 7 of 1,060 sentences presently there, and all of them are indeed in Biblical Hebrew. So I think we're good. @moz-dfeller  I'd like your opinion.

**Comment by moz-dfeller** [comment]
@kwikwag The biblical verses should be deleted already, maybe you could confirm that? :) 

We're currently not using filter rules to decide whether or not we are displaying a sentence to the user. The filtering process already happens at sentence submission, so that these sentences don't make it inside the corpus. It would be awesome if you could add your validation for the hebrew language.[Here](https://github.com/common-voice/common-voice/blob/main/server/src/core/sentences/validation/VALIDATION.md) is a description on how to do that.

As for sentences already inside the corpus, I would prefer to write a migration to delete sentences from that source.

Thank you for your effort, it's really a great help!

**Comment by kwikwag** [comment]
@moz-dfeller I just issued a pull request to add Hebrew sentence validation.

Regarding your question about biblical verses - I no longer see sentences from the Westminster Leningrad Codex -- however I mentioned that there is another source ("book of proverbs") that also contains Biblical Hebrew.

I don't know how to run the validator against the current database. I ran it against [server/data/he/sentence-collector.txt](https://github.com/common-voice/common-voice/blob/main/server/data/he/sentence-collector.txt) and got all (but one) sentences in Biblical Hebrew.

If I use a more lenient version of the validator, only Biblical Hebrew comes up.

```javascript
const INVALID_LENIENT_REGEX = new RegExp("[^" +
    VALID_CHAR_CLASSES.punctuation +
    VALID_CHAR_CLASSES.extraPunctuationValidInEn +
    VALID_CHAR_CLASSES.hebrewNiqqud +
    VALID_CHAR_CLASSES.hebrewLetters +
    VALID_CHAR_CLASSES.whitespace +
    VALID_CHAR_CLASSES.dashes +
    VALID_CHAR_CLASSES.quotation +
    VALID_CHAR_CLASSES.combinedPunctuation +
"]", "u");
```

I can try to write a migration but it would involve a regular expression in MySQL. Is there way you can provide a database dump of the Hebrew sentences? Or is this exactly  [server/data/he/sentence-collector.txt](https://github.com/common-voice/common-voice/blob/main/server/data/he/sentence-collector.txt)?

**Comment by kwikwag** [comment]
And another idea - if you think it has merit - should I include a pull request that randomizes the order of sentences for review? This way we would at least present users with different sentences. If you want consistency for a specific user, we can use the user ID as a seed.
