### ISSUE TITLE
[BUG] Null returned in voice validation in Swahili

### ISSUE THREAD

**Issue by jessicarose** [common-voice/common-voice#4128]
**Describe the bug**

Null and no clips both returned instead of expected clips

Bug collected via email from community member. Email copy below:
"We currently have some individuals helping us with validation of the Kiswahili dataset.
Here's the same error being experiences...this time, refreshing does not solve the problem."
"I hope that you are well today. I’d like to ask for some assistance resolving this issue that champions are experiencing when trying to access voice validation prompts on the Common Voice platform.

These screenshots below indicate the challenges they are having. I think it’s a null error caused by issues of rendering the audio.

Please help me to resolve them. Let me know if there’s any way I can help"

**To Reproduce**

**Expected behavior**
Voice clips are presented for review

**Screenshots**
![image0](https://github.com/common-voice/common-voice/assets/4729371/a96b5f8a-9811-4e8a-8a3c-dcd461bcfd65)
![image1](https://github.com/common-voice/common-voice/assets/4729371/054b8d10-3fd4-43f9-8272-3f3ede1fde05)

**Desktop or Mobile (please complete the following information):**

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**

**Comment by HarikalarKutusu** [comment]
Hey @jessicarose, a recent PR caused this and it is shortly after reverted [by this PR](https://github.com/common-voice/common-voice/pull/4129).

**Comment by moz-dfeller** [comment]
Is solved by #4131 so I am gonna close this issue :)
