### ISSUE TITLE
[BUG] Submitted and validated sentences are not available for recording

### ISSUE THREAD

**Issue by raivisdejus** [common-voice/common-voice#4133]
**Describe the bug**
It seems sentences that are added via common voice web interface f.e. `/lv/write` and then get validated via `/lv/review` never actually end up available for recording.

To be selected for recording a sentence among other things needs `is_used` flag to be `true` https://github.com/common-voice/common-voice/blob/main/server/src/lib/model/db.ts#L318

But from a quick glance, I do not see any process that would set `is_used` or `is_validated` columns in the `sentences` table in the database to `true` for any sentences that have collected enough validation upvotes.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/lv/speak
2. There are no sentences to record, but at least several have been added and validated.

**Expected behavior**
Proposed and validated sentences are available to record.

**Comment by moz-dfeller** [comment]
Hey @raivisdejus . Yes for now there are not displayed for recordings, we are just collecting votes. Before there was a weekly export from the sentence collector which contained the new validated sentences. We are currently investigating the best strategy to release new validated sentences, e.g. 
- as soon as the last vote comes in
- once a day
- once a week (as before)

The first options would be probably what most community members prefer I assume.

**Comment by raivisdejus** [comment]
@moz-dfeller I think I remember something about a bunch of sentences being cached for 1 day, like 10K of them being selected cached and then recordings for the day select some sentences from this cached list. If this is still the case, I think adding approved sentences to the common pool once per day is perfectly fine. 

I would also be perfectly happy with getting approved sentences to the list of possible recordings once per week.

**Comment by raivisdejus** [comment]
The issue has been fixed. Thanks, everybody!
