### ISSUE TITLE
LOCALIZATION REQUEST: Ossetic [os]

### ISSUE THREAD

**Issue by amikeco** [common-voice/common-voice#4139]
## Pontoon Set-up

**Language name**

Ossetic

**Language code**

os

**Language size**

500.000

**Plural forms**

0 дуры
1 дур
2 дуры
3 дуры
4 дуры
5 дуры
10 дуры
20 дуры
100 дуры
1000 дуры
Уынын 0 дуры зæххыл.
Уынын 1 дур зæххыл.
Уынын 10 дуры зæххыл.
Уынын дуртæ зæххыл.

// so it's genitive singular with numbers except 1

**Pontoon manager**

[Amikeco](https://pontoon.mozilla.org/contributors/_l3Rid-SZaa-HZXerV-ii_tyZmw/)

**Language Script**

Cyrillic (with an additional symbol Ææ and some digraphs considered letters)

## Sentence Collection Requirements

**Sentence Requirement Band**

- [ ] Band A

## Creating Community 

(Thank you for the links).

1. [optional to share] Why do you want to take part in Common Voice ? _I had some experience with the Esperanto version (registering sentences mostly, but also popularising the project), and as a language enthusiast for Ossetic I see some interest online in the tools that may become available with the help of Common Voice._

**Comment by ftyers** [comment]
Dear @amikeco, thank you for your interest in Common Voice. Are you a native speaker of Ossetian or are you in contact with any members of the Ossetian-speaking community?

**Comment by amikeco** [comment]
> Dear @amikeco, thank you for your interest in Common Voice. Are you a native speaker of Ossetian or are you in contact with any members of the Ossetian-speaking community?

I am actually not a native speaker of the language, but I grew up in Ossetia, and I am almost fluent and have experience in translating interfaces (VK, telegram, Wikipedia) and other activities for the language (e. g. [presenting it](https://www.youtube.com/watch?v=6bPAgu_gzu8) at language festivals, and keeping a popular [site about the language](https://www.ironau.ru)).

Yes, I am in contact with the community, I think I can reach thousands of views with my announcements. I also can contact personally a dozen of speakers who may be interested in the activity like translating the interface, collecting the texts and reading them for the Common Voice initiative.

**Comment by ftyers** [comment]
That sounds fine! It would be good to have speakers involved in the translation. Could you invite them to make Pontoon accounts and post them here? Thanks!

**Comment by amikeco** [comment]
> That sounds fine! It would be good to have speakers involved in the translation. Could you invite them to make Pontoon accounts and post them here? Thanks!

All right, going to do that.

**Comment by chibrus** [comment]
I am a native speaker of Ossetian ( or Ossetic), I would like to take part in the project. My username at Pontoon is "chibupel".

**Comment by theJosephGoodman** [comment]
Hi! Could you please add ossetian language. I am a native speaker of ossetic too. My Pontoon username is geor_lolaev. Right now I have free time, so I can help in translating

**Comment by amikeco** [comment]
> I am a native speaker of Ossetian ( or Ossetic), I would like to take part in the project. My username at Pontoon is "chibupel".

> Hi! Could you please add ossetian language. I am a native speaker of ossetic too. My Pontoon username is geor_lolaev. Right now I have free time, so I can help in translating

Thank you for your support of the idea.

**Comment by ftyers** [comment]
I've added [Ossetian](https://pontoon.mozilla.org/os/common-voice/) to Common Voice on Pontoon. If you could log in and suggest a translation, I will add you all as translators. Any questions, please feel free to contact us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by ftyers** [comment]
I've added @amikeco as a translator, if the other translators could also log in and make suggestions I will add them too. Also, there should be a manager for the locale, ideally it should be a native speaker. 

In addition a next step will be to collect 750 public domain sentences in Ossetian for contributors to read out. I'm happy to provide advice on doing this. Please feel free to get in contact with me on Matrix.

**Comment by ArturGudiev** [comment]
Hi, I am also aaa native speaker of Ossetian. I want to participate in the project. My Pontoon username is [arturgudiev](https://pontoon.mozilla.org/contributors/arturgudiev/)

**Comment by ftyers** [comment]
Thanks @ArturGudiev, could you please make a few suggestions and I will add you as a translator. :)

**Comment by ArturGudiev** [comment]
@ftyers What do you mean by suggestions? Should I translate something? Is it on Pontoon website?

**Comment by ArturGudiev** [comment]
@ftyers I got it. I've suggested several translations on Pontoon

**Comment by theJosephGoodman** [comment]
@ArturGudiev Салам. Tell me your telegram please

**Comment by ArturGudiev** [comment]
@theJosephGoodman Салам. It's @arturgudiev

**Comment by amikeco** [comment]
There is an important correction: when we speak about the Ossetic/Ossetian version, we mean its bigger dialect known as [Iron [ee-rohn]](https://en.wikipedia.org/wiki/Iron_Ossetian). The other dialect is known as Digoron, it has its own literary tradition, press, and even some people calling it a separate language, it may appear later with its own activists. Collecting both under one name seems not possible, since the differences are deeper than in reading same words differently.

I see in the list there are already many languages with narrowing descriptions, so it'd be nice to write ours as "Ossetic (Iron)", "Ossetian (Iron)", "Iron Ossetian" or in any other way that fits the project's tradition.

**Comment by amikeco** [comment]
> It is the case for many languages on Common Voice (like Arabic, Portuguese, [Armenian](https://ekeleshian.github.io/posts/armenian-common-voice-frequently-asked-questions/#how-are-dialects-addressed-is-there-a-voice-corpus-for-each-dialect-similar-to-how-the-language-is-split-in-wikipedia), Swahili, etc.) that have very different variants. Common Voice so far goes by ISO codes to distinguish languages that we support.

We have other levels of variation to call "variants", "subdialects" that are united by the writing system (there will be at least 4 in Iron Ossetic).

It's up to you how to present it so far: it could be code OS and name Ossetic, and when the Digor dialect (and literary norm) topic appears with the people ready to collect sentences and voices in it, we can come back to the discussion again.

**Comment by amikeco** [comment]
75% localization at Pontoon is ready.

**Comment by ArturGudiev** [comment]
> It is the case for many languages on Common Voice (like Arabic, Portuguese, [Armenian](https://ekeleshian.github.io/posts/armenian-common-voice-frequently-asked-questions/#how-are-dialects-addressed-is-there-a-voice-corpus-for-each-dialect-similar-to-how-the-language-is-split-in-wikipedia), Swahili, etc.) that have very different variants. Common Voice so far goes by ISO codes to distinguish languages that we support. We currently support variants for individual speakers (you can read about it [here](https://foundation.mozilla.org/en/blog/how-we-are-making-common-voice-even-more-linguistically-inclusive/) and we have a plan to support variants for text sentences too.

I see 2 Armenian languages in the lists (Armenian and Armenian Western). So Armenian Western is a different variant with its own dataset. The same would be suitable for Digoron Ossetian. It has its own grammar and vocabulary. Although there are similarities with Iron Ossetian the differences are significant. (by the way, Digoron Ossetian is also sometimes called Western Ossetian). 

![image](https://github.com/common-voice/common-voice/assets/4563342/5d50c94d-69b9-45d1-9eae-65476678dd61)

**Comment by ftyers** [comment]
There are not two variants of Armenian, as you can read in [this blogpost](https://ekeleshian.github.io/posts/armenian-common-voice-frequently-asked-questions/#how-are-dialects-addressed-is-there-a-voice-corpus-for-each-dialect-similar-to-how-the-language-is-split-in-wikipedia).

**Comment by amikeco** [comment]
https://commonvoice.mozilla.org/os/ is running now, thank you very much.
We will start new topics for other issues about it, right?

**Comment by ftyers** [comment]
![imatge](https://github.com/common-voice/common-voice/assets/449545/dce9209d-fbbf-4386-a4ac-4ccb874aa649)

So far Ossetian only has 7 sentences contributed and approved. It will need 750 to launch.

**Comment by amikeco** [comment]
Dear Francis, 

Can we have an additional line of code somewhere in the Ossetic product? As Cyrillic Æ is poorly supported in fonts, people use the Latin code for it, Æ (absolutely identical visually, but other letter from the point of view of computers).
So either in the sentence collector or while packing the dataset, all Latin codes for Ææ should be changed to Cyrillic ones. Will it be possible?

Also the Main page of Common Voice uses some font that does not support Cyrillic letters, it is very obvious because of how Ossetic Æ's appear among the adjacent other letters:
https://commonvoice.mozilla.org/os
https://commonvoice.mozilla.org/os/review

**Comment by ArturGudiev** [comment]
> There are not two variants of Armenian deployed in Common Voice, as you can read in [this blogpost](https://ekeleshian.github.io/posts/armenian-common-voice-frequently-asked-questions/#how-are-dialects-addressed-is-there-a-voice-corpus-for-each-dialect-similar-to-how-the-language-is-split-in-wikipedia) and see in the datasets. In addition, any region specific language codes are a result of legacy inclusions. We are planning to merge them when the technical capacity exists.

There are essential differences in grammar, vocabulary, and pronunciation between the Iron and Digor languages. One object can have different words in Iron and Digor, correspondingly. You either need to provide 2 variants for every phrase (Iron and Digor) or create two separate datasets.

In Ossetia, books are printed in either Iron or Digor. Foreign books can have two translations (Iron and Digor). I still think it's better to create two different interfaces for the Iron and Digor languages. Otherwise, datasets will be mixed, which can result in lower quality speech recognition.

**Comment by ftyers** [comment]
Why do you think it would result in lower quality speech recognition? If ASR systems can be improved by adding data from unrelated languages, why not from related languages or variants of the same language? Anyway, in any case, this GitHub issue is not the place for this discussion, it would be better to take it to [Discourse](https://discourse.mozilla.org/c/voice/239), and please feel free to link it here.

**Comment by ArturGudiev** [comment]
> Why do you think it would result in lower quality speech recognition? If ASR systems can be improved by adding data from unrelated languages, why not from related languages or variants of the same language? Anyway, in any case, this GitHub issue is not the place for this discussion, it would be better to take it to [Discourse](https://discourse.mozilla.org/c/voice/239), and please feel free to link it here.

Sure, thanks. We can continue the discussion there.

**Comment by ArturGudiev** [comment]
> ![imatge](https://user-images.githubusercontent.com/449545/269696439-dce9209d-fbbf-4386-a4ac-4ccb874aa649.png)
> 
> So far Ossetian only has 7 sentences contributed and approved. It will need 750 to launch.

Now there are 757 sentences in Ossetian. Should the voice recording option appear automatically? I don't see it right now. 

![image](https://github.com/common-voice/common-voice/assets/4563342/c5d5ae09-4905-4765-b8b0-26249c4fcc70)

**Comment by ftyers** [comment]
It should appear at the next release, so within 1-2 weeks.
