### ISSUE TITLE
[BUG] Translated skip string (de) does not fit the review page (mobile)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4142]
**Describe the bug**

Please compare screenshot 1 + 2 (en) + (de)

**To Reproduce**
1. Log into CV
2. Go to the german review section
3. https://commonvoice.mozilla.org/de/review
4. Translated skip string overlapping 

**Expected behavior**
Translated string fits with a shorter translated string or
a flexible routine to adjust the size of the skip button depending on the length of the translated string
(Maybe other language sections have the same issue)

**Screenshots**
![Screenshot_20230809-195102](https://github.com/common-voice/common-voice/assets/92784377/55202631-2309-4132-a22b-deb4404ba593)
![Screenshot_20230809-195233_1](https://github.com/common-voice/common-voice/assets/92784377/0b9c9464-9c6e-4c2f-add8-2356d8bbd444)

**Mobile :**
 - OS: Android 13 GrapheneOS stable
 - Browser Vanadium
 - Version [e.g. 22] 115.0.5790.166

 **Additional Hardware :**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by moz-rotimib** [comment]
Thanks for filing this issue. I've created a ticket for this bug and a fix for this should be out in the coming weeks. As always we welcome open source contributions so if anyone wants to raise a PR to fix this feel free to do so ❤️

**Comment by adarrssh** [comment]
Hey @moz-rotimib, what should be the ideal solution for this issue?
The button size should increase or the text size should decrease.

**Comment by moz-rotimib** [comment]
Hi @adarrssh thanks for your potential contribution. I think you can try to slightly increase the width of the skip button (I think this would mean you might have to move the **yes** and **no** buttons a bit more to the left and right respectively). In addition, you can also show an ellipsis (...) for text that could be too long for the button so it does not overflow like it does now.

**Comment by adarrssh** [comment]
Okay, I'll try to do that.

**Comment by adarrssh** [comment]
Hey, I made some changes. Please let me know if you need any further revisions.








https://github.com/common-voice/common-voice/assets/85433137/e470f5a1-6b6e-44a5-827e-d1f9d73ab429

**Comment by adarrssh** [comment]
Hey @moz-rotimib , I made some changes. Please let me know if you need any further revisions.



https://github.com/common-voice/common-voice/assets/85433137/f056aa1e-9878-4324-b5c2-cf519030f8d6
