### ISSUE TITLE
Anyone is using this to Collect data for Speaker Verification?

### ISSUE THREAD

**Issue by dimuthuanuraj** [common-voice/common-voice#4145]
Here we collect speech data, Is there anyone who modified the code to use for collecting speaker verification?

I believe we need that case all the recordings should be saved under speakerID. I am new to this. but appreciate other's views on this, please.

**Comment by jessicarose** [comment]
Hi, I'm so sorry that I need some extra information to better understand this issue.

Are you asking for support/advice in forking and modifying the MCV platform to verify speaker identity in your own voice collection project?

Are you asking for support/advice in forking and modifying the MCV platform to verify speaker identity in the MCV datasets? 
- In this case, I would flag that we ask speaker identification not be attempted as part of our dataset download process.
- 
Are you asking about another technical process not listed above?

**Comment by jessicarose** [comment]
I'm going to go ahead and close this as stale for now but if you do want to continue this conversation, please do open this back up to continue the conversation.
