### ISSUE TITLE
[FR] Increase recording limit to 20 seconds

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4149]
**Is your feature request related to a problem? Please describe.**
It is discussed in [this Discourse post](https://discourse.mozilla.org/t/discussion-relaxation-of-the-10-sec-recording-limitation/114142).

I propose including this in the project plans.

**Comment by jessicarose** [comment]
Thanks so much for continuing to champion this! We're going to be continuing to discuss this internally with the team and participate in discussions with the community as we continue to look at how and when to make changes to samples in the speech data we collect and make available in our datasets.

**Comment by HarikalarKutusu** [comment]
Before the v17.0 release, the recording period is increased to 15 seconds. Although it needs other changes (longer texts), this will enough for now.

Thank you team!
