### ISSUE TITLE
[BUG] Outdated Sentence Collector guideline on About page

### ISSUE THREAD

**Issue by MichaelKohler** [common-voice/common-voice#4152]
On the "About" page there is a section towards the bottom saying "How do I add sentences?". The answer to that is by now quite outdated, most notably the following paragraphs. Link: https://commonvoice.mozilla.org/en/about?tab=how-add-sentences#playbook

> Sentence Collector is a tool for collecting and validating public domain sentences. You will [need to create an account](https://commonvoice.mozilla.org/sentence-collector/login). Then, add your language to your Profile. You can Add sentences or Review previously-added sentences.

This is not the case anymore, as it now is part of the CV website.

> Sentences that have been validated are exported on Wednesdays, and are available after the next release.

This is also not true anymore.

![image](https://github.com/common-voice/common-voice/assets/330324/545f90f7-6999-4ee9-b77d-40ed32062d30)

**Comment by jessicarose** [comment]
Thanks so much for catching this, I'll revise the text and links for this now but this may have to wait a few days for @moz-rotimib to be back from a well deserved vacation to put live.

**Comment by moz-rotimib** [comment]
Thanks @jessicarose I'll create a ticket to update this

**Comment by jessicarose** [comment]
Thanks so much for your patience, @moz-rotimib addressed this in [this PR](https://github.com/common-voice/common-voice/pull/4162) which I hope fixed the issue to your satisfaction. Thanks so much again for flagging this!
