### ISSUE TITLE
LOCALISATION REQUEST:  EWONDO

### ISSUE THREAD

**Issue by germes96** [common-voice/common-voice#4157]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Éwondo

**Language code**

ewo  ( ISO-639-2)

**Language size**

580,000

**Plural forms**

**Pontoon manager**

https://pontoon.mozilla.org/contributors/pmi-6vpvd7kjSrVnIwvz1EmQFuY/

**Language Script**

Latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x] Band A

## Creating Community 

<!--- How can you start a community ?
- Establishing [communication platforms](https://github.com/common-voice/common-voice/blob/main/docs/COMMUNITIES.md) for your language can help to connect volunteers and mobilise people for community campaigns. 

1. [optional to share] Why do you want to take part in Common Voice ?

Here are some specific reasons why we want to take part in Common Voice:
* We want to make it easy to access the various datasets and thus enable the rapid growth of tools associated with the ewondo language.
* I want to help to make voice-enabled technology more accessible to people who are currently excluded (low-resource language speeacker).
* I want to be part of a community of people who are working to make the world a better place.
* I want to help to improve the accuracy of speech recognition models for people with different accents and languages.
* I want to support the development of open-source speech recognition technology.

**Comment by germes96** [comment]
HI @ftyers
Plural forms:

0 rocks :  təgé ai ngɔg ziŋ
1 rock : ngɔg dziá
2 rocks :  ngɔg ébɛ́
3 rocks : ngɔg élɛ́
4 rocks : ngɔg ényii
5 rocks : ngɔg étán
10 rocks : ngɔg awôm
20 rocks : ngɔg məwôm mə́bɛ́
100 rocks :  ngɔg ǹtɛd
1000 rocks : ngɔg tóyina
I see 0 rocks on the ground: máyén kig ngɔg ziŋ á sí
I see 1 rock on the ground : mayén ngɔg dziá á sí
I see 10 rocks on the ground : mayén ngɔg awôm á sí 
I see rocks on the ground : mayén ngɔg á sí

**Comment by ftyers** [comment]
Thanks! I have enabled [Ewondo in Pontoon](https://pontoon.mozilla.org/ewo/) and added [Common Voice](https://pontoon.mozilla.org/ewo/common-voice/). Could you suggest a translation and I'll add you as a translator!

**Comment by germes96** [comment]
Hi @ftyers
Thanks for added Ewondo. I have suggest 7 translations on [Ewondo in Pontoon](https://pontoon.mozilla.org/ewo/)

**Comment by ftyers** [comment]
Dear @germes96 I have added you as a translator. Please let us know if you would like help collecting sentences, you can join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by Ngue-Um** [comment]
Dear @germes96,

My name is Emmanuel Ngue Um and I am currently leading a voice data collection project for under-served African languages. We are planning an [event](https://inhunumaf.hypotheses.org/964) in Yaoundé, Cameroon, very soon. The event will bring together participants representing different languages across Africa for a six-day intensive on-site data collection. Ewondo has been selected as one of the languages in question. As we will be using Common Voice as the data-collecting interface, and given that you already requested Ewondo to be created on Mozilla's Pontoon, we would be grateful if you would be willing to collaborate with us in this initiative. We have a team of two young enthusiasts and indigenous language champions from the Ewondo community who will be joining us. They have already compiled sentences which will be used as prompts in the interface and are also working on translating the interface. We believe your collaboration in this endeavour would be invaluable, and we look forward to hearing from you.
