### ISSUE TITLE
LOCALISATION REQUEST: Gujarati

### ISSUE THREAD

**Issue by Piratesarereal** [common-voice/common-voice#4159]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Gujarati

**Language code**

 gu

**Language size**

50 Million+

**Plural forms**

0 rocks  - shunya pathra
1 rock - Ek pathro
2 rocks - Be pathra
3 rocks - Tran pathra
4 rocks - Chaar pathra
5 rocks - Paanch pathra
10 rocks - Das pathra
20 rocks - Vees pathra
100 rocks - Sau pathra
1000 rocks - Hajar pathra
I see 0 rocks on the ground - Mane jameen upar shunya pathra dekhaay che
I see 1 rock on the ground - Mane jameen upar ek pathro dekhaay che
I see 10 rocks on the ground - Mane jameen upar das pathra dekhaay che
I see rocks on the ground - Mane jameen upar pathra dekhay che. 
**Pontoon manager**

**Language Script**

Gujarati

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ ] Band B

- [x] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
- I want to get my native language added to the Common Voice Database. 
2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Hi @Piratesarereal thanks for your interest, could you fill out the remaining questions in the questionnaire above? Thanks!

**Comment by Piratesarereal** [comment]
Hi @ftyers, I am not sure I understand some of the things asked here. 

- For plural forms, I am not sure how to describe them.
- for the pontoon manager, who should manage it?

**Comment by ftyers** [comment]
There is already a Pontoon locale for gu-IN, which is written in Gujarati script. https://pontoon.mozilla.org/gu-IN/ Does this look right? If this is the case, I would recommend getting in touch with the two managers there. I'm happy to enable Common Voice for Gujarati, but you will need to discuss with them about getting translation permissions.

**Comment by Piratesarereal** [comment]
That looks right. Thanks for finding this for me. I am closing the issue.

**Comment by ftyers** [comment]
[Here](https://pontoon.mozilla.org/gu-IN/common-voice/) it is! Feel free to get in touch with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
