### ISSUE TITLE
[BUG] Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [common-voice/common-voice#4165]
**Describe the bug**
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

**To Reproduce**
Scroll to bottom and see old logo of twitter

**Expected behavior**
Twitter logo should be changed to X

**Screenshots**
<img width="960" alt="Screenshot 2023-09-08 160637" src="https://github.com/common-voice/common-voice/assets/91591901/81c4a873-49b9-4b2f-822e-bc2f080d2e6b">

**Desktop or Mobile (please complete the following information):**

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**
@bobreyes 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by jessicarose** [comment]
Thanks so much for flagging this for the team! I see that @bobreyes would be excited to work on this. If you do create a PR for this could you tag me so that I can review this and get it out into the world for you quickly?

**Comment by KSSaiTeja** [comment]
i have prior skills to fix this.. and i will raise a PR please review my PR.

**Comment by KSSaiTeja** [comment]
@jessicarose please review my PR

**Comment by KSSaiTeja** [comment]
i will raise a new PR.. please review it and merge my PR.. it will be more beneficial to my opensource journey.. please review my new PR.
