### ISSUE TITLE
[Req] checkbox (submit a report) for artificial/unlogic sentences in Speak, Listen, Review needed ?

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4166]
**Is your feature request related to a problem? Please describe.**

In the (de) language i had some unlogical sentences which were gramatically correct, but simply made no sense. 

For example:
In the north of germany is a special breed of cows, that are laying eggs. 
🤯(what?!)😂

This could be a joke or an artificially created sentence.

**Describe the solution you'd like**
Another checkbox for "submit a report" for unlogical/artificial sentences in Speak/Listen/Review section

**Describe alternatives you've considered**

Leave it "as is " and have a good laugh or
Mark."others" checkbox and writing manually nonsense/artificial sentence 

**Additional context**
![Screenshot_20230910-160120](https://github.com/common-voice/common-voice/assets/92784377/f926e6ee-63b2-489b-94ce-6512c6869a9c)

I do not want to play internet police here, but this is presenting  fiction as facts. 

Jogging in the world famous dutch mountains is another classic. 🤣

**Comment by jessicarose** [comment]
Hello and thank so much for getting in touch with this issue. While it might seem a bit strange to have factually inaccurate sentences in the text corpus for a given language, one of the main sources for our text corpora are copyright free texts. These texts often include works of fiction, so factually incorrect (and often fanciful!) sentences may show up in the platform.

These don't need to be reported unless they're offensive or unsuitable for other reasons but please feel free to skip them if you don't feel comfortable dictating the benefits of jogging in those less-than-real Dutch mountain ranges.

I'll close this issue for now, but if you want to discuss this further I'm happy to chat in more detail here or in the forums.
