### ISSUE TITLE
LOCALIZATION REQUEST: Laz Language

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4179]
Note: This request is posted in the name of Laz community in Turkey 

# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Laz Language (Lazuri in Laz)

**Language code**

lzz

**Language size**

There are 10-20.000 active speakers, but around 250.000 worldwide population who know the language.

**Plural forms**

0 kva
1 kva
2 kva
3 kva
4 kva
5 kva
10 kva
20 kva
şilya kva
Tude 0 kva bdzirem.
Tude 1 kva bdzirem.
Tude 10 kva bdzirem.
Tude kvalepe bdzirem.

**Pontoon manager**

https://pontoon.mozilla.org/contributors/0nrdxF-GJgnCF5pIsK3hL-khH_Y/

**Language Script**

Latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ X] Band A

Laz Language is classified as "Definitely Endangered" by UNESCO.

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

## Additional Information on the Laz Language

Laz belongs to the South Caucasian Language Family. Along with Laz, Mingrelian, Svan, and Georgian are the other members of this language family. Laz and Mingrelian are sister languages with the possibility of mutual understanding at a basic level.

Laz is spoken by the Laz people living in the Eastern Black Sea Region of Turkey, specifically in the districts of Pazar (Atina), Ardeşen (Arťaşeni), Çamlıhemşin (Vica), and Fındıklı (Viǯe) in Rize province, and Arhavi (Arkabi), Hopa (Xopa), Kemalpaşa (Noğedi), and Borçka (Boçxa) in Artvin province. Furthermore, despite the complete depopulation of many Laz villages during the 1877-78 Russo-Turkish War, known as the 93 Harbi, Laz continues to be spoken in the city of Batumi and its associated villages.

Due to the 1877-78 Russo-Turkish War, numerous Laz families from the Batumi-Hopa-Borçka triangle migrated to the Marmara Region. As a result of these migrations, Laz settlements were formed in areas like İzmit, Sapanca, Düzce, Akçakoca, Bursa, Bolu, Karamürsel, Yalova, and surrounding regions. In these areas where Laz refugees of the 93 Harbi reside, especially among the older generation, the Laz language continues its existence.

There are mainly two dialects of Laz. The eastern dialect encompasses Laz spoken in Fındıklı, Arhavi, Hopa, and Borçka, while the western dialect includes Laz spoken in Pazar, Ardeşen, and Çamlıhemşin. Among the Laz in the Marmara Region, the Hopa sub-dialect of the eastern dialect predominates. The dialectal differences in Laz are not significant enough to prevent mutual understanding.

What Kind of Language is Laz?

Laz is an agglutinative language, where affixes can be added to the beginning or end of a verb root (e.g., oǩo-v-i-sinap-am-t), and in some cases, in the middle of the verb root (e.g., ǩi-tx-um).

In an inflected verb, both the subject and object can be present simultaneously (e.g., g-żirem). An action can be neutral, benefiting no one (e.g., p̌-ç̌ar-um), for the benefit of the subject (e.g., i-ç̌ar-ams), or for the benefit of the object (e.g., u-ç̌ar-ams). Directional prefixes can be added to almost all verbs (e.g., golo-vulur) indicating in which direction the action continues. Depending on the type of Laz verb (e.g., being a stative or motion verb, taking an object or not), third-person subjects can be in the nominative (e.g., bere 'child'), ergative (e.g., bere-k 'by the child'), or dative (e.g., bere-s 'to the child') case. Additionally, words/prefixes that strengthen or specify the meaning of the sentence (such as ho, ko, do, menda) can be added to the very beginning of the verb (e.g., ko-moxtu). All these characteristics demonstrate that Laz is a language rich in expression, especially in terms of its verbs.

**Comment by ftyers** [comment]
Set up, thanks ! :)
