### ISSUE TITLE
[BUG] Log in not possible - Callback URL mismatch (android13)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4192]
**Describe the bug**

Please watch screenrecording and screenshot
Since today i get this page when trying to log in CV

**To Reproduce**
1. Go to '...'https://commonvoice.mozilla.org/en
2. Click on '....'Tap on log in (top right)
3. Get the oops something went wrong page
4. See error: Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.

**Expected behavior**
Log in without error page

**Screenshots/recording**
![Screenshot_20230925-220436](https://github.com/common-voice/common-voice/assets/92784377/91b4ee8c-05b3-437a-aac7-3a7197a844ad)

https://github.com/common-voice/common-voice/assets/92784377/023d0a21-85bc-434a-beea-66954a35c222

**Mobile (please complete the following information):**
 - OS: [e.g. iOS] Android 13 GrapheneOS
 - Browser [e.g. chrome, safari] Vanadium 
 - Version [e.g. 22] 117.0.5938.60

 **Hardware **
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

The link get help is not reachable https://mozilla.service-now.com/

The Application Settings page link leads to nothing, password not accepted, no email sent to my email address.

Also sent an email to servicedesk@mozilla.com

On discourse i can log in. 

In combination with:

https://github.com/common-voice/common-voice/issues/4187

Who is "fumbling" on the public server without prior notice ?! 🙄

**Comment by HarikalarKutusu** [comment]
A similar error occurred when reviewing sentences:

![image](https://github.com/common-voice/common-voice/assets/8849617/73f8531c-1509-4c33-8376-fb5bafeda994)

I think #4191 will fix these, right?

**Comment by moz-rotimib** [comment]
Hello @robovoice1 @HarikalarKutusu thanks for reporting this issue. The team is aware of this and we are working on getting this resolved as soon as possible

**Comment by moz-dfeller** [comment]
It is fixed now. There was a mismatch in the configuration. Thank you for bringing it up 👍
