### ISSUE TITLE
Last updated note for the stats page

### ISSUE THREAD

**Issue by ftyers** [common-voice/common-voice#4195]
It would be great to have a "Last updated" note on any stats page, e.g. on

https://commonvoice.mozilla.org/en/languages

![imatge](https://github.com/common-voice/common-voice/assets/449545/3ded9385-7186-44f3-b40b-16b4ff0719fe)

A `Last updated: 14:40, 26th September, 2023` would be a great addition here.

It would be good for community members to be able to find out when the stats were last updated and how any contribution/validation campaigns are going.

**Comment by moz-michelleuv** [comment]
@ftyers what would the reasoning be for the time to be listed?  Would just the date suffice?

**Comment by lalitkumawat1m** [comment]
I want to work on this issue could you please assign it to me?

**Comment by moz-rotimib** [comment]
This is currently available on the Languages page so I'm closing this now
