### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by Saire2022** [common-voice/common-voice#4211]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

KICHWA (from Ecuador)

**Language code**

This is a derivative of the Quechuwa language with ISO-639-1 code "qu" which is spoken in different Latin American countries such as: Colombia, Ecuador, Peru, Bolivia, Chile and Argentina. However, the new language that needs to be added to common voice is a derivative of this language spoken in the north of Ecuador and is called KICHWA. 

**Language size**

According to the national census conducted in 2010, there are 591,448 Kichwa speakers in the country. There are no current figures since the government does not publish the statistics of the new census.

**Plural forms**

**Pontoon manager**

https://pontoon.mozilla.org/contributors/P8pN6qyue4U2llayOPe2FPz1OBs/

**Language Script**

Kichwa 

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x] Band A

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

  I want to be part of Common voice because it seems to me a very interesting and useful platform, besides being easily accessible for 
  the creation of data, which is the essential part in the creation of artificial intelligence models.

3. [optional to share] Would you like to have a follow up conversation regarding community building ?
   
   Yes, I would like to meet the participants.

**Comment by ftyers** [comment]
Dear @Saire2022 thanks for your interest in Common Voice. I've opened up Kichwa at: https://pontoon.mozilla.org/qvi/common-voice/ 

Please make some translations and I will add you as translator.
