### ISSUE TITLE
LOCALIZATION REQUEST: for Pular Guinée

### ISSUE THREAD

**Issue by fulaguinea** [common-voice/common-voice#4223]
Dear , 
Please find below a request to add pular Guinée langue (Spoken in Guinea)

**Language name**

Pular Guinée

**Language code**

 ISO-639-1 code : ff

**Language size**

Number of active speakers of this language in the world: 8 millions

**Plural forms: 
similar to Fulah 

<!--- How would you translate the following in this language?

0 want
1 sa
2 want
3 want
4 want
5 want
10 want
20 want
100 want
1000 want
janndim0 wantngofrawe
janndim1 sa ngofrawe
janndim10 wantngofrawe
janndimwantngofrawe

**Language Script**

Language scripts:  latin,

**Sentence Requirement Band**

[ ] Band B

**Comment by jessicarose** [comment]
Thanks so much for your interest in adding Pular Guinée to Common Voice and helping computers learn more about how real people around the world speak. I've looped in our languages expert, @ginamoape to help with next steps.

**Comment by ftyers** [comment]
Dear @fulaguinea, it's great to hear from you. We already have [Fulah](https://pontoon.mozilla.org/ff/common-voice/) in Pontoon, our localisation platform. The interface is at 55% translated, it needs to be at 75% to be launched. You will also need to collect 750 or more sentences of public domain text. If you'd like further assistance, please let us know!

**Comment by fulaguinea** [comment]
Dear @ftyers 
The Fulah dialects vary significantly from country to country, and the version spoken in Guinea is commonly known as Pular. I am interested in knowing if the Pular dialect in Guinea has already been registered.

**Comment by ftyers** [comment]
Dear @fulaguinea, thanks for the clarification, in that case the language code would be `fuf`. Would you like it to be set up on the model of Fulah `ff`?  Which writing system would you like to use? Latin or Adlam?

**Comment by fulaguinea** [comment]
Dear @ftyers 
Yes, the language code would be ff, the writing system Latin, and the name Pular Guinea.

**Comment by ftyers** [comment]
@fulaguinea The language code `ff` is for Fulah, the language code `fuf` is for Pular Guinea. I will add it to Pontoon with the Latin script.

**Comment by fulaguinea** [comment]
@ftyers thanks. What would be the next step?

**Comment by ftyers** [comment]
I've added you as a translator for the Common Voice project. You should now be able to approve as well as suggest translations. Please feel free to join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) for further assistance!
