### ISSUE TITLE
Downloading the Latest Datasets for All Languages on Linux

### ISSUE THREAD

**Issue by speechless-z** [common-voice/common-voice#4224]
I would like to inquire about the process of writing a script to download the latest Common Voice datasets for different languages with a single command. Could you please provide guidance on how to achieve this? Thank you.

**Comment by jessicarose** [comment]
Hello and thanks so much for your interest in the datasets. While our team doesn't have the capacity to support with scripting, you can [download our datasets here](https://commonvoice.mozilla.org/en/datasets) and we also have a [Discourse](https://discourse.mozilla.org/c/voice/239) and [Matrix channel](https://app.element.io/#/room/#common-voice:mozilla.org) where community members might be able to support!
