### ISSUE TITLE
Adding new language: Sindhi

### ISSUE THREAD

**Issue by asadm** [common-voice/common-voice#4227]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
Sindhi

**Language code**
sd

**Language size**
32 million (2011–2017)

**Plural forms**

0 پٿر
1 پٿر
2 پٿر
3 پٿر
4 پٿر
5 پٿر
10 پٿر
20 پٿر
100 پٿر
1000 پٿر
مون کي زمين تي 0 پٿر نظر اچن ٿا
مون کي زمين تي 1 پٿر نظر اچي ٿو
مون کي زمين تي 10 پٿر نظر اچن ٿا
مون کي زمين تي پٿر نظر اچن ٿا

**Pontoon manager**
https://pontoon.mozilla.org/contributors/asad/

**Language Script**
Naskh and Devanagari

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ ] Band B

- [x] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
I am a native Sindhi and me and my friends would like to contribute on common voice so that Sindhi is part of the dataset.

2. [optional to share] Would you like to have a follow up conversation regarding community building ?
Sure!

**Comment by ftyers** [comment]
Dear @asadm thanks for your interest in Common Voice! I've set up [Sindhi on Pontoon](https://pontoon.mozilla.org/sd/) and added [Common Voice](https://pontoon.mozilla.org/sd/common-voice/). You should now be able to suggest translations. Please feel free to suggest some, and when you have done that I can add you with permissions to review/translate. If you have any further questions, please don't hesitate to get in touch on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by ftyers** [comment]
Dear @asadm, thank you for your contributions. I have now added translator permissions for Common Voice for you.

**Comment by asadm** [comment]
Hello @ftyers, me and a friend have contributed translations. How do I now get the language added to common voice website?
