### ISSUE TITLE
LOCALIZATION REQUEST: 

### ISSUE THREAD

**Issue by 18orkidea** [common-voice/common-voice#4229]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Wayuunaiki

**Language code**

[guc](https://iso639-3.sil.org/code/guc)

**Language size**

600,000 six hundred thousand

**Plural forms**

0 ipa
1 ipa
2 ipa
3 ipa
4 ipa
5 ipa
10 ipa
20 ipa
100 ipa
1000 ipa
Terüin 0 ipa mülo'u
Terüin 1 mülo'u
Terüin 10 ipa mülo'u
Terüin  Ipairua mülo'u

**Pontoon manager**

(https://pontoon.mozilla.org/contributors/GNSBHoIFP7ru7Pn3cOhvg7EFJqw/)

**Language Script**

 latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

I want to be the liaison between Common Voice and the Wayuu community to create an open audio and text database that allows developers to create voice and text processing systems in Wayuunaiki.

3. [optional to share] Would you like to have a follow up conversation regarding community building ?

At the moment, we are a small community that is in contact via a WhatsApp group because not all members feel one hundred percent comfortable with new communication channels; we currently use this channel to communicate and support each other.

**Comment by ftyers** [comment]
Dear @18orkidea, thank you for your interest in Common Voice! I also got your email. One quick question: Is there a typo for *Terüin 1 mülo'u*, should this be *Terüin 1 __ipa__ mülo'u* ?

**Comment by 18orkidea** [comment]
Yes, the correct one is Terüin 1 ipa mülo'u

**Comment by ftyers** [comment]
It's enabled [here](https://pontoon.mozilla.org/guc/common-voice/). Good luck with the translation and we can be in communication on WhatsApp! :)
