### ISSUE TITLE
[BUG] CV cancel message in german validation not fully translated (de)(android14)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4230]
**Describe the bug**
Please watch the screenshot

**To Reproduce**
1. Go to '...' https://commonvoice.mozilla.org/de/listen
2. Click on '....'Validate 1 german  clip  with yes/no
3. Tap on the back button in activated 3 point navigation in android14

**Expected behavior**
Fully translated german message 

**Screenshots**
![Screenshot_20231109-165106](https://github.com/common-voice/common-voice/assets/92784377/dfbe6ae5-b154-4820-a826-bdbdb3c86064)

**Mobile (please complete the following information):**
 - OS: Android14 GrapheneOS
 - Browser Vanadium
 - Version 119.0.6045.134 

 **Hardware:**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**
none

**Comment by moz-rotimib** [comment]
Thanks for reporting this issue. We are aware of this bug and are working to fix it as soon as possible

**Comment by moz-rotimib** [comment]
This has been fixed now.
