### ISSUE TITLE
[BUG] Run out of Basque sentences to validate

### ISSUE THREAD

**Issue by Txopi** [common-voice/common-voice#4233]
**Describe the bug**
Many Basque friends and also me got the message "We may have run out of clips - refresh the page, or try again later" in Basque while we are validating sentences, but there are many clips pending for validation (about 160 hours).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Listen' page in Basque language: [https://commonvoice.mozilla.org/eu/listen](https://commonvoice.mozilla.org/eu/listen)
2. Validate 20-30 clips.
3. After a while you got the error page so you can't continue validating clips.

**Expected behavior**
If there are clips pending, you shouldn't see this page and you should keep validating clips.

**Screenshots**
![2023-11-12 21-47-24](https://github.com/common-voice/common-voice/assets/4833545/db7dc1b5-6af8-4e2e-8c2b-5dc712dd3c96)

**Desktop or Mobile (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 119.0

**Additional context**
It is not the first time a problem like this has been reported here:
- [No more sentences to validate in Welsh](https://github.com/common-voice/common-voice/issues/2746)
- [Can't validate clips in Catalan](https://github.com/common-voice/common-voice/issues/4013)

According to [this comment](https://github.com/common-voice/common-voice/issues/4013#issuecomment-1536405689) there is a limitation in the amount of clips that can be validated. Perhaps, Basque language (EU) should be removed from the [SSRL list](https://github.com/common-voice/common-voice/pull/4026)?

NOTE: On 3rd of December we celebrate the Internation Day of Basque Language and right now we are in the middle of a campaign to encourage Basque speakers to make recordings and validate them on Common Voice. Perhaps that's why so many people is having the problem described above. In two weeks Basque TV is going to ask Basque speakers to participate on Common Voice so it would be great if we can fix this bug before 20th of November.

**Comment by laubonghaudoi** [comment]
I thought this is WAI. The system doesn't allow you to validate incessantly, because otherwise it will enable people using bots to spam

**Comment by Txopi** [comment]
If this is a feature, I think we should put the threshold much more higher. Basque language and many other languages have thousands of clips pending to be reviewed and volunteers can't help on this task. In the case of Basque language they are 412 hours of recordings pending to be validated.

**Comment by laubonghaudoi** [comment]
Not sure if this is related but someone has already complaint about this before https://discourse.mozilla.org/t/giving-progress-notification-after-every-5-listened-sentences-is-annoying/113347

And I have also left my message in https://github.com/common-voice/common-voice/pull/3876#issuecomment-1872996969

**Comment by martin-kokos** [comment]
Still an issue after validating only one batch of 5 clips for EN, CS, SK, I've tried.
CS has only 24% approved clips possibly due to this.

**Comment by HarikalarKutusu** [comment]
This is finally fixed by @raivisdejus in https://github.com/common-voice/common-voice/pull/4608, Thank you!
Currently it works without any interruptions, even after 24-25 recordings.

**Comment by jessicarose** [comment]
I'll close this out and continue to send my effusive thanks to @raivisdejus
