### ISSUE TITLE
LOCALIZATION REQUEST: Request for moderator rights in the added language — tuvan (tyv)

### ISSUE THREAD

**Issue by huurak** [common-voice/common-voice#4255]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
tuvan 

**Language code**
ISO 639-3 — tyv

**Language size**
302 662

**Plural forms**
0 rocks — 0 даштар (тик даштар)
1 rock — 1 даш (бир даш)
2 rocks — 2 даштар (ийи даштар)
3 rocks — 3 даштар (үш даштар)
4 rocks — 4 даштар (дөрт даштар)
5 rocks — 5 даштар (беш даштар)
10 rocks — 10 даштар (он даштар)
20 rocks — 20 даштар (чээрби даштар)
100 rocks — 100 даштар (чүс даштар)
1000 rocks — 1000 даштар (муң даштар)
I see 0 rocks on the ground — Мен черде 0 даштар көрүп тур мен 
I see 1 rock on the ground — Мен черде 1 даш көрүп тур мен 
I see 10 rocks on the ground — Мен черде 10 даштар көрүп тур мен 
I see rocks on the ground — Мен черде даштарны көрүп тур мен 

**Pontoon manager**
https://pontoon.mozilla.org/contributors/wgsvMnGDsoEvlK72uKggnfNCIJ4/

Can I add another manager?
https://pontoon.mozilla.org/contributors/l2OtHBKNtMbCYDIVyGdKeDhUatM/

**Language Script**
Cyrillic

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [x] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

My name is Chingis, I work at the Tuvan Institute of Humanities and Applied Socio-Economic Research in the Department of Digital Development. Me and my colleagues, volunteer translators and other interested people, want to contribute to the promotion of the Tuvan language on the Internet through the Common Voice project too.

We have already translated almost all the lines of the Common Voice interface from English to Tuvan. Now you need to add transfers to Pontoon and confirm them.

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

We want to continue working and expand the community concerning the Tuvan language in the Common Voice project by attracting more and more interested people.

**Comment by ftyers** [comment]
Dear @huurak it's great to hear from you and thank you for your interest in Common Voice. I have added you as a translator to Pontoon. You should now be able to approve the translations yourself. If you are interested in more help, please feel free to contact us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
