### ISSUE TITLE
[BUG] Textbox covering some rules in review (chromium)(Firefox)(android14)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4306]
**Describe the bug**

Since the newest update update today the textbox is overlapping the fist rules in the review screen.
Please watch the screenrecording.

**To Reproduce**

1. Log into cv account
2. https://commonvoice.mozilla.org/en/review
3. During the change of the sentences, you can see that some sentences of the grammar rules are now covered by the now bigger textbox.

**Expected behavior**
All grammar can be read

**Screenrecording**

https://github.com/common-voice/common-voice/assets/92784377/5bd93cf7-5bd1-4f25-8129-221ad7587a01

**Mobile (please complete the following information):**
 - OS: [e.g. iOS] Android14 GrapheeOS
 - Browser Mull (based on Firefox)
 - 121.0.0 (Build #21210020), 1955f8455f+
GV: 121.0-20231219112436
AS: 121.0

 **Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:Google Pixel
 - Model: 6 pro

**Additional context**
Also tested with Vanadium (chromium based) browser latest version
Vanadium 120.0.6099.193

**Comment by moz-rotimib** [comment]
Thanks for filing this @robovoice1 this will be fixed soon
