### ISSUE TITLE
LOCALISATION REQUEST: Kidaw'ida [dav]

### ISSUE THREAD

**Issue by waleghwa** [common-voice/common-voice#4331]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Kidaw'ida

**Language code**

dav

**Language size**

300,000 (Three hundred thousand)

**Plural forms**

- 0 rocks - magho ndeghiko
- 1 rock - igho jimweri
- 2 rocks - magho aw'i
- 3 rocks - magho adadu
- 4 rocks - magho ana
- 5 rocks - magho masanu
- 10 rocks - magho ikumi
- 20 rocks - magho mrongo iw'i
- 100 rocks - magho ighana
- 1000 rocks - magho elfu
- I see 0 rocks on the ground - Siw'onie magho andonyi
- I see 1 rock on the ground - Naw'ona igho jimweri andonyi
- I see 10 rocks on the ground - Naw'ona magho ikumi andonyi
- I see rocks on the ground - Naw'ona magho andonyi

**Pontoon manager**

**Language Script**

latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [X] Band A

- [ ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Hi @waleghwa thanks for your interest in Common Voice! Could you let us know what the plural forms are (by translating the sentences in the template) and also who the Pontoon manager should be? If you need any help, feel free to get in contact on our [Matrix channel](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by waleghwa** [comment]
Hi @ftyers. I put a dash after each English sentence and then the Kidawida translation, on the same line. So they're there but they don't show on the rendered page.
I will be the Pontoon manager. I didn't understand how to indicate this.
Thanks!

**Comment by ftyers** [comment]
Thanks, I editted your post so the translations are visible, hope that is ok. I set up Kidaw'ida in Pontoon, our localisation platform and [added Common Voice](https://pontoon.mozilla.org/dav/common-voice/). Please make a Pontoon account and make a couple of translation suggestions. From there I will be able to pick up your username and add you as a translator.

**Comment by ftyers** [comment]
Done! You're set up and have permissions. Please let us know on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) if you have any further questions!
