### ISSUE TITLE
Misspelling of a local name

### ISSUE THREAD

**Issue by Prasanta-Hembram** [common-voice/common-voice#4332]
Hi, I have found a typo Siki in **Santali (Ol Siki)**, which should should be: **Santali (Ol Chiki)**

https://github.com/common-voice/common-voice/blob/9f4a4a6890104c4a524b97fed9eeee8697061977/web/locales/wo/messages.ftl#L171

**Comment by jessicarose** [comment]
Hello, and thanks for getting in touch with an issue that proved to require an unexpected amount of exciting research. At first glance, this does look like a typo. But as this is the Wolof localized file listing available Common Voice languages, this spelling may be appropriate in this context. 

As a non-expert making a quick glance at the language, it looks like "ch" sounds for many loan words from some languages are localized by shifting "ch" to "s" when writing Wolof in Latin script. If it's ok with you, I'll close this for now, unless you are a Wolof speaker or we're able to find a Wolof speaker who has a strong opinion on the spelling chosen?

Thank you again for raising this.

**Comment by Prasanta-Hembram** [comment]
> But as this is the Wolof localized file listing available Common Voice languages,

Got it, thank you for explaining in detail.
