### ISSUE TITLE
[BUG] Languages page does not fully load, gives server error.

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4336]
**Describe the bug**
This seems to be an infrastructure issue which happens from time to time, rather frequently... Normally, when you go to "LANGUAGES" menu item/page, first "skeletons" are shown, which are further filled with values. But frequently the server times out and the skeletons are kept. No error is shown.

NOTE: I'm aware this might seem an _intended_ behavior, the timeout/access is correctly checked,  and -although only on console- an error is given. If you try after a couple of minutes (usually 30 sec as indicated in the error is not enough),  you can get the required result after a hard refresh. On the other hand, this happens quite often and the user does not get any indication on what is happening.

**To Reproduce**
1. Go to Languages menu item / page
2. See the error on developer console after some time (see. Screenshots)

This might depend on the language and/or time of day.

**Expected behavior**
Languages with values should be fully shown after a reasonable time.
If a server error occurs, that should be shown in the front-end.

**Screenshots**

Display:
![image](https://github.com/common-voice/common-voice/assets/8849617/ceaa2d38-4ed5-49b2-9a9a-61a5590c3841)

Error on console:
![image](https://github.com/common-voice/common-voice/assets/8849617/f1768b14-23a4-4c8b-aa35-fbe07b98ac12)

**Comment by jessicarose** [comment]
Hello! While this must be inconvenient for users and contributors, that this is currently expected system behavior that can result from requesting the languages list while the cache has expired and the page crawls each of the 120+ languages that are in our system and live for collection. 

While we're exploring UX fixes to better explain why a wait of up to 2-3 min could be happening if folks are unlucky enough to visit during a cache refresh, looking at future DB improvements or streamlining how often these are run, I'm so sorry that these aren't likely to be improvements that community contributors are able to address and that fixes for this behavior isn't going to make it into the team's workflows for the foreseeable future. Thank you for flagging this and I'll close this for now but this is documented as something to keep an eye on internally.
