### ISSUE TITLE
LOCALISATION REQUEST FOR KALENJIN LANGUAGE [kln]

### ISSUE THREAD

**Issue by akebut** [common-voice/common-voice#4347]
# I am writting to request for localization of Kalenjine language in Kenya , we have already collected data for the language and swahili translation of the same, any assistance on this matter will be highly appreciated

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**  KALENJIN

**Language code**  Ikln-Latn

  ISO 639-3

**Language size**

 2 MILLION

**Plural forms**

0 rocks  Momite koita
1 rock  KOITA Agenge
2 rocks KOIK Oeng
3 rocks KOIK Somok
4 rocks KOIK angwan
5 rocks koik muut
10 rocks koik taman
20 rocks Koik tiptem
100 rocks Koik bogol
1000 rocks  koik elibut
I see 0 rocks on the ground  mogere koita eng  ng'uny
I see 1 rock on the ground agere koita agenge eng ng'uny
I see 10 rocks on the ground agere koik taman eng ng'uny
I see rocks on the ground agere koik eng ng'uny

**Pontoon manager**  Andrew  Kipkebut

https://support.mozilla.org/en-US/user/AKipkebut/

**Language Script**

 [Latin [Latn]]

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**  

   Band B sentences

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ? 
Improving Speech Recognition Technology
Supporting Multilingualism
Community Engagement
Educational Value
Advancing Natural Language Processing (NLP)
Supporting Linguistic Diversity

3. [optional to share] Would you like to have a follow up conversation regarding community building ?
yes

**Comment by akebut** [comment]
Looking forward to a positive feedback

**Comment by ftyers** [comment]
Dear @akebut, I have set up Kalenjin on Pontoon, our localisation platform. You can access it by loading [this page](https://pontoon.mozilla.org/kln/common-voice/). Please make some translation suggestions, when you have done that I will add you as a translator with the possibility to review suggestions and translate. If you have any further questions, please feel free to get in contact on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by ftyers** [comment]
@akebut I have now added you as a translator. Please feel free to [contact us](https://app.element.io/#/room/#common-voice:mozilla.org) if you have further questions.
