### ISSUE TITLE
LOCALISATION REQUEST: Norwegian Bokmål (nb-NO) admin/Team manager on Prontoon

### ISSUE THREAD

**Issue by punnerud** [common-voice/common-voice#4388]
Hi, could I get admin rights / Team manager on the Norwegian Bokmål language?
https://pontoon.mozilla.org/nb-NO/common-voice/

There is several translations awaiting approval. I have not retranslated them to "improve" my sentence contribution score.
I have earlier contributed to code.org and Scratch translations in Norwegian.
Norwegian Bokmål (nb-NO) is the native language of over 5 million people, to bad not to see it on Common Voice so I want to help with both that and voice contributions when its approved.

Here is my user on Prontoon:
https://pontoon.mozilla.org/contributors/ZCQ8c-Iipt6jOEcIYtBNb4o_0DQ/

**Comment by ftyers** [comment]
Hi @punnerud thanks for your interest in Common Voice. I've added you permissions.
