### ISSUE TITLE
Create issues template for documentation updates or new docs needed

### ISSUE THREAD

**Issue by jessicarose** [common-voice/common-voice#4441]
**Is your feature request related to a problem? Please describe.**
I would like for team members, community members and users to be able to create docs issues with a template that offers guidance that clearly communicates:
- The topic of the documentation needed
- If this is new documentation, an update or a change
- If documentation is existing docs needing a change, what should be changed
- What new information needs to be added to the documentation

**Describe the solution you'd like**
- Making a new template file

**Describe alternatives you've considered**
- Could create bug/feature requests for documentation but this would be really frustrating as the templates aren't applicable

**Additional context**
- To do this, creating a new markdown file here in the [templates folder](https://github.com/common-voice/common-voice/tree/main/.github/ISSUE_TEMPLATE) would be the fastest way to do this

**Comment by HarikalarKutusu** [comment]
Let me put my ideas for this as a community contribution:

First: May I ask where the documentation is? Currently, the "information" (not a "documentation") is fully scattered:

- Pages & sentences in the WebApp, like the About page, or most important section living deep inside (https://commonvoice.mozilla.org/en/guidelines)
- Github readme's
- Several blog posts
- Several discourse posts
- Some stuff deep in shared Google Drive documents (e.g. PowerPoint)
- The community Playbook https://common-voice.github.io/community-playbook/ nobody knows
- ...

And there is no information on how the whole system works (e.g. how the repos in GitHub are interconnected).

I know it is  a huge work to build well-defined documentation, CV is low on resources, but here is an example of it, right from Mozilla:
https://deepspeech.readthedocs.io/en/r0.9/

`readthedocs` is an ideal place for OpenSource documentation, also supporting GitHub integration (where people can suggest changes there through issues & PR), versioning, and multi-lingual versions, much more and free for OS (https://about.readthedocs.com/pricing/#/community). Of course, there should be directions on the front end for casual users, but it is a pain to keep track of the changes through Pontoon, which is not designed for documentation, but simple localization. For example, there are (say) 3 examples somebody wrote about dinosaurs, but in your language, you should give 5 other special cases, and there is no way to do it. So you cannot even localize it.

To solve these issues, I have been promoting `readthedocs`, but until some real documentation comes out, we had to create long posts under the sub-Discourse (and point to them), open several Social Media or IM (Telegram) channels, give lectures, record videos, etc.

So, IMHO, let's create documentation first, then try to fix it...
