### ISSUE TITLE
LOCALISATION REQUEST: nqo_Nkoo

### ISSUE THREAD

**Issue by mdoumbouya** [common-voice/common-voice#4466]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**
NKo

**Language code**
ISO-639: nqo
ISO 15924: Nkoo

**Language size**
50 Million people
https://en.wikipedia.org/wiki/N%27Ko_script
https://en.wikipedia.org/wiki/N%27Ko_script

**Plural forms**
|Eng|NKo|
|--|--|
|0 rocks |ߞߓߊ߫ ߀ |
| 1 rock| ߞߓߊ߫ ߁|
| 2 rocks|  ߞߓߊ߫ ߂|
| 3 rocks| ߞߓߊ߫ ߃|
| 4 rocks| ߞߓߊ߫ ߄|
| 5 rocks| ߞߓߊ߫ ߅|
| 10 rocks| ߞߓߊ߫ ߁߀|
| 20 rocks| ߞߓߊ߫ ߂߀|
| 100 rocks|  ߞߓߊ߫ ߁߀߀  |                                                    
|1000 rocks|ߞߓߊ߫ ߁߀߀߀|
|I see 0 rocks on the ground|ߒ ߢߊ߫ ߞߓߊ߫ ߀ ߠߊ߫ ߘߎ߱ ߡߊ߬|
|I see 1 rock on the ground|ߒ ߢߊ߫ ߞߓߊ߫ ߁ ߠߊ߫ ߘߎ߱ ߡߊ߬|
|I see 2 rock on the ground| ߒ ߢߊ߫ ߞߓߊ߫ ߂ ߟߊ߫ ߘߎ߱ ߡߊ߬|
|I see 3 rock on the ground|ߒ ߢߊ߫ ߞߓߊ߫ ߃ ߟߊ߫ ߘߎ߱ ߡߊ߬|
|I see 10 rocks on the ground|ߒ ߢߊ߫ ߞߓߊ߫ ߁߀ ߠߊ߫ ߘߎ߱ ߡߊ߬|
|I see rocks on the ground|ߒ ߢߊ߫ ߞߓߊ ߟߎ߬ ߟߊ߫ ߘߎ߱ ߡߊ߬|

**Pontoon manager**
doumbouya.moussa@gmail.com  (technical contact)
babamamadidiane@gmail.com
solofarabado@gmail.com

**Language Script**
ISO 15924: Nkoo

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ ] Band B

- [x] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?
The scarcity of speech resources for Nko hinders the development of usable speech technology for manding language speakers. We are submitting this request to bootstrap speech resource collection for Nko toward the development of automated speech recognition algorithms.
In previous work [1], we translated existing multilingual parallel text corpora and build the baseline machine translation system for Nko. Our goal is to extend those corpora with speech utterances collected on Common Voice.
2. [optional to share] Would you like to have a follow up conversation regarding community building ?
yes

# References
[1] [Doumbouya, M., Diané, B. M., Cissé, S. F., Diané, D., Sow, A., Doumbouya, S. M., ... & Manning, C. D. (2023, December). Machine Translation for Nko: Tools, Corpora, and Baseline Results. In Proceedings of the Eighth Conference on Machine Translation (pp. 312-343).](https://aclanthology.org/2023.wmt-1.34)

[2] [Common Parallel Corpora](https://github.com/common-parallel-corpora/common-parallel-corpora)

**Comment by ftyers** [comment]
Dear @mdoumbouya thank you for your interest in Common Voice. I have enabled Common Voice in Pontoon, our localisation platform, you can access it [here](https://pontoon.mozilla.org/nqo/common-voice/).  Please consider making a translation suggestion and I will add you as translator.

**Comment by ftyers** [comment]
Dear @mdoumbouya I have added you permission as translator. Please feel free to review the translation suggestions. I will close this issue, please feel free to get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) if you have any further questions.
