### ISSUE TITLE
LOCALISATION REQUEST for Shan (ISO-639-3: shn) language

### ISSUE THREAD

**Issue by NoerNova** [common-voice/common-voice#4488]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Shan

**Language code**

ISO-639-3: shn

**Language size**

About 4.7 million

**Plural forms**

မၢၵ်ႇႁိၼ် 0 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 1 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 2 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 3 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 4 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 5 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 10 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 20 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 100 ႁူၺ်ႇ
မၢၵ်ႇႁိၼ် 1000 ႁူၺ်ႇ
ၶႃႈႁၼ်မၢၵ်ႇႁိၼ် 0 ႁူၺ်ႇၼိူဝ်ပိုၼ်ႉ
ၶႃႈႁၼ်မၢၵ်ႇႁိၼ် 1 ႁူၺ်ႇၼိူဝ်ပိုၼ်ႉ
ၶႃႈႁၼ်မၢၵ်ႇႁိၼ် 10 ႁူၺ်ႇၼိူဝ်ပိုၼ်ႉ
ၶႃႈႁၼ်မၢၵ်ႇႁိၼ်တင်းၼမ်ၼိူဝ်ပိုၼ်ႉ

**Pontoon manager**

https://pontoon.mozilla.org/contributors/6gfkmbr6ITirVyyWBafB-YND9gw/

**Language Script**

Brahmic abugida

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [x] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by NoerNova** [comment]
Hi @ftyers,

I hope you're having a good day. I understand you must be quite busy, but could you please give an indication of when the next review cycle for adding a new localization will be?

Or any further information needed for this localization?

Thank you!

**Comment by ftyers** [comment]
Dear @NoerNova, thanks for your interest in Common Voice. I have set up [Common Voice for Shan](https://pontoon.mozilla.org/shn/common-voice/) on Pontoon, our localisation platform. Please feel free to go and add some translation suggestions and I will set you up as a translator. If you have any questions, feel free to contact us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by NoerNova** [comment]
Thanks so much, @ftyers ! Glad to hear that. Shall we close this?

**Comment by ftyers** [comment]
Yep that works, I've added you as a translator!

**Comment by ftyers** [comment]
@NoerNova you should be able to directly translate strings now instead of just suggesting them. Can you check that it works for you?

**Comment by NoerNova** [comment]
> @NoerNova you should be able to directly translate strings now instead of just suggesting them. Can you check that it works for you?

I'm about to ask, I'm currently only seeing the "Suggest" button and am not able to approve or take any other actions.

**Comment by ftyers** [comment]
Check under settings:

![imatge](https://github.com/common-voice/common-voice/assets/449545/5e477df6-00ac-40af-960a-239e35c0edb9)

**Comment by NoerNova** [comment]
<img width="762" alt="Screenshot 2567-06-26 at 21 25 57" src="https://github.com/common-voice/common-voice/assets/9565672/6974f61b-8b72-4b62-bd4c-38cdb176c65c">

**Comment by ftyers** [comment]
Hmm, try logging in/out and trying again.

**Comment by NoerNova** [comment]
Strange, I'm the Translator in "Terminology" I've not made any suggestions word yet, but in Common Voice I've made some suggestions already I'm just "Contributor".

Terminology
<img width="1498" alt="Screenshot 2567-06-26 at 21 39 29" src="https://github.com/common-voice/common-voice/assets/9565672/c0214a7c-0443-4091-9295-8bc34250c1e8">


Common Voice
<img width="1498" alt="Screenshot 2567-06-26 at 21 39 35" src="https://github.com/common-voice/common-voice/assets/9565672/c28ac15b-84ce-4ca5-b966-d8130a71b469">


All settings page
<img width="762" alt="Screenshot 2567-06-26 at 21 37 25" src="https://github.com/common-voice/common-voice/assets/9565672/bad5280f-99f4-47f3-892b-a8b12e91072c">

**Comment by ftyers** [comment]
Would you be able to join on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) to investigate further?

**Comment by NoerNova** [comment]
> Would you be able to join on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) to investigate further?

Yes, I've already joined Matrix.
