### ISSUE TITLE
Konkani (Devanagari) 'knn' language code must be changed to "kok"

### ISSUE THREAD

**Issue by chasingdragonflies** [common-voice/common-voice#4516]
**Edit: Before you read the request below, please understand that I am not a language expert and when I had posted this, I was not aware about konkani having so many scripts. I thought there were only two scripts: roman and devnagari. And felt that since it was written in [this paper](https://ceur-ws.org/Vol-2364/13_paper.pdf) that "Roman script is only used in select weeklies and tiatr (drama)", I mistakenly thought there was nothing else written in romi konkani. Hence thought it would obvious to use devnagri for the website. But the fact is there is a lot of literature written in romi konkani. If you scroll down a bit further, you will see my attempt to include konkani speakers who use other orthographies (scripts)**

---

Devanagari script is the official standard writing script for konkani in Goa.

Devanagari writing script is prevalent in Goa as well as in Maharashtra. (Marathi, Hindi, and Konkani (goan) are all using the Devanagari script.) So whether it is Maharashtrian konkani or Goan konkani, the official writing script is the same - devanagari.

Devanagari is also the standard script used to teach konkani in schools of Goa, where the language is official.

In goa, where konkani is spoken locally, Devanagari and Roman scripts are prevalent.

Currently in Pontoon, the "GOM" language code is being used for the Roman script and "KNN" is used for devanagari.

Already the Unicode CLDR has used devanagari script for konkani.

Even a unicode report advices to use 'kok' code for standard konkani instead of the 'knn' code.
https://www.unicode.org/reports/tr35/

![Screenshot_20240618-144620_Firefox](https://github.com/common-voice/common-voice/assets/167803089/72f2b0e2-ea3e-4c0d-8aee-9cca1ff124da)

The language "Konkani (Devanagari)" on MCV should be given the correct language code 'kok' as both, the script as well as the code, are the official standards for the Konkani language.

**Comment by ftyers** [comment]
Thanks for the request, we'll look into it, in the meantime could you share this request with other members of the Konkani community, for example @alvynabranches. You can find others in the GitHub issues and comments.

**Comment by alvynabranches** [comment]
This notation will be better to identify the languages.

**Comment by ftyers** [comment]
Hi @chasingdragonflies the two codes were originally added to permit the inclusion of Konkani in both Latin script and in Devanagari script before the support was included for multiple orthographies in the sentences. 

Now the only question is if you merge the two, which script would the interface be in? That's something that the community as a whole would need to come to consensus on.

**Comment by alvynabranches** [comment]
Both the scripts has to be separated because there are people researching on both the scripts.

**Comment by HarikalarKutusu** [comment]
> before the support was included for multiple orthographies in the sentences.

@ftyers,is this feature already implemented and online? As you might guess I cannot see it on my side (Turkish).
- If it is implemented, for a language L which used sentences with script S1 until now (but also written in script S2), would one need to write a database migration for that?
- What would one need if the existing text corpus is mixed, containing both sentences with S1 and S2?
- Will the metadata include a "orthography" column in this case, so that people could sub-sample a dataset and work on a single orthography (which would solve the case @alvynabranches emphasized)?

**Comment by ftyers** [comment]
> @alvynabranches i understand your point.
> 
> But if tomorrow someone asks for kannadi script, how would that be incorporated? We only have 3 language codes for konkani. And then if 4th person asks for malayalam script, how would MCV deal with it?

It would have to be added as a separate variant, which should not be too much trouble.

> If we released (translated MCV website in) both the dominant scripts separately and see which one performs well, we could use the well-performing database/langcode for supporting the other orthographies. But it would also mean that we are forcing kannada-script konkani people to choose between devanagari and roman script for reading the website.

The website can currently only be translated in one variant per language code, so the community would have to decide which one they prefer. 

> And then the issue that would come up would be: Suppose roman script database is chosen by kannada script users. What if there are kannada script users who prefer devanagari over roman? Even though both databases will be supporting kannada script (due to multi-orthography), the kannada script would then be scattered in two different databases. And if there is only one user of kannada script who decides to use devnagri `knn`, he would not get the feedback from other users who decided to use the `gom` (roman script website) database for recording kannadi script.

In the data dumps the scripts would be trivially separable by the variant field.
