### ISSUE TITLE
[BUG] "https://commonvoice.mozilla.org/de/review" not working

### ISSUE THREAD

**Issue by ichDaheim** [common-voice/common-voice#4518]
The site: "https://commonvoice.mozilla.org/de/review" is not working for a few days now. (Code 503)
Could you have a look into it ?

Many thanks

**Comment by moz-dfeller** [comment]
Hey @ichDaheim, thanks for bringing this to our attention! We will look into that 👍

**Comment by milupo** [comment]
The same for Upper Sorbian: https://commonvoice.mozilla.org/hsb/review

Loer Sorbian (dsb) works.

**Comment by jessicarose** [comment]
Thank you so much for this, I'll go through and test and see which other languages might be impacted when I'm at my desk tomorrow!

**Comment by milupo** [comment]
Hi, Upper Sorbian and German work now. Thank you very much.
