### ISSUE TITLE
[BUG] Develoment setup - Cannot build docker and run common voice

### ISSUE THREAD

**Issue by Siyaosk129** [common-voice/common-voice#4543]
**Describe the bug**
I just cloned the repo to locally host the common voice but I couldn't build the docker. When I wen through the development setup
```
> cd docker/
> docker build .
```
I got
```
  42 |     # Run build
  43 | >>> RUN yarn build
  44 |     
  45 |     # Default command to start the server
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```
Moreover, even when I opened Docker Desktop and ran the following commands
```
> cd common-voice
> docker-compose up
```
I got this.
```
web        | error Could not write file "/code/yarn-error.log": "EACCES: permission denied, open '/code/yarn-error.log'"
web        | error An unexpected error occurred: "EACCES: permission denied, mkdir '/code/node_modules'".
web        | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
web exited with code 1
```
I think this problem might be due to yarn but I couldn't find any work around for this.

OS:
Ubuntu 22.04.4

**Comment by moz-dfeller** [comment]
Hey @Siyaosk129 , the problem is probably caused by the user settings in the Dockerfile. Other users had success by reverting the changes made in https://github.com/common-voice/common-voice/pull/3999/files . You can check the comments in https://github.com/common-voice/common-voice/issues/4003 for more information. Hope that helps!

**Comment by Siyaosk129** [comment]
Hi. Thanks for your help. However, I still got this error
```
 > [7/7] RUN yarn build:
0.361 yarn run v1.22.19
0.383 error Couldn't find a package.json file in "/code"
0.383 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------

 1 warning found (use --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 39)
Dockerfile:36
--------------------
  34 |     
  35 |     # Run build
  36 | >>> RUN yarn build
  37 |     
  38 |     # Default command to start the server
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```
Do you have any suggestion?

**Comment by moz-dfeller** [comment]
Could you pull the latest changes from main and run
`docker compose up web --build --no-cache`
This will rebuild the docker container and the latest changes in the `docker-compose.yaml` should use the user configured on your system to start the container. That should eliminate the conflicting users with the mounted volume inside the container.

**Comment by Siyaosk129** [comment]
Big thanks for your help. I just tried what you said, it shows `unknown flag: --no-cache`. Not sure why but I found `--no-cache` with this command: `docker compose build --help`
Moreover, with only docker compose up web, it shows these messages

```
web  | warning "workspace-aggregator-1b1cbef1-cbd3-4afb-9e27-4359866d333e > server > db-migrate-plugin-typescript@2.0.0" has incorrect peer dependency "ts-node@^3.3.0".
web  | warning "workspace-aggregator-1b1cbef1-cbd3-4afb-9e27-4359866d333e > server > ts-jest@27.1.5" has incorrect peer dependency "typescript@>=3.8 <5.0".
web  | warning "workspace-aggregator-1b1cbef1-cbd3-4afb-9e27-4359866d333e > web > react-balance-text@2.0.1" has incorrect peer dependency "react@^0.14.7 || ^15.0.0 || ^16.0.0-0".
web  | warning "workspace-aggregator-1b1cbef1-cbd3-4afb-9e27-4359866d333e > web > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
web  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
web  | error Could not write file "/code/yarn-error.log": "EACCES: permission denied, open '/code/yarn-error.log'"
web  | error An unexpected error occurred: "EACCES: permission denied, mkdir '/code/node_modules'".
web exited with code 1
```
Do you have any suggestions on this?

**Comment by raivisdejus** [comment]
I was able to solve permission denied issues with these commands on Ubuntu 24.04:
```
export UID=$(id -u)
export GID=$(id -g)
docker compose up --force-recreate web
```

**Comment by jessicarose** [comment]
Thanks so much for flagging what the issue was, I'll make a note to better document out the Docker process and thank you again!
