### ISSUE TITLE
LOCALISATION REQUEST: Afar Language

### ISSUE THREAD

**Issue by qafarafa** [common-voice/common-voice#4561]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

Afar (Qafár afa)

**Language code**

aa

**Language size**

3 Millions

**Plural forms**

0 rocks =   0 xeeti
1 rock   = 1 xaa
2 rocks = 2 xaa
3 rocks =  3 xaa
4 rocks = 4 xaa
5 rocks = 5 xaa
10 rocks = 10 xaa
20 rocks = 20 xaa
100 rocks = 100 xaa
1000 rocks = 1000 xaa
I see 0 rocks on the ground = Anu baaxol xeetik 0 able
I see 1 rock on the ground   = Anu baaxol 1 xaa able
I see 10 rocks on the ground = Anu baaxol 10 xaa able
I see rocks on the ground  = Anu baaxol xeet able

**Pontoon manager**

Charif Ayfarah

**Language Script**

Latin

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [ x ] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by qafarafa** [comment]
Please add Afar language to the list of languages on Common Voice.

**Comment by qafarafa** [comment]
the Pontoon manager link:

https://pontoon.mozilla.org/contributors/AAKS5WCmbyED98t1U6VR8zhZ874/

**Comment by ftyers** [comment]
Dear @qafarafa, Thanks for your interest in Common Voice! :) I have set up [Afar in Pontoon](https://pontoon.mozilla.org/aa/common-voice/). Could you please make a couple of translation suggestions and I will add you as translator.

**Comment by ftyers** [comment]
Dear @qafarafa I have now added you as a translator. You should be able to make translations and approve suggestions. Good luck and feel free to get in contact with us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
