### ISSUE TITLE
Make Partner logo clickable to redirect towards partner site.

### ISSUE THREAD

**Issue by Jash2606** [common-voice/common-voice#4569]
### **Is your feature request related to a problem? Please describe.**
Currently, in the "Our Partners" section, all logos of partners are present as static images. This approach does not provide an easy way for users to validate and explore the partners' websites, which could enhance the user experience and provide additional value.

### **Describe the solution you'd like**
I would like to make the logos of the partners clickable. Clicking on a logo should redirect the user to the respective partner's website. This feature will help users to validate the partners and explore their offerings easily.

### **Describe alternatives you've considered**
An alternative solution could be to add a "Learn More" button below each logo that redirects to the partner's website. However, making the logos clickable is a more intuitive and user-friendly approach, as it reduces the need for additional buttons and utilizes the logos effectively.

**Comment by Jash2606** [comment]
Hey @moz-dfeller @moz-rotimib , 
I had raised a pr #4570 for above issue , Could you please review it and let me know if further changes required .

**Comment by jessicarose** [comment]
Thanks so much for spotting this and sending in a really great fix for this, I'll close this now
