### ISSUE TITLE
UI Enhancment 

### ISSUE THREAD

**Issue by TUSHAR1651** [common-voice/common-voice#4573]
Enhance the user experience by adding hover effects to the "About," "Discourse," and "Contact" links.

When a user hovers over any of the links, change the text color or underline the text.
Ensure the hover effect is smooth and consistent across all links.

![WhatsApp Image 2024-08-04 at 23 27 06](https://github.com/user-attachments/assets/564ee381-d9c4-4f26-96f4-7f417db0ab78)

**Comment by mintxdp** [comment]
You should add smooth transition and other properties on hover.
