### ISSUE TITLE
[BUG] Sign in with google option produces error.

### ISSUE THREAD

**Issue by mintxdp** [common-voice/common-voice#4594]
**Describe the bug**
Sign in with google option produces error 404 not found,

**To Reproduce**
 Go to login/signup field and enter login with google.

**Screenshot**
![404error](https://github.com/user-attachments/assets/0ee68d02-1701-42a5-b1e5-6007634f43b5)

**Comment by HarikalarKutusu** [comment]
@jessicarose: It is not deterministic.
> Tested on Chrome 127.0 desktop and got a 404 shown on the screen but the login was successful. Future login attempts did not result in a 404.
This happens from time to time in Opera desktop, which is also Chromium based. It started a while back, several months at least. Might be related to a setting in Auth provider.
