### ISSUE TITLE
LOCALISATION REQUEST: EWE

### ISSUE THREAD

**Issue by zouberou-sayibou** [common-voice/common-voice#4607]
# Welcome to the Common Voice Community !

> Common Voice aims to make speech technology accessible to everyone by building an open sourced dataset of labelled voice data that is representative of languages, variants and accents spoken across the world. This template helps us to know how your language could participate in the Common Voice Project. There are three sections of this form, once you have filled out a section please click the checkbox. If you have any issues please contact <commonvoice@mozilla.org>.

## Pontoon Set-up

> To start a language on Common Voice volunteers localise our platform [via Pontoon](https://pontoon.mozilla.org/projects/common-voice/) and create sentence corpus’ of cc0 text. </p>

**Language name**

 

Ewe

**Language code**

639-1

**Language size**
5 million native speakers according to Wikipedia, but we expect the numbers to be higher

**Plural forms**

0 rocks kpe meli o
1 rock kpe ɖeka
2 rocks kpe eve
3 rocks kpe etɔ̃
4 rocks pke ene
5 rocks pke atɔ̃
10 rocks pke ewo
20 rocks pke blaeve
100 rocks pke  alafa ɖeka
1000 rocks kpe akpe ɖeka
I see 0 rocks on the ground  Nye me kpɔ ekpe le anyigba
I see 1 rock on the ground Mekpɔ kpe ɖeka le anyigba
I see 10 rocks on the ground Mekpɔ kpe ewo le anyigba
I see rocks on the ground Mekpɔ kpewo le anyigba

**Pontoon manager**

https://pontoon.mozilla.org/contributors/zouberou/

**Language Script**

 Latin and Ewe Braille

## Sentence Collection Requirements

> On the Common Voice Platform contributors on the platform read out public domain sentences generated through sentence collection. Sentence collection is a crucial part in launching languages on Common Voice. To support the equitable participation of languages of Common Voice we have introduced [three new sentence collection requirements bands](https://discourse.mozilla.org/t/share-your-views-nuancing-sentence-collection-requirements-new-sentence-collection-bands/93134).

**Sentence Requirement Band**

- [ ] Band A

- [X] Band B

- [ ] Band C

## Creating Community 

1. [optional to share] Why do you want to take part in Common Voice ?

2. [optional to share] Would you like to have a follow up conversation regarding community building ?

**Comment by ftyers** [comment]
Dear @zouberou-sayibou thanks for your interest in Common Voice! I have [enabled Ewe](https://pontoon.mozilla.org/ee/common-voice/) for translation in Pontoon, our localisation platform. Please make a translation in the `contribute/` section and I will add you as a translator.

![imatge](https://github.com/user-attachments/assets/a62b25b9-6f92-4a72-ab18-89fa008ba146)

The next steps will be to translate the entirety of the `contribute/` section, some 24% of the interface and to collect 2000 sentences. If you have any questions, please feel free to join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).

**Comment by zouberou-sayibou** [comment]
Dear Francis,

Thanks for accepting our request. I was wondering if you would add me as a
the project manager as well. And what are some of the ways we can have
contributors engaging on pontoon.

Regards,

Zouberou Sayibou

**Comment by zouberou-sayibou** [comment]
Hi there again,

I just contributed to a sentence translation on pontoon. Charlot, my
colleague on this project, has also made a translation, can you add both of
us as translators for now?

Thank you so much!


Zouberou & Charlot

**Comment by ftyers** [comment]
Done! You should both be able to make translations now.

**Comment by zouberou-sayibou** [comment]
Thanks Francis!

What if we want to add a third person to help us validate the translations,
can we add people?

**Comment by ftyers** [comment]
Dear @zouberou-sayibou I am happy to add more people. It is not possible to make a Pontoon manager for a specific project (e.g. Common Voice), so if you would like to take on as manager for all Pontoon projects I can make you manager, or alternatively I can add the people you would like as translators. Just email me their email addresses, or ask them to make a suggestion and I will find it from there.
