### ISSUE TITLE
[BUG] Missing file paths in Common Voice Corpus 1

### ISSUE THREAD

**Issue by Calandiel** [common-voice/common-voice#4641]
After downloading version 1 of the dataset from https://commonvoice.mozilla.org/en/datasets I extracted the files and opened included `.tsv` files.

In all of them, the `path` column stores some kind of hash / id value (for example, `9051169da60fcf5e22c3927734b4dcfc794a6e833f98d7f767a9ec3843e6047d12a91b4f518a4eb3af18241cb125ac13769d60f19ff564a9859ac069579ba133`), instead of a string containing a file name (for example, `common_voice_en_41074651.mp3`).

This is unlike some of the newer subsets of the dataset, such as `Common Voice Delta Segment 19.0`.

Is this intentional? If so, how can we retrieve the "actual" path from the (seemingly) hashed value?

**Comment by HarikalarKutusu** [comment]
Yes, CV v1.0 is different in that respect. In its first version some hash value is used also for audio file name, but they quickly moved away from the idea. So it is not a bug.

Actually the hash-like value in metadata path field matches the audio filenames under clips directory. The dataset by itself is fully correct.

New FULL versions (not DELTA releases) already include the recordings from all previous versions (minus deleted users' audio), so if you use v19.0, there is no need to go back.

One exception: For detailed metadata, audio analysis (e.g. for academic purposes) across versions like the ones I'm doing. Probably the only way to match is get the hash from audio from each v1 and v3 (I skip v2) and rename the "path" and audio filenames in v1 so they have the same naming.

**Comment by Calandiel** [comment]
I see. Makes sense. I'll close the issue then, sorry for the confusion! :slightly_smiling_face:
