### ISSUE TITLE
[BUG]Some write functions unavailable on smaller screens

### ISSUE THREAD

**Issue by jessicarose** [common-voice/common-voice#4695]
**Describe the bug**
Small batch submissions and other write page activities unavailable on smaller screen sizes

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop or Mobile (please complete the following information):**

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**
Context in Matrix thread: **https://matrix.to/#/!WpvTgzNfcLIgzJZdSE:mozilla.org/$KR7EyHfI1ZLR69DWNUd3D4RHo6ttxkV8EvHXpTlQS14?via=mozilla.org&via=matrix.org&via=t2bot.io
**

**Comment by moz-rotimib** [comment]
@jessicarose this issue should be fixed now
