### ISSUE TITLE
Recordings made before spelling corrections still have incorrect text when listening.

### ISSUE THREAD

**Issue by iveskins** [common-voice/common-voice#633]
I came across a recording with a spelling mistake.
{"glob":"8a23633f-2e4f-4935-a277-27f95508322e/9bcdbd45afcb84afb8bc02d7de370fce5720d50a7c6217016bd9f2467dd615c1","text":"That's why I'm here in the middle of het desert."
i.e "het" not "the"
it seems the sentence is fixed in the files.
not-used/new-sentences.txt:That's why I'm here in the middle of the desert.
The reader said "the"
I think the change was made in #409 
Because recording text files are made at recording time, any corrections to sentences later do not get updated in the recordings. 
Does this make this a "nope" recording?
If I understand correctly 
"8a23633f-2e4f-4935-a277-27f95508322e" is the user ID and
"9bcdbd45afcb84afb8bc02d7de370fce5720d50a7c6217016bd9f2467dd615c1" is a hash of the text.
Is there a way to find all files called 
9bcdbd45afcb84afb8bc02d7de370fce5720d50a7c6217016bd9f2467dd615c1.txt and correct "het" to "the" ?
and possibly the same with some of the other spelling corrections?

**Comment by jf99** [comment]
Imo, if the text is "het" and the reader says "the", this must lead to a Nope, regardless of whether "het" was written erroneously. Otherwise, we would train the software to write "the" as "het". It's probably a good idea to just throw away all the misspelled sentences together with their recordings.

**Comment by MichaelKohler** [comment]
I'd love to discuss this and see whether this is still an issue.

**Comment by iveskins** [comment]
Hi @MichaelKohler. I haven't looked in a while. At the time It seemed to me that every recording had its own sentence data, that was made at recording time. So unless there has been some action to go and change the sentence data on older recordings then the initial problem would still exist. As for if this is still an issue or not, that would depend on if these old recordings are still waiting to be validated, or if they have all been marked as invalid. if they have been marked as invalid, there is a chance to "recover" these recordings by correcting the text and resetting their vote counts and putting them back up for validation. 
If they have been marked as valid, that might make bad data. 
Such recordings would be identified by getting a list of prompts that had been changed for spelling mistakes from the commit history and searching for all those in the dataset.. 
I guess. It's been a while.

**Comment by mbransn** [comment]
@MichaelKohler @iveskins this was submitted when only the English language was present on the site. There have been attempts to clean up sentence data though I'm unclear how retroactive this may have been? 

Is it possible to determine if this is still an issue in current sentences first? If so we'd most likely focus on improving the quality of new sentences at a minimum. cc @nukeador for input based on sentence collection strategy.

**Comment by MichaelKohler** [comment]
Last I checked older recordings still had the associating to the old version. See also https://github.com/mozilla/voice-web/issues/2259#issuecomment-558350127

**Comment by MichaelKohler** [comment]
> If so we'd most likely focus on improving the quality of new sentences at a minimum.

That's not really all we should do. There will *always* be sentences that slip through.

**Comment by mbransn** [comment]
@MichaelKohler right, this is why I said 'at a minimum'. If we can figure a way to apply edits retroactively to old .txt I'm all for it. Will categorize this as sentence quality for now during initial triage round. We're actively working on sentence effort prioritization so this is helpful to now be aware of.

**Comment by jessicarose** [comment]
Hello and thank you for your incredible patience in hearing back from us on an impossibly old issue. Sentences in the text corpus can't currently be corrected but can be removed via the quality control process or re-balanced by being diluted with correct, higher quality sentences if they have been accepted and recorded into the corpus. I'll close this issue for now but rest assured that sentence quality is something we're not forgetting about and will remain a priority as we work with language and contributor communities.
