### ISSUE TITLE
user-scalable=no - Zooming and scaling must not be disabled

### ISSUE THREAD

**Issue by KBPsystem777** [common-voice/common-voice#773]
I found `user-scalable=no` under the `<meta name="viewport">`  at **[voice-web/web/index.html](https://github.com/mozilla/voice-web/blob/master/web/index.html)**
This tag disables zooming in the browser for several devices.

**Comment by mikehenrty** [comment]
Whoops, I broke this. @KBPsystem777 can you tell me why we should not disable zoom?

**Comment by KBPsystem777** [comment]
Thanks for looking on this @mikehenrty . 
This is a very critical app feature, disabling zooming capabilities on mobile browser users may not be a good experience for people that has a low or vision problems who simply relies on screen magnification/zooming to properly see the contents of a web page.
And I know people personally who experienced the same problem after running the site on their mobile browsers. This might help: https://dequeuniversity.com/rules/axe/2.2/meta-viewport
