### ISSUE TITLE
Add ability to Tag recording, Save more metadata with recordings

### ISSUE THREAD

**Issue by ghost** [common-voice/common-voice#814]
Since this database could in the end be used for any voice related work, maybe we could define better each audio clip by saving more metadata. I'm not talking about identifying data of course, but data you can hear in the recording like mood, volume, speed, mispronunciations... That way when AIs become smarter they can detect the tone or other information. It could also be used to filter datasets in the database if someone only wants "clean" recordings or "noisy" recordings. And that also makes some recordings more valuable : I read in an issue that people didn't know if they should accept recordings with people coughing, well if could help the robot train to recognize and ignore (or not) coughing.

Technically, I'm thinking about adding tags to the recording and validation process. Users would be able to select them from a list and maybe add their own. Examples of such tags : "laughing", "stuttering", "coughing", "shouting", "slow", "noisy"... Of course each tag needs to be validated at the validation process.

Since the UX would be more complex then, maybe just add like an "advanced" button to make it optional and hidden by default. Or I read in some issue that there might be an account feature coming along, so maybe show it only when the user is logged in. Because people with an account would be the ones who would want to get more involved, in my opinion.

This kind of topic as been discussed in PR #273 . That issue is however about the validation criterias, that's why I'm posting a new issue.

**Comment by Gregoor** [comment]
I'd really like that idea, as it would not only be helpful for people working with the dataset but also for us to get a better idea where the most common recording problems lie (i.e. missed words vs volume). Though for now I'd only add it to the validation flow as an optional (visible) field. I'll ask if we find room for it in our next design iteration.

**Comment by m-branson** [comment]
This is a great flag and something for us to plan for. @Gregoor + @mikehenrty first step may be to identify what attributes we want to include and if we'd like to include the option to 'add your own'. I appreciate the call out for an advanced UI option as well @zecakeh 👍 Not sure how this will manifest in the UX/UI quite yet, but is great feedback we can factor in to future iterations.

**Comment by Gregoor** [comment]
I thought we might want to go with an autocomplete-like text field with tag-creation option, so that the limits of our imagination is not the limit of what's possible to tag. Or should we have misuse concerns there?

**Comment by m-branson** [comment]
@Gregoor I'm absolutely open to auto complete, but yes, misuse comes to mind. Thinking this ultimately depends on how much clip 'clean up' and maintenance we're able to commit to? (also, I only saw your comment because I came back to reference this issue for wireframes, please remember to tag me so I don't leave you hanging 👍 )

**Comment by Gregoor** [comment]
@m-branson @mikehenrty thought about this a bit more: I think we should start with an open-tagging system and as soon as handling of misuses takes too much of a toll, we close it down to only allow pre-existing tags. At that point we might already have a sizable body of community suggested tags.

**Comment by m-branson** [comment]
@Gregoor @mikehenrty sounds great to me, we'll continue focusing on open field input method in the UX for now.

**Comment by jsalsman** [comment]
commenting to reference https://discourse.mozilla.org/t/can-db-vote-be-a-boolean-union-with-a-utf-8-string/45941

I am trying to come up with a plan to supplement the boolean votes with a utf-8 text field (which could be used for controlled vocabulary category tags, too, e.g. with hashtags at the end, or maybe at front if you lead with #true and #false to represent the boolean vote.) I want to supplement the boolean thumbsUpIcons and thumbsDownIcons without disturbing any existing workflow.

@mbransn there are design choices like where the text field should render in the HTML, 

@Gregoor Currently I use Python's Dataset DB API (and "from autocorrect import spell; from itertools import product") to condition my transcripts' intelligibility "match" as follows:

    db = dataset.connect(connect_string)
    tt = db['transcriptions']
    pt = db['prompts']
    wt = db['words']
    okchars = ascii_lowercase + digits + " '"
    for t in tt.find(exemplar=False, order_by='id'):
        p = pt.find_one(id=t['promptid'])
        wl = p['words']
        ws = [] # two layer list of spellings plus homographs
        match = False
        for w in wl:
            tw = wt.find_one(id=w)
            ws.append([tw['spelling']] + tw['homops']) # lowercase already
        ts = ''.join([c.lower() for c in t['transcription'] # keep only lower-
            if c.lower() in okchars]).strip() + ' ' # case, spaces & apostrophes
        tc = '' # autocorrect-ed alternative
        for w in ts.split():
            tc += spell(w) + ' ' # spelling correction
        # compare permutations.startswith(word(s)), appending a space to each
        for ps in [' '.join(s) + ' ' for s in product(*ws)]: # itertools.product
            if (tc.startswith(ps) or tc.startswith(ps.replace(' ', '') + ' ')
                    or (tc.replace(' ', '') + ' ').startswith(ps) or
                    ts.startswith(ps) or ts.startswith(ps.replace(' ', '') +' ')
                    or (ts.replace(' ', '') + ' ').startswith(ps)):
                match = True
                break
        tt.update(dict(id=t['id'], intelligible=match), ['id'])
        print('transcription ', ts, 'is', match, 'for:', p['display'])

**Comment by dabinat** [comment]
Does this actually need to happen at the validation stage?

It seems to me that not every user will add metadata and some users may not always tag every specific piece of metadata in a clip. So a clip might need multiple passes before all metadata is properly tagged. Also, would there be a system to validate that tags are correct?

It seems better to have it as a separate system where all clips are available for metadata tagging and if you tag/skip a clip it only hides it from your own queue and not those of other people. It needn’t necessarily even be hosted on the CV site.

You could then vote up/down a particular tag or add a new one, with the highest rated tags getting accepted. That way it may not necessarily matter if users add too many custom tags.

**Comment by jsalsman** [comment]
@dabinat I am trying to obtain transcripts from listeners, because that is the only way to train models of authentic intelligibility, as per https://www.docdroid.net/gvbP0Jc/paslides.pdf

The metadata (which might occur, for example, just after the first newline) can be thought of as entirely separate, and need not be in the same database column. If the tagging request is keeping transcriptions from happening, I want to get both at the same time. 

@mbransn sorry I wrote you an incomplete sentence above. Where can I find the UI graphics presentation guidelines? If I write a pull request for this, will you review the design aspects? @Gregoor will you review the backend parts? Should I try to get tagging at the same time or leave it for another column?

**Comment by nukeador** [comment]
Hi all,

This is an interesting proposal and it's definitely on the team's mind, we are currently working on a final proposal around how to better capture accents that also talks about a similar need.

In terms of time availability, right now we are really focused on the partner work and we don't really have much time for reviewing this right now.

Can I suggest we all wait a bit until the new accents proposal is presented by the end of this month and we all discuss how we can find a solution for all the needs together? I think this will result into a more solid proposal, better collaboration and potentially unlock some time allocation from the staff team to review a prioritized feature.

Thanks everyone for this!
