### ISSUE TITLE
how do we get more noisy samples and is it useful to classify them as such?

### ISSUE THREAD

**Issue by Djfe** [common-voice/common-voice#914]
I noticed that most peoples' recordings don't have any noise or echo in them.

The topic of this issue is:
How can we encourage people to record outside? (next to streets, in tunnels, with radio/music in the background etc.)
I mean except from mentioning it.

I don't really have any ideas, except for organizing meet-ups.
Maybe as a side-part on other events that Mozilla does.

This definitely should be prioritized at some point to train better speech recognition under noisy conditions.

Would it make sense to separate noisy and clear voice recordings (table column with a boolean value) to be able to train two neural networks instead of one?
I could imagine scientiests would like to try that out.

Also possible would be calculating the SNR to categorize all samples in a few categories of different noise levels, though this would exclude something like car horns etc.

Of course this would require additional work, so the question is: does this additonal information add value to the database?

**Comment by jf99** [comment]
I don't think this is an issue. Afaik, the [paper](https://arxiv.org/abs/1412.5567) implemented by DeepSpeech automatically generates noise by adding many other voice recordings with low volume.

**Comment by Djfe** [comment]
interesting approach :)
but I would argue that that's not all the type of noise there is

**Comment by kdavis-mozilla** [comment]
@Djfe I agee, but they also add in non-voice recordings too.

**Comment by jimregan** [comment]
There's an open [corpus](http://www.openslr.org/17/) of noise; one of Kaldi's [recipes](https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/aspire_data_prep.sh) adds reverberation using impulse response data; xiph.org have a project for [noise suppression](https://people.xiph.org/~jm/demo/rnnoise/) that they're [collecting noise](https://people.xiph.org/~jm/demo/rnnoise/donate.html) for, but there hasn't been a data release yet.

**Comment by kdavis-mozilla** [comment]
Didn't know about SLR17. Thanks.

I know the person that doing the xiph.org  work. I think the data set is likely too small to be of use, a system would overfit to that noise.

[Deep Speech](https://github.com/mozilla/deepspeech) is planning on using data from [freesound.org](http://freesound.org/), which provides lots of data with lots of variety, along with [voice-corpus-tool](https://github.com/mozilla/voice-corpus-tool) to create a convincing mix of background noise and speech corpora.

**Comment by MichaelKohler** [comment]
@kdavis-mozilla I feel that mentioning it on the CV would make sense, but introducing noise sounds like something for DeepSpeech. Do you agree? Or is this already solved and we can close this issue?

**Comment by jessicarose** [comment]
Hello hello! I'm so sorry to have left your (very interesting!) issue open and waiting for so long. In the proceeding years we have begun to do more fieldwork with specific language communities, resulting in more recordings taken in environments with a range of ambient noise. We've also worked to improve the mobile contributor experience. We'll continue to think about how background noise impacts dataset consumers and thank you so much again for raising this issue.

**Comment by Djfe** [comment]
thanks for cleaning up and moderating issues. 🙌
